src/main/metadata-au/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Home_Phone_2__c</fullName>
        <label>Home Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is "Address_Province"
Attribute in Data Dictionary object Dealer is "Dealer_ProvinceEN"</description>
        <label>Province</label>
        <picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is "Contact_CustomerStatus"</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer's address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is "Dealer_ZipCode"</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <externalId>true</externalId>
        <label>Campaign Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Execution_Type__c</fullName>
        <description>Used only for Campaign Execution record type. To defined the execution channel.</description>
        <label>Execution Type</label>
        <picklist>
            <picklistValues>
                <fullName>OB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Created_By__c</fullName>
        <label>Task Created By</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata-au/classes/TriggerCampaignMembers_TestClass.cls
/*
    Type:       Test Class
    Purpose:    TriggerCampaignMembers 
    User Story:     
    Used By:    
    ---------------------------------------------------------------
    History:
    
    10-July-2013 Stephano Shi (Breakingpoint)    Created
*/
@isTest
public class TriggerCampaignMembers_TestClass{
    static testmethod void runTriggerCampaignMembers(){
        Map<String, Schema.RecordTypeInfo> cpRecordTypeMap_test = Schema.SObjectType.Campaign.getRecordTypeInfosByName();
        Map<String, Schema.RecordTypeInfo> accRecordTypeMap_test = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Id caeSim_RecordTypeId = cpRecordTypeMap_test.get('Campaign Execution - Simple').getRecordTypeId();                       // CAC Campaign
        Id accPerson_RecordTypeId = accRecordTypeMap_test.get('Person Account').getRecordTypeId();      // Person Account.
        
        // Execution Campaign Inital
        Campaign TestData_CAE_OBC = new Campaign(Name='TestData_CAE_OB_SIM_C',
                                                Campaign_Code__c='code exe ob sim testc',
                                                Execution_Type__c='OB Call',
                                                Task_Created_By__c='Contact',
                                                RecordTypeId=caeSim_RecordTypeId);
        Database.insert(TestData_CAE_OBC);

        // Contact                
        Account testPerAcc = new Account(LastName='TEST ACC',
                                      Type='Company',
                                      Status__c='VIP',
                                      Province__c='Shanghai',
                                      City__c='Baoshan district',
                                      ZipCode__c='123456',
                                      PersonMobilePhone='1235678910',
                                      RecordTypeId=accPerson_RecordTypeId,
                                      Salutation='Brother',FirstName='Test',Email__c='test@mbau.com',Email2__c = 'testemail2@test.com',Home_Phone_2__c = '98765413'
                                     );        
        insert(testPerAcc);
                                         
        testPerAcc = [Select Id, PersonContactId From Account Where Id = :testPerAcc.Id];
        
        // Campaign Member Initial
        CampaignMember cm1 = new CampaignMember(CampaignId = TestData_CAE_OBC.Id,
                                                Status ='Sent',
                                                ContactId = testPerAcc.PersonContactId
                                                );  
        insert cm1;
    }
        
}