src/main/metadata-au/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Flag for this dealer
Attribute in Data Dictionary object Dealer is "Dealer_ActiveFlag"</description>
        <label>Dealer Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Tool_Kit__c.object
<CustomObject>
    <fields>
        <fullName>Apply_Status__c</fullName>
        <description>Apply Status of the tool kit</description>
        <label>Apply Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Modify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tool Kit Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ToolKitApprover</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>StarElite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Dealer Name of the tool kit</description>
        <label>Dealer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tool Kits (Dealer Name)</relationshipLabel>
        <relationshipName>Tool_Kits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Director__c</fullName>
        <description>Event Director of the Tool Kit</description>
        <label>Event Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Participant__c</fullName>
        <description>Event Participant of the Tool Kit</description>
        <label>Event Participant</label>
        <picklist>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Event Type of the Tool Kit</description>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Road Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Festival</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Car Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Showroom Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prints relevant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Showroom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Feedback_Status__c</fullName>
        <description>Feedback Status of the tool kit</description>
        <label>Feedback Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Modify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Size__c</fullName>
        <description>Location Size of the Tool Kit</description>
        <label>Location Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location of the Tool Kit</description>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Indoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Showrrom</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Plan_End_Date__c</fullName>
        <description>Date for the tool kit end</description>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Start_Date__c</fullName>
        <description>Date for the tool kit start</description>
        <label>Plan Start Date</label>
        <type>Date</type>
    </fields>
    <label>Tool Kit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tool Kits</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Headquarters activities supported by the Toolbox application</description>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Media</fullName>
        <active>true</active>
        <description>Headquarters support Media Kit request</description>
        <label>Media</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/classes/MassApproveToolKitControllerTest.cls
/*
    Type:       Test Class
    Purpose:    Test On MassApproveToolKitController
    ---------------------------------------------------------------
    History:
    
    1. Cyril Created on 2014-10-24

*/
@isTest(seeAllData=false)
public class MassApproveToolKitControllerTest {
    static testMethod void myUnitTest() {
        Account dealer = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId(),
            Name = 'test dealer',
            Dealer_Active__c = true
        );
        insert dealer;
        
        Tool_Kit__c toolKit = new Tool_Kit__c(
            RecordTypeId = Schema.SObjectType.Tool_Kit__c.getRecordTypeInfosByName().get('Event').getRecordTypeId(), 
            Name = 'test tool kit',
            Dealer_Name__c = dealer.id,
            Plan_Start_Date__c = System.today(),
            Plan_End_Date__c = System.today() + 20,
            Apply_Status__c = 'Planned',
            Feedback_Status__c = 'Planned',
            Brand__c = 'MB',
            Event_Type__c = 'Road Show',
            Event_Director__c = 'test',
            Event_Participant__c = 'Media',
            Location__c = 'test',
            Location_Size__c = 10,
            Approver__c = Userinfo.getUserId()
        );
        insert toolKit;
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(toolKit.id);
        req1.setSubmitterId(Userinfo.getUserId()); 
        req1.setProcessDefinitionNameOrId('Tool_Kit_Approval_Process');
        req1.setSkipEntryCriteria(false);
        Approval.ProcessResult result = Approval.process(req1);
        
        
        Test.startTest();
        System.assert(result.isSuccess());
        System.assert([Select Id, Apply_Status__c from Tool_Kit__c where id = :toolKit.id][0].Apply_Status__c == 'Confirmed');
        
        PageReference pr = new PageReference('/apex/MassApproveToolKit');
        Test.setCurrentPage(pr);
        
        MassApproveToolKitController con = new MassApproveToolKitController();
        con.toolKit.Dealer_Name__c = dealer.id;
        con.getRecordTypes();
        con.getApplyStatusOptions();
        con.getFeedbackStatusOptions();
        con.getRegions();
        con.getSubRegions();
        
        con.query();
        system.debug(con.hasPrev);
        system.debug(con.hasNext);
        con.previous();
        con.next();
        con.first();
        con.last();
        system.debug(con.recordNumbering);
        
        //con.toolKitsInfo[0].isToApprove = true;
        
        con.approve();
        Test.stopTest();
    }
}