src/main/metadata-au/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Home_Phone_2__c</fullName>
        <label>Home Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is "Contact_CustomerStatus"</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Retail_Task__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retail Tasks (Account Name)</relationshipLabel>
        <relationshipName>Retail_Tasks5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Call_Task_1_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Annual Call Task 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Annual_Call_Task_2_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Annual Call Task 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Annual_Call_Task_3_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Annual Call Task 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Annual_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Annual Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EOC_Call_Task_1_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EOC Call Task 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EOC_Call_Task_2_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EOC Call Task 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EOC_Call_Task_3_del__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EOC Call Task 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EOC_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EOC Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GFV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GFV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved for financing</fullName>
            </picklistValues>			
            <picklistValues>
                <fullName>Asset Released</fullName>
            </picklistValues>
			<picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closing Receipt Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditioned</fullName>
            </picklistValues>			
            <picklistValues>
                <fullName>Continue with existing borrower</fullName>
            </picklistValues>
			<picklistValues>
                <fullName>Current</fullName>
            </picklistValues>		
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default-Collection Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default-External Agent</fullName>
            </picklistValues>			
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
			<picklistValues>
                <fullName>Early Payout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Payout-Cheque Under Clearance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Payout-Sale and Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Payout-Sale of Asset</fullName>
            </picklistValues>			
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
			<picklistValues>
                <fullName>Executed-Existing Borrower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed-Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed-Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat Cancel Contract</fullName>
            </picklistValues>			
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
			<picklistValues>
                <fullName>Insurance Loss Arrangement</fullName>
            </picklistValues>		
            <picklistValues>
                <fullName>Insurance Write off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irregular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irregular Complied</fullName>
            </picklistValues>			
            <picklistValues>
                <fullName>Litigation</fullName>
            </picklistValues>
			<picklistValues>
                <fullName>New</fullName>
            </picklistValues>		
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Welcome_Call_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Welcome Call Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Welcome_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Welcome Call</label>
        <type>Checkbox</type>
    </fields>
    <label>Retail Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/User.object
<CustomObject>
    <fields>
        <fullName>Active_Permission_Set__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Permission Set</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata-au/classes/ScheduledSharingContractToCROsTest.cls
/*
    Type:       Test Class
    Purpose:    Test the ScheduledSharingContractToCROs class
    User Story: 
    ---------------------------------------------------------------
    History:

    1. Barney lai created on 2014-3-3
*/
@isTest(seeAllData=true)
public class ScheduledSharingContractToCROsTest{

    static testMethod void testScheduledSharingContractToCROs(){

        String userRoleId = [select id, name from UserRole where name = 'Customer Retention Office 1'].id;
        String profileId = [select id, name from Profile where name = 'Customer Retention'].id;
        
        User usr = new User();
        usr.UserName = 'test' + Math.rint(Math.random() * 100000) + '@daimler.com';
        usr.UserRoleId = userRoleId;
        usr.ProfileId = profileId;
        usr.LastName = 'Test User';
        usr.Email = 'test001@daimler.com.full';
        usr.Alias = 'test';
        usr.TimeZoneSidKey = 'Asia/Shanghai';
        usr.EmailEncodingKey = 'UTF-8';
        usr.LanguageLocaleKey = 'en_US';
        usr.localesidkey='en_US';
        usr.isActive = true;
        usr.Active_Permission_Set__c= true;
        insert usr;   
        
        system.runAs(usr){
            Test.startTest();
            testMain1();
            Test.stopTest();
        }
    }
    
    @future
    private static void testMain1() {
    
        String personAccountRT = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();   
    
        Account account1 = new Account(
            firstName = 'Test',
            lastName = 'lai',
            Salutation = 'Doctor',
            PersonMobilePhone = '13011111111',
            PersonOtherPhone = '13022222222',
            Phone = '1234567',
            Individual_Home_Phone__c = '1234567',
            PersonAssistantPhone = '1234567',
            RecordTypeId = personAccountRT,Email__c='test@mbau.com',Email2__c = 'testemail2@test.com',Home_Phone_2__c = '98765413');
        
        insert account1;
        
        Account account2 = new Account(
            firstName = 'Test',
            lastName = 'lai',
            Salutation = 'Doctor',
            Email__c = 'xiaomusyz@sohu.com',
            PersonAssistantPhone = '1234567',
            PersonMobilePhone ='1800999999',
            RecordTypeId = personAccountRT,Email2__c = 'testemail2@test.com',Home_Phone_2__c = '98765413');
        insert account2;
        
        Retail_Task__c contract1 = new Retail_Task__c (Account__c= account1.id,
                                          StartDate__c= date.today().addDays(-5),
                                          Duration__c= 13,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          Welcome_Call__c = true,
                                          Welcome_Call_Task__c = true);
        insert contract1;
        Retail_Task__c contract11 = new Retail_Task__c (Account__c= account2.id,
                                          StartDate__c= date.today().addDays(-5),
                                          Duration__c= 13,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          Welcome_Call__c = true,
                                          Welcome_Call_Task__c = true);
        insert contract11;
        
        Retail_Task__c contract2 = new Retail_Task__c(Account__c= account1.id,
                                          StartDate__c= date.today().addYears(-1),
                                          Duration__c= 37,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          Annual_Call__c = true,
                                          Annual_Call_Task_1_del__c = true);
        insert contract2;
        
        Retail_Task__c contract3 = new Retail_Task__c(Account__c= account1.id,
                                          StartDate__c= date.today().addYears(-2),
                                          Duration__c= 49,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          Annual_Call__c = true,
                                          Annual_Call_Task_2_del__c = true);
        insert contract3;
        
        Retail_Task__c contract4 = new Retail_Task__c(Account__c= account1.id,
                                          StartDate__c= date.today().addYears(-3),
                                          Duration__c= 61,
                                          Status__c  = 'Current',
                                          GFV__c = true,
                                          Annual_Call__c = true,
                                          Annual_Call_Task_3_del__c = true);
        insert contract4;
        
        Retail_Task__c contract5 = new Retail_Task__c(Account__c= account1.id,
                                          StartDate__c= date.today().addDays(1),
                                          Duration__c= 13,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          EOC_Call__c = true,
                                          EOC_Call_Task_1_del__c = true);
        insert contract5;
        
        Retail_Task__c contract6 = new Retail_Task__c(Account__c= account1.id,
                                          StartDate__c= date.today().addDays(1),
                                          Duration__c = 6,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          EOC_Call__c = true,
                                          EOC_Call_Task_2_del__c = true);
        insert contract6;
        
        Retail_Task__c contract7 = new Retail_Task__c(Account__c= account1.id,
                                          StartDate__c= date.today().addDays(1),
                                          Duration__c = 3,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          EOC_Call__c = true,
                                          EOC_Call_Task_3_del__c = true);
        insert contract7;
        
        Retail_Task__c contract22 = new Retail_Task__c(Account__c= account2.id,
                                          StartDate__c= date.today().addYears(-1),
                                          Duration__c = 37,
                                          Status__c = 'Current',
                                          GFV__c = true,
                                          Annual_Call__c = true,
                                          Annual_Call_Task_1_del__c = true);
        insert contract22;
        
        Retail_Task__c contract33 = new Retail_Task__c(Account__c= account2.id,
                                          StartDate__c= date.today().addYears(-2),
                                          Duration__c = 49,
                                          Status__c= 'Current',
                                          GFV__c = true,
                                          Annual_Call__c = true,
                                          Annual_Call_Task_2_del__c = true);
        insert contract33;
        
        Retail_Task__c contract44 = new Retail_Task__c(Account__c= account2.id,
                                           StartDate__c= date.today().addYears(-3),
                                          Duration__c = 61,
                                          Status__c= 'Current',
                                          GFV__c = true,
                                          Annual_Call__c = true,
                                          Annual_Call_Task_3_del__c = true);
        insert contract44;
        
        Retail_Task__c contract55 = new Retail_Task__c(Account__c= account2.id,
                                          StartDate__c= date.today().addDays(1),
                                          Duration__c = 13,
                                          Status__c= 'Current',
                                          GFV__c = true,
                                          EOC_Call__c = true,
                                          EOC_Call_Task_1_del__c = true);
        insert contract55;
        
        Retail_Task__c contract66 = new Retail_Task__c(Account__c= account2.id,
                                          StartDate__c= date.today().addDays(1),
                                          Duration__c = 6,
                                          Status__c= 'Current',
                                          GFV__c = true,
                                          EOC_Call__c = true,
                                          EOC_Call_Task_2_del__c = true);
        insert contract66;
        
        Retail_Task__c contract77 = new Retail_Task__c(Account__c= account2.id,
                                          StartDate__c= date.today().addDays(1),
                                          Duration__c = 3,
                                          Status__c= 'Current',
                                          GFV__c = true,
                                          EOC_Call__c = true,
                                          EOC_Call_Task_3_del__c = true);
        insert contract77;
        
     String jobId = System.schedule('ScheduledSharingContractToCROsTest', '0 0 6 * * ?', new ScheduledSharingContractToCROs());
    }
}