src/main/metadata-au/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Gender of the person 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is "Contact_Gender"</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer's address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is "Dealer_ZipCode"</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-retrieve/objects/Account.object
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>

src/main/metadata-au/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <description>Record type for person account</description>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/classes/ViewTaskControllerTest.cls
/*
    Type:       Test Class
    Purpose:    Test Class for ViewTaskController
    User Story: Data Sharing V1.0
    Used By:    
    ---------------------------------------------------------------
    History:
    
    1. Chaos Created on 2014-06-11
*/
@isTest
public class ViewTaskControllerTest {

    
    public static String personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    public static Account personAccount;
    public static Task historicalActivity1;
    public static Task historicalActivity2;
    public static Case cas;
    public static testMethod void testMyController() 
    {
    	
       
        createTestData();
        
        
       
        // Test Start from here
         Test.startTest();
            ViewTaskController con = new ViewTaskController(
        	new ApexPages.StandardController(personAccount));
        // Validate if 2 historical activity records have been found.
        Test.stopTest();
        System.assertEquals(historicalActivity1.Status, 'Closed');
        System.assertEquals(historicalActivity2.Status, 'Closed');
        System.assertEquals(con.wraps.size(), 2);
	}
    
    static void createTestData()
    {
         // Create Person Account
        personAccount = new Account();

        personAccount.RecordTypeId = personAccRecordTypeId; 
        personAccount.FirstName = 'Customer';
        personAccount.Gender__c = '0=Male';
        personAccount.ZipCode__c = '200235';
        personAccount.LastName = 'lastname';
        personAccount.Salutation = 'Unknown';
        personAccount.Individual_Home_Phone__c = '98958';
        personAccount.Email__c = 'abc@wrw.com';
        
        insert personAccount;
        
        // Prepare for the historical activity record
        // Create an activity for personAccount
        historicalActivity1 = new Task(WhatId = personAccount.Id);
        UtilTestData.createSobject(historicalActivity1, UtilTestData.TASK_RT_EDM);
        historicalActivity1.Status = 'Closed';
        update historicalActivity1;
        // Create Case
        cas = (Case)UtilTestData.createSobject(new Case(AccountId = personAccount.Id), UtilTestData.CASE_RT_MB_COMPLAINT);
        // Prepare for the second historical activity record
        //  Connect the case to activity record
        historicalActivity2 = new Task(WhatId = cas.Id);
        UtilTestData.createSobject(historicalActivity2, UtilTestData.TASK_RT_EDM);
        
        historicalActivity2.Status = 'Closed';
        update historicalActivity2;
    }
}