src/main/metadata-au/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Attribute in Data Dictionary object Contact is "Contact_CompanyName"</description>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is "Address_Province"
Attribute in Data Dictionary object Dealer is "Dealer_ProvinceEN"</description>
        <label>Province</label>
        <picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is "Contact_CustomerStatus"</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer's address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is "Dealer_ZipCode"</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <controllingField>Market__c</controllingField>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>Suburb</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
	IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
	IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',
        IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
        IF(ISPICKVAL($User.Market__c, 'MY'), 'MY',
	IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA')
	)))))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preferred</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Post Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
	
</CustomObject>  

src/main/metadata-au/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata-au/classes/Addresscontroller.cls
public class Addresscontroller{
//Variable declaration
public static list<Address__c> addresslist=new list<Address__c>();
public static boolean Preferred{get;set;}
public static string marketdiscriminator{get;set;}

//Constructor Called to get the current account record id
   public Addresscontroller(ApexPages.StandardController controller) {
        Preferred=true;
         if(ApexPages.currentPage().getParameters().get('id')!=Null)
          {
              addresslist=[select id,Name,Customer__c,Company_Name__c,MD__c,Preferred__c,City__c,Address_Type__c,Address_Line_1__c,Address_Line_2__c,Country__c,ZipCode__c,Province__c,Status__c,District__c 
                          from Address__c Where Customer__c=:ApexPages.currentPage().getParameters().get('id') AND Preferred__c=:true Limit 1]; 
             if(addresslist!=Null && !addresslist.isEmpty())
             {   
                 marketdiscriminator = addresslist.get(0).MD__c ;
                 Preferred=false; 
             }                               
          }
        }
        
  public Address__c getaddressList_details() {   
          if(addresslist!=Null && !addresslist.isEmpty())         
            return addresslist[0];        
          else
            return new Address__c();          
      }
       
}