src/main/metadata-au/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Presales__c</fullName>
        <description>Dealer PreSales Contact - updated by the GSSN system 
Read only in SFDC 
Rich text field with : Name (Chinese + English), Phone and Email</description>
        <label>Dealer Presales</label>
        <length>500</length>
        <type>Html</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Dealer_Complaint_Gate_Keeper__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Permission set:</inlineHelpText>
        <label>Dealer Complaint Gate Keeper</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Presales__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dealer Presales</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/classes/VehicleRelLookingControllerTest.cls
/*
    Type:       test class
    Purpose:    VehicleRelLookingController test class
    User Story: Release 1.2 Report S&M R006

    Used By:    VehicleRelLookingController
    ---------------------------------------------------------------
    History:

    9-Jun-2014 Sinow    Created
*/
@isTest(SeeAllData=true)
public class VehicleRelLookingControllerTest {
    public static testMethod void testVehicleRelLookingController ()
    {
    	Test.startTest();
        Account dealer = (Account)UtilTestData.createSobject(new Account(), UtilTestData.ACCOUNT_RT_DEALER);
        Contact conComplaint = new Contact(AccountId = dealer.Id, LastName = 'b', Phone = '1212313', email = 's@s.s', Dealer_Complaint_Gate_Keeper__c = true, Dealer_Presales__c = true);
        insert conComplaint;
        PageReference vehicleRelLooking = Page.VehicleRelLooking;
        vehicleRelLooking.getParameters().put('id',conComplaint.id);
        Test.setCurrentPage(vehicleRelLooking);
        VehicleRelLookingController extension = new VehicleRelLookingController();
        Test.stopTest();
        System.assertEquals(conComplaint.AccountId,dealer.Id);
        System.assert(conComplaint!=null);
    }
}