src/main/metadata-au/objects/Car_Model__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model info to be used in DM and Car Model comparison.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Abarth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alfa Romeo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aston Martin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austral Denning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bentley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Borcat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadillac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caterpillar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chevrolet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chrysler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citroen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corsa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daewoo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daihatsu</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Car Model</label>
    <nameField>
        <label>Car Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Model</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Car_Model__c</fullName>
        <label>Car Model</label>
        <length>200</length>
        <type>Text</type>
    </fields>
	
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
			
</CustomObject>

src/main/metadata-au/classes/InlineVFToShowVehicleDetailController.cls
public with sharing class InlineVFToShowVehicleDetailController 
{
    public Id leadId = ApexPages.currentPage().getParameters().get('id');
    list<Lead__c> leadList = new list<Lead__c>();
    public string GenericVehicleDetails {get;set;}
    public InlineVFToShowVehicleDetailController(ApexPages.StandardController controller) 
    {
        if(leadId != null)
        {
            leadList = [Select Id, Current_Vehicle__r.ModelYear__c, Current_Vehicle__r.Car_Model__c, Current_Vehicle__r.Car_Model__r.Name,
                        Current_Vehicle__r.Brand__c, Current_Vehicle__r.RecordTypeId, Current_Vehicle__c 
                        From Lead__c where Current_Vehicle__r.RecordType.DeveloperName = 'Competitor' and ID =: leadId and Current_Vehicle__c != null];
            if(!leadList.isEmpty() && leadList != null)
            {
                if(leadList[0].Current_Vehicle__c != null)
                {
                    if(leadList[0].Current_Vehicle__r.Brand__c != null && leadList[0].Current_Vehicle__r.Brand__c != '')
                    {
                        GenericVehicleDetails = leadList[0].Current_Vehicle__r.Brand__c;
                    }
                    if(leadList[0].Current_Vehicle__r.Car_Model__r.Name != null && leadList[0].Current_Vehicle__r.Car_Model__r.Name != '')
                    {
                        GenericVehicleDetails = GenericVehicleDetails  + ', ' + leadList[0].Current_Vehicle__r.Car_Model__r.Name;
                    }
                    if(leadList[0].Current_Vehicle__r.ModelYear__c != null && leadList[0].Current_Vehicle__r.ModelYear__c != '')
                    {
                        GenericVehicleDetails = GenericVehicleDetails  + ', ' + leadList[0].Current_Vehicle__r.ModelYear__c;
                    }
                }
            }
        }
    }
}