src/main/metadata-au/objects/Car_Model__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model info to be used in DM and Car Model comparison.</description>
    <fields>
        <fullName>Vehicle_Group__c</fullName>
        <label>Vehicle Group</label>
        <picklist>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Car Model</label>
    <nameField>
        <label>Car Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Model</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>Car_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car Model</label>
        <referenceTo>Car_Model__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All New A-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C63 AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-Class Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLA-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLA-Class Coupe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLC-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLK-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS63 AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLS Shooting Brake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concept Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E63 AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fighter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G55 AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G63 AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G65 AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GLA - Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GLC-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GL-Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GLE-Class</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_Group__c</fullName>
        <label>Vehicle Group</label>
        <picklist>
            <picklistValues>
                <fullName>Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>  

src/main/metadata-au/classes/TriggerVehicleTriggerHandler.cls
public class TriggerVehicleTriggerHandler 
    implements TriggerHandlerIf
{
    public void handleTrigger()
    {
        Map<Id,Vehicle__c> oldmap = (Map<Id,Vehicle__c>)trigger.oldmap;
        Map<Id,Vehicle__c> newmap = (Map<Id,Vehicle__c>)trigger.newmap;
        list<Vehicle__c> newVehicleList = (list<Vehicle__c>)trigger.new;
        
        Set<String> carClasses = new Set<String>();
    
        for(Vehicle__c newCar : newVehicleList){
            if(!carClasses.contains(newCar.Class__c)){
                carClasses.add(newCar.Class__c);
            }
        }
    
        Map<String,String> vehicleGroupMappings = new Map<String,String>();
        for(Car_Model__c vgm : [select Name, Vehicle_Group__c from Car_Model__c where Name in :carClasses]){
            String stringName = vgm.Name;
            stringName = stringName.toUpperCase();
            if(!vehicleGroupMappings.containsKey(stringName)){
                vehicleGroupMappings.put(stringName,vgm.Vehicle_Group__c);
            }
        }
        for(Vehicle__c newCar : newVehicleList){
            if(newCar.Class__c != null && newCar.Class__c != '')
            {
                String stringClass = newCar.Class__c;
                stringClass = stringClass.toUpperCase();
                newCar.Vehicle_Group__c = vehicleGroupMappings.get(stringClass);
            }
        }
    }
}