src/main/metadata-au/objects/Survey_Question__c.object
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/objects/SurveyQuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipName>Survey_Question_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Question Response</label>
    <nameField>
        <displayFormat>Response-{0000000}</displayFormat>
        <label>Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/classes/UtilSurveyQuestionResponse.cls
public class UtilSurveyQuestionResponse {
    public static void countSurveyQuestionResponseRecordsOnParent(List<SurveyQuestionResponse__c> listSqr){
        
        Set<String> sqrSet = new Set<String>();
        
        for(SurveyQuestionResponse__c sqrObj : listSqr){
            if(sqrObj.Survey_Question__c != null){
                sqrSet.add(sqrObj.Survey_Question__c);
            }
        }
        
        if(!sqrSet.isEmpty())
        {
           database.executeBatch(new BatchSurveyQuestionResponse(sqrSet), 2000);
        }
    }
}