src/main/metadata-retrieve/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_CN__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is &quot;Dealer_CityCN&quot;</description>
        <label>City CN</label>
        <picklist>
            <controllingField>Province__c</controllingField>
            <picklistValues>
                <fullName>七台河市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>万州区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>万盛区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>三亚市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>三明市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>三门峡市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>上海市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>上虞市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>上饶市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>东丽区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>东城区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>东城区东莞市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>东莞市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>东营市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>东阳市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>中卫市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>中山市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>丰台区</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>丰都县</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>临夏州</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>临汾市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>临沂市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>临沧市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>临海市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>丹东市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>丹阳市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>丽水市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>丽江市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>义乌市</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>乌兰察布市</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
        <picklist>
            <picklistValues>
                <fullName>Anhui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beijing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chongqing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fujian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gansu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangdong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guizhou</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hainan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hebei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heilongjiang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hongkong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hubei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inner Mongolia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangsu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiangxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jilin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liaoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Macau</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ningxia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qinghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shaanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shandong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sichuan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taiwan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-retrieve/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-retrieve/classes/TaskFailBlacklistTrigger_TestClass.cls
/*
    Type:       Test Class
    Purpose:    Task for updating account black list
    User Story: 	
    Used By:    
    ---------------------------------------------------------------
    History:
    
    10-July-2013 Stephano Shi (Breakingpoint)    Created
*/
@isTest
public class TaskFailBlacklistTrigger_TestClass{
    static testmethod void runTaskFailBlacklistTrigger(){
    	Map<String, Schema.RecordTypeInfo> accRecordTypeMap_test = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String, Schema.RecordTypeInfo> tkRecordTypeMap_test = Schema.SObjectType.Task.getRecordTypeInfosByName();
        Id accPerson_RecordTypeId = accRecordTypeMap_test.get('Person Account').getRecordTypeId();     	// Person Account.
        Id tkSMS_recordTypeId = tkRecordTypeMap_test.get('SMS').getRecordTypeId();
        
        // Person Contact                
        Account testPerAcc = new Account(LastName='TEST ACC',
                                      Type='Company',
                                      Status__c='VIP',
                                      Province__c='Shanghai',
                                      City_CN__c='Baoshan district',
                                      ZipCode__c='123456',
                                      PersonMobilePhone='12345678910',
                                      RecordTypeId=accPerson_RecordTypeId
                                     );        
        insert(testPerAcc);        
        
 		testPerAcc = [Select Id, PersonContactId From Account Where Id = :testPerAcc.Id]; 
		
        Task testSMSTask = new Task(Subject='SMS TEST',
                                    WhoId=testPerAcc.PersonContactId,
                                    Activity_Status__c='Sent'
        							);
        insert testSMSTask;
        
        testSMSTask.Activity_Status__c='Fail-Blacklist';
        
        update testSMSTask;
		        
    }
}