src/main/metadata-retrieve/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-retrieve/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Owner_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To indicates which dealer owns the vehicle relationship</description>
        <label>Owner Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship (Owner Dealer)</relationshipLabel>
        <relationshipName>Vehicle_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-retrieve/classes/VehicleDataSharingHandler.cls
public class VehicleDataSharingHandler extends SharingDataHandlerBase{

    private Id recordTypeRetail = 
        UtilRecordType.getRecordTypeIdByName('Vehicle_Relationship__c', 'Vehicle Relationship Retail');
    
    public VehicleDataSharingHandler() {
        super('Vehicle__c', 'Read');
    }

    public override void executeProcessByCRMCode(List<sObject> scope) {
        system.debug('I am runing');
        CMap dmsAndDealer = super.filterDealer(scope);
        dmsAndDealer.cleanLessThanTwoList();

        if(dmsAndDealer.KeySet().size() < 1){return;}
        
        Set<String> dealerIds = dmsAndDealer.values2();
        SYSTEM.debug('dmsAndDealer====:'+dmsAndDealer);

        //get user
        CMap userAndDealer = new CMap();
        for(user u : [Select u.Id, u.AccountId From User u 
                      WHERE AccountId in :dealerIds
                      and isActive = true]) {
            
            userAndDealer.add(u.AccountId, u.Id);
        }

        //get vehicle
        CMap vehicleAndDealer = new CMap();
        for(Vehicle_Relationship__c vrc: [Select v.Vehicle_ID__c, v.Owner_Dealer__c 
                                          From Vehicle_Relationship__c v
                                          WHERE recordTypeId = :recordTypeRetail
                                          and Owner_Dealer__c in :dealerIds]){
            vehicleAndDealer.add(vrc.Owner_Dealer__c, vrc.Vehicle_ID__c);
        }

        //make them use crm code
        for(String crmCode : dmsAndDealer.KeySet()){
            for(String accountid : dmsAndDealer.get(crmCode)){
                parentIds.addAll(crmCode, vehicleAndDealer.get(accountid));
                userOrGroupIds.addAll(crmCode, userAndDealer.get(accountid));
            }
        }

        List<sObject> shareRecs = makeInserRecords(parentIds, userOrGroupIds);

        try {
            List<Database.SaveResult> result = Database.insert(shareRecs,false);  
            system.debug('Success Amount: [' + result.size() +'] |  Is :' + result);            
        } catch (DmlException e) {
            system.debug('DML Exception: ' + e.getDmlMessage(0));
        }
  
    }

}