src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Required by business during the workshop, which exists in current avarto system ( 区号).</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_SR_Code__c</fullName>
        <label>Dealer DMS SR Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Branch_name__c</fullName>
        <label>Branch name (CHS)</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <label>City</label>
</CustomObject>

src/main/metadata/classes/GenericCSVLoaderControllerTest.cls
@isTest
public class GenericCSVLoaderControllerTest {
    
   private static Id acc3rdPartyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party').getRecordTypeId();
    private static Account customer;
    private static Account BranchName ;
                                    
    public static void preparedTestdata()
    {
    customer = new Account(Dealer_DMS_SR_Code__c='',
                                    Status__c='xCustomer',
                                    City__c='Beijing',
                                    Phone = '80801010',
                                    Area_code__c = '010',
                                    LastName = 'galaxy2',
                                    ZipCode__c='000000',
                                    Branch_name__c = '2014/06/05',
                                    File_Name__pc = 'C://User/folder',
                                    RecordTypeId=acc3rdPartyRecordTypeId);
                                   
    }        
    
    public static void preparedTestAccountdata()
    {
    BranchName = new Account(Dealer_DMS_SR_Code__c='',
                                    Status__c='xCustomer',
                                    City__c='Beijing',
                                    Phone = '80801010',
                                    Area_code__c = '010',
                                    LastName = 'galaxy2',
                                    ZipCode__c='000000',
                                     Branch_name__c = '2014-06-05',
                                    File_Name__pc = 'C://User/folder',
                                    RecordTypeId=acc3rdPartyRecordTypeId);
                                   
    }                        
    static testMethod void TestuploadAccounts() {
    preparedTestdata();
        List<Account> accs = new List<Account>();
        accs.add(customer);
        GenericCSVLoaderController.uploadObjects(accs);
       system.assert(accs!=null);
        system.assert(customer!=null);
    }
    
    static testMethod void TestuploadAccountsElseCondition() {
    preparedTestAccountdata();
        List<Account> accbranch = new List<Account>();
        accbranch .add(BranchName);
        GenericCSVLoaderController.uploadAccounts(accbranch );
        system.assert(accbranch!=null);
        system.assert(BranchName!=null);
    }
}