src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Aftersales_Manager_Email__c</fullName>
        <label>Dealer Aftersales Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: GS Code of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_GCcode &quot;</description>
        <label>Dealer GC Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Sales_Manager_Email__c</fullName>
        <description>Email of Sales Manager from GSSN</description>
        <label>Dealer Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer in regards of complaint 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Primary Case Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Dealer)</relationshipLabel>
        <relationshipName>Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Participating_Dealer__c.object
<CustomObject>
    <description>Campaign: Dealers that participate the campaign</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Participating Dealers</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participating Campaigns</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Participating Dealer</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <formula>Contact.Account.Dealer_GC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer GC Code</label>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/Batch_EmailNotification.cls
global class Batch_EmailNotification implements Database.Batchable<sObject> ,Database.stateful{
    global final Set<id> query;
    global Set<Id> partid=new Set<Id>();
     global List<Participating_Dealer__c> listpart=new List<Participating_Dealer__c>();
    global Batch_EmailNotification  (Set<id> q){
        query = q;
        system.debug('++++++++++++++++++'+query);
        
    }
    
     global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select id,Dealer__c,Dealer__r.Dealer_GC_Code__c,Campaign__c,Dealer__r.Dealer_Sales_Manager_Email__c,Dealer__r.Dealer_Aftersales_Manager_Email__c,Dealer__r.Name,ownerId from Participating_Dealer__c Where Campaign__c =:query ] );
    }
    global void execute(Database.BatchableContext BC, List<Participating_Dealer__c> scope){
    
    Set<Id> sid = New Set<Id>();
    Set<Id> DealerIds = New Set<Id>();
    Set<Id> ParticipateIds = New Set<Id>();
  List<Id> userIds = new List<Id>();
          Map<Id, Map<String, String>> AssignedDealers = new Map<Id, Map<String, String>>();
        Map<Id, List<User>> AssignedDealerRecipients = new Map<Id, List<User>>();
        Set<String> assignedDealerGCCodes = new Set<String>();
        Map<Id, User> AssignedUserMap = new Map<Id, User>();
  List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
   EmailTemplate templateId = [Select id from EmailTemplate where name = 'ListMaintenanceNotification']; 
     
  
     For(Participating_Dealer__c parDealer : scope){
          
          partid.add(parDealer.id);
             DealerIds.add(parDealer.Dealer__c);
             ParticipateIds.add(ParDealer.Id);
          
         assignedDealerGCCodes.add(parDealer.Dealer__r.Dealer_GC_Code__c);
                
                 Map<String, String> GcNdMap = new Map<String, String>();
            GcNdMap.put(parDealer.Dealer__r.Name, parDealer.Dealer__r.Dealer_GC_Code__c);
            AssignedDealers.put(parDealer.Id, GcNdMap);
           }
           
         List<User> userRecords = [Select id,Name,contact.accountId,email,Market__c,Dealer_GC_Code__c,Notification_Campaign__c from User where IsActive = True and contact.AccountId=:DealerIds and ((profile.Name='Japan Dealer Sales Manager') OR (profile.Name='Japan Dealer Service Manager') ) ];
            
            for(User us:userRecords)
            {
                AssignedUserMap.put(us.id,us);
            }
            List<User> userGccodeRecords = [Select id,Name,contact.accountId,email,Market__c,Dealer_GC_Code__c,Notification_Campaign__c from User where IsActive = True and Dealer_GC_Code__c IN : assignedDealerGCCodes];
         
              
        for (Id lid: AssignedDealers.keySet()) {
            List<User> leadAssignedDealerRecipientsList = new List<User>();
            for (User u: userGccodeRecords) {
                for (String assignedDealerName: AssignedDealers.get(lid).keySet()){
                    if (u.Dealer_GC_Code__c == AssignedDealers.get(lid).get(assignedDealerName)){
                        if (u.Notification_Campaign__c != Null){
                            List<String> outletNameList = u.Notification_Campaign__c.split(';');
                            for (String outletName: outletNameList){
                                if (outletName == assignedDealerName){
                                    leadAssignedDealerRecipientsList.add(u);
                                }
                            }
                        }
                    }
                }
            }
            AssignedDealerRecipients.put(lid, leadAssignedDealerRecipientsList);
        }
        /* If(DealerIds.size() >0){
             
          List<User> UseList = [Select id,profile.name,email,contactId,contact.AccountId from User where contact.AccountId=:DealerIds AND ((profile.Name='Japan Dealer Sales Manager') OR (profile.Name='Japan Dealer Service Manager') ) ]; 
          
          For(Participating_Dealer__c parDealer : Scope){
          For(User u : UseList  )
          { 
          
          If(u.contact.AccountId == parDealer.Dealer__c){
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         mail.saveAsActivity = false;
         mail.setTargetObjectId(u.Id);
       
         mail.setWhatId(parDealer.Id);
        
         mail.setTemplateID(templateId.Id); 
         mail.setUseSignature(false);
         mail.setSaveAsActivity(false);
              
       mails.add(mail); 
      }     
   }
       
         
    }
     Messaging.sendEmail(mails);
             
             
             
  
   } */
    
    
     sendMail(AssignedUserMap,AssignedDealerRecipients);     
    
    }
    
     //SENDING EMAILS TO SALES MANAGERS  
    public void sendMail(Map<Id, User> AssignedUserMap,Map<Id, List<User>> AssignedDealerRecipients){        
        List<Id> userIds = new List<Id>();
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        if(partid !=null)
        {
        listpart=[Select id,Dealer__c,Dealer__r.Dealer_GC_Code__c from Participating_Dealer__c where id=:partid];
        }
        
        EmailTemplate e =  [select id,name from EmailTemplate WHERE NAME =: 'ListMaintenanceNotification' limit 1];
        System.debug('@@@@@@@@@@@@@@AssignedDealerRecipients'+AssignedDealerRecipients);
        System.debug('@@@@@@@@@@@@@@AssignedUserMap'+AssignedUserMap);
        System.debug('@@@@@@@@@@@@@@AssignedDealerRecipients'+AssignedDealerRecipients);
        
        for(Participating_Dealer__c pd:listpart)
        {
       
         for(Id lid : AssignedUserMap.keySet()){ 
         for(user usd:AssignedUserMap.values())
         {
           
         if( usd.contact.AccountID==pd.Dealer__c && usd.id==lid)  
         {       
            if (AssignedUserMap.get(lid).Id != null){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.saveAsActivity = false;
                mail.setTargetObjectId(AssignedUserMap.get(lid).Id);
                mail.setTemplateId(e.Id);
                if (AssignedUserMap.get(lid).Market__c == 'JP'){
                    mail.setCharset('JIS');
                }
                mail.setUseSignature(false);
                mail.setWhatId(pd.id);
                mail.setSaveAsActivity(false);
                mails.add(mail);
            }
            }
            }
        }
        
        if(AssignedDealerRecipients !=null)
        {
        
        for(Id lid : AssignedDealerRecipients.keySet()){
             System.debug('@@@@@@@@@@@@@@AssignedDealerRecipients'+AssignedDealerRecipients);
            for (User u: AssignedDealerRecipients.get(lid)) {
                 System.debug('@@@@@@@@@@@@@@AssignedDealerRecipients'+AssignedDealerRecipients);
                if (u.Id != null  && u.Dealer_GC_Code__c==pd.Dealer__r.Dealer_GC_Code__c && pd.id==lid){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.saveAsActivity = false;
                    mail.setTargetObjectId(u.Id);
                    mail.setTemplateId(e.Id);
                    if (u.Market__c == 'JP'){
                        mail.setCharset('JIS');
                    }
                    mail.setUseSignature(false);
                    mail.setWhatId(pd.id);
                    mail.setSaveAsActivity(false);
                    mails.add(mail);
                }
            }
        }
           }
            }
           System.debug('@@@@@@@@@@@@@@mails '+mails );  
           if(mails !=null)
           {
           Messaging.sendEmail(mails);
           }  
        
        
       
    }
    
    global void finish(Database.BatchableContext BC){
       

}
    
    
    
    
    
    }