src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag to allow data sharing 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_DoCdata&quot;</description>
        <label>Allow Data Sharing</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Choice Yet</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City_CN__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is &quot;Dealer_CityCN&quot;</description>
        <label>City CN</label>
		<length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_SR_Code__c</fullName>
        <label>Dealer DMS SR Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Default_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Function:  Indicates that this dealer is unique and should be visible in SFDC.  Defined by the GSSN interface. 

Feb18-2013-  Rob and Falk - based on GSSN interface requirements</description>
        <label>Dealer Default Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Gender of the person 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_Gender&quot;</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Preferred language of individual 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_PreferredLanguage &quot;</description>
        <label>Preferred Language</label>
        <picklist>
            <picklistValues>
                <fullName>Mandarin Chinese</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantonese</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Data Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <formula>TEXT(Contact__r.Gender__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>*Gender</label>
        <type>Text</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/UtilAccount.cls
/**
** @Description Link Dealer to Dealer City by City and Province.
** Type:       Utility for TriggerAccount
** Created By: 
** Date: 2013-03-28
** Modified By : 
** Modified date : Updated on 2013-07-04 for US-Lead-009; 27-10-2015
** User Story: US-DS-001, US-Lead-009
** Used By:    TriggerAccount.trigger
**/

public class UtilAccount {
    // When Account Allow Data Sharing is True
	
	 /**	
     * @Description Based on the Query if allow data sharing field is updated or changed to yes then lead owner to dealer owner		 
     * @author  
     * @Date 10/27/2015(mm/dd/yy)
	 * @param  List of new accounts and map of Old accounts
	 * @return 
	 * @see  TriggerAccountTriggerHandler(UtilAccount.accountSetForUpdateLead)
	 */   
	 	 
    public static void accountSetForUpdateLead(List<Account> triggerNew,Map<id,Account> oldAcc){
        Set<Id> accIdSet = new Set<Id>();
        Set<Id> accIdSetForUpdateLead = new Set<Id>();
        if(triggerNew!=Null && !triggerNew.isEmpty()){
            for (Account newAcc : triggerNew) {             
                // US-Lead-009
                if(oldAcc!=Null && !oldAcc.isEmpty()){
                    if (newAcc.Allow_Data_Sharing__c != oldAcc.get(newAcc.Id).Allow_Data_Sharing__c) {
                        accIdSet.add(newAcc.Id);
                    }            
                    // US-DP-022, US-DP-023
                    if((newAcc.Allow_Data_Sharing__c == 'Yes' && newAcc.Allow_Data_Sharing__c != oldAcc.get(newAcc.Id).Allow_Data_Sharing__c) ||  
                       (newAcc.Gender__c != null && !String.isBlank(newAcc.Gender__c) && newAcc.Gender__c != oldAcc.get(newAcc.Id).Gender__c) ||
                       (newAcc.Province__c != null && !String.isBlank(newAcc.Province__c) && newAcc.Province__c != oldAcc.get(newAcc.Id).Province__c) ||
                       (newAcc.City_CN__c != null && !String.isBlank(newAcc.City_CN__c) && newAcc.City_CN__c != oldAcc.get(newAcc.Id).City_CN__c) ||
                       (newAcc.Preferred_Language__c != null && !String.isBlank(newAcc.Preferred_Language__c) && newAcc.Preferred_Language__c != oldAcc.get(newAcc.Id).Preferred_Language__c) ) {
                        accIdSetForUpdateLead.add(newAcc.Id);
                    }
                }
            }
          }
        // US-Lead-009
        if (accIdSet.size() > 0) {
            UtilAccount.updateLeadForDataSharing(accIdSet);
        }        
        // US-DP-022, US-DP-023
        if (accIdSetForUpdateLead.size() > 0) {
            AccountHelper.updateLeads(accIdSetForUpdateLead);
        }
    }       
    // US-Lead-009
	
	  
	
	 /**	
     * @Description  When Account Allow Data Sharing is True
     * @author  
     * @Date 10/27/2015(mm/dd/yy)
	 * @param  Set of Account Id's
	 * @return 
	 * @see   UtilAccount
	 */   
	
    public static void updateLeadForDataSharing(Set<Id> accIds) {
        List<Lead__c> leadList = 
            [SELECT Allow_Data_Sharing__c, Contact__r.Allow_Data_Sharing__c 
             FROM Lead__c WHERE Contact__c IN :accIds];

        for (Lead__c lead : leadList) {
            if (lead.contact__r.Allow_Data_Sharing__c == 'Yes') {
                lead.Allow_Data_Sharing__c = true;
            }
            else {
                lead.Allow_Data_Sharing__c = false;
            }
        }

        try {
            update leadList;
        }
        catch (DMLException e) {
            trigger.new[0].addError(e.getDMLMessage(0));
            System.debug('UtilAccount.updateLeadForDataSharing eXception: ' + e);
        }
    }
    	
	 /**	
     * @Description  DealerCodes Info for an Account. 
	 *				 It gets record counts from Vehichle relationShip which Contact is current Acount.
	 *				 Also fills in the Zip Code automatically based on the City
     * @author  
     * @Date 10/27/2015(mm/dd/yy)
	 * @param  Passing trigger Parameters.
	 * @return 
	 * @see   TriggerAccountTriggerHandler(UtilAccount.beforeAccDealerInfo)
	 */   
	 
   public static void beforeAccDealerInfo(List<Account> triggerNew,Map<id,Account> oldAcc,boolean isInsert,boolean isUpdate){
      
        
                List<String> dealerCodes = new List<String>();
        List<id> ids = new List<id>();
        List<String> citys = new List<String>();        
        Profile integrationProfile = [select Id from Profile where Name = 'IntegrationAPI'];
       
        for (Account curAcc : triggerNew) {        
            // "Dealer DMS SR Code 1" has a value and "Dealer Default Flag" 
            if (curAcc.Dealer_Default_Flag__c && String.isBlank(curAcc.Dealer_DMS_SR_Code__c)){
                if (isInsert) {
                    dealerCodes.add(curAcc.Dealer_DMS_SR_Code__c);
                }
                if (isUpdate) {  
                  if (oldAcc!=Null && !oldAcc.isEmpty()) {                    
                    if (oldAcc.get(curAcc.Id).Dealer_Default_Flag__c != curAcc.Dealer_Default_Flag__c ||
                         oldAcc.get(curAcc.Id).Dealer_DMS_SR_Code__c != curAcc.Dealer_DMS_SR_Code__c){
                         dealerCodes.add(curAcc.Dealer_DMS_SR_Code__c);
                    }
                  }
                }
            }    
            
            if ('Customer' == curAcc.Status__c && UserInfo.getProfileId() != integrationProfile.Id){
                //if(trigger.isInsert){
                    //ids.add(curAcc.id);
                //}
                if(isUpdate){ 
                   if(oldAcc!=Null && !oldAcc.isEmpty()){                  
                    if (oldAcc.get(curAcc.Id).Status__c != curAcc.Status__c){
                        ids.add(curAcc.id);
                     }
                   }
                }           
            }            
            if (!String.isBlank(curAcc.City_CN__c)){
                citys.add(curAcc.City_CN__c);
            }            
         }         
             
       /*Fill in the Zip Code automatically based on the City*/
        
        for(Account account : triggerNew){   
          if(oldAcc!=Null && !oldAcc.isEmpty()){         
            if(!isUpdate || account.City_CN__c != oldAcc.get(account.Id).City_CN__c){
                try{
                    City__c city = City__c.getInstance(account.City_CN__c);
                    account.ZipCode__c = city == null ? null:city.Zip__c;
                }
                catch (System.InvalidParameterValueException e){
                   	system.debug('DML Exception: ' + e.getMessage());
                }
            }
          }
        }   
   }
}