src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Block__c</fullName>
        <label>Block</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>Town</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
		IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
		IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA')))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Prefecture</label>
        <picklist>
            <picklistValues>
                <fullName>Hokkaido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aomori</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iwate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miyagi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamagata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukushima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ibaraki</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tochigi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gunma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saitama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tokyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kanagawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niigata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ishikawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamanashi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shizuoka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aichi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shiga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kyoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Osaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wakayama</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Post Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Address__c.object
	<fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
	<fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP', 
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'MY'), 'MY', 
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA'))))))</defaultValue>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
			IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;)))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/DM_Request__c.object
<CustomObject>
    <description>Case: Track the DM Request. This is also used by Campaign for bulk DM Request</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account, Person Account Manual Merge, Person Account Soft Deleted</value>
            </filterItems>
            <infoMessage>Search and select account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DM Request</relationshipLabel>
        <relationshipName>DM_Request</relationshipName>
        <type>Lookup</type>
    </fields>
     <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DM Request</label>
    <nameField>
        <displayFormat>DMR-{000000}</displayFormat>
        <label>DM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DM Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata4au/objects/DM_Request__c.object
    <fields>
        <fullName>City__c</fullName>
        <formula>Customer_Name__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/DMRequestHelperBase.cls
public with sharing class  DMRequestHelperBase {
    public static User Usr = [SELECT Id, Market__c,Profile.Name FROM User WHERE Id = : UserInfo.getUserId()];
      
      /**             
        * @Description: Update Address fields of DMRequest on Address type pickilist of DM request on Update of DM Request
        * @author     : sushma bharti
        * @Date       : 25/10/2016
        * @param      : list of new DMRequests, old map and some trigger evenets
        * @return     : void
        * @see:       : DMRequestHelperBase
        */
    
    public static void UpdateDMRequest(List<DM_Request__c> triggerNew,Map<ID,DM_Request__c> oldMap,boolean isUpdate,string market){
        set<id> CustomerId = new set<id>();  
        Map<id,map<string,Address__c>> addressMap =new Map<id,map<string,Address__c>>();
        map<string,Address__c> admap =new map<string,Address__c>();
        map<string,Address__c> promap = new map<string,Address__c>();
        string regexForNullValue ='null';
        string nullValue ='';
        String province;
         Set<String> province1=new set<String>();
        Map<String, String> addtrmapUpdate = UtilAddressTranslation.addtrmap;
        if(test.isrunningtest() && Usr.Profile.Name != 'IntegrationAPI' && Usr.Market__c !=null)
        {
            UtilAddressTranslation.gettranslatedvalues(Usr.Market__c);
        }
                 //get the accountIds 
                for(DM_Request__c lstDMR:triggerNew){
                    CustomerId.add(lstDMR.Customer_Name__c);
                }  
              
              
                 String str;
               for(Account s:[select id,MD__c From Account Where id =:CustomerId] )
               {
               
               str = s.MD__c;
               }
                if(!test.isrunningtest() && Usr.Profile.Name == 'IntegrationAPI' && usr.Market__c ==null && str!=null)
        {
        UtilAddressTranslation.gettranslatedvalues(str);
        }
                //query for arelated addresses and create a nested map
                for(Address__c addrlst:[select Customer__c,Address_Type__c,ZipCode__c,Province__c,City__c,District__c,Block__c,Address_Line_1__c,Address_Line_2__c,Address_Line_3__c,Company_Name__c,TitleOfHonor__c from Address__c where Customer__c IN:CustomerId])
                {
                    admap.put(addrlst.Address_Type__c, addrlst);
                    addressMap.put(addrlst.Customer__c, admap);
                } 
            
            for(DM_Request__c lstDMR:triggerNew){          
               
               if((lstDMR.Sending_Address__c!=null)&&(lstDMR.Sending_Address__c!='Temporary'))
               {
                   if(lstDMR.Sending_Address__c!=oldMap.get(lstDMR.id).Sending_Address__c)
                   {
                        if((addressMap.containsKey(lstDMR.Customer_Name__c))&&(addressMap.get(lstDMR.Customer_Name__c).containsKey(lstDMR.Sending_Address__c)))
                        {
                                if(addressMap.get(lstDMR.Customer_Name__c).get(lstDMR.Sending_Address__c).Address_Type__c==lstDMR.Sending_Address__c){                                                                       
                                    Address__c address = addressMap.get(lstDMR.Customer_Name__c).get(lstDMR.Sending_Address__c);
                                    lstDMR.Zip_Code__c=address.ZipCode__c;
                                    lstDMR.Address__c=address.Address_Line_1__c+' '+address.Address_Line_2__c+' '+address.Address_Line_3__c+' '+address.city__c+' '+address.District__c+' '+address.Province__c+' '+address.zipcode__c;
                                    lstDMR.Attention__c=address.Company_Name__c;
                                    lstDMR.TitleOfHonor__c=address.TitleOfHonor__c;
                                    if(addtrmapUpdate.containsKey(address.Province__c))
                                    {
                                       province = addtrmapUpdate.get(address.Province__c);
                                    }
                                    lstDMR.Province__c = province;
                                }
                                else{
                                    lstDMR.adderror(Label.DMRequest_validation_error);
                                }
                                lstDMR.Address__c=lstDMR.Address__c.replaceAll(regexForNullValue,nullValue);
                        }
                        else{
                                lstDMR.adderror(Label.DMRequest_validation_error);
                            }
                    
                  }
               }
                
            }  
        
    }
    
    /**             
        * @Description: Update Address fields of DMRequest on Address type pickilist of DM request on Insert of DM request
        * @author     : sushma bharti
        * @Date       : 25/10/2017
        * @param      : list of new DMRequests, old map and some trigger evenets
        * @return     : void
        * @see:       : DMRequestHelperBase
        */
    
    public static void InsertDMRequest(List<DM_Request__c> triggerNew,boolean isInsert,string market)
    {
        set<id> CustomerId = new set<id>();  
        Map<id,map<string,Address__c>> addressMap =new Map<id,map<string,Address__c>>();
        map<string,Address__c> admap =new map<string,Address__c>();
        map<string,Address__c> promap = new map<string,Address__c>();
        string regexForNullValue ='null';
        string nullValue ='';
        String province;
        Set<String> province1=new set<String>();
        Map<String, String> addtrmapInsert = UtilAddressTranslation.addtrmap;
        
          if(!test.isrunningtest() && Usr.Profile.Name != 'IntegrationAPI' && usr.Market__c !=null)
        {
        UtilAddressTranslation.gettranslatedvalues(Usr.Market__c);
        }
                 //get the accountIds 
                 if(triggerNew!=null)
                {
                for(DM_Request__c lstDMR:triggerNew){
                if(lstDMR.Customer_Name__c!=null)
                    {
                    CustomerId.add(lstDMR.Customer_Name__c);
                    province1.add(lstDMR.Md__c);
                    }
                }  
              }
               
               String str;
               for(Account s:[select id,MD__c From Account Where id =:CustomerId] )
               {
               
               str = s.MD__c;
               }
                if(!test.isrunningtest() && Usr.Profile.Name == 'IntegrationAPI' && usr.Market__c ==null && str!=null)
        {
        UtilAddressTranslation.gettranslatedvalues(str);
        }
                //query for arelated addresses and create a nested map
                for(Address__c addrlst:[select Customer__c,Address_Type__c,ZipCode__c,Province__c,City__c,District__c,Block__c,Address_Line_1__c,Address_Line_2__c,Address_Line_3__c,Company_Name__c,TitleOfHonor__c from Address__c where Customer__c IN:CustomerId])
                {
                    admap.put(addrlst.Address_Type__c, addrlst);
                    addressMap.put(addrlst.Customer__c, admap);
                } 
            if(triggerNew!=null)
                {
            for(DM_Request__c lstDMR:triggerNew){          
                
               if((lstDMR.Sending_Address__c!=null)&&(lstDMR.Sending_Address__c!='Temporary'))
               {                   
                   if((addressMap.containsKey(lstDMR.Customer_Name__c))&&(addressMap.get(lstDMR.Customer_Name__c).containsKey(lstDMR.Sending_Address__c)))
                        {
                                if(addressMap.get(lstDMR.Customer_Name__c).get(lstDMR.Sending_Address__c).Address_Type__c==lstDMR.Sending_Address__c){                                                                                                           
                                    Address__c address = addressMap.get(lstDMR.Customer_Name__c).get(lstDMR.Sending_Address__c);
                                    lstDMR.Zip_Code__c=address.ZipCode__c;
                                    lstDMR.Address__c=address.Address_Line_1__c+' '+address.Address_Line_2__c+' '+address.Address_Line_3__c+' '+address.city__c+' '+address.District__c+' '+address.Province__c+' '+address.zipcode__c;
                                    lstDMR.Attention__c=address.Company_Name__c;
                                    lstDMR.TitleOfHonor__c=address.TitleOfHonor__c;
                                    if(addtrmapInsert.containsKey(address.Province__c))
                                    {
                                       province = addtrmapInsert.get(address.Province__c);
                                    }
                                    lstDMR.Province__c = province;
                                }
                                else{
                                    lstDMR.adderror(Label.DMRequest_validation_error);
                                }
                                lstDMR.Address__c=lstDMR.Address__c.replaceAll(regexForNullValue,nullValue);
                        }
                        else{
                                lstDMR.adderror(Label.DMRequest_validation_error);
                            }                    
                  
               }
                
            }  
            }
        
    }
    
    public static list<DM_Material__Share> insertDMMaterialShareList = new list<DM_Material__Share>();
    public static void shareDMRequestRecordsWithDealer (list<DM_Request__c> dmRequestListNew, Map<ID, DM_Request__c> dmRequestlListOld, String market)
    {
        if(userinfo.getUserType() == 'PowerPartner')
        {
            list<DM_Request__Share> insertDMRequestShareList = new list<DM_Request__Share>();
            list<Id> userIdList = new list<Id>();
            set<string> dealerCompNdCodeSet = new set<string>();
            list<Group> dealerCompGroupList = new list<Group>();
            User currentUser = [select Id, Contact.Account.Dealer_Type__c, Contact.Account.Dealer_ND_Code__c from User where Id =: UserInfo.getUserId()];
            
            if(String.isNotBlank(currentUser.Contact.Account.Dealer_ND_Code__c)){
               String dealerndcode = currentUser.Contact.Account.Dealer_ND_Code__c;
               dealerCompGroupList = [select Id, Name from Group where Name = :dealerndcode];
               if(!dmRequestListNew.isEmpty() && dmRequestListNew != null)
                {
                    for(DM_Request__c dmRqtl : dmRequestListNew)
                    {
                        if(!dealerCompGroupList.isEmpty() && dealerCompGroupList != null)
                        {
                            for(group grp : dealerCompGroupList)
                            {
                                DM_Request__Share dmRqtShare = new DM_Request__Share();
                                dmRqtShare.ParentId = dmRqtl.Id;
                                dmRqtShare.AccessLevel = 'Edit';
                                dmRqtShare.UserOrGroupId = grp.Id;
                                insertDMRequestShareList.add(dmRqtShare);
                            }
                        }
                    }
                }
            }
            system.debug('*$*$*$*$* insertDMRequestShareList  ' + insertDMRequestShareList);
            if(!insertDMRequestShareList.isEmpty() && insertDMRequestShareList != null)
            {
                DMLManagerService.InsertAsSystem(insertDMRequestShareList);
            }
        }
        else{
            list<DM_Request__Share> insertDMRequestShareList = new list<DM_Request__Share>();
            list<Id> userIdList = new list<Id>();
            set<Id> ownerIdSet = new set<Id>();
            set<string> dealerCompNdCodeSet = new set<string>();
            list<Group> dealerCompGroupList = new list<Group>();
            List<DM_Request__c> lDMRqt = new List<DM_Request__c>([Select id, Assigned_Dealer__r.Dealer_ND_Code__c, Actual_DM_Material1__c, Actual_DM_Material2__c, Actual_DM_Material3__c, Expected_DM_Material1__c, Expected_DM_Material2__c, Expected_DM_Material3__c from DM_Request__c where ID in :dmRequestListNew]);
            Map<ID, String> mDMRqtToDealerND = new Map<ID, String>();
            for(DM_Request__c dmRqtl : lDMRqt){
                if((Trigger.isInsert && dmRqtl.Assigned_Dealer__c != NULL) || (Trigger.isUpdate && dmRqtl.Assigned_Dealer__c != NULL && dmRqtl.Assigned_Dealer__c != dmRequestlListOld.get(dmRqtl.ID).Assigned_Dealer__c)){
                    mDMRqtToDealerND.put(dmRqtl.ID, dmRqtl.Assigned_Dealer__r.Dealer_ND_Code__c);
                }       
            }
            if(!mDMRqtToDealerND.isEmpty()){
                dealerCompGroupList = [select Id, Name from Group where Name in :mDMRqtToDealerND.values()];
                if(!dealerCompGroupList.isEmpty() && dealerCompGroupList != NULL){
                    Map<String, ID> mGroupNameToID = new Map<String, ID>();
                    for(Group grp : dealerCompGroupList){
                        mGroupNameToID.put(grp.name, grp.ID);
                    }
                    if(!mGroupNameToID.isEmpty()){
                        for(DM_Request__c dmRqst : lDMRqt){
                            DM_Request__Share dmRequestShare = new DM_Request__Share();
                            dmRequestShare.ParentID = dmRqst.ID;
                            dmRequestShare.AccessLevel = 'EDIT';
                            dmRequestShare.UserOrGroupID = mGroupNameToID.get(dmRqst.Assigned_Dealer__r.Dealer_ND_Code__c);
                            insertDMRequestShareList.add(dmRequestShare);
                            if((Trigger.isInsert && dmRqst.Actual_DM_Material1__c != NULL) || (Trigger.isUpdate && dmRqst.Actual_DM_Material1__c != NULL && dmRqst.Actual_DM_Material1__c != dmRequestlListOld.get(dmRqst.ID).Actual_DM_Material1__c))
                            addDMMaterialShareRecordToList(dmRqst.Actual_DM_Material1__c, mGroupNameToID.get(dmRqst.Assigned_Dealer__r.Dealer_ND_Code__c)); 
                            if((Trigger.isInsert && dmRqst.Actual_DM_Material2__c != NULL) || (Trigger.isUpdate && dmRqst.Actual_DM_Material2__c != NULL && dmRqst.Actual_DM_Material2__c != dmRequestlListOld.get(dmRqst.ID).Actual_DM_Material2__c))
                            addDMMaterialShareRecordToList(dmRqst.Actual_DM_Material2__c, mGroupNameToID.get(dmRqst.Assigned_Dealer__r.Dealer_ND_Code__c));
                            if((Trigger.isInsert && dmRqst.Actual_DM_Material3__c != NULL) || (Trigger.isUpdate && dmRqst.Actual_DM_Material3__c != NULL && dmRqst.Actual_DM_Material3__c != dmRequestlListOld.get(dmRqst.ID).Actual_DM_Material3__c))
                            addDMMaterialShareRecordToList(dmRqst.Actual_DM_Material3__c, mGroupNameToID.get(dmRqst.Assigned_Dealer__r.Dealer_ND_Code__c));
                            if((Trigger.isInsert && dmRqst.Expected_DM_Material1__c != NULL) || (Trigger.isUpdate && dmRqst.Expected_DM_Material1__c != NULL && dmRqst.Expected_DM_Material1__c != dmRequestlListOld.get(dmRqst.ID).Expected_DM_Material1__c))
                            addDMMaterialShareRecordToList(dmRqst.Expected_DM_Material1__c, mGroupNameToID.get(dmRqst.Assigned_Dealer__r.Dealer_ND_Code__c));
                            if((Trigger.isInsert && dmRqst.Expected_DM_Material2__c != NULL) || (Trigger.isUpdate && dmRqst.Expected_DM_Material2__c != NULL && dmRqst.Expected_DM_Material2__c != dmRequestlListOld.get(dmRqst.ID).Expected_DM_Material2__c))
                            addDMMaterialShareRecordToList(dmRqst.Expected_DM_Material2__c, mGroupNameToID.get(dmRqst.Assigned_Dealer__r.Dealer_ND_Code__c));
                            if((Trigger.isInsert && dmRqst.Expected_DM_Material3__c != NULL) || (Trigger.isUpdate && dmRqst.Expected_DM_Material3__c != NULL && dmRqst.Expected_DM_Material3__c != dmRequestlListOld.get(dmRqst.ID).Expected_DM_Material3__c))
                            addDMMaterialShareRecordToList(dmRqst.Expected_DM_Material3__c, mGroupNameToID.get(dmRqst.Assigned_Dealer__r.Dealer_ND_Code__c));
                        }
                        
                        if(insertDMRequestShareList != NULL && !insertDMRequestShareList.isEmpty()){
                            DMLManagerService.InsertAsSystem(insertDMRequestShareList);
                        }
                        if(insertDMMaterialShareList != NULL && !insertDMMaterialShareList.isEmpty()){
                            DMLManagerService.InsertAsSystem(insertDMMaterialShareList);
                        }   
                    }
                }
            }
        }
    }
    
    public static void addDMMaterialShareRecordToList(ID DMMaterialID, ID UserGroupID){
        DM_Material__Share dmMtrlShare = new DM_Material__Share();
        dmMtrlShare.ParentId = DMMaterialID;
        dmMtrlShare.AccessLevel = 'Edit';
        dmMtrlShare.UserOrGroupId = UserGroupID;
        insertDMMaterialShareList.add(dmMtrlShare);
    }
}