src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Flag for this dealer
Attribute in Data Dictionary object Dealer is &quot;Dealer_ActiveFlag&quot;</description>
        <label>Dealer Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_CRM_Code__c</fullName>
        <description>Used for dealer mapping</description>
        <label>Dealer DMS CRM Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Lead_Gate_Keeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Mouse Liu 
Used by: Lead__c (US-Lead-15) 
Function: Used in Email Template

Used in: 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>*Dealer Lead Gate Keeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Vehicle_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by Central Complaint Case. Need Clarification</description>
        <label>Vehicle Relationship</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account must be the same as Vehicle Relationship Account</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Vehicle_Relationship__c.Contact__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle_Relationship__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/*
Created by:  Chris.Huang
Used by:  Chris.Huang
Function:
Used in: Page Layouts, Reports 

Modify History
Modify By: 
Modify Reason: 
*/</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata4au/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Dealer_Complaint_Gate_Keeper__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Permission set:</inlineHelpText>
        <label>Dealer Complaint Gate Keeper</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Lead_Gate_Keeper__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Permission set: clues</inlineHelpText>
        <label>Dealer Lead Gate Keeper</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To indicates which dealer owns the vehicle relationship</description>
        <label>Owner Dealer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship (Owner Dealer)</relationshipLabel>
        <relationshipName>Vehicle_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-excluded/classes/TestBatchSharingAccountOfretailVR.cls
@isTest
public with sharing class TestBatchSharingAccountOfretailVR {
    static Id recordTypeRetail = 
        Schema.SObjectType.Vehicle_Relationship__c.getRecordTypeInfosByName().get('Vehicle Relationship Retail').getRecordTypeId();

    static List<Account> accounts = new List<Account>();
    static List<Contact> contacts = new List<Contact>();
    static List<Vehicle__C> cars = new List<Vehicle__C>();
    static List<Vehicle_Relationship__c> vehicleRelates = 
            new List<Vehicle_Relationship__c>();
    static List<User> newUsers = new List<User>();  
	static List<Account> dealers = new List<Account>();
    static User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
    static List<Profile> profileIds = [
                Select Id 
                From Profile 
                Where Name ='Dealer-Complaint Manager'];

	@isTest
    static void testA() {
        // TO DO: implement unit test
        //initialData();
      
        List<Account> dealerst = new List<Account>();
        Map<String, Sobject> dealerA = createDealer('KL');
        dealerst.add((Account)dealerA.get('Account'));
        Map<String, Sobject> dealerB = createDealer('KL');
        dealerst.add((Account)dealerB.get('Account'));
        Map<String, Sobject> dealerC = createDealer('AF');
        dealerst.add((Account)dealerC.get('Account'));        
        /**

        Map<String, Sobject> dealerD = createDealer('AF');
        dealerst.add((Account)dealerD.get('Account'));        
        Map<String, Sobject> dealerE = createDealer('DE');
        dealerst.add((Account)dealerE.get('Account'));        
        Map<String, Sobject> dealerF = createDealer('ED');
        dealerst.add((Account)dealerF.get('Account'));        
*/
		Test.StartTest();
		
		List<Account> accountsT = new List<Account>();
		for(integer i = 0; i< 2; i++) {
			Account personAccountA = (Account)UtilTestData.createSobject(new Account(), 
	                UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
	        accountsT.add(personAccountA);
			Vehicle_Relationship__c vrc = new Vehicle_Relationship__c();
	        String retailRvId = recordTypeRetail; 
        
	        vrc.RecordTypeId = retailRvId;
	        vrc.Contact__c = personAccountA.id;
	        vrc.Owner_Dealer__c =dealerst[i].id;
        
       		insert vrc;

		}
		
		system.debug('ready to excuteBatch');
                    
        BatchSharingAccountOfretailVR batch1 = new BatchSharingAccountOfretailVR();
        ID batchprocessid = Database.executeBatch(batch1);
        system.debug(batchprocessid);
        //id bLeadKeeperId = dealerB.get('LeadKeeper').id;
        Test.StopTest();
        
        system.assertEquals(1, [select id from AccountShare where AccountId = :accountsT[0].id and  userorgroupid = :dealerb.get('LeadKeeper').id].size());
        system.assertEquals(0, [select id from AccountShare where AccountId = :accountsT[0].id and userorgroupid = :dealerC.get('LeadKeeper').id].size());
        

    }

    /**
     * Create a Dealer and retrun a Map contains info of the dealer
     * key: Account , return account object
     * key: ComplaintKeeper, return case keeper user
     * key: LeadKeeper, return lead keeper user
     *
     */    
    private static Map<String, Sobject> createDealer(String crmCode){
        
        Map<String, Sobject> rtnDealerInfo = new Map<String, Sobject>();
        
        //Following is Create Dealer info
        //A and B have same CRM code
		Account dealer = (Account)UtilTestData.createSobject(new Account(), 
                UtilTestData.ACCOUNT_RT_DEALER);

        dealer.Dealer_Active__c = true;
        dealer.Dealer_DMS_CRM_Code__c = crmCode;
        update dealer;
        rtnDealerInfo.put('Account', dealer);
        
        //AccountA contact
        List<Contact> dealerContacts = new List<Contact>();

        for (integer i = 0; i<4 ; i++){
            //Contact
            Contact contact = (Contact)UtilTestData.createSobject(new Contact(), 
                '');
            contact.AccountId = dealer.id;
            if(i==0){
            	contact.Dealer_Complaint_Gate_Keeper__c = true;
            }
            if(i==1){
            	contact.Dealer_Lead_Gate_Keeper__c = true;
            }

        	dealerContacts.add(contact);
        }
        
        update dealerContacts;
        
        //Create users
        integer i = 0;
        List<User> newUsers1 = new List<User>();  
        System.runAs ( thisUser ) {
            
            for(Contact c: dealerContacts){
                User usr = new User();
                usr.UserName = 'test' + Math.rint(Math.random() * 100000) + '@daimler.com';
                usr.ProfileId = profileIds[0].Id;
                usr.LastName = 'Test User';
                usr.Email = 'test001@daimler.com.full';
                usr.Alias = 'test';
                usr.TimeZoneSidKey = 'Asia/Shanghai';
                usr.EmailEncodingKey = 'UTF-8';
                usr.LanguageLocaleKey = 'en_US';
                usr.localesidkey='en_US';
                usr.contactId = c.ID;
                i++;
                newUsers1.add(usr);
            }
            
            insert newUsers1;

        }
        
         rtnDealerInfo.put('ComplaintKeeper', newUsers1[0]);
         rtnDealerInfo.put('LeadKeeper', newUsers1[1]);
    	 
    	 return rtnDealerInfo;
    }

}