src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: GS Code of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_GCcode &quot;</description>
        <label>Dealer GC Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Task__c.object
<CustomObject>
    <fields>
        <fullName>Contractor_Address1__c</fullName>
        <label>Address (kanji)-Actual</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contractor_Name_Native__c</fullName>
        <label>Contractor Name (katakana)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contractor_Name__c</fullName>
        <label>Contractor Name (kanji)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contractor_ZipCode1__c</fullName>
        <label>Zip Code-Actual</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor1_ZipCode__c</fullName>
        <label>Guarantor1 Zip Code - actual</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latest_Sales_Person__c</fullName>
        <label>Sales Person</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_Owner_Address__c</fullName>
        <label>MOT Owner Address</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_Owner_Name_Native__c</fullName>
        <label>MOT Owner Name Native</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_Owner_Name__c</fullName>
        <label>MOT Owner Name</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_User_Address__c</fullName>
        <label>MOT User Address</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_User_Name_Native__c</fullName>
        <label>MOT User Name Native</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_User_Name__c</fullName>
        <label>MOT User Name</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_User_Phone__c</fullName>
        <label>MOT User Phone</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOT_User_Postal__c</fullName>
        <label>MOT User Postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Dealer</label>
         <lookupFilter>
            <active>true</active>
			<booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please select the proper dealer account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>			
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>IntegrationAPI</value>
            </filterItems>
            <infoMessage>Search and select dealer account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retail Tasks</relationshipLabel>
        <relationshipName>Retail_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Registration_No__c</fullName>
        <label>Vehicle Registration No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Retail Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Tasks</pluralLabel>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <formula>Contact.Account.Dealer_GC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer GC Code</label>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>User_Type__c</fullName>
        <description>Pick-list to represent user&apos;s type (MBJ, MBF, External System, Dealer)</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MBJ</fullName>
                </value>
                <value>
                    <fullName>MBF</fullName>
                </value>
                <value>
                    <fullName>External System</fullName>
                </value>
                <value>
                    <fullName>Dealer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/dealerViewForContract.cls
public without sharing class dealerViewForContract
{
public Retail_Task__c retail{get;set;}
public Retail_Task__c displayRetail{get;set;}
public User us1{get;set;}
public String alkID{get;set;}
public String MotuserName{get;set;}
public String MotuserNameNative{get;set;}
public String AddressActual{get;set;}
public String MotuserPostal{get;set;}
public String MotuserAddress{get;set;}
public String MotuserPhone{get;set;}
public String MotownerName{get;set;}
public String MotuserownerNameNative{get;set;}
public String MotOwnerAddress{get;set;}

public dealerViewForContract(ApexPages.StandardController controller) {
     retail=new Retail_Task__c ();
     displayRetail=new Retail_Task__c ();
     alkID=ApexPages.currentPage().getParameters().get('id');
     us1 = [select id,ContactID,Dealer_GC_Code__c,User_Type__c from User WHERE Id =:UserInfo.getUserId()];
     if(alkID!=null)
     {
        retail = [select id,Latest_Sales_Person__c,Guarantor1_ZipCode__c,recordtype.Name,Contractor_Name__c,Related_Dealer__c,Related_Dealer__r.Dealer_GC_Code__c,Contractor_Name_Native__c,Vehicle_Registration_No__c,Contractor_ZipCode1__c,Contractor_Address1__c,MOT_User_Name__c,MOT_User_Name_Native__c,MOT_User_Postal__c,MOT_User_Address__c,MOT_User_Phone__c,MOT_Owner_Name__c,MOT_Owner_Name_Native__c,MOT_Owner_Address__c from Retail_Task__c WHERE ID = :alkID];
      
       }
        
   
    if((us1.ContactId ==null) && ((us1.User_Type__c == 'MBF')||(us1.User_Type__c == 'MBJ'))  && retail!=null)
        { 
           displayRetail= [select Latest_Sales_Person__c,Related_Dealer__c,Guarantor1_ZipCode__c,Contractor_Name__c,Contractor_Name_Native__c,Vehicle_Registration_No__c,Contractor_ZipCode1__c,Contractor_Address1__c,MOT_User_Name__c,MOT_User_Name_Native__c,MOT_User_Postal__c,MOT_User_Address__c,MOT_User_Phone__c,MOT_Owner_Name__c,MOT_Owner_Name_Native__c,MOT_Owner_Address__c from Retail_Task__c where id=:alkId and recordtype.Name='Contract'];
           
        }  
        system.debug('$%$%$%%$ us1.ContactId '+us1.ContactId );
        system.debug('&*&*&*&*& us1.User_Type__c'+us1.User_Type__c);
        system.debug('8978787878787&&&&&'+retail.Related_Dealer__r.Dealer_GC_Code__c);
        system.debug('us1.Dealer_GC_Code__c^&^&^'+us1.Dealer_GC_Code__c);
        system.debug('us1.retail'+retail);

        
        if((us1.ContactId !=null) &&(us1.User_Type__c == 'Dealer') && (retail.Related_Dealer__r.Dealer_GC_Code__c == us1.Dealer_GC_Code__c) && retail!=null)
        { 
        if(alkID!=null)
     {
        retail = [select id,Latest_Sales_Person__c,Guarantor1_ZipCode__c,recordtype.Name,Contractor_Name__c,Related_Dealer__c,Related_Dealer__r.Dealer_GC_Code__c,Contractor_Name_Native__c,Vehicle_Registration_No__c,Contractor_ZipCode1__c,Contractor_Address1__c,MOT_User_Name__c,MOT_User_Name_Native__c,MOT_User_Postal__c,MOT_User_Address__c,MOT_User_Phone__c,MOT_Owner_Name__c,MOT_Owner_Name_Native__c,MOT_Owner_Address__c from Retail_Task__c WHERE ID = :alkID];
      if(retail !=null && retail.recordtype.Name=='Contract' && us1.ContactId !=null)
       {
       MotuserName=retail.MOT_User_Name__c;
       
       AddressActual=retail.Contractor_Address1__c;
      
       MotuserNameNative=retail.MOT_User_Name_Native__c;
       
       MotuserAddress=retail.MOT_User_Address__c;
      
       MotownerName=retail.MOT_Owner_Name__c;
       
       MotuserPostal=retail.MOT_User_Postal__c;
       
       MotuserPhone=retail.MOT_User_Phone__c;
       
       MotuserownerNameNative=retail.MOT_Owner_Name_Native__c;
       
       MotOwnerAddress=retail.MOT_Owner_Address__c ;
       }
       }
        system.debug('Testing');
           displayRetail= [select Latest_Sales_Person__c,Guarantor1_ZipCode__c,Related_Dealer__c,Contractor_Name__c,Contractor_Name_Native__c,Vehicle_Registration_No__c,Contractor_ZipCode1__c,Contractor_Address1__c,MOT_User_Name__c,MOT_User_Name_Native__c,MOT_User_Postal__c,MOT_User_Address__c,MOT_User_Phone__c,MOT_Owner_Name__c,MOT_Owner_Name_Native__c,MOT_Owner_Address__c from Retail_Task__c where id=:alkId and recordtype.Name='Contract'];
            system.debug('Testing+displayRetail'+displayRetail);

        }    
    }
}