src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Source of the contact to find out about us (first time) 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_DataSource&quot;</description>
        <label>Data Source</label>
        <picklist>
            <picklistValues>
                <fullName>Partners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd party data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web/Mobile Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mercedes-Benz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mercedes-Benz DrivingAcademy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBAFC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mercedes - Benz Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friends recommend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Searching engine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB website</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Gender of the person 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_Gender&quot;</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Main_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Main Aftersales Dealer for this contact 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_MainDealer&quot;</description>
        <label>Main Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Main Dealer)</relationshipLabel>
        <relationshipName>Main_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Allow_Data_Sharing2__c</fullName>
        <label>Allow Data Sharing</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No Choice Yet</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email2</label>
        <type>Email</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email3__c</fullName>
        <label>Other E-Mail</label>
        <type>Email</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>LastName_Native_1__c</fullName>
        <label>Last Name Native</label>
        <length>40</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Portal_Apply_Date__c</fullName>
        <label>Portal Apply Date</label>
        <type>Date</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Portal_Apply_Status__c</fullName>
        <description>The info to identify the Account to register MyM Accont.</description>
        <label>Portal Apply Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>To be Sent</fullName>
                </value>
                <value>
                    <fullName>Waiting for confirmation</fullName>
                </value>
                <value>
                    <fullName>none</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Portal_Apply_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Apply User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Portal_Email__c</fullName>
        <label>Portal Mail Address</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>Portal_Email__c</fullName>
        <label>Portal E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Portal_ID__c</fullName>
        <label>My Mercedes Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Dealer Type</label>
        <picklist>
            <picklistValues>
                <fullName>My Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Selling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Servicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign/Project Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Shops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>Mercedes Me Portal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fromRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links (Contact to Contact)</relationshipLabel>
        <relationshipName>Account_Links1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>toRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links(External Link)</relationshipLabel>
        <relationshipName>Account_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <recordTypes>
        <fullName>ContactSector</fullName>
        <active>true</active>
        <description>To link customer records with dealer records.</description>
        <label>ContactSector</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/classes/CustomerMymercInterfaceController.cls
/************************************************************
LastModifiedDate : May 10, 2017
LastModifiedBy   : Lokesh M
Related JIRA     : SFDCJP-2100,SFDCJP-2000
************************************************************/

public with sharing class CustomerMymercInterfaceController {
    
    public list<Account_Link__c> acclist{get;set;}    
    public Id Accid;
    public id IndividualCustomerExternaLink;
    public id ContactSector;
    public list<Account_Link__c> accl{get;set;}
    public Account_Link__c AclinkPop{get;set;}
    public list<Account_Link__c> aclsize;
    public account accont{get;set;}
    public boolean result;
    public boolean displayPopup{get;set;}
    public string myMercId{get;set;}
    public string MyMercEmail{get;set;}
    public string RegOutlet{get;set;}
    public boolean MyMercVar{get;set;}
    public boolean MyMercEmailVar{get;set;}
    public boolean ContactSectorvar{get;set;}
    public string returnvalue{get;set;}
    public String FinalEmail{get;set;}
    public String AcId;
    public String aclId;
    public String emailRegEx = '[ァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヰヱヲンヴヵヶ－ー]+';
    public Account_Link__c aLink{get;set;}
    public User usr = new user();
    
    public CustomerMymercInterfaceController(ApexPages.StandardController controller) {
        usr = [Select Id,name,contact.AccountId from User WHERE ID =: UserInfo.getUserId() ];
        MyMercVar = false;
        MyMercEmailVar = true;
        RegOutlet  = 'No';
        ContactSectorvar = true;
        RecordType rec = [select id from RecordType where sObjecttype = 'Account_Link__c' AND Name = 'ContactSector' limit 1];
        ContactSector = rec.Id;
        aclsize = new list<Account_Link__c>();
        Accid = apexpages.currentpage().getparameters().get('id');
        aclsize  = [select id, toRole__c  from Account_Link__c where toRole__c =: Accid ];
        if(aclsize.size() >0)
            accl = [select id,name,fromRole__r.Name,fromRole__r.Email2__c,fromRole__r.Email__c,Portal_ID__c,System__c,RecordtypeId,Primary__c,Portal_Email__c,toRole__c from Account_Link__c where toRole__c =: Accid ];
        accont = [select id,Data_Source__C, Allow_Data_Sharing2__c,Gender__c,Main_Dealer__c,RecordtypeId,email3__c,Portal_Apply_Date__c,Portal_Apply_Status__c,Portal_Apply_User__c,LastName_Native_1__c,PersonBirthdate,Email2__c,email__c,(select id,name,fromRole__r.Name,fromRole__r.Email2__c,fromRole__r.Email__c,Portal_ID__c,System__c,RecordtypeId,Primary__c,Portal_Email__c,toRole__c from Account_Links__r) from account where id =: Accid limit 1];
        if(accl != null && !accl.isEmpty())
        {
            for(Account_Link__c acc: accl){
                if(acc.System__c == 'My Mercedes'){
                    myMercId = acc.name;
                    MyMercVar = true;
                    MyMercEmailVar = false;
                    ContactSectorvar = false;
                    aclId = acc.Id;
                    if(string.IsnotBlank(acc.Portal_Email__c)){
                        MyMercEmail = acc.Portal_Email__c;        
                    }
                }
            }
        }
        for(Account_Link__c acclink: accont.Account_Links__r){
            if(acclink.fromRole__c !=null && acclink.toRole__c !=null && acclink.RecordtypeId == ContactSector){
                RegOutlet = 'Yes';
                ContactSectorvar = true;
            }
        } 
   }

     public pagereference createContractSector()
     {
         //user usr =[select id,profileId,contactId,Contact.AccountId from user where id =: userinfo.getUserId()];
         Profile po = [SELECT Id,UserLicense.Name FROM Profile where id =: usr.profileId];         
         if(po.UserLicense.Name == 'Partner Community') {
         Contact con  = [select id,AccountId from Contact where Id =: usr.contactId ];
         Account_Link__c acc = new Account_Link__c ();
         acc.RecordtypeId = ContactSector;
         acc.Status__c = 'My Shops';
         acc.toRole__c = Accid; //con.AccountId;
         acc.name= '販売店関係情報';
         acc.fromRole__c = usr.contact.accountId;
         if(acc != null)
         insert acc;
       pagereference pr = new pagereference ('/'+Accid);
       pr.setRedirect(true);
       return pr;
         }
         else
         {
             Account_Link__c acc = new Account_Link__c ();
         acc.RecordtypeId = ContactSector;
         acc.Status__c = 'My Shops';
         acc.toRole__c = Accid;
         acc.name= '販売店関係情報';
         if(acc != null)
         insert acc;
       pagereference pr = new pagereference ('/'+Accid);
       pr.setRedirect(true);
       return pr;
             
         }
     }
 
     public void closePopup()
     {       
         displayPopup = false;   
     }    
     public void showPopup()
     {     
         String aID= apexpages.currentpage().getParameters().get('recordID');   
        aLink = [select id,fromRole__r.Email2__c,fromRole__r.Email__c,Portal_Email__c,toRole__r.Email3__c,toRole__r.Email2__c,toRole__r.Email__c from Account_Link__c where ID=:aID limit 1];
        displayPopup = true;   
     } 
        
    public pagereference savepop()
    {
        if( MyMercEmail == NULL || string.isBlank(MyMercEmail)){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'please input "My Mercedes Email Id"'));
            return null;
        } 
        else{ 
            Account_Link__c aLink = [SELECT id,Portal_Email__c,toRole__c from Account_Link__c where ID=:aclId limit 1];
            aLink.Portal_Email__c = MyMercEmail;
            Database.SaveResult results = Database.Update(aLink);
            accont.Email3__c  = MyMercEmail;
            Database.SaveResult accResults = Database.Update(accont);
            pagereference pr = new pagereference ('/apex/CustomerMymercInterface?id='+Accid);
            pr.setRedirect(true);
            return pr;
        }
    }
 
    public PageReference mymercnew(){
    try{
        Pattern MyPattern = Pattern.compile(emailRegex);
        if(!String.isBlank(accont.LastName_Native_1__c)){
        Matcher MyMatcher = MyPattern.matcher(accont.LastName_Native_1__c);
        result  = MyMatcher.matches();
        }
        
        if( MyMercEmail == NULL || string.isBlank(MyMercEmail)){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'please input "My Mercedes Email Id"'));
            return null;
        }
        else if(!string.isBlank(MyMercEmail)){// && (!MyMercEmail.endsWith('.com') || !MyMercEmail.contains('@') || MyMercEmail.);
            String emailRegex = '^[a-zA-Z0-9._|\\\\%#~`=?&/$^*!{}+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$'; 
            Pattern MyPatternn = Pattern.compile(emailRegex);
            Matcher MyMatcher = MyPatternn.matcher(MyMercEmail);
        
            if (!MyMatcher.matches()){ 
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'please enter valid Email'));
                return null;    
            }
        }
        else{ 
            accont.Email3__c  = MyMercEmail;
        }
        if(accont.recordtypeid == System.Label.PersonAccount_Record_Type_From_Account ) {
              if(accont.PersonBirthdate != NUll && accont.LastName_Native_1__c != NULL && accont.Gender__c!= NULL){
              
                 accont.Portal_Apply_Date__c = system.today();
                 accont.Portal_Apply_Status__c = 'To be Sent';
                 accont.Portal_Apply_User__c = userinfo.getUserid();
                 if(accont.Allow_Data_Sharing2__c == 'No' && accont.Data_Source__C == 'Dealer Outlet'){
                     accont.Allow_Data_Sharing2__c= 'Yes';
                     accont.Data_Source__C = 'My Mercedes';
                 }
                 system.debug('accountMainDealer'+accont.main_dealer__C);
                 if(accont.Main_Dealer__c == NULL ){
                     system.debug('usrcontactaccountid'+usr.contact.AccountId);    
                     accont.Main_Dealer__c = usr.contact.AccountId;
                 }
                 
                 update accont;
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Records Updated'));
             }
            else{
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter Mandatory fields on Account - Birthdate, LastNameNative, Gender'));
                 return null; 
            }
        }
       }
       catch(exception e){
                 ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
       }
       
        /* else
         {
             accont.Portal_Apply_Date__c = system.today();
             accont.Portal_Apply_Status__c = 'To be Sent';
             accont.Portal_Apply_User__c = userinfo.getUserid();
             update accont;
         }*/
         pagereference pr = new pagereference ('/'+Accid);
         pr.setRedirect(true);
         return pr;
         
     }
     
    public pagereference saveAndReturn(){
        pagereference pr = new pagereference ('/'+Account.id);
        pr.setRedirect(true);
        return pr;
    }
}