src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Flag for this dealer
Attribute in Data Dictionary object Dealer is &quot;Dealer_ActiveFlag&quot;</description>
        <label>Dealer Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Sales_Type__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: The sales type of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_SalesType&quot;</description>
        <label>Dealer Sales Type</label>
        <picklist>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Star-Elite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Service_Codes__c</fullName>
        <description>Dealer Services - based on the GSSN interface for the Dealer ActivityDefCodes

Feb-18-2012: Added by Rob and Falk
Attribute in Data Dictionary object Dealer is &quot;Dealer_Service&quot;</description>
        <label>Dealer Service Codes</label>
        <picklist>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSC Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aftersales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata-retrieve/objects/Account.object
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>

src/main/metadata/objects/Campaign_Lead__c.object
<CustomObject>
    <description>Lead: To link campaign and lead</description>
    <fields>
        <fullName>Lead__c</fullName>
        <label>Lead</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Lead</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Assigned_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Assigned_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Mobile__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.PersonMobilePhone, 
Collectioner_Name__r.MobilePhone
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile</label>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Package_Item__c.object
<CustomObject>
    <description>Campaign: Conjunction object of Campaign Package and Campaign Offering</description>
    <fields>
        <fullName>Offering__c</fullName>
        <label>Offering</label>
        <referenceTo>Campaign_Offering__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Package Item</label>
    <nameField>
        <displayFormat>CPI-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Participating_Dealer__c.object
<CustomObject>
    <description>Campaign: Dealers that participate the campaign</description>
    <fields>
        <fullName>Campaign_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Package</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The campaign package does not belong to the participanting dealer&apos;s campaign.</errorMessage>
            <filterItems>
                <field>Campaign_Package__c.Campaign__c</field>
                <operation>equals</operation>
                <valueField>$Source.Campaign__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign_Package__c</referenceTo>
        <relationshipLabel>Participating Dealers</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participating Campaigns</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Participating Dealer</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/SelectAssignedDealerControllerTest.cls
/*
    Type:       Test class for SelectAssignedDealerController
    Purpose:    Test logic in SelectAssignedDealerController.cls
    User Story: US-Lead-003
    
    1. Mouse Created on 2013-05-03
*/
@isTest
private with sharing class SelectAssignedDealerControllerTest 
{
    private static Account dealer;
    private static Account personAccount;
    private static Lead__c lead;
    private static Campaign centralMKTCampaign;
    private static Campaign_Package__c camPackage;
    private static Campaign_Offering__c offering;
    private static Package_Item__c packageItem;
    private static Participating_Dealer__c partDealer;
    private static Campaign cacCampaign;
    private static Campaign campaignExecution;
    private static Campaign_Lead__c camLead;
    private static string utilTest='UtilTestData.LEAD_RT_SALES_LEADS';
    private static string pageRef = '/apex/SelectAssignedDealer?Id=';
    private static string provinceValue = 'Anhui';
    
    public static Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    public static Id DealercRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
    public static Id centralRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
    public static Id camexecuRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Campaign Execution - Simple').getRecordTypeId();
    public static Id salesleadRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('Sales Leads').getRecordTypeId();
    
    public static testMethod void testSelectAssignedDealerController()
    {
        Test.startTest();
        prepareTestdata(utilTest);
        PageReference pr = new PageReference(pageRef + lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        // Test Dealer Province is Beijing, so has query result
        selectDealer.dealer.Province__c = provinceValue;
        selectDealer.dealer.City__c = 'Anyang';
        selectDealer.query();
        Test.stopTest();
        System.assertequals(true,selectDealer.hasQueryResult);
    }
    
    public static testMethod void testgetCityOptions()
    {
        Test.startTest();
        prepareTestdata(utilTest);
        PageReference pr = new PageReference(pageRef + lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        selectDealer.dealer.Province__c = provinceValue;
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--None--'));
        options.add(new SelectOption(dealer.City__c,dealer.City__c));
        selectDealer.getCityOptions();
        Test.stopTest();
        system.assertequals(options,selectDealer.getCityOptions());
    }
    
    public static testMethod void testrefreshPage()
    {
        Test.startTest();
        prepareTestdata(utilTest);
        PageReference pr = new PageReference(pageRef + lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        selectDealer.refreshPage();
        Test.stopTest();
        system.assertequals(null,selectDealer.refreshPage());
    }
    
    public static testMethod void testchoose()
    {
        Test.startTest();
        prepareTestdata(utilTest);
        PageReference pr = new PageReference(pageRef + lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        selectDealer.choosenDealerId=dealer.Id;
        id expectedID;
        selectDealer.choose();
        expectedID=selectDealer.lead.Assigned_Dealer__c;
        Test.stopTest();
        system.assertequals(dealer.Id,expectedID);
    }
    
    public static testMethod void testcampaignOptions()
    {
        Test.startTest();
        prepareTestdata(utilTest);
        PageReference pr = new PageReference(pageRef+ lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        List<SelectOption> campaignOptions = new List<SelectOption>();
        campaignOptions.add(new SelectOption('', '--None--'));
        campaignOptions.add(new SelectOption(campaignExecution.Id, campaignExecution.Name));
        List<SelectOption> temp=selectDealer.campaignOptions;
        Test.stopTest();
        system.assertequals(campaignOptions,temp);
    }
    
    public static testMethod void testquery()
    {
        Test.startTest();
        prepareTestdata('UtilTestData.LEAD_RT_AFTER_SALES_LEADS');
        PageReference pr = new PageReference(pageRef + lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        // Test Dealer Province is Beijing, so has query result
        selectDealer.dealer.Province__c = provinceValue;
        selectDealer.dealer.City__c = 'Anyang';
        selectDealer.lead= new Lead__c();
        selectDealer.query();
        Test.stopTest();
        System.assertequals(true,selectDealer.hasQueryResult);
        System.assertequals(camLead.Lead__c,lead.id);
    }
    
    public static testMethod void testqueryelseCondition()
    {
        Test.startTest();
        prepareTestdata('UtilTestData.LEAD_RT_AFTER_SALES_LEADS');
        PageReference pr = new PageReference(pageRef + lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        // Test Dealer Province is Beijing, so has query result
        selectDealer.dealer.Province__c = 'test';
        selectDealer.dealer.City__c = 'test';
        selectDealer.lead= new Lead__c();
        selectDealer.query();
        Test.stopTest();
        System.assertequals(false,selectDealer.hasQueryResult);
        System.assertequals(camLead.Lead__c,lead.id);
    }
    
    public static testMethod void testchooseelseCondition()
    {
        Test.startTest();
        prepareTestdata(utilTest);
        PageReference pr = new PageReference(pageRef + lead.Id);
        Test.setCurrentPage(pr);
        SelectAssignedDealerController selectDealer = new SelectAssignedDealerController(new ApexPages.StandardController(lead));
        selectDealer.choosenDealerId=personAccount.Id;
        id expectedID;
        selectDealer.choose();
        expectedID=selectDealer.lead.Assigned_Dealer__c;
        Test.stopTest();
        system.assertequals(personAccount.Id,expectedID);
    }
     
    static void prepareTestdata(string leadType) {
   List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
   //insert updatecustomsettings;
Trigger__c newtrg = new Trigger__c(Name= 'TriggerAccountLink',Trigger_Name__c = 'TriggerAccountLink',Trigger_Handler__c = 'TriggerAccountLinkTriggerHandlerJP',Market__c ='JP',
                               enabled__c = False,after__c= False,before__c= False,delete__c= False,update__c= False,insert__c= False);
        insert newtrg;
   dealer = new Account(RecordTypeId=DealercRecordTypeId,Dealer_Sales_Type__c ='MB', Province__c = provinceValue, City__c = 'anyang', 
                        Dealer_Active__c = true, Dealer_Service_Codes__c = 'Sales',Name = 'Beijing Test',Mobile__c='0000000000'); 
   insert dealer;       

   personAccount = new Account();
   personAccount.RecordTypeId=personAccRecordTypeId;
   personAccount.Lastname='testlastname';
   personAccount.Mobile__c='0000000000';
   personAccount.Email__c='test@mbau.com';
   personAccount.Email2__c = 'testemail2@test.com';
   personAccount.Home_Phone_2__c = '0000009842';  
        
   insert personAccount;
        
   // One Lead which has a reference to this person account
        
   lead = new Lead__c();
   lead.Contact__c = personAccount.Id;
   lead.RecordTypeId=salesleadRecordTypeId;
   insert lead;
        
   centralMKTCampaign = new Campaign(RecordTypeId=centralRecordTypeId,Name='Testnamecampaign');
   insert centralMKTCampaign;
    
   camPackage = new Campaign_Package__c(Campaign__c = centralMKTCampaign.Id);
   insert camPackage;
        
   offering = new Campaign_Offering__c(Campaign__c = centralMKTCampaign.Id);
   insert offering;
        
   packageItem= new Package_Item__c(Offering__c = offering.Id,Package_Name__c = camPackage.Id);
   insert packageItem;
    
   partDealer = new Participating_Dealer__c(Campaign__c = centralMKTCampaign.Id,Dealer__c = dealer.Id,Campaign_Package__c = camPackage.Id);
   insert partDealer;
        
   cacCampaign = new Campaign(Name = 'TYest Rec',RecordTypeId=centralRecordTypeId,ParentId = centralMKTCampaign.Id);
   insert cacCampaign;
        
   campaignExecution = new Campaign(Name = 'TYest Rec1',RecordTypeId=camexecuRecordTypeId,ParentId = cacCampaign.Id);
   insert campaignExecution;
        
   camLead = new Campaign_Lead__c(Lead__c = lead.Id,Campaign__c = campaignExecution.Id);
   insert camLead;
        
   system.assertNotEquals(null,packageItem);
   system.assertNotEquals(null,partDealer);
 }
}