src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <description>Added based on the GSSN interface mapping

Feb-18-2012: Added by Rob and Falk</description>
        <label>Dealer ND Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/DateTimeForShareBatch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>noOfHours__c</fullName>
        <label>noOfHours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DateTimeForShareBatch</label>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <formula>Contact.Account.Dealer_ND_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer ND Code</label>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/UserRecordShareBatchMY.cls
global class UserRecordShareBatchMY implements Database.Batchable<sObject>, Database.Stateful {
public String market;
public List<User> usrLst;
global UserRecordShareBatchMY (String Market) {
        this.market = Market;
        usrLst=new List<User> ();
  
             }
           
global Database.QueryLocator start(Database.BatchableContext BC) {
        String qry;
        Integer noOfHours;
        datetime myDateTime = datetime.now();
        String dmmStatus = 'Processed';
        DateTimeForShareBatch__c dt = DateTimeForShareBatch__c.getValues('UserRecordshareBatch');
            if(dt != NULL){
                noOfHours = Integer.valueOf(dt.noOfHours__c) * (-1);
                myDateTime = myDateTime.addHours(noOfHours);
            }
            
        qry='Select Id,contact.account.Dealer_Nd_code__c from User where contact.account.Dealer_Nd_code__c!=NULL and Market__c = :market and createddate >=:myDateTime' ;
return database.getQueryLocator(qry);
}
global void execute(Database.BatchableContext BC, List <User> scope) {
 for(User u : scope)
     {
          usrLst.add(u);       
     }
     }
global void finish(Database.BatchableContext BC) {
UserHelperMY.shareRecordsAfterInsertAndUpdate(usrLst,label.MY);
}
}