src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email2</label>
        <type>Email</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email3__c</fullName>
        <label>Other E-Mail</label>
        <type>Email</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>FirstName_Native_1__c</fullName>
        <label>First Name Native</label>
        <length>40</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_2__c</fullName>
        <label>Home Phone 2</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>LastName_Native_1__c</fullName>
        <label>Last Name Native</label>
        <length>40</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Mobile2__c</fullName>
        <label>Mobile 2</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Block__c</fullName>
        <label>Block</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
		IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
		IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA')))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Prefecture</label>
        <picklist>
            <picklistValues>
                <fullName>Hokkaido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aomori</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iwate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miyagi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamagata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukushima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ibaraki</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tochigi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gunma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saitama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tokyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kanagawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niigata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ishikawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamanashi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shizuoka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aichi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shiga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kyoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Osaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wakayama</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TitleOfHonor__c</fullName>
        <label>TitleOfHonor</label>
        <picklist>
            <picklistValues>
                <fullName>To Person</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>To Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Post Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Record type for company addresses.</description>
        <label>Company</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/classes/CheckAccountDuplicateController_Test.cls
@istest
public class CheckAccountDuplicateController_Test 
{
    public static Account objAccount;
    public static Account objAccount1;
    public static Account personAcc;
    public static Account personAcc1;
    public static Address__C addressobj ;
    
    public static String companyAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
    public static string strPerson=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    
    
    static testmethod void AddressSearchValidationControllerTest4()
    {
        createTestData();
        
        ApexPages.currentPage().getParameters().put('Id',personAcc.Id);
        //ApexPages.StandardController objSc = new ApexPages.StandardController(personAcc);
        CheckAccountDuplicateController JPAcccontroller= new CheckAccountDuplicateController();
     
        test.startTest();
     Test.setMock(WebServiceMock.class, new WebServiceMockImpl2 ());
        JPAcccontroller.onLineDeduplication();       
        test.stopTest();
  
    }
    static testmethod void AddressSearchValidationControllerTest5()
    {
        createTestData();
        
        ApexPages.currentPage().getParameters().put('Id',objAccount.Id);
        //ApexPages.StandardController objSc = new ApexPages.StandardController(personAcc);
        CheckAccountDuplicateController JPAcccontroller= new CheckAccountDuplicateController();
     
        test.startTest();
     Test.setMock(WebServiceMock.class, new WebServiceMockImpl2 ());
        JPAcccontroller.onLineDeduplication();       
        test.stopTest();
  
    }
    
   
    static void createTestData()
    {
        objAccount= new Account();
        objAccount.RecordtypeId= companyAccRecordTypeId;
        objAccount.Name='Test Person 1st';
        objAccount.Status__c='Active';
        objAccount.Province__c='Province1';
        objAccount.City__c='Test';
        objAccount.ZipCode__c = '1004236';
        objAccount.Email__c='test@mbj.com';
        objAccount.Mobile__c ='0000000000';
        objAccount.MBK_Data_Source__c ='Email';
        objAccount.Province__c = 'Province1';
        objAccount.Phone = '08022420181';
        insert objAccount;
        
        objAccount1 = new Account();
        objAccount1.RecordtypeId= companyAccRecordTypeId;
        objAccount1.Name='Test Person 1st';
        try{insert objAccount1;}
        catch(DMLException e)
        {
            system.debug('!!!'+ e);
        }
        personAcc= new Account();
        personAcc.RecordtypeId= strPerson;
        personAcc.FirstName = 'Test Person';
        personAcc.LastName='Test Person 1st';
        personAcc.LastName_Native_1__c = 'ァアィイゥウェエォオ';
        personAcc.FirstName_Native_1__c ='ァアィイゥウェエォオ';
        personAcc.Province__c='Province1';
        personAcc.City__c='Test';
        personAcc.ZipCode__c = '1004287';
        personAcc.Email__c='test@mbj.com';
        personAcc.Email2__c ='test@mbj.com';
        personAcc.Email3__c='test@mbj.com';
        personAcc.Individual_Home_Phone__c = '0000000000';
        personAcc.MBK_Data_Source__c ='Email';
        personAcc.Home_Phone_2__c = '08022420181';
        personAcc.Work_Phone__c= '08022420181';
        personAcc.Phone= '08022420181';
        personAcc.Mobile2__c = '08022420181';
        personAcc.Mobile__c = '08022420181';
        personAcc.Province__c = 'Province1';
        personAcc.MD__c = 'JP';
        insert personAcc;
        
        personAcc1 = new Account();
        personAcc1.RecordtypeId= strPerson;
        personAcc1.LastName='Test Person 2nd';
        try{insert personAcc1;}
        catch(DMLException e){            
            system.debug('!!! '+ e);            
        }
        
        addressobj =new Address__C();
        addressobj =  new Address__C();
        addressobj.Address_Type__c = 'Home';
        addressobj.Address_Line_1__c = 'line 1';
        addressobj.Address_Line_2__c = 'line 2';
        addressobj.Block__c = 'Block';
        addressobj.Customer__c = objAccount.id;
        addressobj.ZipCode__c = '1040041';
        addressobj.Province__c ='Fukushima';
        addressobj.TitleOfHonor__c = 'To Person';
        insert addressobj;
        
    }
}