src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Owner_Relation__c</fullName>
        <label>Owner Relation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Grand Child</fullName>
                </value>
                <value>
                    <fullName>Husband Wife</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Relative</fullName>
                </value>
                <value>
                    <fullName>Same</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>UCID__c</fullName>
        <label>UCID</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
			IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;)))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Loyalty_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loyalty Card</relationshipLabel>
        <relationshipName>Loyalty_Card</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Loyalty_Card_End_Date__c</fullName>
        <label>LoyaltyCardEndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loyalty_Card_Number__c</fullName>
        <externalId>true</externalId>
        <label>Loyalty Card Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP', 
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA')))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Loyalty Card</relationshipLabel>
        <relationshipName>Loyalty_Card</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>owner_relation__c</fullName>
        <label>Owner Relation</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grand Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband Wife</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Same</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loyalty Card</label>
    <nameField>
        <displayFormat>LC-{0000000000}</displayFormat>
        <label>Loyalty Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Card</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA')))</defaultValue>
        <label>MD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegistrationNo__c</fullName>
        <label>RegistrationNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Relationship end date
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_EndDate“</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA')))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Relation__c</fullName>
        <description>Person's relationship to the vehicle's owner</description>
        <label>Owner Relation</label>
        <picklist>
            <picklistValues>
                <fullName>Same</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband・Wife</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grand parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grand child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/customerVehiceStatus.cls
@RestResource(urlMapping='/ValidateNewCustomer/*')
global without sharing class customerVehiceStatus {
    public static final Id personRecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    @HttpPost
    global static Map<String,String> findUCID(){
        Map<String,String> response=new Map<String,String>();
        response.put('UCID', 'Nil');
        response.put('VehicleExists', 'False');
        response.put('VehicleRelationship', 'Nil');
        response.put('LoyalityCardNumber', 'Nil');
        String jsonText = RestContext.request.requestBody.toString();
        Map<String, Object> cObjMap = (Map<String, Object>) JSON.deserializeUntyped(jsonText);
        Object res=cObjMap.get('data');
        Map<String,Object> obj= (Map<String,Object>)res;
        String FirstName=(String)obj.get('FirstName');
        String LastName=(String)obj.get('LastName');
        String Email=(String)obj.get('Email');
        String Mobile=(String)obj.get('Mobile');
        String RegistrationNumber=(String)obj.get('RegistrationNumber');
        String name='';
        if(LastName!='' && !String.isBlank(LastName) && LastName!=' ' && lastname!=null){
                name+=lastname;                   
        }
        if(FirstName!='' && !String.isBlank(FirstName) && FirstName!=' ' && FirstName!=null){
            if(Pattern.matches('.*[A-Za-z]{1,}.*', FirstName) || Pattern.matches('.*[A-Za-z]{1,}.*', lastname)){
               name+=name!='' ? (' '+FirstName) :(FirstName);
            }
            else{
                name+=FirstName;
            }
        }
        system.debug(name);
        system.debug(Email);
        system.debug(Mobile);
        //changes for Frst & lastname
        List<Account> acc= new List<Account>();
        List<Account> acc2= new List<Account>();
        List<Vehicle__c> vehicle=new List<Vehicle__c>();
        if((mobile==null || mobile=='' || String.isBlank(mobile)) && Email !=null && Email !='' && !String.isBlank(Email) && name!=''){
            acc2=[select id,Ucid__c,email__c,firstname,lastname from Account where Email__c=:Email and RecordtypeId=:personRecordTypeId and Md__c='KR' Order By LastModifiedDate DESC ];
        }
        else if(mobile !=null && mobile !='' && !String.isBlank(mobile) && name!=''){
            acc2=[select id,Ucid__c,email__c,firstname,lastname from Account where Mobile__c=:Mobile and RecordtypeId=:personRecordTypeId and Md__c='KR' Order By LastModifiedDate DESC ];
        }
        for(Account a:acc2){
            if((a.firstname!=null && a.firstname.containsIgnoreCase(name)) || (a.lastname!=null && a.lastname.containsIgnoreCase(name))){
                acc.add(a);
                break;
            }
        }
        system.debug('acc'+acc);
        if(acc.size()>0){
        response.put('UCID', acc[0].Ucid__c);
        }
        //considering removal of white spaces
        RegistrationNumber=RegistrationNumber.deleteWhitespace();
        if(RegistrationNumber==null || RegistrationNumber==''){
            return response;
        }
        String regNumwithwildcards='%';
        for(Integer i=0;i<RegistrationNumber.length();i++){
            regNumwithwildcards+=RegistrationNumber.substring(i,i+1)+'%';
        }
        List<Vehicle__c> vehicles=new List<Vehicle__c>();
        vehicles=[select id,RegistrationNo__c from vehicle__c where RegistrationNo__c like :regNumwithwildcards and Md__c='KR' limit 50000];
        String regNumber=null;
        for(vehicle__c v:vehicles){
            system.debug(v.RegistrationNo__c.deleteWhitespace().right(5));
            if(v.RegistrationNo__c.deleteWhitespace().right(5)==RegistrationNumber){
                regNumber=v.RegistrationNo__c;
            }
        }
        //considering removal of white spaces
        if(regNumber !=null && regNumber !='' && !String.isBlank(regNumber)){
            vehicle=[select id from Vehicle__c where RegistrationNo__c=:regNumber limit 1];
        }
        if(vehicle.size()==0){
            return response;
        }
        response.put('VehicleExists', 'True');
        response.put('VehicleId', vehicle[0].id);
        if(response.get('UCID')=='Nil' && name!=''){
            List<Vehicle_Relationship__c> vr=new List<Vehicle_Relationship__c>();
            vr=[select id,Vehicle_ID__c,Contact__r.UCID__c from Vehicle_Relationship__c where Vehicle_ID__c=:vehicle[0].id and
                (Contact__r.LastName LIKE :('%' + name + '%') or Contact__r.FirstName LIKE :('%' + name + '%')) and Contact__r.Recordtype.name='Person Account' and Md__c='KR'  Order By LastModifiedDate DESC limit 1];
            if(vr.size()>0){
                response.put('UCID', vr[0].Contact__r.UCID__c);
                acc=[select id,Ucid__c,email__c from Account where Ucid__c=:vr[0].Contact__r.UCID__c limit 1];                            
            }
        }
        List<Loyalty_Card__c> lcv=new List<Loyalty_Card__c>();
        lcv=[select id,Loyalty_Card_Number__c from Loyalty_Card__c where vehicle__c=:vehicle[0].id and Loyalty_Card_End_Date__c>=:system.today() and Md__c='KR' limit 1];
        system.debug(lcv.size());
        if(lcv.size()>0){
              response.put('VehicleRelationship', lcv[0].Loyalty_Card_Number__c+';Nil');
        }
        if(acc.size()>0){
            List<Vehicle_Relationship__c> vrs=new List<Vehicle_Relationship__c>();
            vrs=[select id,Owner_Relation__c,Vehicle_ID__c from Vehicle_Relationship__c where Contact__c=:acc[0].id and Vehicle_ID__c=:vehicle[0].id and End_Date__c =null and Md__c='KR' Order By LastModifiedDate DESC limit 1]; 
            system.debug(vrs.size());
            if(response.get('VehicleRelationship')!='Nil' && vrs.size()>0){
              String relation=vrs[0].Owner_Relation__c=='Same'?'Owner':'Contact';
                response.put('VehicleRelationship', lcv[0].Loyalty_Card_Number__c+';'+relation);
            }
            else if(vrs.size()>0){
                response.put('VehicleRelationship', vrs[0].Owner_Relation__c=='Same'?'Owner':'Contact');    
            }
            List<Loyalty_Card__c> lc=new List<Loyalty_Card__c>();
            lc =[select id,Loyalty_Card_Number__c from Loyalty_Card__c where Account__c=:acc[0].id and Loyalty_Card_End_Date__c>=:system.today() and Md__c='KR' Order By LastModifiedDate DESC limit 1];
            if(lc.size()>0){
                response.put('LoyalityCardNumber', lc[0].Loyalty_Card_Number__c);
            }
        }
        return response;
    }
}