src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax_Validity__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag whether the fax number is valid 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_FaxValidity&quot;</description>
        <label>Fax Validity</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blacklisted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email2</label>
        <type>Email</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email3__c</fullName>
        <label>Other E-Mail</label>
        <type>Email</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email_Last_Modified_By2__c</fullName>
        <label>Email Last Modified By 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email_Last_Modified_By3__c</fullName>
        <label>Other E-mail ModifiedBy</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email_Last_Modified_By__c</fullName>
        <label>Email Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email_Last_Modified_Date2__c</fullName>
        <label>Email Last Modified Date 2</label>
        <type>DateTime</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email_Last_Modified_Date3__c</fullName>
        <label>Other E-mail ModifiedDate</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email_Last_Modified_Date__c</fullName>
        <label>Email Last Modified Date</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email_Status_2__c</fullName>
        <label>Email Status 2</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email_Status_3__c</fullName>
        <label>Other E-mail Validity</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Bounce-Back</fullName>
                </value>
                <value>
                    <fullName>Incompleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email_Status__c</fullName>
        <description>value will be delivered in general by external sources, but can be maintained manually as well</description>
        <label>Email Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Fax2__c</fullName>
        <label>Work Fax</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Fax_Validity2__c</fullName>
        <label>Work FAX Validity</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Bounce-Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_2__c</fullName>
        <label>Home Phone 2</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_Last_Modified_By2__c</fullName>
        <label>Home Phone Last Modified By 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_Last_Modified_By__c</fullName>
        <label>Home Phone Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_Last_Modified_Date2__c</fullName>
        <label>Home Phone Last Modified Date 2</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_Last_Modified_Date__c</fullName>
        <label>Home Phone Last Modified Date</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_Status_2__c</fullName>
        <label>Home Phone Status 2</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone_Status__c</fullName>
        <description>Individual home phone status</description>
        <label>Home Phone Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Mobile2__c</fullName>
        <label>Mobile 2</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Mobile_Status__c</fullName>
        <description>value will be delivered in general by external sources, but can be maintained manually as well</description>
        <label>SMS / MMS / IM Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>SMS_Last_Modified_By2__c</fullName>
        <label>SMS/MMS/IM Last Modified By 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>SMS_Last_Modified_By__c</fullName>
        <label>SMS/MMS/IM Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>SMS_Last_Modified_Date2__c</fullName>
        <label>SMS/MMS/IM Last Modified Date 2</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>SMS_Last_Modified_Date__c</fullName>
        <label>SMS/MMS/IM Last Modified Date</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>SMS_MMS_IM_Status_2__c</fullName>
        <label>SMS / MMS / IM Status 2</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone_Last_Modified_By2__c</fullName>
        <label>Work Phone Last Modified By 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone_Last_Modified_By__c</fullName>
        <label>Work Phone Last Modified By</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone_Last_Modified_Date2__c</fullName>
        <label>Work Phone Last Modified Date 2</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone_Last_Modified_Date__c</fullName>
        <label>Work Phone Last Modified Date</label>
        <type>DateTime</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone_Status_2__c</fullName>
        <label>Work Phone Status 2</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone_Status__c</fullName>
        <description>value will be delivered in general by external sources, but can be maintained manually as well</description>
        <label>Work Phone Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/classes/ContactTableController.cls
/*
    Type:      Extension Controller(Account) for VF page -ContactTable
    ---------------------------------------------------------------
    
    
    26-10-2015 Created by Narasimha Gundurao
*/

public class ContactTableController 
{
    /* Variables Declaration */ 
    private ApexPages.StandardController stdController;
    public boolean editMode {get; set;} 
    public string AccId {get; set;}
    public Account ParAcc {get; set;}
    
    /**
  *@Description : Constructor.
  *@Date : 26/10/2015
  *@param:Apexpages Standard Controller (Account)
  *@return:This mehtod does not return any value.

  */ 
    public  ContactTableController(ApexPages.StandardController stdController)
    {
        editMode = false;
        AccId = stdController.getId();
         
        stdController.addFields(new List<String> {'Id','Mobile__c','Mobile2__c','Individual_Home_Phone__c',
            'Home_Phone_2__c','Work_Phone__c','Phone','Email__c','Email2__c','Email3__c','Fax2__c',
            'Fax','Fax_Validity2__c','Fax_Validity__c','Email_Status__c','Email_Status_2__c','Email_Status_3__c',
            'Work_Phone_Status__c','Work_Phone_Status_2__c','Individual_Home_Phone_Status__c','Home_Phone_Status_2__c' ,
            'Mobile_Status__c','SMS_MMS_IM_Status_2__c','Email_Last_Modified_By__c','Email_Last_Modified_By2__c',
            'Email_Last_Modified_By3__c','Work_Phone_Last_Modified_By__c','Work_Phone_Last_Modified_By2__c','Home_Phone_Last_Modified_By__c',
            'Home_Phone_Last_Modified_By2__c','SMS_Last_Modified_By__c','SMS_Last_Modified_By2__c','SMS_Last_Modified_Date__c',
            'SMS_Last_Modified_Date2__c','Home_Phone_Last_Modified_Date__c','Home_Phone_Last_Modified_Date2__c','Work_Phone_Last_Modified_Date__c',
            'Work_Phone_Last_Modified_Date2__c','Email_Last_Modified_Date__c','Email_Last_Modified_Date2__c','Email_Last_Modified_Date3__c'});
        
        ParAcc = (Account)stdController.getRecord();
        
    }
    
    public void EditAccount()
     /**
  *@Description : This method makes editMode true which allows the user to input values to the phone numbers  and email fields.
  *@Date : 26/10/2015
  *@param: None
  *@return:This mehtod does not return any value.

  */ 
    {
        editMode = true;
    }
    
    public void UpdateAccount()
    
     /**
  *@Description : This method updates the Account with the values entered by user to phone number and email fields.
  *@Date : 26/10/2015
  *@param: None
  *@return:This mehtod does not return any value.

  */ 
    {
        try
        {
            if(ParAcc != null)
                update ParAcc;
        }
        
        catch(DMLException de)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,de.getDmlMessage(0)));
            
        }
    }
    
    public void CancelUpdate()
    /**
  *@Description : This method Makes Edit mode false.
  *@Date : 26/10/2015
  *@param: None
  *@return:This mehtod does not return any value.

  */ 
    {
        editMode = false; 
        
    }
    
}