src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <description>Added based on the GSSN interface mapping

Feb-18-2012: Added by Rob and Falk</description>
        <label>Dealer ND Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Outlet</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
			IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;)))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Survey__c.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'NZ') ,'NZ', 
IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA'))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <formula>Contact.Account.Dealer_ND_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer ND Code</label>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/TriggerSurveyTriggerHandlerJPTest.cls
@isTest
private class TriggerSurveyTriggerHandlerJPTest
{
    Public static Id personrectypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    Public static Survey__c survy;
    Public static Survey__c survyHq;
    Public static Account acc;
    Public static Account acchq;
    public static Account dlrAcc;
    public static Group accGrp;
    public static User usrMBJ;
    public static User usrSup;
    public static User user3 = TestUtils.IntegrationAPIUser();

    
    static testmethod void test_shareSurverTakertoDealer()
    {
        test.startTest();
        createTestData();
        test.stopTest();
    }
    
    static void createTestData()
    {
Trigger__c TriggerSurvey = new Trigger__c(Name='TriggerSurvey',Trigger_Name__c='TriggerSurvey',Trigger_Handler__c='TriggerSurveyTriggerHandlerJP',update__c=True,insert__c=True,delete__c=True,after__c=True,before__c=True,enabled__c=True,Market__c='JP');
  insert TriggerSurvey;
        
       User thisUser = [ select Id,ContactId from User where Id = :UserInfo.getUserId()];
       System.runAs(thisUser)
       {
           Profile supportProfile = [select Id from Profile where Name =:'System Administrator'];
           UserRole usrRole = [SELECT Id, Name FROM UserRole where Name = 'MBJ IT Department'];
           usrMBJ = new User();
           usrMBJ.UserName = 'TestUser.MBJSupport' + Math.rint(Math.random() * 1300000) + '@daimler.com.supportUser';        
           if(supportProfile != Null)
           {
               usrMBJ.ProfileId = supportProfile.Id;
           }
           if(usrRole != null)
           {
                usrMBJ.UserRoleId = usrRole.Id;
           }
           usrMBJ.LastName = 'MBj Support User';
           usrMBJ.Email = 'test.support.user@daimler.com.testuser';
           usrMBJ.Alias = 'SupUsr';
           usrMBJ.TimeZoneSidKey = 'Asia/Tokyo';
           usrMBJ.EmailEncodingKey = 'UTF-8';
           usrMBJ.LanguageLocaleKey = 'en_US';
           usrMBJ.localesidkey='en_US';
           usrMBJ.isActive = true;
           usrMBJ.Market__c = 'JP';
           insert usrMBJ;
       }
        
        dlrAcc = (Account)UtilTestData.createSobject(new Account(mobile__c='0123654',Dealer_ND_Code__c = 'MBJ0463',Dealer_Type__c = 'Company', OwnerId = usrMBJ.Id, MD__c = 'JP'), UTilTestData.ACCOUNT_RT_DEALER); 
        
        Contact contDlr = new Contact();
        contDlr.AccountId = dlrAcc.Id; 
        contDlr.LastName = 'Test Contact'; 
        contDlr.Phone = '0123654'; 
        contDlr.email = 'test@hqcontact.com';        
        insert contDlr;
        
        system.runAs(usrMBJ)
        {
            Profile JapanDealerCompanyManager = [select Id from Profile where Name ='Japan Dealer Company Manager'];
            usrSup = new User();
            usrSup.UserName = 'test.dealer.callcenter' + Math.rint(Math.random() * 14000000) + '@daimler.com.testuser';        
            if(JapanDealerCompanyManager!= Null)
            {
               usrSup.ProfileId = JapanDealerCompanyManager.Id;
            }
               usrSup.LastName = 'Test Call Center User';
               usrSup.Email = 'dealer.hqcallcenter.test@daimler.com';
               usrSup.ContactId = contDlr.Id;
               usrSup.Alias = 'MBJUsr';
               usrSup.TimeZoneSidKey = 'Asia/Tokyo';
               usrSup.EmailEncodingKey = 'UTF-8';
               usrSup.LanguageLocaleKey = 'en_US';
               usrSup.localesidkey='en_US';
               usrSup.isActive = true;
               usrSup.Market__C='JP'; 
               insert usrSup;
        }
        
        accGrp = new group();
        accGrp.Name = dlrAcc.Dealer_ND_Code__c;
        insert accGrp;

        
        survy = new Survey__c();
        survy.Name = 'MBJ Survey';
        survy.Survey_Type__c = 'OB Call';
        survy.MD__c = 'JP';
      //  insert survy;
        
        system.runAs(usrSup)
        {

        
           survyHq = new Survey__c();
           survyHq.Name = 'DealerSurvey';
           survyHq.Survey_Type__c = 'OB Call';
           survyHq.MD__c = 'JP';
           insert survyHq;
                      survyHq.MD__c = 'JP';
           Update survyHq;
        }
                 system.runAs(user3) {
            TriggerUtil.userCreate = false;
            Survey__c  testSurvey1 =new Survey__c(Name='Survey1');
                insert testSurvey1;
				update testSurvey1;



        }

        
    }    
}