src/main/metadata/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <externalId>true</externalId>
        <label>Campaign Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Offering__c.object
<CustomObject>
    <description>Campaign: Components of Campaign Package.</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Offerings</relationshipLabel>
        <relationshipName>Campaign_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Campaign Offering</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Package__c.object
<CustomObject>
    <description>Campaign: Combination of campaign offerings</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Packages</relationshipLabel>
        <relationshipName>Campaign_Packages_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Package_Description__c</fullName>
        <label>Package Description</label>
        <type>TextArea</type>
    </fields>
    <label>Campaign Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Package_Item__c.object
<CustomObject>
    <description>Campaign: Conjunction object of Campaign Package and Campaign Offering</description>
    <fields>
        <fullName>Offering__c</fullName>
        <label>Offering</label>
        <referenceTo>Campaign_Offering__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <referenceTo>Campaign_Package__c</referenceTo>
        <relationshipLabel>Package Items</relationshipLabel>
        <relationshipName>Package_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Package Item</label>
    <nameField>
        <displayFormat>CPI-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Participating_Dealer__c.object
<CustomObject>
    <description>Campaign: Dealers that participate the campaign</description>
    <fields>
        <fullName>Campaign_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Package</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The campaign package does not belong to the participanting dealer&apos;s campaign.</errorMessage>
            <filterItems>
                <field>Campaign_Package__c.Campaign__c</field>
                <operation>equals</operation>
                <valueField>$Source.Campaign__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign_Package__c</referenceTo>
        <relationshipLabel>Participating Dealers</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Participating Dealers</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participating Campaigns</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Participating Dealer</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/classes/TriggerPackageItem_TestClass.cls
/*
    Type:       Test Class
    Purpose:    TriggerPackgeItem_TestClass
    User Story: US--005
    29-June-2013 Stephano (Breakingpoint)    Created
*/
@isTest
public with sharing class TriggerPackageItem_TestClass{
    static testmethod void runTriggerPackgeItem(){
        // Campaign Record Type Id Search
        Map<String, Schema.RecordTypeInfo> cpRecordTypeMap_test = Schema.SObjectType.Campaign.getRecordTypeInfosByName();
        Map<String, Schema.RecordTypeInfo> acRecordTypeMap_test = Schema.SObjectType.Account.getRecordTypeInfosByName();        
        Id cca_RecordTypeId = cpRecordTypeMap_test.get('Central Marketing Campaign').getRecordTypeId();         // Central Campaign
        Id dl_RecordTypeId = acRecordTypeMap_test.get('Dealer').getRecordTypeId();      // Dealer.
        Test.startTest();
        // Central Campaign Inital
        Campaign TestData_CCA = new Campaign(Name='TestData_CCA_Campaign',
                                             Campaign_Code__c='Code_CCA',
                                             Type='Other',
                                             Campaign_Objectives__c='Objectives',
                                             Description='Description',
                                             Status='Confirmed',
                                             StartDate=date.newinstance(2013, 5, 17),
                                             EndDate=date.newinstance(2013, 10, 17),
                                             RecordTypeId=cca_RecordTypeId);   
        insert TestData_CCA;
        
        
        // Campaign Offering
        Campaign_Offering__c co = new Campaign_Offering__c(Name='TEST Campaign Offering DATA',
                                                          Campaign__c=TestData_CCA.Id);
        insert co;
        
        
        // Campaign Package
        Campaign_Package__c cp = new Campaign_Package__c(Name='Campaign Package',
                                                        Campaign__c=TestData_CCA.Id,
                                                        Package_Description__c='12313');
        insert cp;
        
        // Dealer
        Account acc = new Account(Name='TEST DATA DEALER', Phone='12345678', RecordTypeId=dl_RecordTypeId);
        insert acc;
        
        // Package Item
        Package_Item__c pi = new Package_Item__c(Package_Name__c=cp.Id,
                                                Offering__c=co.Id);
        insert pi;
                
        // Participating Dealer
        Participating_Dealer__c pd = new Participating_Dealer__c(Campaign__c=TestData_CCA.Id,Dealer__c=acc.Id, Campaign_Package__c=cp.Id);
        insert pd;
                
        delete pi;
        
        // Package Item
        Package_Item__c pi1 = new Package_Item__c(Package_Name__c=cp.Id,
                                                Offering__c=co.Id);
        insert pi1;  
        
        Package_Item__c piTest = [select Package_Name__c,Offering__c from Package_Item__c where id=:pi1.id];
        Test.stopTest();
        system.assertEquals(piTest.Package_Name__c, pi1.Package_Name__c);
  
    }
}