src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Executer__c</fullName>
        <description>Defines the owner of the campaign record</description>
        <label>Campaign Executer</label>
        <picklist>
            <picklistValues>
                <fullName>WholeSale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Execution_Channels__c</fullName>
        <description>This field is used to define whether the campaign will be executed via which channel, whether it will be an outbound email, SMS, outbound call etc</description>
        <label>Campaign Execution Channels</label>
        <picklist>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM Magazine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Sub_Type__c</fullName>
        <label>Campaign Sub Type</label>
        <picklist>
            <picklistValues>
                <fullName>Crosspoint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales and After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance - &gt;  Prematurity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales -&gt; Crosspoint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <description>The Type of Campaign</description>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parts Cross Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idle Hour Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Product Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for new vehicle owners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for dormant customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEP(Seasonal Check)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used-car buy-back/Trade-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion on Technical accessories and collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POM/Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <description>This field can be used to track the progress of the execution campaign life cycle</description>
        <label>Campaign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to set the status of the campaign member</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <description>Retail Campaign: The Type of Campaign</description>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parts Cross Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idle Hour Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Product Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for new vehicle owners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for dormant customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEP(Seasonal Check)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used-car buy-back/Trade-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion on Technical accessories and collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POM/Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Campaign_Execution_Channels__c</fullName>
        <label>Campaign Execution Channels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>DM</fullName>
                </value>
                <value>
                    <fullName>OB</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>DM Magazine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Campaign_Sub_Type__c</fullName>
        <label>Campaign Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>After Sales</fullName>
                </value>
                <value>
                    <fullName>Sales and After Sales</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Sales -&gt; Crosspoint</fullName>
                </value>
                <value>
                    <fullName>Finance - &gt; Prematurity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <label>Campaign Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Segmentation</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Response collection</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Close_Date__c</fullName>
        <description>This field is used to capture the end date of the campaign</description>
        <label>Close Date</label>
        <type>Date</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Parent_Campaign1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Campaign</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Retail_Campaign__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Planning &amp; Design Campaign</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Retail_Campaign__c</referenceTo>
        <relationshipLabel>Retail Campaigns (Parent Campaign)</relationshipLabel>
        <relationshipName>Retail_Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field is used to capture the start date of the campaign</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field can be used to track the progress of the campaign as part of campaign life cycle</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/Batch_BounceStatusretailretailTest.cls
@isTest
public class Batch_BounceStatusretailretailTest   {

    public static Id camIdExec= Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
      public static Id camIdPlan= Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Planning & Design Campaign').getRecordTypeId();
      //public static Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
       
    
   static testmethod void batchBounceStatus()
   {
   
   
      //String mainQuery = ;
     Test.startTest(); 
    
   Retail_Campaign__c camobj = new Retail_Campaign__c();
    camobj.RecordTypeId = camIdPlan;
    camobj.Name = 'camptest1';
    camobj.Campaign_Sub_Type__c= 'Sales';
    camobj.Status__c= 'Draft';
    camobj.Start_Date__c= System.today();
    camobj.Close_Date__c= System.today()+30;
    //camobj.Campaign_Executer__c='Retail';
    camobj.Child_Campaign_Status__c='Response collection';
   // camobj.Campaign_Objectives__c = 'camobjectives';
    camobj.Description__c= 'testdescrip';
    camobj.Campaign_Execution_Channels__c='eMail';
    camobj.Campaign_Type__c = 'After Sales';
    insert camobj;
  
  
    
        Retail_Campaign__c camobj1 = new Retail_Campaign__c();
        camobj1.RecordTypeId = camIdExec;
        camobj1.Parent_Campaign1__c=camobj.id;
        camobj1.Child_Campaign_Status__c='Response collection';
      
        camobj1.MD__c='JP';
        camobj1.Name = 'camptest1';
        camobj1.Campaign_Type__c='After Sales';
      //  camobj1.Type = 'Other';
        camobj1.Segmentation_Date__c= System.today()+4;
        camobj1.Execution_Start_Date__c = System.today()+10;
        camobj1.Execution_Type__c= 'eMail';
       // camobj1.Description = 'testdescrip';
        insert camobj1;
   
    Campaign_Member__c camMem = New Campaign_Member__c();
     camMem.Retail_Campaign_Id__c = camobj1.id;
     camMem.Status__c = 'Ready';

      insert camMem;
      
     Campaign_Member__c camMem1 = New Campaign_Member__c();
     camMem1.Retail_Campaign_Id__c = camobj1.id;
     camMem1.Status__c = 'Ready';

      insert camMem1;
      
      
      system.debug('+++++++++'+camMem1);
      system.debug('+++++++++'+camobj1);
      system.debug('+++++++++'+camobj);
  
    
    
    Batch_BounceStatusretail batchSch = New Batch_BounceStatusretail();
           
       
        Database.executeBatch(new Batch_BounceStatusretail());
    

         Test.stopTest();
         

}





}