src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <description>The Type of Campaign</description>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parts Cross Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idle Hour Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Product Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for new vehicle owners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for dormant customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEP(Seasonal Check)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used-car buy-back/Trade-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion on Technical accessories and collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POM/Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to refer the related retail campaign execution record</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign member (Retail Campaign)</relationshipLabel>
        <relationshipName>Campaign_member1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to set the status of the campaign member</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Member__c.object
    <fields>
        <fullName>Convert_To_Lead_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Convert To Lead Flag</label>
        <type>Checkbox</type>
    </fields>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <recordTypes>
        <fullName>Sales_Leads</fullName>
        <active>true</active>
        <label>Sales Leads</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <description>Retail Campaign: The Type of Campaign</description>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parts Cross Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idle Hour Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Product Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for new vehicle owners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for dormant customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEP(Seasonal Check)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used-car buy-back/Trade-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion on Technical accessories and collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POM/Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <description>Retail Campaign: Lead of the campaign</description>
        <label>Lead</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Parent_Campaign1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Campaign</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Retail_Campaign__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Planning &amp; Design Campaign</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Retail_Campaign__c</referenceTo>
        <relationshipLabel>Retail Campaigns (Parent Campaign)</relationshipLabel>
        <relationshipName>Retail_Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field can be used to track the progress of the campaign as part of campaign life cycle</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/coverttolead1controllerTest.cls
@isTest
public class coverttolead1controllerTest{
 public static Id parentRetailCampaign_RecordTypeID = Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
   public static Id parentCampaign_RecordTypeID = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
    private static Account dealer;
    private static Account contact;
    private static Lead__c lead;
    public static testMethod void CampaignTest()
    { User user1 = TestUtils.createAdminUser();
        System.runAs (user1) {
        Test.StartTest();
        retail_campaign__c re=new Retail_Campaign__C(Name='test par',RecordtypeID=Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Planning & Design Campaign').getRecordTypeId(),Campaign_Type__c='Sales');
       insert re;
        Retail_Campaign__c parentCamp=new Retail_Campaign__c(
             Name='test par',
            //EndDate=System.Today(),
            //StartDate=System.Today(),
            RecordtypeID=parentRetailCampaign_RecordTypeID,
            Parent_Campaign1__c=re.id
           );
    insert parentcamp;
         Campaign_Member__c cmm=new Campaign_Member__c(     
             Status__c='Responded',OwnerId = userinfo.getuserId(),
             Retail_Campaign_Id__c=parentcamp.id,Convert_To_Lead_Flag__c=false);
             insert cmm;
            PageReference pageRef = Page.Converttolead1;
           pageRef.getParameters().put('campaignMemberId', cmm.Id);
          
            Test.setCurrentPage(pageRef);   
         coverttolead1controller controller = new coverttolead1controller ();   
         controller.recordtypevalue = 'Sales_leads';
        controller.interstmodel='c-class';
        controller.displayPopup=false;
           controller.objectAPIName = 'Retail_Campaign__c';
           try{
               controller.getItems();
               controller.showPopup();
                   controller.closePopup();
                   //controller
                   //controller
            controller.convertToLead();
            }catch(exception e){}
           controller.cancel();
          
       Test.stopTest();
     }
}
    public static testMethod void CampaignTest1()
    { User user1 = TestUtils.createAdminUser();
        System.runAs (user1) {
        Test.StartTest();
        campaign re=new Campaign(Name='test par',RecordtypeID=Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Planning & Design Campaign').getRecordTypeId(),Campaign_Type__c = 'Finance');
       insert re;
        Campaign parentCamp=new Campaign(
             Name='test par',
            //EndDate=System.Today(),
            //StartDate=System.Today(),
            RecordtypeID=parentCampaign_RecordTypeID,
            Parent=re
            //parent.Campaign_Type__c == 'Sales'
           );
    insert parentcamp;
         Campaign_Member__c cmm=new Campaign_Member__c(     
             Status__c='Responded',OwnerId = userinfo.getuserId(),
             Campaign_ID__c=parentCamp.id,Convert_To_Lead_Flag__c=false);
             insert cmm;
            PageReference pageRef = Page.Converttolead1;
           pageRef.getParameters().put('campaignMemberId', cmm.Id);
          
            Test.setCurrentPage(pageRef);   
         coverttolead1controller controller = new coverttolead1controller ();   
         controller.recordtypevalue = 'Sales_leads';
        controller.interstmodel='c-class';
        controller.displayPopup=false;
           controller.objectAPIName = 'Retail_Campaign__c';
           try{
               controller.getItems();
               controller.showPopup();
                   controller.closePopup();
                   //controller
                   //controller
            controller.convertToLead();
            }catch(exception e){}
           controller.cancel();
          
       Test.stopTest();
     }
}
    }