src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag to allow data sharing 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_DoCdata&quot;</description>
        <label>Allow Data Sharing</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Choice Yet</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Car_Model__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model info to be used in DM and Car Model comparison.</description>
    <label>Car Model</label>
    <nameField>
        <label>Car Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Model</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Data Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Car_License__c</fullName>
        <label>Car License</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Car_Model__c</fullName>
        <label>Car Model</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentMileage__c</fullName>
        <label>CurrentMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EuroVIN__c</fullName>
        <label>EuroVIN</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NextMileage__c</fullName>
        <label>NextMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Dealer__c</fullName>
        <label>Selling Dealer</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <label>UsVIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleRel_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VehicleRel No.</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Vehicle_Relationship__c.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle_Relationship__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Purchase_Date__c</fullName>
        <label>Vehicle Purchase Date</label>
        <type>Date</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <formula>VehicleRel_No__r.Purchase_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <formula>TEXT( Existing_Contract__r.Related_Vehicle__r.Model__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle Model</label>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>Car_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car Model</label>
        <referenceTo>Car_Model__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentMileage__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: The current mileage 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is "Vehicle_CurrentMileage“</description>
        <label>CurrentMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EuroVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Euro VIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is”Vehicle_EuroVIN“</description>
        <externalId>true</externalId>
        <label>EuroVIN</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NextMileage__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Vehicle mileage of the next service 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_NextMileage“</description>
        <label>NextMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Vehicle UsVIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_UsVIN“</description>
        <externalId>true</externalId>
        <label>UsVIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Purchase date of vehicle (information from leads, not from sales)
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is "VehicleRel_PurchaseDate"</description>
        <inlineHelpText>Purchase date of vehicle (information from leads, not from sales)</inlineHelpText>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Registration_Number__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Licence plate number of vehicle 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is" VehicleRel_RegistrationNumber"</description>
        <externalId>true</externalId>
        <inlineHelpText>Licence plate number of vehicle</inlineHelpText>
        <label>Registration Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selling_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Name of the last dealer who sold the vehicle
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is "VehicleRel_ProvidedDealer"</description>
        <inlineHelpText>Name of the last dealer who sold the vehicle</inlineHelpText>
        <label>Selling Dealer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper dealer account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships(Vehicle Relationship Selling Dealer)</relationshipLabel>
        <relationshipName>Vehicle_Relationships_Selling_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <formula>Vehicle_ID__r.UsVIN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UsVIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <formula>Vehicle_ID__r.Model_Description__c</formula>
        <label>Vehicle Model</label>
        <type>Text</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle_Relationship__c.object
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The flag to identify if this record can be shared with MBJ</description>
        <label>Allow Data Sharing</label>
        <type>Checkbox</type>
    </fields>

src/objects/Vehicle_Relationship__c.object
    <fields>
        <fullName>Car_Model__c</fullName>
        <formula>Vehicle_ID__r.Car_Model__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Car Model</label>
        <type>Text</type>
    </fields>

src/main/metadata-excluded/classes/UtilLead.cls
/*
    Type:       Trigger
    Purpose:    Populate Vehicle Rel Related Fields
    User Story: US-Lead-021, // US-Lead-009
    Used By:    TriggerLead.trigger
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-04-27
    2. Mouse Updated on 2013-07-04 for US-Lead-009
*/
public class UtilLead {
    // US-Lead-009
    public static void updateLeadForDataSharing(List<Lead__c> leads) {
        Set<Id> accIds = new Set<Id>();
        for (Lead__c lead : leads) {
            accIds.add(lead.Contact__c);
        }

        Map<Id, Account> accMap = new Map<Id, Account>(
            [SELECT Id, Allow_Data_Sharing__c 
             FROM Account WHERE Id IN :accIds]
        );

        for (Lead__c lead : leads) {
            String allowDataSharing = accMap.get(lead.Contact__c).Allow_Data_Sharing__c;
            lead.Allow_Data_Sharing__c = allowDataSharing == 'Yes' ? true : false;
        }
    }

    // US-Lead-021
    public static void updateRelatedVehicleRelFields(List<Lead__c> leads) {
        Set<Id> leadIdSet = new Set<Id>();
        for (Lead__c lead : leads) {
            if (lead.VehicleRel_No__c != null) {
                leadIdSet.add(lead.VehicleRel_No__c);
            }
        }

        Map<Id, Vehicle_Relationship__c> relationshipMap = 
            new Map<Id, Vehicle_Relationship__c>([SELECT Id, Registration_Number__c, 
                    Vehicle_ID__r.UsVIN__c, 
                    Vehicle_ID__r.EuroVIN__c,
                    Vehicle_ID__r.CurrentMileage__c,
                    Vehicle_ID__r.NextMileage__c,
                    Selling_Dealer__r.Name, 
                    Vehicle_Model__c,
                    Purchase_Date__c
             FROM Vehicle_Relationship__c
             WHERE Id IN :leadIdSet]);

        for (Lead__c lead : leads) {
            if (lead.VehicleRel_No__c != null) {
                Vehicle_Relationship__c relationship = relationshipMap.get(lead.VehicleRel_No__c);
                lead.Car_License__c = relationship.Registration_Number__c;
                lead.UsVIN__c = relationship.Vehicle_ID__r.UsVIN__c;
                lead.EuroVIN__c = relationship.Vehicle_ID__r.EuroVIN__c;
                lead.Selling_Dealer__c = relationship.Selling_Dealer__r.Name;
                lead.Car_Model__c = relationship.Vehicle_Model__c;
                lead.Vehicle_Purchase_Date__c = relationship.Purchase_Date__c;
                lead.CurrentMileage__c = relationship.Vehicle_ID__r.CurrentMileage__c;
                lead.NextMileage__c = relationship.Vehicle_ID__r.NextMileage__c;
            }
        }
    }
}