src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_CN__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is &quot;Dealer_CityCN&quot;</description>
        <label>City CN</label>
		<length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>MBDA</fullName>
        <active>true</active>
        <label>MBDA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>CAC_Lead_Status__c</fullName>
        <label>CAC Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Failed For 3 Days(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visited Showroom(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(CAC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(Dealer)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan to Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gave up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Instructor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MBDA_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_Vehicle_Brand__c</fullName>
        <label>Interested Vehicle Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TA&amp;C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Need Follow Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Need_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recommended_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recommended Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Recommended Dealer)</relationshipLabel>
        <relationshipName>MBDA_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Dealer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visit Dealer</label>
        <type>Checkbox</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata4au/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <description>Send Message to Customer</description>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-todo/classes/SendMessageToCustomerAndInstructorTest.cls
/**
 * This class contains unit tests for validating the behavior of 
 * SendMessageToCustomerAndInstructor trigger.
 */
@isTest
private class SendMessageToCustomerAndInstructorTest {

    static testMethod void testSendMessageToCustomerAndInstructor() {
        // Create test data
        String personalAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String dealerAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account testAccount = new Account(RecordTypeId = personalAccRecordTypeId, LastName = 'Acme 2', Status__c = 'Prospect', Type = 'Army', Province__c = 'AnHui', City_CN__c = '安庆市', PersonMobilePhone = '12322322343');
        Account testAccount2 = new Account(RecordTypeId = dealerAccRecordTypeId, Name = 'Test Dealer');
        insert new List<Account>{testAccount, testAccount2};
        
        User testPartnerUser = [select Id, Name from User where IsActive = true and ContactId != null limit 1];
        Id testUserId = testpartnerUser.Id;
        
        String mbdaLeadRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('MBDA Leads').getRecordTypeId();
        String otherLeadRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('Sales Leads').getRecordTypeId();
        Lead__c testLead1 = new Lead__c(RecordTypeId = mbdaLeadRecordTypeId, Lead_Type__c = 'No Need Follow Up', CAC_Lead_Status__c = 'Plan to Purchase', Interested_Vehicle_Brand__c = 'Interested Vehicle Class', Contact__c = testAccount.Id, Recommended_Dealer__c = testAccount2.Id, Instructor__c = testUserId, Need_Contact__c = true, Visit_Dealer__c = true);
        Lead__c testLead2 = new Lead__c(RecordTypeId = mbdaLeadRecordTypeId, Lead_Type__c = 'No Need Follow Up', CAC_Lead_Status__c = 'Plan to Purchase', Interested_Vehicle_Brand__c = 'Interested Vehicle Class', Contact__c = testAccount.Id, Recommended_Dealer__c = testAccount2.Id, Instructor__c = testUserId, Visit_Dealer__c = true, Need_Contact__c = true);
        Lead__c testLead3 = new Lead__c(RecordTypeId = mbdaLeadRecordTypeId, Lead_Type__c = 'No Need Follow Up', CAC_Lead_Status__c = 'Plan to Purchase', Interested_Vehicle_Brand__c = 'Interested Vehicle Class', Contact__c = testAccount.Id, Recommended_Dealer__c = testAccount2.Id, Instructor__c = testUserId, Visit_Dealer__c = true, Need_Contact__c = true);
        Lead__c testLead4 = new Lead__c(RecordTypeId = otherLeadRecordTypeId, Contact__c = testAccount.Id);
        Lead__c testLead5 = new Lead__c(RecordTypeId = otherLeadRecordTypeId, Contact__c = testAccount.Id);
        insert new List<Lead__c>{testLead1, testLead2, testLead3, testLead4, testLead5};
        
        system.assertEquals(6, [select Id from Task where Subject = 'SMS' and Status = 'Closed'].size());
    }
}