src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: GS Code of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_GCcode &quot;</description>
        <label>Dealer GC Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Executer__c</fullName>
        <description>Defines the owner of the campaign record</description>
        <label>Campaign Executer</label>
        <picklist>
            <picklistValues>
                <fullName>WholeSale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Execution_Channels__c</fullName>
        <description>This field is used to define whether the campaign will be executed via which channel, whether it will be an outbound email, SMS, outbound call etc</description>
        <label>Campaign Execution Channels</label>
        <picklist>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM Magazine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <description>The Type of Campaign</description>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parts Cross Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idle Hour Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Product Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for new vehicle owners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Familiarization workshop for dormant customers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VEP(Seasonal Check)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used-car buy-back/Trade-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion on Technical accessories and collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POM/Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Permission_Set_Settings__c</fullName>
        <inlineHelpText>Clues--the customer, vehicle, vehicle
Case-- Customer, vehicle, vehicle
Adds an active member/membership status/update activity generated sales leads--the customer, vehicle, vehicle, clues, and joint marketing activities and dealer campaigns</inlineHelpText>
        <label>Permission Set Settings</label>
        <picklist>
            <picklistValues>
                <fullName>Leads_Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint_Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S_M_Yearly_TA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S_M_Retail_Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS_Yearly_TA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS_Retail_Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation_execution_Retail_Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best_Practise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tool_Kit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info_Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer_Score</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer_Report</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <fields>
        <fullName>City__c</fullName>
        <formula>Dealer_Name__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Campaign_Execution_Channels__c</fullName>
        <label>Campaign Execution Channels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>DM</fullName>
                </value>
                <value>
                    <fullName>OB</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>DM Magazine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field can be used to track the progress of the campaign as part of campaign life cycle</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <formula>Contact.Account.Dealer_GC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer GC Code</label>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/Batch_RetailCampaignNotificationTest.cls
@isTest

public class Batch_RetailCampaignNotificationTest
{
    static String ParentCampID= Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Planning & Design Campaign').getRecordTypeId();
    static Id RetailcentmarcampRecordTypeId = Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
    public static Set<Id> RetailChildcampId = new Set<Id>();
    public static Id DealerAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
    public static Id camIdPlan= Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Planning & Design Campaign').getRecordTypeId();
    public static Profile DealerProfile= [select Id from Profile where Name = 'Japan Dealer Sales Manager' limit 1];
    public static testmethod void executeBatch_RetailCampaignNotification()
    {
        test.starttest();
        
        Account DealerAccount= new Account();
        DealerAccount.RecordtypeId=DealerAccRecordTypeId;
        DealerAccount.Name='Test Person 1st';
        DealerAccount.Type='Personal';
        DealerAccount.Status__c='Active';
        DealerAccount.Dealer_GC_Code__c='12345';
        DealerAccount.Province__c='Province1';
        DealerAccount.City__c='Test';
        DealerAccount.Email__c='test@mbj.com';
        DealerAccount.Mobile__c ='0435488899';
        insert DealerAccount;
        
         Contact   con = new Contact(AccountId = DealerAccount.Id,Permission_Set_Settings__c='Leads_Management', LastName = 'b', Phone = '123', email = 's@s.s');
        insert con;
        
       User usr = new User(
            Username = System.now().millisecond() + 'testDaimlerUser212121@Daimler-test.com',
            FirstName = 'firstname',
            ProfileId = DealerProfile.Id,            
            Alias = 'test123',
            Email = 'test12345@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'McTesty',
            Market__c = 'JP',
            CommunityNickname = System.now().millisecond() + 'test12345',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ContactId=con.id,   
            Notification_Campaign__c='long text'         
        );
        Insert usr;
        
        Campaign camobj12 = new Campaign();
        camobj12.RecordTypeId = camIdPlan;
        camobj12.Name = 'camptest1';
        camobj12.Type = 'Other';
        camobj12.Status = 'Draft';
        camobj12.StartDate = System.today();
        camobj12.EndDate = System.today()+30;
        camobj12.Campaign_Executer__c='Retail';
        camobj12.Campaign_Objectives__c = 'camobjectives';
        camobj12.Description = 'testdescrip';
        camobj12.Campaign_Execution_Channels__c='eMail';
        camobj12.Campaign_Type__c = 'After Sales';
        insert camobj12;
        
         Retail_Campaign__c RParentCamp = new Retail_Campaign__c(
            name='ParentCamp',
            Start_Date__c=System.Today(),
            Close_Date__c=System.Today()+4,
            Status__c='Draft',
            RecordTypeId=ParentCampID
         );
         insert RParentCamp;
        Retail_Campaign__c RChildCamp = new Retail_Campaign__c(
            Name='ChildCamp',
            Parent_Campaign__c = camobj12.id,
            Execution_Start_Date__c=System.Today()+1,
             Segmentation_Date__c=System.Today(),
             Parent_Campaign1__c=RParentCamp.Id,
             Segmentation_Base__c='Customer',
             Execution_Type__c='eMail',
             RecordTypeId=RetailcentmarcampRecordTypeId,
             Dealer_Name__c=DealerAccount.id             
             );
             insert RChildCamp;
      
     RetailChildcampId.add(RChildCamp.Id);
    
      Batch_RetailCampaignNotification batcherntwo = new Batch_RetailCampaignNotification(RetailChildcampId);
       Database.executeBatch(batcherntwo, 1);
       test.stoptest();
    }
}