src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Attribute in Data Dictionary object Contact is &quot;Contact_CompanyName&quot;</description>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to refer the related retail campaign execution record</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_ID__c</fullName>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign Member ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <formula>""</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to refer the related Customer/Contact  record</description>
        <label>Contact Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Task</label>
        <referenceTo>Retail_Task__c</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_Model__c</fullName>
        <label>Interested  Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Sub_Type__c</fullName>
        <label>Lead Sub Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign member (Retail Campaign)</relationshipLabel>
        <relationshipName>Campaign_member1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to set the status of the campaign member</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will have Vehicle reference ID from Marketing Cloud</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Member__c.object
	<fields>
        <fullName>Contract_Phone1_1__c</fullName>
        <label>Contract Phone 1</label>
        <length>100</length>
        <type>Text</type>
    </fields> 

src/main/metadata/objects/Campaign_Member__c.object
	<fields>
        <fullName>Contract_Phone2_2__c</fullName>
        <label>Contract Phone 2</label>
        <length>100</length>
        <type>Text</type>
    </fields> 

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field can be used to track the progress of the campaign as part of campaign life cycle</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>OB_Call</fullName>
        <active>true</active>
        <description>Outbount Call</description>
        <label>OB Call</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
    <!---->
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/ConvertToTask1Controller.cls
public class ConvertToTask1Controller
{
     private final String campaignId = ApexPages.currentPage().getParameters().get('CampaignMemberId');
    private String objectAPIName;
    public account contactList=new account();
    public List<Campaign_Member__c> campaignMembers {get; set;}
    public static Id OB_Call = Schema.SObjectType.Task.getRecordTypeInfosByName().get('OB Call').getRecordTypeId();
    public ConvertToTask1Controller()
    {
           
           if(String.isNotBlank(campaignId)) 
           {
            objectAPIName = (Id.valueOf(campaignId)).getSObjectType().getDescribe().getName();
            String query = 'SELECT Id,Name, Campaign_ID__r.OwnerId, Retail_Campaign_Id__r.OwnerId,Contract_Phone1_1__c,Contract_Phone2_2__c, Vehicle__c,Contact_Id__c,Company_Name__c,Contract__c ,Lead_Type__c, Lead_Sub_Type__c, Interested_Model__c';
      
      query += ' FROM Campaign_Member__c WHERE Status__c = \'Responded\' AND Id =: campaignId';
            
            List<Campaign_Member__c> campaignMemberList = Database.query(query);
            campaignMembers = new List<Campaign_Member__c>();
            system.debug('cms>>>'+campaignMemberList);
            for(Campaign_Member__c campaignMemberRec : campaignMemberList) 
            {
                campaignMembers.add(campaignMemberRec);
            }
          }
    }
    
      public PageReference cancel() 
      {
        return new PageReference('/' + campaignId);
      }
    
     public PageReference convertToTask() 
     {
        List<Task> taskList = new List<Task>();
        List<Task> taskListToInsert = new List<Task>();
        for(Campaign_Member__c campaignMemberObj : campaignMembers) 
        { 
                if(campaignMemberObj.Campaign_ID__c != null && campaignMemberObj.Retail_Campaign_Id__c == null) 
                {
                        taskListToInsert .add(setTaskRecordFields(campaignMemberObj.Campaign_ID__c, campaignMemberObj));
                        
                } else if(campaignMemberObj.Campaign_ID__c == null && campaignMemberObj.Retail_Campaign_Id__c != null) 
                {
                        taskListToInsert .add(setTaskRecordFields(campaignMemberObj.Retail_Campaign_Id__c, campaignMemberObj));
                        
                }
         }
        if(taskListToInsert.size() > 0)
        {
            insert taskListToInsert;
            system.debug('$%$%$%$%taskListToInsert'+taskListToInsert);
        }
        
      return new PageReference('/' + taskListToInsert[0].id);
     }
     
  @TestVisible   private Task setTaskRecordFields(String campaignId, Campaign_Member__c campaignMember) 
     {

        System.debug('camid<<<'+campaignMember.Campaign_Id__c);
        System.debug('camid<<<'+campaignMember.Company_Name__c);
        System.debug('camid<<<'+campaignMember.Contract_Phone1_1__c);
        System.debug('camid<<<'+campaignMember.Contract_Phone2_2__c);
        System.debug('camid<<<'+campaignMember.Contact_Id__c);
        Task taskRec = new Task(RecordTypeId = OB_Call);
        contactList=[select id,PersonContactId from account where id=:campaignMember.Contact_Id__c];
        taskRec.status= 'New';
        taskRec.Priority='Low';
        taskRec.subject = 'Campaign Executed';
        taskRec.Whatid = campaignMember.Campaign_Id__c ;
        taskRec.whoid = contactList.PersonContactId;
        taskRec.Contract__c = campaignMember.Contract__c ;
        taskRec.Related_Vehicle__c= campaignMember.Vehicle__c;    
        taskRec.Account_Name__c =campaignMember.Company_Name__c;
       taskRec.Phone__c = campaignMember.Contract_Phone1_1__c;
      taskRec.Phone_number__c= campaignMember.Contract_Phone2_2__c;
     taskRec.Campaign_Member_ID__c = campaignMember.Name; 

  
  
        if(objectAPIName == 'Campaign' || objectAPIName == 'Retail_Campaign__c')
         {
           taskRec.whatID=campaignId;
           taskRec.OwnerId = UserInfo.getUserId();//campaignMember.Campaign_ID__r.OwnerId;
        }
         else if(objectAPIName == 'Retail_Campaign__c')
          { 
            taskRec.whatID=campaignId;
            taskRec.OwnerId = UserInfo.getUserId();//campaignMember.Retail_Campaign_Id__r.OwnerId;
        }  
        
        if(OB_Call!= null) {
            taskRec.RecordTypeId = OB_Call;
        }
        return taskRec;
    }
}