src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Attribute in Data Dictionary object Contact is &quot;Contact_CompanyName&quot;</description>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Block__c</fullName>
        <label>Block</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>Town</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preferred</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Prefecture</label>
        <picklist>
            <picklistValues>
                <fullName>Hokkaido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aomori</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iwate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miyagi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamagata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukushima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ibaraki</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tochigi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gunma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saitama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tokyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kanagawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niigata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ishikawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamanashi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shizuoka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aichi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shiga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kyoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Osaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wakayama</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TitleOfHonor__c</fullName>
        <label>TitleOfHonor</label>
        <picklist>
            <picklistValues>
                <fullName>To Person</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>To Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Post Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/classes/AddressDisplayInlineEditController.cls
/**   
    Purpose:  Innline controller To add, edit and delete related address to an account   
    created by: Srinivas 11/3/2015
    modified by: Sriram Kalluri 11/4/2015
   
*/
public class AddressDisplayInlineEditController { 

   public List<Address__c> adds {get; set;}
   public Address__c addressobj {get; set;}
   public Boolean ShowpageBlockFlag {get;set;}
   private ApexPages.StandardController stdController;   
   public string addressId {get;set;}   
   public String aid; 
   
   
  
   public AddressDisplayInlineEditController(ApexPages.StandardController stdController){
	       this.stdController = stdController;     
	       aid = ApexPages.currentPage().getParameters().get('id');
	       system.debug('######'+ aid);
       
		     if(ApexPages.currentPage().getParameters().get('id')!=Null){
		     	
		        adds = [Select id,Name, Address_Type__c, Status__c , ZipCode__c,Province__c,Preferred__c,Company_Name__c,
		        Address_Line_2__c ,Address_Line_1__c,District__c,City__c, Block__c, TitleOfHonor__c from Address__c where Customer__c =: aid ];        
		        system.debug('@Account Information :' +adds);
		     }
     
	     /*Intitializing address object*/
	     addressobj = new Address__c();
   } 
 
 
    /**    
     * @Description : Cancel functionality 
     * @author      : Srinivas
     * @Date        : 11/3/2015
     * @return      : null
      
    **/	 
    public PageReference cancelEdit() {
        ShowpageBlockFlag = null;
        return null;        
    }
    
   
    /**    
     * @Description : saves edited records
     * @author      : Srinivas
     * @Date        : 11/3/2015    
      
    **/	 
   public void saveEditedRecords(){
       system.debug('@Changed Address Records :' +adds);
	       try{
	       	update adds;
	       }catch (Exception e) {
	        ApexPages.addMessages(e);
	       }
   }
   
   
    /**    
     * @Description : to load updated data after deletion of address
     * @author      : Srinivas
     * @Date        : 11/3/2015     
    **/	 
   private void loadData() {
	       system.debug('@Loading Addresses...');
	       adds = [Select id,Name, Address_Type__c, Status__c , ZipCode__c,Province__c,Preferred__c,Company_Name__c,
	              Address_Line_2__c ,Address_Line_1__c,District__c,City__c, Block__c,TitleOfHonor__c  from Address__c where Customer__c =: aid];
   }
   
   
   
    /**    
     * @Description : deletes the address record 
     * @author      : Srinivas
     * @Date        : 11/3/2015    
      
    **/	 
   
   public void delAccountAddress(){
	        system.debug('@Entered Delete method...');
	        system.debug('@addressId :' +addressId);
	        
        
      	// if for any reason we are missing the reference 
	      if (addressId == null) {
	         return;
	      }
      
	      // find the address record within the collection
	      Address__c tobeDeleted = null;
	      for(Address__c a : adds)
	       if (a.Id == addressId){
	          tobeDeleted = a;
	          break;
	       }      
      
      
	      //if address record found delete it
	      if(tobeDeleted != null) {
	         system.debug('@Delete DML' +tobeDeleted.id);
	         try{
	         	Delete tobeDeleted;
	         }catch (Exception e) {
	       		 ApexPages.addMessages(e);
	         }
	         system.debug('@Delete Address...');
	      }
	      //refresh the data
	      loadData();
	  }
      
   public void addEditOptions(){
   	
       ShowpageBlockFlag = true;
       
   }
 
 
 /**    
     * @Description : creates new address record  
     * @author      : Srinivas
     * @Date        : 11/3/2015    
      
    **/	 
  
  public void saveAddress(){
  	
	      system.debug('addressobj>>>>>'+addressobj);
	      system.debug('@Account Id :' +ApexPages.currentPage().getParameters().get('id'));
	      
        if(addressobj != null ){ 
      	
	        Account acc=[select id,name from Account where id=:ApexPages.currentPage().getParameters().get('id')];
	        system.debug('ACCid>>>>>'+acc); 
	        addressobj.Customer__c = acc.id;
          
        try{
        	upsert addressobj;  
        }catch (Exception e) {
	        ApexPages.addMessages(e);
	       }
	       
      }
  }
  
 
  
}