src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_CN__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is &quot;Dealer_CityCN&quot;</description>
        <label>City CN</label>
		<length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>MBDA</fullName>
        <active>true</active>
        <label>MBDA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Car_Type__c</fullName>
        <label>Car Type</label>
        <picklist>
            <picklistValues>
                <fullName>PbP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Inquiry</fullName>
        <active>true</active>
        <businessProcess>Inquiry Process</businessProcess>
        <description>Customer Inquiry Case</description>
        <label>Inquiry</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-excluded/classes/CreateOBTaskForMBDACaseTest.cls
/**
 * This class contains unit tests for validating the behavior of trigger CreateOBTaskForMBDACase.
 */
@isTest
private class CreateOBTaskForMBDACaseTest {

    static testMethod void testCreateOBTaskForMBDACase() {
        // Create test data
        String mbdaComplaintId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('MBDA Complaint').getRecordTypeId();
        String mbdaInquiryId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('MBDA Inquiry').getRecordTypeId();
        String CAC_MBDA_QueueId = [select Id from Group where DeveloperName = 'CAC_MBDA' and Type = 'Queue' order by CreatedDate desc limit 1].Id;
        String OBTaskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('OB Task').getRecordTypeId();
        String personalAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account testPersonalAccount = new Account(RecordTypeId = personalAccRecordTypeId, LastName = 'Acme 29', Status__c = 'Prospect', Type = 'Army', Province__c = 'AnHui', City_CN__c = '安庆市', PersonMobilePhone = '12322322943');
        insert testPersonalAccount;
        
        Case testCase1 = new Case(RecordTypeId = mbdaComplaintId, AccountId = testPersonalAccount.Id, Car_Type__c = 'CBU', Status = 'Open', Subject = 'Test MBDA - 01', OwnerId = CAC_MBDA_QueueId);
        Case testCase2 = new Case(RecordTypeId = mbdaComplaintId, AccountId = testPersonalAccount.Id, Car_Type__c = 'CBU', Status = 'Open', Subject = 'Test MBDA - 02', OwnerId = CAC_MBDA_QueueId);
        Case testCase3 = new Case(RecordTypeId = mbdaInquiryId, AccountId = testPersonalAccount.Id, Car_Type__c = 'CBU', Status = 'Open', Subject = 'Test MBDA - 03', OwnerId = CAC_MBDA_QueueId);
        Case testCase4 = new Case(RecordTypeId = mbdaInquiryId, AccountId = testPersonalAccount.Id, Car_Type__c = 'CBU', Status = 'Open', Subject = 'Test MBDA - 04', OwnerId = CAC_MBDA_QueueId);
        Case testCase5 = new Case(RecordTypeId = mbdaInquiryId, AccountId = testPersonalAccount.Id, Car_Type__c = 'CBU', Status = 'Open', Subject = 'Test MBDA - 05');
        Case testCase6 = new Case(RecordTypeId = mbdaInquiryId, AccountId = testPersonalAccount.Id, Car_Type__c = 'CBU', Status = 'Open', Subject = 'Test MBDA - 06');
        Case testCase7 = new Case(RecordTypeId = mbdaInquiryId, AccountId = testPersonalAccount.Id, Car_Type__c = 'CBU', Status = 'Open', Subject = 'Test MBDA - 07');
        insert new List<Case>{testCase1, testCase2, testCase3, testCase4, testCase5, testCase6, testCase7};
        
        List<Task> obTasks = [select Id from Task where RecordTypeId = :OBTaskRecordTypeId];
        System.assertEquals(4, obTasks.size());
        
        update new List<Case>{new Case(Id = testCase5.Id, OwnerId = CAC_MBDA_QueueId), new Case(Id = testCase6.Id, OwnerId = CAC_MBDA_QueueId), new Case(Id = testCase7.Id, OwnerId = CAC_MBDA_QueueId)};
        List<Task> obTasks2 = [select Id from Task where RecordTypeId = :OBTaskRecordTypeId];
        System.assertEquals(7, obTasks2.size());
    }
}