src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Required by business during the workshop, which exists in current avarto system ( 区号).</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_SR_Code__c</fullName>
        <label>Dealer DMS SR Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Default_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Function:  Indicates that this dealer is unique and should be visible in SFDC.  Defined by the GSSN interface. 

Feb18-2013-  Rob and Falk - based on GSSN interface requirements</description>
        <label>Dealer Default Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Gender of the person 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_Gender&quot;</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Stop All Postal contact for this person 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_StopPostal&quot;</description>
        <label>Postal Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email2</label>
        <type>Email</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email3__c</fullName>
        <label>Other E-Mail</label>
        <type>Email</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_2__c</fullName>
        <label>Home Phone 2</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Mobile2__c</fullName>
        <label>Mobile 2</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Personal_Agreement__c</fullName>
        <label>Personal Agreement</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Primary_Email__c</fullName>
        <label>Sales Mail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>E-mail1</fullName>
                </value>
                <value>
                    <fullName>E-mail2</fullName>
                </value>
                <value>
                    <fullName>E-mail3</fullName>
                </value>
                <value>
                    <fullName>E-Mail(Private)</fullName>
                </value>
                <value>
                    <fullName>E-Mail(Business)</fullName>
                </value>
                <value>
                    <fullName>Mobile E-Mail(Private)</fullName>
                </value>
                <value>
                    <fullName>Mobile E-Mail(Business)</fullName>
                </value>
                <value>
                    <fullName>Other E-Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Primary_Fax__c</fullName>
        <label>Sales FAX</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FAX1</fullName>
                </value>
                <value>
                    <fullName>FAX2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Updated_Consent_Date__c</fullName>
        <label>Updated Consent Date</label>
        <type>Date</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <recordTypes>
        <fullName>Dealer1</fullName>
        <active>true</active>
        <description>Recordtype for dealer</description>
        <label>Dealer1</label>
    </recordTypes>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA')))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Agreement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personal Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Dealer Type</label>
        <picklist>
            <picklistValues>
                <fullName>My Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Selling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Servicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign/Project Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Shops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Link__c.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;) ,&apos;MY&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/PA_Doc_CustomerUpdateBatchTest.cls
/*
    Type:Test class
    Purpose:Test Class for PA_Doc_CustomerUpdateBatch
    User Story:
    Used By:     
    ---------------------------------------------------------------
    History:
    1. Created on 22-08-2018 by Ashish vashisht
    2. Modified     
*/
@isTest 
public class PA_Doc_CustomerUpdateBatchTest
{
    public static User user2=TestUtils.IntegrationAPIUser();
    public static User user1 = TestUtils.createTRAdminUser();
    public static List<Account>acclst= new List<Account>();
    public static List<Account_link__c>acclnklst= new List<Account_link__c>();
    public static Id dealerType =Schema.SObjectType.Account.getRecordTypeInfosByName().get(UtilTestData.ACCOUNT_RT_DEALER).getRecordTypeId();
    public static Id Person_RecordTypeId = RecordTypeAccessService.getRecordTypeId('Account_Link__c', 'Retail Person');
    public static testmethod void testMethod1() 
    {
        
        system.runas(user2)
        {

            Account acct1= new Account(Dealer_Default_Flag__c=false,
                           Dealer_DMS_SR_Code__c='test code 2',
                           //Individual_Home_Phone__c = '02-202-2456',
                           Home_Phone_2__c = '02-202-2457',Work_Phone__c = '+601212378978',Personal_Agreement__c ='Yes',Updated_Consent_Date__c = date.valueOf('2007-05-05'),
                           Status__c='NoCustomer',Email__c = 'testemail@test.com',Email2__c = 'testemail2@test.com',Email3__c = 'testemail3@test.com',
                           City__c='Beijing',
                           Gender__c = 'Male',
                           Phone = '0801801110',
                           Area_code__c = '03',
                           MD__c = 'TR',
                           Market__c = 'TR',
                           LastName = 'galaxy1',
                           FirstName = 'First Name1',
                           Salutation = 'Unknown',
                           Postal_Opt_Out__c=false,     
                           Province__c = 'Shanghai',
                           ZipCode__c= '32703',
                           //Mobile__c = '918197597651',
                           //Mobile2__c = '918197597651',
                           Primary_Email__c = 'Email1',
                           Primary_Fax__c = 'FAX2',
                           Primary_Phone__c ='Other2',
                           PersonDoNotCall=false,
                           // ownerid=user1.id,
                           PersonHasOptedOutOfEmail=false,
                           Opt_In_Email__c=false,
                           Data_Source__c='Employee Referral',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()); 
                           
            
                           
            Account acct3= new Account(Dealer_Default_Flag__c=false,
                           Dealer_DMS_SR_Code__c='test code 2',
                           //Individual_Home_Phone__c = '02-202-2456',
                           Home_Phone_2__c = '02-202-2457',Work_Phone__c = '+601212378978',Personal_Agreement__c ='Yes',Updated_Consent_Date__c = date.valueOf('2007-05-05'),
                           Status__c='NoCustomer',Email__c = 'testemail23@test.com',Email2__c = 'testemail2@test.com',Email3__c = 'testemail3@test.com',
                           City__c='Beijing',
                           Gender__c = 'Male',
                           Phone = '0801801110',
                           Area_code__c = '03',
                           MD__c = 'TR',
                           Market__c = 'TR',
                           LastName = 'galaxy1',
                           FirstName = 'First Name1',
                           Salutation = 'Unknown',
                           Postal_Opt_Out__c=True,     
                           Province__c = 'Shanghai',
                           ZipCode__c= '32703',
                           //Mobile__c = '918197597651',
                           //Mobile2__c = '918197597651',
                           Primary_Email__c = 'Email1',
                           Primary_Fax__c = 'FAX2',
                           Primary_Phone__c ='Other2',
                           PersonDoNotCall=True,
                           // ownerid=user1.id,
                           PersonHasOptedOutOfEmail=True,
                           Opt_In_Email__c=true,
                           Data_Source__c='Employee Referral',
                           //owner=user1,
                           //PersonBirthdate=date.today(),
                           
                           RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()); 
        
            acclst.add(acct1);
            acclst.add(acct3);
            
            insert acclst;
            
            Account dealer1 =  new Account(Dealer_DMS_CRM_Code__c = 'DealerCode',Market__c='TR', Individual_Home_Phone__c='+66-9885857857', RecordTypeId = dealerType, Name = 'test dealer1',Dealer_GC_Code__c = '12345',Dealer_nd_Code__C='1235');
            insert dealer1;
            
            Account_Link__c acclnk1 = new Account_Link__c(Name = 'aTest',ToRole__c = acct1.Id, fromRole__c = dealer1.id, ReCordTypeId = Person_RecordTypeId,Retail_Postal_OptOut__c=true,Retail_Email_OptOut__c=true,Retail_Phone_OptOut__c=true,Retail_SMS_OptIn__c=true,Retail_SMS_OptOut__c=true);
            acclnklst.add(acclnk1);
            
            
            
            Account_Link__c acclnk3 = new Account_Link__c(Name = 'aTest',ToRole__c = acct3.Id, fromRole__c = dealer1.id, ReCordTypeId = Person_RecordTypeId,Retail_Postal_OptOut__c=true,Retail_Email_OptOut__c=true,Retail_Phone_OptOut__c=true,Retail_SMS_OptIn__c=true,Retail_SMS_OptOut__c=true);
            acclnklst.add(acclnk3);
            
            insert acclnklst;
            
            test.starttest(); 
                PA_Doc_CustomerUpdateBatch b = new PA_Doc_CustomerUpdateBatch();
                Database.executebatch(b);
            test.stoptest(); 
        }
    }
    
     public static testmethod void testMethod2() 
    {
        User user2=TestUtils.IntegrationAPIUser();
        system.runas(user2)
        {
            Account dealer1 =  new Account(Dealer_DMS_CRM_Code__c = 'DealerCode',Market__c='TR', Individual_Home_Phone__c='+66-9885857857', RecordTypeId = dealerType, Name = 'test dealer1',Dealer_GC_Code__c = '12345',Dealer_nd_Code__C='1235');
            insert dealer1;
            Account acct2= new Account(Dealer_Default_Flag__c=false,
                           Dealer_DMS_SR_Code__c='test code 2',
                           //Individual_Home_Phone__c = '02-202-2456',
                           Home_Phone_2__c = '02-202-2457',Work_Phone__c = '+601212378978',Personal_Agreement__c ='Yes',Updated_Consent_Date__c = date.valueOf('2006-05-05'),
                           Status__c='NoCustomer',Email__c = 'testemai2344l@test.com',Email2__c = 'testemail2@test.com',Email3__c = 'testemail3@test.com',
                           City__c='Beijing',
                           Gender__c = 'Male',
                           Phone = '0801801110',
                           Area_code__c = '03',
                           MD__c = 'TR',
                           Market__c = 'TR',
                           LastName = 'galaxy1',
                           FirstName = 'First Name1',
                           Salutation = 'Unknown',
                           Postal_Opt_Out__c=false,     
                           Province__c = 'Shanghai',
                           ZipCode__c= '32703',
                           //Mobile__c = '918197597651',
                           //Mobile2__c = '918197597651',
                           Primary_Email__c = 'Email1',
                           Primary_Fax__c = 'FAX2',
                           Primary_Phone__c ='Other2',
                           PersonDoNotCall=True,
                           // ownerid=user1.id,
                           PersonHasOptedOutOfEmail=True,
                           Opt_In_Email__c=false,
                           Opt_In_SMS__c=false,
                           Postal_Opt_In__c=false,
                           Opt_In_Mobile__c=false,
                           Data_Source__c='Employee Referral',
                           //owner=user1,
                           //PersonBirthdate=date.today(),
                           
                           RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()); 
        
        insert acct2;
        
        Account_Link__c acclnk2 = new Account_Link__c(Name = 'aTest',ToRole__c = acct2.Id, fromRole__c = dealer1.id, ReCordTypeId = Person_RecordTypeId,Retail_Postal_OptOut__c=false,Retail_Email_OptOut__c=false,Retail_Phone_OptOut__c=false,Retail_SMS_OptIn__c=false,Retail_SMS_OptOut__c=false);
        
        insert acclnk2;

            test.starttest(); 
                    PA_Doc_CustomerUpdateBatch b = new PA_Doc_CustomerUpdateBatch();
                    Database.executebatch(b);
            test.stoptest(); 
        }
    }
    
}