src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Ideas__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>oCRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>aCRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Quality Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Reduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process Improvements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed by Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taken up for product roadmap</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Idea</label>
    <nameField>
        <label>Idea Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Registered_Users__c.object
<CustomObject>
    <fields>
        <fullName>emailId__c</fullName>
        <description>used to store email of the requestor</description>
        <label>EmailId</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>first_Name__c</fullName>
        <description>used to store firstname</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_Name__c</fullName>
        <description>used to store last name</description>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>request_Status__c</fullName>
        <label>request Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>userName__c</fullName>
        <description>Based on the firstname and last name this field is autopopulated.
firstname_lastname@rugcollaboration.diamler.com</description>
        <label>userName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Registered User</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registered Users Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registered User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/Rug_util.cls
/****************************************************************
 * Modified by : Sarath
 * Last Modified On : 11 Oct 2017
 * Company: Infosys Ltd
 * Description : Util Class for Test Methods
*****************************************************************/
@istest
public class Rug_util {
    
	public static testMethod list<Registered_Users__c> Registereduser(){    
        list<Registered_Users__c> regList=new list<Registered_Users__c>();
        Trigger__C rugtrigger=new Trigger__C(name='RegisteredUsersTriggerTH',after__c=true,before__c=true,delete__c=true,enabled__c=true,insert__c=true,Market__c='TH',Trigger_Handler__c='RegisteredUsersTriggerHandler',Trigger_Name__c='RegisteredUsersTrigger',update__c=true);
	    insert rugtrigger;
       /* String orgId = userInfo.getOrganizationId().substring(0,5);
    	String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        string datestr=dateString.substring(0,5);
    	Integer randomInt = Integer.valueOf(math.rint(math.random()*1000));
    	String uniqueName = orgId + datestr;
        Integer randomInt2 = Integer.valueOf(math.rint(math.random()*1000));
        String uniqueName2 = orgId + datestr + randomInt2;**/        
        Registered_Users__c TestRegUserUtil = new Registered_Users__c();
        TestRegUserUtil.First_Name__c = 'test324'+System.now().millisecond();
        TestRegUserUtil.EmailId__c = '1'+System.now().millisecond() +'@infosys.com';
        TestRegUserUtil.Last_Name__c='2'+System.now().millisecond();
        TestRegUserUtil.Request_Status__c='New';
        TestRegUserUtil.UserName__c='4'+System.now().millisecond()+'@rugcollaboration.com';
        insert TestRegUserUtil;
        reglist.clear();
        reglist.add(TestRegUserUtil);
		//insert regList;        
        return reglist;
    }
    public static testMethod list<user> userCreated(){        
        Profile p = [SELECT Id FROM Profile WHERE Name='Honorary Membership'];
        list<user> userlist=new list<user>();
        User TestUserUtil = new User();
        TestUserUtil.Alias = 'TestUser';
        TestUserUtil.Email='TestUser@testorg.daimlerasia.com';
        TestUserUtil.EmailEncodingKey='UTF-8';
        TestUserUtil.LastName='TestUser';
        TestUserUtil.LanguageLocaleKey='en_US';
        TestUserUtil.LocaleSidKey='en_US';
        TestUserUtil.ProfileId = p.Id;
        TestUserUtil.TimeZoneSidKey='America/Los_Angeles';
        TestUserUtil.UserName='TestUser@testorg.com.daimlerasia';
        
        insert TestUserUtil;
        userlist.add(TestUserUtil);
        system.assertEquals(TestUserUtil.LastName, 'TestUser');
        return userlist;
    }
    
     public static testMethod user honoraryProfileUser(){        
        Profile p = [SELECT Id FROM Profile WHERE Name='Honorary Member'];
        Account ac = new Account(name ='Grazitti') ;    
        User testUser = new User();
        testUser.Alias = 'TestUser';
        testUser.Email='TestUser@testorg.daimlerasia.com';
        testUser.EmailEncodingKey='UTF-8';
        testUser.LastName='TestUser';
        testUser.LanguageLocaleKey='en_US';
        testUser.LocaleSidKey='en_US';
        testUser.ProfileId = p.Id;
        testUser.TimeZoneSidKey='America/Los_Angeles';
        testUser.UserName='12346g@testorg.com.daimlerasia445645' ;
        insert testUser;   
		return testUser;
     }
    public static testMethod Ideas__c newIdea(){ 
   		Ideas__c newIdea = new Ideas__c(Name = 'Name251',Category__c = 'oCRM', Status__c = 'Open', Classification__c = 'Quality Improvement');
      
        Insert newIdea;
        return newIdea;
    }

}