src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Region__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Region of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_Region&quot;</description>
        <label>Dealer Region</label>
        <picklist>
            <picklistValues>
                <fullName>NORTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>StarElite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBAFC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CBU_PbP__c</fullName>
        <label>CBU/PbP</label>
        <picklist>
            <picklistValues>
                <fullName>CBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PbP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBU&amp;PbP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>外展/路演</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>试乘试驾</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>地方车展</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>事件/节日营销</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>新车上市发布</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>联合品牌活动</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>展厅活动</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>体育营销活动</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>赞助/慈善</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>制作物相关</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>其他</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Media_Type__c</fullName>
        <label>Media Type</label>
        <picklist>
            <picklistValues>
                <fullName>户外</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>电视</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>广播</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>数字媒体</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>手机</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>报纸</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>杂志</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>其他</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <label>活动工具箱</label>
    </recordTypes>
</CustomObject>

src/main/metadata/objects/Tool_Kit__c.object
<CustomObject>
    <fields>
        <fullName>Ad_Color__c</fullName>
        <description>Ad. Color of the tool kit</description>
        <label>Ad. Color</label>
        <picklist>
            <picklistValues>
                <fullName>Black and White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ad_Copy__c</fullName>
        <label>Ad. Copy</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ad_Format__c</fullName>
        <description>Ad, Format of the tool kit</description>
        <label>Ad. Format</label>
        <picklist>
            <picklistValues>
                <fullName>Picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ad_Size_Height__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Ad. Size Height of the tool kit</description>
        <inlineHelpText>Units (cm)</inlineHelpText>
        <label>Ad. Size Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ad_Size_Width__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Ad. Size Width of the tool kit</description>
        <inlineHelpText>Units (cm)</inlineHelpText>
        <label>Ad. Size Width</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Background__c</fullName>
        <description>Background of the Tool Kit</description>
        <label>Background</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bleed_Size_Height__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Bleed Size Height of the tool kit</description>
        <inlineHelpText>Units(cm)</inlineHelpText>
        <label>Bleed Size Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bleed_Size_Width__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Bleed Size Width of the tool kit</description>
        <inlineHelpText>Units(cm)</inlineHelpText>
        <label>Bleed Size Width</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>StarElite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Dealer Name of the tool kit</description>
        <label>Dealer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tool Kits (Dealer Name)</relationshipLabel>
        <relationshipName>Tool_Kits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Region__c</fullName>
        <label>Dealer Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deliver_Date__c</fullName>
        <description>Deliver Date of the tool kit</description>
        <label>Deliver Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Director__c</fullName>
        <description>Event Director of the Tool Kit</description>
        <label>Event Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Participant__c</fullName>
        <description>Event Participant of the Tool Kit</description>
        <label>Event Participant</label>
        <picklist>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Event Type of the Tool Kit</description>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Road Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Festival</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Car Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joint Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Showroom Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sports Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prints relevant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Showroom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location_Size__c</fullName>
        <description>Location Size of the Tool Kit</description>
        <label>Location Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location of the Tool Kit</description>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Indoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Showrrom</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Media_Name__c</fullName>
        <description>Media Name of the tool kit</description>
        <label>Media Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Media_Type__c</fullName>
        <description>Media Type of the tool kit</description>
        <label>Media Type</label>
        <picklist>
            <picklistValues>
                <fullName>OOH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspaper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_End_Date__c</fullName>
        <description>Date for the tool kit end</description>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Expense__c</fullName>
        <description>Plan Expense of the tool kit</description>
        <label>Plan Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Plan_Start_Date__c</fullName>
        <description>Date for the tool kit start</description>
        <label>Plan Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Purpose of the Tool Kit</description>
        <label>Purpose</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>Request of the Tool Kit</description>
        <label>Request</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Tool Kit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tool Kits</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Headquarters activities supported by the Toolbox application</description>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Media</fullName>
        <active>true</active>
        <description>Headquarters support Media Kit request</description>
        <label>Media</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/ToolKitSelectContentControllerTest.cls
/*
    Type:       Test Class
    Purpose:    To test the Class ToolKitSelectContentController
    User Story: 
    1. Barney Lai Created on 2014-5-15
    2. zhongyang.si update on 2014-11-10
*/
@isTest 
public with sharing class ToolKitSelectContentControllerTest {
Private Static Id eventRT = Schema.SObjectType.Tool_Kit__c.getRecordTypeInfosByName().get('Event').getRecordTypeId();
Private Static Id mediaRT = Schema.SObjectType.Tool_Kit__c.getRecordTypeInfosByName().get('Media').getRecordTypeId();
Private Static Account dealerAcc;
Private Static Account acc;
Private Static Tool_Kit__c etk1;
Private Static Tool_Kit__c mtk1;  
Private Static String recordNumbering;
Private Static Boolean hasNext=true;
Private Static Boolean hasPrev=true;
public static void preparedTestData()
{
    List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
		 insert updatecustomsettings;
 /*Insert account with record type Dealer*/
        Id dealerRecTypeId = [SELECT Id FROM RecordType WHERE Name = 'Dealer' limit 1].Id;
        dealerAcc = new Account (Name='Test Account', RecordTypeId=dealerRecTypeId, Dealer_Region__c='Test region');
        insert dealerAcc;
        
        acc = [select id from Account where RecordTypeId = :dealerRecTypeId and Dealer_Region__c!='' limit 1];
        
         etk1 = new Tool_Kit__c(RecordTypeId = eventRT,
                                           Dealer_Name__c = acc.id,
                                           Brand__c='MB',
                                           Plan_Start_Date__c = Date.today().addDays(-10),
                                           Plan_End_Date__c = Date.today().addDays(10),
                                           name = 'laitest01',
                                           Event_Director__c = 'laisichao',
                                           Plan_Expense__c = 1234,
                                           Location_Size__c = 123456,
                                           Event_Type__c = 'Test drive',
                                           Location__c = 'Indoor',
                                           Event_Participant__c = 'Media',
                                           Purpose__c ='OK',
                                           Background__c = 'back',
                                           Request__c = 'request'
                                          );
                                          
         mtk1 = new Tool_Kit__c(RecordTypeId = mediaRT,
                                           Dealer_Name__c = acc.id,
                                           Brand__c='AMG',
                                           Plan_Start_Date__c = Date.today().addDays(-10),
                                           Plan_End_Date__c = Date.today().addDays(10),
                                           name = 'laitest02',
                                           Purpose__c = 'OK',
                                           Background__c = 'back',
                                           Request__c = 'request',
                                           Media_Type__c = 'Outdoor',
                                           Ad_Color__c = 'Black and white',
                                           Ad_Copy__c = 'copy',
                                           Ad_Format__c = 'Picture download',
                                           Ad_Size_Height__c = 123,
                                           Ad_Size_Width__c = 456,
                                           Bleed_Size_Height__c = 789,
                                           Bleed_Size_Width__c = 798,
                                           Media_Name__c = 'laitest10',
                                           Deliver_Date__c = Date.today());                                                                                  
        insert etk1;
        insert mtk1;
       
          
}
    
    
    @isTest static void testToolKitSelectContentController(){       
        
        preparedTestData();
        Test.startTest();
        
        PageReference page = new PageReference('/apex/ToolKitSelectContent?toolkitId=' + etk1.id + '&today=2014-10-21');
        Test.setCurrentPage(page);
        ToolKitSelectContentController controller = new ToolKitSelectContentController();
        controller.contentVersion = new ContentVersion(PathOnClient='test',title='tests',Brand__c='MB',CBU_PbP__c='CBU',Class__c='A-Class',Due_Date__c=Date.newInstance(2014,10,21),Media_Type__c='Outdoor',Ad_Type__c='TEST');
        controller.query();
        controller.previous();
        controller.next();
        controller.first();
        controller.last();
        controller.choose();
        
        PageReference page2 = new PageReference('/apex/ToolKitSelectContent?toolkitId=' + mtk1.id + '&today=2014-10-21');
        Test.setCurrentPage(page2);
        ToolKitSelectContentController controller2 = new ToolKitSelectContentController();
        controller2.contentVersion = new ContentVersion(PathOnClient='testp',title='testt',Brand__c='MB',CBU_PbP__c='CBU',Class__c='A-Class',Event_Tool_Kit__c='testkit',Event_Type__c='Outreach/Roadshow',Due_Date__c=Date.newInstance(2014,10,21));
        controller2.query();
        controller2.choose();
         recordNumbering = controller2.recordNumbering;
         hasNext=controller2.hasNext;
         hasPrev=controller2.hasPrev;
        Test.stopTest();
        System.assertEquals(hasNext,controller2.hasNext);
        System.assertEquals(hasPrev,controller2.hasPrev);
        system.assertEquals(recordNumbering,controller2.recordNumbering);
    }
}