src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Gender of the person 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_Gender&quot;</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/App_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>System App Settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>App Setting</label>
</CustomObject>

src/main/metadata4au/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used only for Campaign Execution record type. To lookup Template object to define Callscript, eDM name, SMS or MMS template based on the Execution Type.</description>
        <inlineHelpText>Select Callscript, eDM name,  SMS or MMS template based on the Execution Type</inlineHelpText>
        <label>SMS/MMS/eDM Template</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>OB Call</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Callscript</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>SMS</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>SMS</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>eDM</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>eDM</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>MMS</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>MMS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Campaign Executions</relationshipLabel>
        <relationshipName>Campaign_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Lead__c.object
<CustomObject>
    <description>Lead: To link campaign and lead</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Lead</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SSI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>New camplain during surveying.</description>
        <label>SSI</label>
        <referenceTo>SSI__c</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Voice_Record_Link__c</fullName>
        <label>Voice Record Link</label>
        <type>Url</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata4au/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS/MMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Contact.object
    <fields>
        <fullName>Type__c</fullName>
        <description>The contact type for Customer(Company)</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warrantor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata4au/objects/QC__c.object
<CustomObject>
    <description>QC: Quality Control record based on a outbound call or SSI record</description>
    <fields>
        <fullName>CSR_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSR Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calibration__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Calibration</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SSI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup related SSI record</description>
        <label>SSI</label>
        <referenceTo>SSI__c</referenceTo>
        <relationshipLabel>QC</relationshipLabel>
        <relationshipName>QC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Task ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>QC</label>
    <nameField>
        <displayFormat>QC-{000000}</displayFormat>
        <label>QC No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/smart_SSI__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmatched</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>smart SSI</label>
    <nameField>
        <displayFormat>SM-SSI{000000}</displayFormat>
        <label>SSI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>smart SSI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/SSI__c.object
<CustomObject>
    <description>SSI: To record each SSI record</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmatched</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SSI</label>
    <nameField>
        <displayFormat>SSI-{000000}</displayFormat>
        <label>SSI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-excluded/objects/Survey_Result__c.object
<CustomObject>
    <description>SSI: To record SSI survey result</description>
    <fields>
        <fullName>Gender__c</fullName>
        <formula>TEXT(Account__r.Gender__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NA_Number__c</fullName>
        <description>Store Number of N/A answers of 1st Survey, if value larger than 5, than will not generate QC.</description>
        <label>NA Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaskId__c</fullName>
        <description>Related to Task.</description>
        <label>*TaskId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Successful__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by Chris Huang, 20131204.
Created for CR-000248, 131115-19</description>
        <label>Task Successful</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Result No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata4au/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>MMS</fullName>
        <active>true</active>
        <label>MMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <description>Send Message to Customer</description>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Template__c.object
<CustomObject>
    <description>Case: Use to store SMS, eDM Name for campaign, eDM for ad hoc request, MMS template name. This object is maintenace by data manager and is used by Ad Hoc and Campaign batch request</description>
    <fields>
        <fullName>Message_Detail__c</fullName>
        <label>Message Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used for eDM</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Brochure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochure+Price List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upstream &amp; Downstream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Only Downstream</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <recordTypes>
        <fullName>MMS</fullName>
        <active>true</active>
        <label>MMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata-excluded/classes/TaskHelper.cls
/*
    Type:       Utility for TaskBeforeInsertUpdate, TaskAfterUpdate
    Purpose:    1. Auto create multiple QC records when task.QC Quantity is updated with a number.
                2. Auto create QC records when task.Generate QC is changed to true.
                3. Auto update task's campaign name when this task related to an campaign
                4. Auto create a SMS task record when a task insert.
    User Story: US-QC-015, US-QC-002, US-QC-001, US-SMSS-001
    Used By:    
    ---------------------------------------------------------------
    History:
    
    1. Sinow Created on 2013-04-28
    2. 17-July-2013 Sinow Zhang (NTTData) When a task ucid is not null, update interactionIds from Avato. US-CTI-001
*/
public class TaskHelper {
    // Get Task record type ids
    private static String IBTaskRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('IB Call').getRecordTypeId();
    private static String OBTaskRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('OB Call').getRecordTypeId();
    private static String SSITaskRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('SSI Task').getRecordTypeId();
    private static String smartSSITaskRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('smart SSI Task').getRecordTypeId();
    private static String SMS_TASK_RECORDTYPEID = Schema.SObjectType.task.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
    
    // Get QC__c record type ids
    private static String IBQCRecordTypeId = Schema.SObjectType.QC__c.getRecordTypeInfosByName().get('IB QC').getRecordTypeId();
    private static String OBQCRecordTypeId = Schema.SObjectType.QC__c.getRecordTypeInfosByName().get('OB QC').getRecordTypeId();
    private static String SSIQCRecordTypeId = Schema.SObjectType.QC__c.getRecordTypeInfosByName().get('SSI QC').getRecordTypeId();
    private static List<QueueSobject> QCSVQueues = [select Id, QueueId, Queue.Name from QueueSobject where SobjectType = 'QC__c' and Queue.Name = 'SSI QC' limit 1];
    
    private static Map<String, String> srRecordTypeSubjects = new Map<String, String>{'1st Survey Result'=>'1st Survey Call', '2nd Survey Result'=>'2nd Survey Call', 'Welcome Call + 1st Survey Result'=>'Welcome Call + 1st Survey Call', 'Welcome Call Result'=>'Welcome Call'};
    
    private static void updateSobjects(List<Sobject> sos) {
        try {
            update sos;
        }
        catch (DMLException e) {
            trigger.new[0].addError(e.getDMLMessage(0));
            System.debug('DMLException Exception: ' + e);
        }
    }
    
    private static void insertSobjects(List<Sobject> sos) {
        try {
            insert sos;
        }
        catch (DMLException e) {
            trigger.new[0].addError(e.getDMLMessage(0));
            System.debug('DMLException Exception: ' + e);
        }
    }
    
    /**
     * By Justin - replaces the merge fields.
     */
    public static String replaceMergeField(Contact contact, String content){
        String nameMergeField = '{CONTACT_NAME}';
        String salutationMergeField = '{CONTACT_SALUTATION}';
        
        if(contact.Name != null){
            content = content.replace(nameMergeField, contact.Name);
        }
        
        String salutation;
        if(contact.Account.Gender__c == 'Male'){
            salutation = '先生';
        }
        else if(contact.Account.Gender__c == 'Female'){
            salutation = '女士';
        }
        else{
            salutation = '阁下';
        }
        content = content.replace(salutationMergeField, salutation);
        
        return content;
    }
    
    /**
     * By Justin - replaces the merge fields from templates before task saved.
     */
    public static void replaceMergeFields(List<Task> tasks, Map<String, Contact> contacts){
        for(Task task : tasks){
            Contact contact = contacts.get(task.WhoId);
            if(task.SMS_Content__c != null && contact != null){
                task.SMS_Content__c = replaceMergeField(contact, task.SMS_Content__c);
            }
        }
    }
    
    /**
     * By Justin - Checks the SMS Response Required of task
     */
    public static void checkResponseRequired(List<Task> tasks, Map<String, Template__c> templates){
        for(Task task : tasks){
            Template__c template = templates.get(task.SMSTemplateID__c);
            if(template != null && template.Type__c == 'Upstream & Downstream'){
                task.SMS_Response_Required__c = true;
            }
        }
    }
    
    /**
     * By Justin - Prevents the sms task from saving when the SMS Opt Out of contact is checked.
     */
    public static void preventTaskFromCreating(List<Task> tasks, Map<String, Contact> contacts){
        for(Task task : tasks){
            Contact contact = contacts.get(task.WhoId);
            if(contact != null && contact.SMSOptOut__c){
                task.addError('You can not create a sms/mms task for SMS Opt Out is checked.');
            }
        }
    }
    
    public static void GenerateQCs(List<Task> updateTasks) {        
        //new qc list for insert
        List<QC__c> newQCs = new List<QC__c>();
        QC__c qc;
        
        //connect task ids which to generate qc
        Set<Id> taskIds = New Set<Id>();
        
        for(Task t : updateTasks) {   
            qc = new QC__c();
            qc.CSR_Name__c = t.OwnerId;
            qc.Status__c = 'New';
            qc.Task_ID__c = t.Id;
            if(t.recordTypeId == IBTaskRecordTypeId) {
                qc.RecordTypeId = IBQCRecordTypeId;
                newQCs.add(qc);
            }
            if(t.recordTypeId == OBTaskRecordTypeId) {
                qc.RecordTypeId = OBQCRecordTypeId;
                newQCs.add(qc);
            }
            taskIds.add(t.Id);
        }
        if(newQCs.size() > 0) {
            insertSobjects(newQCs);
        }
        UpdateQCLink(taskIds, updateTasks);
    }
    
    public static void GenerateSSIQCs(List<Task> updateTasks) {
        //new qc list for insert
        List<QC__c> newQCs = new List<QC__c>();
        QC__c qc;
        
        //connect task ids which to generate qc
        Set<Id> taskIds = New Set<Id>();
        Set<String> SRTaskIds = New Set<String>();
        
        for(Task t : updateTasks) {
            system.debug('t++++++++++' + t.id +'t++++1111'+t);
            SRTaskIds.add(String.valueOf(t.Id).subString(0, 15));
        }

        // Added by Chris Huang, 20131209, update Task_Successful__c to 'True' when QC generated.
        List<Survey_Result__c> srs = new List<Survey_Result__c>();

        for(Survey_Result__c sr : [Select id, NA_Number__c, TaskId__c, Task_Successful__c From Survey_Result__c Where TaskId__c In :SRTaskIds]) {
            for(Task t : updateTasks) {
                if(t.Id == sr.TaskId__c && (sr.NA_Number__c == null || sr.NA_Number__c < 5)) {
                    qc = new QC__c();
                    qc.CSR_Name__c = t.OwnerId;
                    qc.Status__c = 'New';
                    qc.RecordTypeId = SSIQCRecordTypeId;
                    if(t.RecordTypeId == SSITaskRecordTypeId) {
                        qc.SSI__c = t.WhatId;
                    } else {
                        qc.smart_SSI__c = t.WhatId;
                    }
                    qc.Survey_Result__c = sr.Id;
                    sr.Task_Successful__c = true;
                    srs.add(sr);
                    if(QCSVQueues.size() > 0) {
                        qc.OwnerId = QCSVQueues[0].QueueId;
                        qc.Task_ID__c = t.Id;
                        newQCs.add(qc);
                        taskIds.add(t.Id);
                    }
                } 
            }
        }

        if(newQCs.size() > 0) {
            insertSobjects(newQCs);
        }

        if (srs.size() > 0) {
            update srs;
        }

        UpdateQCLink(taskIds, updateTasks);
    }
    
    public static void GenerateMultipleQCs(List<Task> updateTasks) {
        List<QC__c> QCForInsert = new List<QC__c>();
        QC__c qc;
        for(Task t : updateTasks) {
            for(Integer i=0; i<t.QC_Quantity__c; i++) {
                qc = new QC__c();
                qc.CSR_Name__c = t.OwnerId;
                qc.Status__c = 'New';
                qc.Calibration__c = true;
                qc.Task_ID__c = t.Id;
                if(t.recordTypeId == IBTaskRecordTypeId) {
                    qc.RecordTypeId = IBQCRecordTypeId;
                    QCForInsert.add(qc);
                }
                if(t.recordTypeId == OBTaskRecordTypeId) {
                    qc.RecordTypeId = OBQCRecordTypeId;
                    QCForInsert.add(qc);
                }
            }
        }
        if(QCForInsert.size() > 0) {
            insertSobjects(QCForInsert);
        }
    }
    
    public static void copyCampaignNameFromRelatedToObject(Set<String> caseIds, Set<String> campaignIds, Set<String> campaignLeadIds, List<Task> tasks){
        Map<String, Case> cases = new Map<String, Case>();
        Map<String, Campaign> campaigns = new Map<String, Campaign>();
        Map<String, Campaign_Lead__c> campaignLeads = new Map<String, Campaign_Lead__c>();
        
        if(caseIds.size() > 0){ 
            cases = new Map<String, Case>([select Id, Campaign__r.Name from Case where Id in :caseIds]);
        }
        if(campaignIds.size() > 0){ 
            campaigns = new Map<String, Campaign>([select Id, Name from Campaign where Id in :campaignIds]);
        }
        if(campaignLeadIds.size() > 0){  
            campaignLeads = new Map<String, Campaign_Lead__c>([select Id, Campaign__r.Name from Campaign_Lead__c where Id in :campaignLeadIds]);
        }   

        for(Task task : tasks){
            String relatedId = task.WhatId;
            if(relatedId.startsWith('500')){
                task.Campaign_Name__c = cases.get(relatedId).Campaign__r.Name;
            }
            else if(relatedId.startsWith('701')){
                task.Campaign_Name__c = campaigns.get(relatedId).Name;
            }
            else if(relatedId.startsWith('a0c')){
                task.Campaign_Name__c = campaignLeads.get(relatedId).Campaign__r.Name;
            }
        }
    }
    
    public static void copyIBCallTypeFromCase(Set<String> caseIds, List<Task> tasks) {
        Map<String, Case> cases = new Map<String, Case>([select Id, RecordType.Name from Case where Id in :caseIds]);
        
        for(Task t : tasks) {
            if(cases.containsKey(t.WhatId) && t.RecordTypeId == IBTaskRecordTypeId && t.CallType == 'Inbound') {
                t.IB_Call_Type__c = cases.get(t.WhatId).RecordType.Name;
            }
        }
    }
    
    private static void UpdateQCLink(Set<Id> taskIds, List<Task> tasks) {
        //map task id and new generate qc id
        Map<Id, Id> taskIdqcIdMap = new Map<Id, Id>();
        
        taskIds.remove(null);
        for(QC__c newQc : [select Id, Task_ID__c from QC__c where Task_ID__c in :taskIds and Task_ID__c != null and Task_ID__c != '' 
                           and (RecordTypeId = :IBQCRecordTypeId or RecordTypeId = :OBQCRecordTypeId or RecordTypeId = :SSIQCRecordTypeId) 
                           and CreatedDate > :Date.Today().addDays(-30) limit 10000]) {
            taskIdqcIdMap.put(newQc.Task_ID__c, newQc.Id);
        }
            
        for(Task t : tasks) {
            if(taskIdqcIdMap.containsKey(t.Id)) {
                t.QC_ID__c = taskIdqcIdMap.get(t.Id);
            }
        }
    }
    
    // Creat new SMS Task 
    // --- Modified by Justin on 2013-12-10
    public static void createSMSTaskAfterIBCall(List<Task> tasks) {
        Template__c ivrTemplates = [select Message_Detail__c from Template__c where RecordType.Name = 'SMS' and Name = 'IB SMS IVR'];
        Template__c smartTemplate = [select Message_Detail__c from Template__c where RecordType.Name = 'SMS' and Name = 'IB SMS IVR Smart'];
        Template__c mbTemplate = [select Message_Detail__c from Template__c where RecordType.Name = 'SMS' and Name = 'IB SMS IVR MB'];
        
        Set<String> contactIds = new Set<String>();
        for(Task t : tasks) {
            contactIds.add(t.WhoId);
        }
        Map<ID, Contact> contacts = new Map<ID, Contact>([select SMSOptOut__c from Contact where Id in :contactIds]); 
         
        List<task> smsTasks = new List<Task>();      
        for(Task t : tasks) {
            Contact contact = contacts.get(t.WhoId);
            if(contact != null && contacts.get(t.WhoId).SMSOptOut__c){
                continue;
            }
            Task smsTask = new Task();
            smsTask.Subject = 'SMS'; 
            smsTask.Status = 'Closed';    
            smsTask.Activity_Status__c = 'Sent';      
            smsTask.RecordTypeId = SMS_TASK_RECORDTYPEID;
            smsTask.Related_Task_Id__c = t.Id;
            smsTask.WhatId = t.WhatId;
            smsTask.WhoId = t.WhoId;
            smsTask.OwnerId = t.OwnerId;
            smsTask.IB_Status__c = t.IB_Status__c;
            smsTask.Phone__c = t.Phone__c;
            if(t.Called__c == '4291'){
                smsTask.SMSTemplateID__c = smartTemplate.Id;
                smsTask.SMS_Content__c = smartTemplate.Message_Detail__c;
            }
            else if(t.Called__c == '4290' || t.Called__c == '4292'){
                smsTask.SMSTemplateID__c = mbTemplate.Id;
                smsTask.SMS_Content__c = mbTemplate.Message_Detail__c;
            }
            else{
                smsTask.SMSTemplateID__c = ivrTemplates.Id;
                smsTask.SMS_Content__c = ivrTemplates.Message_Detail__c;
            }
            smsTasks.add(smsTask);
        }
        
        if(smsTasks.size() > 0) {
            insertSobjects(smsTasks);
        }
    }
    
    public static void UpdateCaseVoiceRecordlink(Map<Id, String> caseIdInteractionIds) {
        List<Case> caseForUpdate = new List<Case>();
        
        List<App_Setting__c> appSettings = [select Name, Value__c from App_Setting__c where Name = 'Voice Recording Location'];
    
        for(Case c : [select Id, Voice_Record_Link__c from Case where Id in :caseIdInteractionIds.keySet()]) {
            if((c.Voice_Record_Link__c != null || c.Voice_Record_Link__c != '') && appSettings.size() == 1) {
                c.Voice_Record_Link__c = appSettings[0].Value__c + caseIdInteractionIds.get(c.Id);
                caseForUpdate.add(c);
            }
        }
        
        if(caseForUpdate.size() > 0) {
            updateSobjects(caseForUpdate);
        }
    }
    
    //US-CTI-001
    @Future(CallOut=True)
    public static void updateInteractionIds(Map<Id, String> taskIdUCIds) {
        List<Task> tasks = new List<Task>();
        for(Task t : [select Id, CreatedDate, InteractionIds__c from Task where Id in :taskIdUCIds.keySet()]) {
            t.InteractionIds__c = AvatoHelper.getInteractionIds( taskIdUCIds.get(t.Id), t.CreatedDate);
            tasks.add(t);
        }
        
        if(tasks.size() > 0) {
            updateSobjects(tasks);
        }
    }
    // By Shuang Li BRD-AS-CAC-007---- strart
    @future(CallOut=True)
    public static void autoUpdateSSITask(Set<Id> userIds){
        Profile CACSSISV = [select Id from Profile where Name = 'CAC SSI SV'];
        Id SSITaskRTId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('SSI Task').getRecordTypeId();
        List<Task> taskSSI = [SELECT ownerId FROM Task WHERE ownerId in :userIds AND RecordTypeId= :SSITaskRTId];
        Id SMARTSSITaskRTId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('smart SSI Task').getRecordTypeId();
        List<Task> taskSmartSSI = [SELECT ownerId FROM Task WHERE ownerId in :userIds AND RecordTypeId= :SMARTSSITaskRTId];
        if(taskSSI.size() > 0){
            User ssiSvUser = [Select id From User Where ProfileId = :CACSSISV.id and IsActive = true limit 1];
            for(Task tk : taskSSI){
                tk.ownerId = ssiSvUser.id;
            }
            try {
                    update taskSSI;
                }
                catch (DMLException e) {
                    trigger.new[0].addError(e.getDMLMessage(0));
                    System.debug('DMLException Exception: ' + e);
                }
       }
       if(taskSmartSSI.size() > 0){
            User ssiSvUser = [Select id From User Where ProfileId = :CACSSISV.id and IsActive = true limit 1];
            for(Task tk : taskSmartSSI){
                tk.ownerId = ssiSvUser.id;
            }
            try {
                    update taskSmartSSI;
                }
                catch (DMLException e) {
                    trigger.new[0].addError(e.getDMLMessage(0));
                    System.debug('DMLException Exception: ' + e);
                }
       }
    }
    // By Shuang Li BRD-AS-CAC-007---- end
}