src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Retail_Email__c</fullName>
        <label>Retail Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Mobile__c</fullName>
        <label>Retail Mobile</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Work_Phone__c</fullName>
        <label>Retail Work Phone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>20</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>Retail_Email__c</fullName>
        <description>Readonly</description>
        <label>Retail Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Individual_Home_Phone__c</fullName>
        <description>Readonly</description>
        <label>Retail Individual Home Phone</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_LastName__c</fullName>
        <label>Retail LastName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Mobile__c</fullName>
        <description>Readonly</description>
        <label>Retail Mobile</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_UCID__c</fullName>
        <label>Retail UCID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Work_Phone__c</fullName>
        <description>Readonly</description>
        <label>Retail Work Phone</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>toRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links(External Link)</relationshipLabel>
        <relationshipName>Account_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Link__c.object
    <fields>
        <fullName>Retail_Salutation__c</fullName>
        <label>Retail Salutation</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata/classes/StouchPersonSearchTH.cls
public class StouchPersonSearchTH {
    public static List<Object> personSearchResultsTH(list<String> accountlinklist1){       
        List<Object> personResultsList=new List<Object>();       
         list<Account_link__c> accountlinklist=[select toRole__r.Name, toRole__r.Salutation__c, Retail_Mobile__c,Retail_Email__c,Retail_Individual_Home_Phone__c,Retail_Work_Phone__c,Retail_ID_Number__c,Retail_UCID__c,Retail_Salutation__c, RecordType.Name,Ownerid from account_link__c where id=:accountlinklist1 order by Retail_LastName__c];
        List<id> userIds=new List<Id>();
        for(Account_link__c ac:accountlinklist){
            userIds.add(ac.OwnerId);
        }
        Map<Id,User> users=new map<Id,User>([select id,federationIdentifier from user where id in :userIds]);
        system.debug('@@'+accountlinklist);
        for(Account_link__c acclink:accountlinklist){
           Map<String,Object> PersonResults=new Map<String,Object>();
           personResults.put('PersonMobilePhone',string.ISBlank(acclink.Retail_Mobile__c)? ' ' : acclink.Retail_Mobile__c.remove('-'));
           personResults.put('PersonEmail',string.ISBlank(acclink.Retail_Email__c)? ' '  : acclink.Retail_Email__c);
           personResults.put('HomePhone',string.ISBlank(acclink.Retail_Individual_Home_Phone__c)? ' ' : acclink.Retail_Individual_Home_Phone__c.remove('-'));
           personResults.put('WorkPhone',string.ISBlank(acclink.Retail_Work_Phone__c)? ' '  : acclink.Retail_Work_Phone__c.remove('-'));
           //personResults.put('Salutation',string.ISBlank(acclink.Retail_Salutation__c)? ' '  : acclink.Retail_Salutation__c);
           personResults.put('Salutation',string.ISBlank(acclink.toRole__r.Salutation__c)? ' ' : acclink.toRole__r.Salutation__c);
           personResults.put('AccountName',string.ISBlank(acclink.toRole__r.Name)? ' ' : acclink.toRole__r.Name);
           personResults.put('IDNumber',string.ISBlank(acclink.Retail_ID_Number__c)? ' '  : acclink.Retail_ID_Number__c);
           personResults.put('Personal_UCID__c',string.ISBlank(acclink.Retail_UCID__c)? ' '  : acclink.Retail_UCID__c);
           personResults.put('RecordType',string.ISBlank(acclink.RecordType.Name)? ' '  : acclink.RecordType.Name);
           personResults.put('Owner',string.ISBlank(users.get(acclink.Ownerid).federationIdentifier)?' ':users.get(acclink.Ownerid).federationIdentifier);
           personResultsList.add(personResults);    
        }
        return personResultsList;
    }
}