src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_CRM_Manager_Email__c</fullName>
        <label>Dealer CRM Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dealer_General_Manager_Email__c</fullName>
        <description>Email of General Manager from GSSN</description>
        <label>Dealer General Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dealer_MB_Sub_Region__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Subregion of MB dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_RegionSubMB&quot;</description>
        <label>Dealer MB Sub-Region</label>
        <picklist>
            <controllingField>Dealer_Region__c</controllingField>
            <picklistValues>
                <fullName>NORTH1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NORTH3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Marketing_Manager_Email__c</fullName>
        <label>Dealer Marketing Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <description>Added based on the GSSN interface mapping

Feb-18-2012: Added by Rob and Falk</description>
        <label>Dealer ND Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Sales_Manager_Email__c</fullName>
        <description>Email of Sales Manager from GSSN</description>
        <label>Dealer Sales Manager Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Dealer_Lead_System__c</fullName>
        <label>Dealer Lead System</label>
        <picklist>
            <picklistValues>
                <fullName>LMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBC POS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Assigned_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Assigned_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAC_Lead_Status__c</fullName>
        <label>CAC Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Failed For 3 Days(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visited Showroom(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(CAC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(Dealer)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan to Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gave up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Audit_Result__c</fullName>
        <label>Dealer Audit Result</label>
        <picklist>
            <controllingField>Dealer_Audit__c</controllingField>
            <picklistValues>
                <fullName>The dealer did not contact the customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealers have contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The customer does not expressly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dealer Audit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Lead_Status__c</fullName>
        <label>Dealer Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Failed For 3 Days(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visited Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(Dealer)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Successful_Contacted__c</fullName>
        <formula>IF( 
AND(
ISPICKVAL(Assigned_Dealer__r.Dealer_LMS__c,&apos;No&apos;),
Dealer_Untouched_In_72H__c = False,
OR(
ISPICKVAL(Dealer_Lead_Status__c,&apos;First Contact Customer&apos;),
ISPICKVAL(Dealer_Lead_Status__c,&apos;Test Drive&apos;),
ISPICKVAL(Dealer_Lead_Status__c,&apos;Visited Showroom(Only Non BDC)&apos;),
ISPICKVAL(Dealer_Lead_Status__c,&apos;Order Placed&apos;),
ISPICKVAL(Dealer_Lead_Status__c,&apos;Purchased(Only Non BDC)&apos;),
ISPICKVAL(Dealer_Lead_Status__c,&apos;Lost(Dealer)&apos;)
)
),
True,
IF(
AND(
ISPICKVAL(Assigned_Dealer__r.Dealer_LMS__c,&apos;Yes&apos;),
Dealer_Untouched_In_72H__c = False,
NOT(
OR(
ISPICKVAL(Dealer_Lead_Status__c,&apos;Assigned&apos;),
ISPICKVAL(Dealer_Lead_Status__c,&apos;Received&apos;),
ISPICKVAL(Dealer_Lead_Status__c,&apos;Accepted&apos;),
AND(
ISPICKVAL(Dealer_Lead_Status__c,&apos;Lost(Dealer)&apos;),
OR(
ISPICKVAL(Dealer_Lost_Reason__c,&apos;Customer can not be reached&apos;),
ISPICKVAL(Dealer_Lost_Reason__c,&apos;Customer does not respond&apos;)
)
)
)
)
),
True,
False
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Successful Contacted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Untouched_In_72H__c</fullName>
        <description>/* 
Created by: Mouse Liu 
Used by: Lead__c (US-Lead-046) 
Function: If no status is updated more than 72 hours after sales lead is assigned to dealer, &quot;Dealer Untouched(In 72H)&quot; field (formula) shows up the value &quot;Untouched&quot; automatically. 

Used in:

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <formula>IF(
ISPICKVAL(Assigned_Dealer__r.Dealer_LMS__c,&apos;No&apos;), 
AND (
    NOW() - 3 &gt; Accepted_Date_Time__c,

    OR (
        ISBLANK(Proxy_Date_Time__c),
        Proxy_Date_Time__c - 3 &gt; Accepted_Date_Time__c
    )
),
IF(
ISBLANK(Accepted_Date_Time__c), 
NOW() - 3 &gt; Received_Date_Time__c, 
Accepted_Date_Time__c - 3 &gt; Received_Date_Time__c
)
)</formula>
        <label>Dealer Untouched(In 72H)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Received_Date_Time__c</fullName>
        <label>Received Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <label>Trigger</label>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <formula>Contact.Account.Dealer_ND_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer ND Code</label>
        <type>Text</type>
    </fields>

src/main/metadata/classes/ScheduleCreateMonthlyRegionOBEmailsTest.cls
/*
    Type:       Test Class
    Purpose:    Test the ScheduleCreateMonthlyRegionOBEmails  class
    User Story:  History:

    1. venky created on 2015-03-13
*/
@isTest
public class ScheduleCreateMonthlyRegionOBEmailsTest{
    
    static testMethod void testScheduleCreateMonthlyRegionOBEmails(){

        Test.startTest();
        List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
        insert updatecustomsettings;

        //Create Account Record : 
        Account testAccount = (Account)UtilTestData.createSobject(new Account(), UtilTestData.ACCOUNT_RT_DEALER);
        
        //Create Lead Records:
        Date lastMonth = System.today().toStartOfMonth().addMonths(-1);
        Lead__c testLead = (Lead__c)UtilTestData.createSobject(new Lead__c(), UtilTestData.LEAD_RT_SALES_LEADS);
        
        testLead.Received_Date_Time__c = lastMonth;
        testLead.Assigned_Dealer__c = testAccount.Id;
        update testLead;
        
        String CRON_EXP = '0 0 0 1 1 ? 2025';  
        String jobId = System.schedule('ScheduleCreateMonthlyRegionOBEmailsTest', CRON_EXP, new ScheduleCreateMonthlyRegionOBEmails() );
        CronTrigger ct = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];
        
        system.assert(testAccount != Null);
        Test.stopTest();
          System.assertEquals(CRON_EXP, ct.CronExpression); 
        System.assertEquals(0, ct.TimesTriggered);
        
        
        //Asserting the Account
        List<Account> accs = 
            [SELECT Id, Name, Dealer_CRM_Manager_Email__c, 
                Dealer_General_Manager_Email__c, Dealer_Marketing_Manager_Email__c, 
                Dealer_Sales_Manager_Email__c, Owner.Email, 
                OwnerId, Owner.UserRole.ParentRoleId, Dealer_MB_Sub_Region__c,
                Dealer_ND_Code__c, Dealer_Lead_System__c,
                (SELECT Id, Dealer_Untouched_In_72H__c, Dealer_Audit__c,
                    Dealer_Audit_Result__c, Dealer_Lead_Status__c, CAC_Lead_Status__c,
                    Dealer_Successful_Contacted__c
                FROM Lead_Assigned_Dealer__r
                WHERE Received_Date_Time__c = LAST_MONTH
                AND RecordType.Name = 'Sales Leads') 
            FROM Account WHERE RecordType.Name = 'Dealer'
            AND Dealer_MB_Sub_Region__c != null
            ORDER BY Dealer_MB_Sub_Region__c];
        
        
        system.assertEquals(testAccount.Id, accs[0].Id);
        
        //Assert the Account seperated by the Sub-Region.
        List<Account> accountList = new List<Account>();
        accountList.add(testAccount);
        Map<String, List<Account>> separatedAccountsBySubRegion = 
            UtilLeadEmailEscalation.getSeparateAccountsBySubRegion(accountList);
      
        Boolean contains = separatedAccountsBySubRegion.containsKey('North1');
        
        system.assertEquals(contains, True);
        
        List<Account> subRegionAccounts = separatedAccountsBySubRegion.get('North1');
        
        system.assertEquals(subRegionAccounts[0].Id, testAccount.Id);   
        system.debug('Final Assertions Contains: ' +contains + ' SubRegion Account Id ' +subRegionAccounts[0].Id + ' Actual Account Id : ' +testAccount.Id);
    }
}