src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Required by business during the workshop, which exists in current avarto system ( 区号).</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_SR_Code__c</fullName>
        <label>Dealer DMS SR Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Gender of the person 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_Gender&quot;</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Email2__c</fullName>
        <label>Email2</label>
        <type>Email</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Email3__c</fullName>
        <label>Other E-Mail</label>
        <type>Email</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Home_Phone_2__c</fullName>
        <label>Home Phone 2</label>
        <type>Phone</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Mobile2__c</fullName>
        <label>Mobile 2</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Primary_Email__c</fullName>
        <label>Sales Mail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>E-mail1</fullName>
                </value>
                <value>
                    <fullName>E-mail2</fullName>
                </value>
                <value>
                    <fullName>E-mail3</fullName>
                </value>
                <value>
                    <fullName>E-Mail(Private)</fullName>
                </value>
                <value>
                    <fullName>E-Mail(Business)</fullName>
                </value>
                <value>
                    <fullName>Mobile E-Mail(Private)</fullName>
                </value>
                <value>
                    <fullName>Mobile E-Mail(Business)</fullName>
                </value>
                <value>
                    <fullName>Other E-Mail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Primary_Fax__c</fullName>
        <label>Sales FAX</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FAX1</fullName>
                </value>
                <value>
                    <fullName>FAX2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Sales TEL</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Work Phone</fullName>
                </value>
                <value>
                    <fullName>Work Mobile</fullName>
                </value>
                <value>
                    <fullName>Other1</fullName>
                </value>
                <value>
                    <fullName>Other2</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/PhoneAreaCode__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Area_Code__c</fullName>
        <label>Mobile Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Area_Code__c</fullName>
        <label>Phone Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Phone Area Codes</label>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/contactTableControllerTest.cls
/*
Type:    Test class
Purpose: Test Class for ContactTableController
---------------------------------------------------------------   
1. Created on 18-Jan-2017  
2: Updated by manjunath 11-05-2017
*/
@istest
public class contactTableControllerTest {
    public static Account objAccount; 
    public static User usr;
    public static Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    private static Profile profile;
    private static UserRole role;
    public static string teststring='test';
    static void createTestData() {
        
        objAccount = new Account();
        objAccount.RecordTypeId = personAccRecordTypeId;
        objAccount.Dealer_DMS_SR_Code__c='test code 2';
        objAccount.Individual_Home_Phone__c = '000-0000-9642';
        objAccount.Home_Phone_2__c = '000-0000-9642';
        objAccount.Work_Phone__c = '000-0000-9642';
        objAccount.Status__c='NoCustomer';
        objAccount.Email__c = 'testemail@test.com';
        objAccount.Email2__c = 'testemail2@test.com';
        objAccount.Email3__c = 'testemail3@test.com';
        objAccount.City__c='Beijing';
        objAccount.Gender__c = 'Male';
        objAccount.Phone = '000-0000-9642';
        objAccount.Area_code__c = '0101';
        objAccount.MD__c = 'KR';
        objAccount.LastName = 'galaxy1';
        objAccount.FirstName = 'First Name';
        objAccount.Salutation = 'Unknown';
        objAccount.Province__c = 'Shanghai';
        objAccount.ZipCode__c= '1002347';
        objAccount.MBK_Data_Source__c='Email';
        objAccount.Mobile__c = '000-0000-9642';
        objAccount.Mobile2__c = '000-0000-9642';
        objAccount.Primary_Email__c = 'Email1';
        objAccount.Primary_Fax__c = 'FAX2';
        objAccount.Primary_Phone__c ='Other2';
        insert objAccount; 
        
    }      
    
    public static testMethod void PhoneNumberFormatTest() {
        
        createTestData();
        ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
        ContactTableController ctc = new ContactTableController(sc);
        test.startTest();
        ctc.PhoneNumberFormat();
        test.stoptest();
        system.assertEquals(objAccount.Individual_Home_Phone__c,'000-0000-9642');
        
    }
    public static testMethod void UpdateAccountTest() {
        createTestData();
        ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
        ContactTableController ctc = new ContactTableController(sc);
        test.startTest();
        ctc.PhoneNumberFormat();
        ctc.UpdateAccount();
        test.stoptest();
        system.assertEquals(objAccount.Individual_Home_Phone__c,'000-0000-9642');
    }
    public static testMethod void EditAccountTest() {
        createTestData();
        ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
        ContactTableController ctc = new ContactTableController(sc);
        test.startTest();
        ctc.EditAccount();
        test.stoptest();
        system.assertEquals(objAccount.MD__c,'KR');
    }
    public static testMethod void AreacodeItemsTest() {
        createTestData();
        ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
        ContactTableController ctc = new ContactTableController(sc);
        test.startTest();
        ctc.getAreacodeItems();
        test.stoptest();
        system.assertEquals(objAccount.Area_code__c,'0101');
    }
    public static testMethod void MobileAreacodeItemsTest() {
        createTestData();
        ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
        ContactTableController ctc = new ContactTableController(sc);
        test.startTest();
        ctc.getMobileAreacodeItems();
        test.stoptest();
        system.assertEquals(objAccount.Mobile__c,'000-0000-9642');
    }
    public static testMethod void CancelUpdateTest() {
        createTestData();
        ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
        ContactTableController ctc = new ContactTableController(sc);
        test.startTest();
        ctc.CancelUpdate();
        test.stoptest();
        system.assertEquals(objAccount.Individual_Home_Phone__c,'000-0000-9642');
    }
    // Manjunath  - This is used for TH
    public static testMethod void EditAccountTHTest() {
        Profile prof = [Select Id from Profile where Name = 'System Administrator'];
        User us = TestClassHelper.createUser('User1TH',prof,'TH');
        insert US;
        system.runAs(US){
            //createTestData();
            objAccount = TestClassHelper.CreateAccount(US.Market__c,'FirstName','LastName');
            insert objAccount;
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            ContactTableController ctc = new ContactTableController(sc);
            test.startTest();
            ctc.EditAccount();
            test.stoptest();
            system.assertEquals(objAccount.FirstName,'FirstName');
        }
    }
    public static testMethod void UpdateAccountTHTest() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'TH');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            insert objAccount;
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            ContactTableController ctc = new ContactTableController(sc);
            test.startTest();
            //ctc.UpdateAccount(); // before it will be blank then edit will parse the code
            ctc.EditAccount();
			ctc.PhoneNumberFormatTH();
            ctc.UpdateAccount();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'TH');
        }
    }
    // Home code is not null;
    /*public static testMethod void UpdateAccountTHPhoneTest() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'TH');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            insert objAccount;
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            ContactTableController ctc = new ContactTableController(sc);
            test.startTest();
            ctc.PhoneNumberFormatTH();
            ctc.UpdateAccount();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'TH');
        }
    }*/
	public static testMethod void UpdateAccountTHPhoneTest2() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'TH');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '';
            objAccount.Fax = '12121222';
            objAccount.Mobile__c = '';
            objAccount.Work_Phone__c = '';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '';
            ctc.wkCountryCode = '';
            ctc.mbCountryCode = '';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.PhoneNumberFormatTH();
            ctc.UpdateAccountTH();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'TH');
        }
    }
    
    public static testMethod void UpdateAccountTHPhoneTest3() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'TH');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '';
            objAccount.Fax = '';
            objAccount.Mobile__c = '';
            objAccount.Work_Phone__c = '';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '';
            ctc.wkCountryCode = '';
            ctc.mbCountryCode = '';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.PhoneNumberFormatTH();
            ctc.UpdateAccountTH();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'TH');
        }
    }
    public static testMethod void AreacodeItemsKRTest() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
         usr = TestClassHelper.createUser('User1KRAcode',profile,'KR');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            createTestData();
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            ContactTableController ctc = new ContactTableController(sc);
            test.startTest();
            List<SelectOption> selectOption =ctc.getAreacodeItems();
            ctc.getMobileAreacodeItems();
            test.stoptest();
            system.assert(selectOption.size()>0);
             system.assertEquals(objAccount.MD__c,'KR');
        }
    }
    
    public static testMethod void UpdateAccountANZTest1() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'AU');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '';
            objAccount.Fax = '';
            objAccount.Mobile__c = '';
            objAccount.Work_Phone__c = '';
            objAccount.MD__C ='AU';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '';
            ctc.wkCountryCode = '';
            ctc.mbCountryCode = '';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.EditAccount();
            ctc.UpdateAccount();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'AU');
        }
    }
	
   public static testMethod void UpdateAccountANZTest2() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'AU');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '+61234567894';
            objAccount.Fax = '';
            objAccount.Mobile__c = '+61485745689';
            objAccount.Work_Phone__c = '+61236547896';
            objAccount.MD__C ='AU';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '+61';
            ctc.wkCountryCode = '+61';
            ctc.mbCountryCode = '+61';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.PhoneNumberFormatANZ();
            ctc.UpdateAccountANZ();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'AU');
        }
    }    
 public static testMethod void UpdateAccountANZTest3() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'NZ');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '+642409894';
            objAccount.Fax = '';
            objAccount.Mobile__c = '+6428574569';
            objAccount.Work_Phone__c = '+6423647896';
            objAccount.MD__C ='NZ';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '+64';
            ctc.wkCountryCode = '+64';
            ctc.mbCountryCode = '+64';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.PhoneNumberFormatANZ();
            ctc.UpdateAccountANZ();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'NZ');
            
        }
    } 
 public static testMethod void UpdateAccountANZTest4() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'NZ');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '+6423647896';
            objAccount.Fax = '';
            objAccount.Mobile__c = '+6448574569';
            objAccount.Work_Phone__c = '+642409894';
            objAccount.MD__C ='NZ';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '+64';
            ctc.wkCountryCode = '+64';
            ctc.mbCountryCode = '+64';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.checkcountrycodeANZ();
            ctc.PhoneNumberFormatANZ();
            ctc.UpdateAccountANZ();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'NZ');
        }
    }   
 public static testMethod void UpdateAccountANZTest5() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'NZ');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '+6425472894';
            objAccount.Fax = '';
            objAccount.Mobile__c = '+6448574569';
            objAccount.Work_Phone__c = '+6423647896';
            objAccount.MD__C ='NZ';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '+64';
            ctc.wkCountryCode = '+64';
            ctc.mbCountryCode = '+64';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.PhoneNumberFormatANZ();
            ctc.UpdateAccountANZ();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'NZ');
        }
    }   

  public static testMethod void UpdateAccountANZTest7() {
        profile = [Select Id from Profile where Name = 'System Administrator'];
        usr = TestClassHelper.createUser('User2TH',profile,'AU');
        insert usr;
        system.runAs(usr){
            objAccount = TestClassHelper.CreateAccount(usr.Market__c,'FirstName','LastName');
            objAccount.Individual_Home_Phone__c = '';
            objAccount.Fax = '';
            objAccount.Secondary_Email__c = 'test@test.com';
            objAccount.Work_Phone__c = '';
            objAccount.MD__C ='AU';
            insert objAccount;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(objAccount);
            
            ContactTableController ctc = new ContactTableController(sc);
            
            ctc.hmCountryCode = '';
            ctc.wkCountryCode = '';
            ctc.mbCountryCode = '';
            ctc.faxCountryCode = '';
            test.startTest();
            ctc.UpdateAccountANZ();
            test.stoptest();
            system.assertEquals(objAccount.MD__c,'AU');
        }
    }    
   //SB2017
    /*
      Name:Sushma Bharti
      Description:Added to setup test data for MY
      Modified Date: 2017-09-13
  */
  
    @testSetup
    static void setupTestData(){
    List<String> PhoneAreaCodes=new List<String>();
    PhoneAreaCodes.add('Name');
    PhoneAreaCodes.add('Country_Code__c');
    PhoneAreaCodes.add('Mobile_Area_Code__c');
    PhoneAreaCodes.add('Phone_Area_Code__c');
    List<PhoneAreaCode__c> PhoneAreaCodesList=DataFactoryServices.createRecords('PhoneAreaCode__c',PhoneAreaCodes,'',2);
    PhoneAreaCodesList[0].name='Area1';
    PhoneAreaCodesList[0].Country_Code__c='+60';
    PhoneAreaCodesList[0].Mobile_Area_Code__c='32';
    PhoneAreaCodesList[0].Phone_Area_Code__c='89';
    PhoneAreaCodesList[1].name='Area2';
    PhoneAreaCodesList[1].Country_Code__c='+65';
    PhoneAreaCodesList[1].Mobile_Area_Code__c='12';
    PhoneAreaCodesList[1].Phone_Area_Code__c='80';
    insert PhoneAreaCodesList;
    List<String> AccountFields=new List<String>();
    AccountFields.add('Lastname');
    AccountFields.add('Individual_Home_Phone__c');
    AccountFields.add('Work_Phone__c');
    AccountFields.add('fax');
    AccountFields.add('Mobile__c');
    AccountFields.add('MD__c');
    List<Account> AccountFieldsList=DataFactoryServices.createRecords('Account',AccountFields,'',3);
    AccountFieldsList[0].Lastname='Lastname1';
    AccountFieldsList[0].Individual_Home_Phone__c='+6003123654789';
    AccountFieldsList[0].Work_Phone__c='+60825634789541';
    AccountFieldsList[0].fax='+60827896541';
    AccountFieldsList[0].Mobile__c='+609856321478';
    AccountFieldsList[0].MD__c='MY';
    AccountFieldsList[1].Lastname='Lastname2';
    AccountFieldsList[1].Individual_Home_Phone__c='';
    AccountFieldsList[1].Work_Phone__c='';
    AccountFieldsList[1].fax='';
    AccountFieldsList[1].Mobile__c='';
    AccountFieldsList[1].MD__c='MY';
    AccountFieldsList[2].Lastname='Lastname3';
    AccountFieldsList[2].Individual_Home_Phone__c='+601236547895';
    AccountFieldsList[2].Work_Phone__c='+601234857612';
    AccountFieldsList[2].fax='+601024563075';
    AccountFieldsList[2].Mobile__c='+601798456321';
    AccountFieldsList[2].MD__c='MY';
    insert AccountFieldsList;
   } 
   
     //SB2017
    /*
      Name:Sushma Bharti
      Description:Added to update the code coverage of the method for MY
      Modified Date: 2017-09-13
  */
  static testmethod void testContactTableController()
    {                  
		 profile = [Select Id from Profile where Name = 'System Administrator'];
         usr = TestClassHelper.createUser('User1MYAcode1',profile,'MY');
        insert usr;
        system.runAs(usr){				
        List<Account> AccountObj  =  [SELECT Lastname,Individual_Home_Phone__c,Work_Phone__c,fax,Mobile__c,MD__c from Account];
        ApexPages.StandardController objSc1 = new ApexPages.StandardController(AccountObj[0]);
        ContactTableController c1=new ContactTableController(objSc1);
        c1.PhoneNumberFormatMY();
        c1.EditAccount();
        c1.UpdateAccountMY();
        ApexPages.StandardController objSc2 = new ApexPages.StandardController(AccountObj[1]);
        ContactTableController c2=new ContactTableController(objSc2);
        c2.PhoneNumberFormatMY();
        c2.EditAccount();
        c2.UpdateAccountMY();
        ApexPages.StandardController objSc3 = new ApexPages.StandardController(AccountObj[2]);
        ContactTableController c3=new ContactTableController(objSc3);
        c3.PhoneNumberFormatMY();
        c3.EditAccount();
        c3.UpdateAccountMY();
		}
     }  
    
}