src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: GS Code of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_GCcode &quot;</description>
        <label>Dealer GC Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <description>Added based on the GSSN interface mapping

Feb-18-2012: Added by Rob and Falk</description>
        <label>Dealer ND Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Outlet</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA')))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fromRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links (Contact to Contact)</relationshipLabel>
        <relationshipName>Account_Links1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>toRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links(External Link)</relationshipLabel>
        <relationshipName>Account_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/accountLinkShareBatch.cls
global class accountLinkShareBatch implements Database.Batchable<sobject>,database.stateful, Schedulable
{
    public static List<string> dealerGCCodeList = new list<string>();
    public static List<string> dealerNDCodeList = new List<string>();
    public static Map<string,string> groupGcCodeMap = new Map<string,string>();
    public static Map<string,string> groupNdCodeMap = new Map<string,string>();
    public static map<string,list<String>> dealeraccntMap = new Map<string,list<String>>();
    public static List<Account_Link__Share> updateaclnkShareList = new List<Account_Link__Share>();
    public static List<AccountShare> updateAccShareList = new List<AccountShare>();
    public static map<string,id> assignedgroupMap = new map<string,id>();
  global database.QueryLocator start(database.BatchableContext bc)
    { 
        string query = 'Select id,fromRole__c,toRole__c,fromRole__r.Dealer_GC_Code__c,fromRole__r.Dealer_ND_Code__c,fromRole__r.Dealer_Type__c from Account_Link__c where fromRole__r.Dealer_GC_Code__c in '+ '(\'GC0037971\',\'GC0011433\',\'GC0037972\',\'GC0011422\',\'GC0011432\',\'GC0011423\',\'GC0037973\',\'GC0037970\',\'GC0011430\',\'GC0037969\',\'GC0011434\') '+ 'and fromRole__c != null and toRole__c != null and MD__C =' +'\'KR\''+ 'and (Recordtype.Name =' +'\'Retail Person\'' + 'or Recordtype.Name = ' +'\'Retail Company\')';
        return database.getQueryLocator(query);
    }
    global void execute(database.BatchableContext bc,List<Account_Link__c> scope)
    {
    
        dealerGCCodeList.add('GC0037971');
        dealerGCCodeList.add('GC0037972');
        dealerGCCodeList.add('GC0011433');
        dealerGCCodeList.add('GC0011434');
        dealerGCCodeList.add('GC0011430');
        dealerGCCodeList.add('GC0011422');
        dealerGCCodeList.add('GC0037969');
        dealerGCCodeList.add('GC0011432');
        dealerGCCodeList.add('GC0011423');
        dealerGCCodeList.add('GC0037973');
        dealerGCCodeList.add('GC0037970');
        Set<string> ndCodeList = New Set<String>();
        
        List<Account> accntList = [select Id, Dealer_ND_Code__c, Dealer_GC_Code__c, Dealer_Type__c from Account where Recordtype.Name = 'Dealer' and Dealer_GC_Code__c =:dealerGCCodeList and MD__c = 'KR'];
        for(Account acc : accntList){
        
           ndCodeList.add(acc.Dealer_ND_Code__c);
           if(!dealeraccntMap.containsKey(acc.Dealer_GC_Code__c))
            {
                dealeraccntMap.put(acc.Dealer_GC_Code__c, new List<string>());
            }
            dealeraccntMap.get(acc.Dealer_GC_Code__c).add(acc.Dealer_ND_Code__c);
           
        }
        
        system.debug('+++++++++++++'+ndCodeList);
        List<group> grpList = [select Id, Name, Type from Group where Name in :ndCodeList];
        if(!accntList.isEmpty() && accntList != null && !grpList.isEmpty() && grpList != null)
        {
            for(group gr : grpList)
            {
               
               
               assignedgroupMap.put(gr.Name, gr.id);
               
               
               
              
            }
        }
        for(Account_Link__c acclnk : Scope)
        {
            
            if(dealeraccntMap.get(acclnk.fromRole__r.Dealer_GC_Code__c) != null){
            for(integer i=0 ; i < dealeraccntMap.get(acclnk.fromRole__r.Dealer_GC_Code__c).size();i++)
                    
            {
                if(assignedgroupMap.get(dealeraccntMap.get(acclnk.fromRole__r.Dealer_GC_Code__c)[i]) != null)
                        {
           
            
            AccountShare achsare = new Accountshare();
            achsare.Accountid=acclnk.toRole__c;
            
            achsare.UserOrGroupId = assignedgroupMap.get(dealeraccntMap.get(acclnk.fromRole__r.Dealer_GC_Code__c)[i]);
            achsare.AccountAccessLevel='edit';
            achsare.OpportunityAccessLevel ='none';
            updateAccShareList.add(achsare);  
            }
            } 
        }  
        }      
        
        if(!updateAccShareList.isEmpty() && updateAccShareList != null)
        {
            insert updateAccShareList;
        }        
    }
    global void finish(database.BatchableContext bc)
    {
        
    }
    global void execute(SchedulableContext ctx) {
    Database.ExecuteBatch(new accountLinkShareBatch(),50);
    }
}