src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Flag for this dealer
Attribute in Data Dictionary object Dealer is &quot;Dealer_ActiveFlag&quot;</description>
        <label>Dealer Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Region__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Region of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_Region&quot;</description>
        <label>Dealer Region</label>
        <picklist>
            <picklistValues>
                <fullName>NORTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOUTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Sales_Type__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: The sales type of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_SalesType&quot;</description>
        <label>Dealer Sales Type</label>
        <picklist>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Star-Elite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Dealer_Service_Codes__c</fullName>
        <description>Dealer Services - based on the GSSN interface for the Dealer ActivityDefCodes

Feb-18-2012: Added by Rob and Falk
Attribute in Data Dictionary object Dealer is &quot;Dealer_Service&quot;</description>
        <label>Dealer Service Codes</label>
        <picklist>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paint Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSC Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aftersales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
		IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
		IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',IF(ISPICKVAL($User.Market__c, 'KR'), 'KR',IF(ISPICKVAL($User.Market__c, 'TH'), 'TH','NA')))))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Lead__c.object
<CustomObject>
    <description>Lead: To link campaign and lead</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account, Person Account Manual Merge, Person Account Retail, Person Account Soft Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <label>Lead</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH','NA'))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Campaign Lead</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Aftersales_Vehicle_Brand__c</fullName>
        <formula>TEXT(VehicleRel_No__r.Vehicle_ID__r.Brand__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aftersales Vehicle Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Combine_Interested_Vehicle_Brand__c</fullName>
        <formula>IF(
OR(
ISPICKVAL(Interested_Vehicle_Brand__c,&apos;MB&apos;),
ISPICKVAL(Interested_Vehicle_Brand__c,&apos;AMG&apos;)
), &apos;MB&apos;, &apos;smart&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Combine Interested Vehicle Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_Vehicle_Brand__c</fullName>
        <label>Interested Vehicle Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Participating_Dealer__c.object
<CustomObject>
    <description>Campaign: Dealers that participate the campaign</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Participating Dealers</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participating Campaigns</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Participating Dealer</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participating_Dealer__c.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;,IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/SelectAssignedDealerController.cls
/*
    Type:       Controller for SelectAssignedDealer
    Purpose:    Select assigned dealer for lead__c
    User Story: US-Lead-003
    Used By:    SelectAssignedDealer.page
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-04-12
*/
public with sharing class SelectAssignedDealerController {
    
    private Map<Id, Campaign> campaignMap = new Map<Id, Campaign>(); // Related Campaigns under the Campaign Lead of this lead
    private final Integer QUERY_LIMIT = 200; // Query return limit and Dealer's Record Type Name
    private final String ACCOUNT_RT_DEALER = 'Dealer';
    
    public Lead__c lead                          {get; set;}
    public String name                           {get; set;}
    public Account dealer                        {get; set;}
    public Boolean hasQueryResult                {get; set;}
    public List<Account> dealers                 {get; set;}
    public Id choosenDealerId                    {get; set;}
    public Id choosenCampaignId                  {get; set;}
    public Boolean hasMessage                    {get; set;}
    public Id dealerRecordTypeId                 {get; set;}
    // this was added to check the market discriminator based on the logged in user
    public user usr;
    
    public SelectAssignedDealerController(ApexPages.StandardController controller) {
        usr = [select id,Market__c from user where id =:userInfo.getUserid()];
        lead = [SELECT RecordType.Name, Name, Contact__r.Province__c, Contact__r.City__c, 
                Interested_Vehicle_Brand__c, Combine_Interested_Vehicle_Brand__c, Aftersales_Vehicle_Brand__c
                FROM Lead__c WHERE Id = :controller.getId()];
        
        // Initiate dealer
        dealerRecordTypeId = UtilRecordType.getRecordTypeIdByName('Account', 'Dealer');
        dealer = new Account(RecordTypeId = dealerRecordTypeId, Province__c = lead.Contact__r.Province__c, City__c = lead.Contact__r.City__c);
        
        // Get all related Campaign Leads
        List<Campaign_Lead__c> camLeads = [ SELECT Id, Campaign__r.Name, 
                                                Campaign__c,
                                                Campaign__r.Parent.ParentId
                                            FROM Campaign_Lead__c
                                            WHERE Lead__c = :lead.Id
                                            ORDER BY LastModifiedDate DESC];
        
        // Populate campaignMap
        for (Campaign_Lead__c camLead : camLeads) {
            campaignMap.put(camLead.Campaign__c, camLead.Campaign__r);
        }
        
        // Intiate choosenCampaignId with lastest one
        choosenCampaignId = camLeads.size() > 0 ? 
            camLeads[0].Campaign__c : null;

        query();
    }
    
    /**
     * 2014-3-5 added by Justin Yu -- List the cities which contains at least one dealer
     */
    public List<SelectOption> getCityOptions(){
        List<SelectOption> options = new List<SelectOption>();
        Set<String> cities = new Set<String>();
        for(Account dealer : [select City__c from Account 
            where Dealer_Active__c = true 
            and RecordTypeId =: dealerRecordTypeId and Province__c = :dealer.Province__c]){
            cities.add(dealer.City__c);
        }
        cities.remove(null);
        options.add(new SelectOption('', '--None--'));
        for(String city : cities){
            options.add(new SelectOption(city, city));
        }
        return options;
    }
    
    /**
     * 2014-3-5 added by Justin Yu
     */
    public PageReference refreshPage(){
        return null;
    }
    
    public List<SelectOption> campaignOptions {
        get {
            List<SelectOption> campaignOptions = new List<SelectOption>();
            campaignOptions.add(new SelectOption('', '--None--'));
            for (Campaign cam : campaignMap.values()) {
                campaignOptions.add(new SelectOption(cam.Id, cam.Name));
            }

            return campaignOptions;
        }
    }
    
    public void query() {
        // We must inculde the IsPsersonAccount in the SOQL, otherwise, 
        // we will get exception in debug log but not display on the page
        String querySOQL = 'SELECT ' + this.getColumns() + 
            'IsPersonAccount, Id FROM Account WHERE Dealer_Active__c = true and ' + 
            'RecordType.Name = :ACCOUNT_RT_DEALER AND ';
        // If Lead Record Type is Sales Leads, this filter is must,
        // if not, no need.
      
        if (lead.RecordType.Name == 'Sales Leads') {
            querySOQL += 'Dealer_Service_Codes__c includes (\'Sales\') AND ';
            /********************************
            if (lead.Interested_Vehicle_Brand__c == 'MB' || lead.Interested_Vehicle_Brand__c == 'AMG') {
                querySOQL += 'Dealer_Sales_Type__c includes (\'MB\') AND ';   
            }
            else if (lead.Interested_Vehicle_Brand__c == 'smart') {
                querySOQL += 'Dealer_Sales_Type__c includes (\'smart\') AND ';   
            }
            ********************************/
        }
        else if (lead.RecordType.Name == 'Aftersales Leads') {
            querySOQL += 'Dealer_Service_Codes__c includes (\'Service\') AND ';
            /********************************
            if (lead.Aftersales_Vehicle_Brand__c != 'smart') {
                querySOQL += 'Dealer_Sales_Type__c excludes (\'smart\') AND ';   
            }
            else if (lead.Aftersales_Vehicle_Brand__c == 'smart') {
                querySOQL += 'Dealer_Sales_Type__c includes (\'smart\') AND ';   
            }
            *******************************/
        }
      
        // Filter Part
        if (choosenCampaignId != null) {
            // Get the Central MKT Campaign Id by choosenCampaignId
            Id centralMKTCampaignId = 
                campaignMap.get(choosenCampaignId).Parent.ParentId;

            if (centralMKTCampaignId != null) {
                // This Variable is used for populating all dealers 
                // in related Participating Dealer of Central MKT Campaign
                Set<Id> participatingDealerIds = new Set<Id>();

                // Get all Participate Dealers in Central MKT Campaign
                List<Participating_Dealer__c> parDealers = 
                    [SELECT Id, Dealer__c FROM Participating_Dealer__c
                     WHERE Campaign__c = :centralMKTCampaignId]; 

                // Populate participatingDealerIds
                for (Participating_Dealer__c parDealer : parDealers) {
                    if (parDealer.Dealer__c != null) {
                        participatingDealerIds.add(parDealer.Dealer__c);
                    }
                }
                if (participatingDealerIds.size() > 0) {
                    querySOQL += 'Id IN : participatingDealerIds AND ';
                }
            }
        }
        if (dealer.Dealer_Sales_Type__c != null && dealer.Dealer_Sales_Type__c != '') {
            String Dealer_Sales_Type = dealer.Dealer_Sales_Type__c;
            querySOQL += 'Dealer_Sales_Type__c = :Dealer_Sales_Type AND ';
        }
        if (dealer.Dealer_Service_Codes__c != null && dealer.Dealer_Service_Codes__c != '') {
            String Dealer_Service_Codes = dealer.Dealer_Service_Codes__c;
            querySOQL += 'Dealer_Service_Codes__c = :Dealer_Service_Codes AND ';
        }
        
        if (name != null && name != '') {
            querySOQL += 'Name Like \'%' + name + '%\' AND ';
        }
        system.debug('dealers >>>1 :'+dealer.Dealer_Service_Codes__c);
        system.debug('dealers >>>2 :'+dealer.Dealer_Sales_Type__c);
        if (dealer.Province__c != null && dealer.Province__c != '') {
            String province = dealer.Province__c;
            querySOQL += 'Province__c = :province AND ';
        }
        //for CR-000259 start
        
        if (!String.isblank(dealer.City__c)) {
            String city = dealer.City__c;
            querySOQL += 'City__c = :city AND ';
        }
        // Below condition was added to imprint the logged in user Market discriminator to find dealer(accounts) in his specific market
        if(usr.Market__c != null && usr.Market__c != ''){
            system.debug('usr.Market__c '+ usr.Market__c);
            
            querySOQL += 'MD__c='+'\''+usr.Market__c+'\'';
        }
        system.debug('querySOQL1 '+ querySOQL);
        //for CR-000259 end
        // Query Dealers               
        querySOQL = querySOQL.subString(0, querySOQL.length()) + 
            ' ORDER BY Dealer_Region__c DESC NULLS LAST LIMIT ' + this.QUERY_LIMIT;
        system.debug('querySOQL '+ querySOQL);
        dealers = Database.query(querySOQL);
        system.debug('dealers >>>3 :'+dealers);
        // If no query result, system alert no search result.
        hasQueryResult = (dealers.size() > 0);
        if (!hasQueryResult) {
            this.addInfoMessage(Label.CP_No_Search_Result);
        }
    }
    
    public PageReference choose() {
        // Populate assigned dealer
        hasMessage = false;
        lead.Assigned_Dealer__c = choosenDealerId;
        try {
            update lead;
        }
        catch (DMLException e) {
            this.addErrorMessage(e.getDMLMessage(0));
            hasMessage = true;
            System.debug('Debug Output ======> {' + hasMessage + '}');
        }

        return null;
    }


    // Get the SOQL Expr of DealerSearchColumns FieldSet fields
    private String getColumns() {
        String columns = '';
        for (Schema.FieldSetMember member : this.getFieldSetMembers()) {
            columns += member.getFieldPath() + ', ';
        }
        
        return columns;
    }
    
    // Get the FieldSet Members of Account FieldSet(AssignedDealerColumns)
    private List<Schema.FieldSetMember> getFieldSetMembers() {
        return SObjectType.Account.FieldSets.AssignedDealerColumns.getFields();
    }
    
    //TODO: not used any where
    /*private void addNoParticipatingDealersMessage() {
        dealers = new List<Account>();
        // If no query result, system alert no search result.
        hasQueryResult = (dealers.size() > 0);
        if (!hasQueryResult) {
            this.addInfoMessage('No Participating Dealers');
        }
    }*/

    private void addInfoMessage(String msg) {
        ApexPages.addMessage(new ApexPages.Message(
            ApexPages.severity.INFO, msg));
    }

    private void addErrorMessage(String msg) {
        ApexPages.addMessage(new ApexPages.Message(
            ApexPages.severity.ERROR, msg));
    }
}