src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DMS_Address__c</fullName>
        <description>DMS address of the customer delivered by GSSN</description>
        <label>DMS Address</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Successful_Call_Office_Phone__c</fullName>
        <description>To record the last successful call time for office phone of the customer</description>
        <label>Last Successful Call (Office Phone)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Master_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Master record of a suspected duplicates group to be flaged by EP</description>
        <label>Master Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>DUPNumber__c</fullName>
        <label>DUP Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>SMS_Last_Modified_Date__c</fullName>
        <label>SMS/MMS/IM Last Modified Date</label>
        <type>DateTime</type>
    </fields>

src/main/metadata4au/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign.object
    <fields>
        <fullName>Campaign_Executer__c</fullName>
        <description>Defines the owner of the campaign record</description>
        <label>Campaign Executer</label>
        <picklist>
            <picklistValues>
                <fullName>WholeSale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/Campaign.object
    <fields>
        <fullName>Campaign_Execution_Channels__c</fullName>
        <description>This field is used to define whether the campaign will be executed via which channel, whether it will be an outbound email, SMS, outbound call etc</description>
        <label>Campaign Execution Channels</label>
        <picklist>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM Magazine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>

src/main/metadata/objects/Campaign.object
    <fields>
        <fullName>Campaign_Sub_Type__c</fullName>
        <label>Campaign Sub Type</label>
        <picklist>
            <picklistValues>
                <fullName>Crosspoint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales and After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance - &gt;  Prematurity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales -&gt; Crosspoint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/Campaign.object
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <description>This field can be used to track the progress of the execution campaign life cycle</description>
        <label>Campaign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/Campaign.object
    <fields>
        <fullName>Response_Date__c</fullName>
        <description>This field is used to capture the response date</description>
        <label>Response Date</label>
        <type>Date</type>
    </fields>

src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to set the status of the campaign member</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Campaign_Execution_Channels__c</fullName>
        <label>Campaign Execution Channels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>DM</fullName>
                </value>
                <value>
                    <fullName>OB</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>DM Magazine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Campaign_Sub_Type__c</fullName>
        <label>Campaign Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>After Sales</fullName>
                </value>
                <value>
                    <fullName>Sales and After Sales</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Sales -&gt; Crosspoint</fullName>
                </value>
                <value>
                    <fullName>Finance - &gt; Prematurity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <label>Campaign Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Segmentation</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Response collection</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Close_Date__c</fullName>
        <description>This field is used to capture the end date of the campaign</description>
        <label>Close Date</label>
        <type>Date</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Response_Date__c</fullName>
        <description>This field is used to capture the response date</description>
        <label>Response Date</label>
        <type>Date</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field is used to capture the start date of the campaign</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field can be used to track the progress of the campaign as part of campaign life cycle</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/classes/Batch_BounceStatusretailretailTest.cls
@isTest
public class Batch_BounceStatusretailretailTest   {

    public static Id camIdExec= Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
      public static Id camIdPlan= Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Planning & Design Campaign').getRecordTypeId();
      //public static Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
       public static Id personaccRecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    
   static testmethod void batchBounceStatus()
   {
   
   
       account objMaster= new Account(RecordTypeId=personaccRecordTypeId,Master_Record__c = true,lastname = '雄志',DUPNumber__c='110',
                               Last_Successful_Call_Office_Phone__c = System.today() - 10,SMS_Last_Modified_Date__c= date.today(),MBK_Data_Source__c='Email',Mobile__c = '00000009642',DMS_Address__c = 'dmsaddress1');  
    
    insert objMaster;
    
   Retail_Campaign__c camobj = new Retail_Campaign__c();
    camobj.RecordTypeId = camIdPlan;
    camobj.Name = 'camptest1';
    camobj.Campaign_Sub_Type__c= 'Sales';
    camobj.Status__c= 'Draft';
    camobj.Response_Date__c = date.today();
    camobj.Start_Date__c= System.today();
    camobj.Close_Date__c= System.today()+30;
    //camobj.Campaign_Executer__c='Retail';
    camobj.Child_Campaign_Status__c='Response collection';
   // camobj.Campaign_Objectives__c = 'camobjectives';
    camobj.Description__c= 'testdescrip';
    camobj.Campaign_Execution_Channels__c='eMail';
    camobj.Campaign_Type__c = 'After Sales';
    insert camobj;
  
  
    
        Retail_Campaign__c camobj1 = new Retail_Campaign__c();
        camobj1.RecordTypeId = camIdExec;
        camobj1.Parent_Campaign1__c=camobj.id;
        camobj1.Child_Campaign_Status__c='Planning';
         camobj1.Response_Date__c = date.today();
      
        camobj1.MD__c='JP';
        camobj1.Name = 'camptest1';
        camobj1.Campaign_Type__c='After Sales';
      //  camobj1.Type = 'Other';
        camobj1.Segmentation_Date__c= System.today()+4;
        camobj1.Execution_Start_Date__c = System.today()+10;
        camobj1.Execution_Type__c= 'eMail';
       // camobj1.Description = 'testdescrip';
        insert camobj1;
   
    Campaign_Member__c camMem = New Campaign_Member__c();
     camMem.Retail_Campaign_Id__c = camobj1.id;
     camMem.Status__c = 'Bounced';
     camMem.Contact_Id__c = objMaster.id;

      insert camMem;
      //camMem.Status__c = 'Bounced';
      //update camMem;
     Campaign_Member__c camMem1 = New Campaign_Member__c();
     camMem1.Retail_Campaign_Id__c = camobj1.id;
     camMem1.Status__c = 'Bounced';
     camMem1.Contact_Id__c = objMaster.id;

      insert camMem1;
      //camMem1.Status__c = 'Bounced';
     // update camMem1;
      
      system.debug('+++++++++'+camMem1);
      system.debug('+++++++++'+camobj1);
      system.debug('+++++++++'+camobj);
  
    
    
    //Batch_BounceStatusretail batchSch = New Batch_BounceStatusretail();
            Test.startTest(); 
       
        Database.executeBatch(new Batch_BounceStatusretail(),200);
    

         Test.stopTest();
         

}


static testmethod void batchBounceStatus1()
   {
   
   
      //String mainQuery = ;
    
    
   Retail_Campaign__c camobj = new Retail_Campaign__c();
    camobj.RecordTypeId = camIdPlan;
    camobj.Name = 'camptest1';
    camobj.Campaign_Sub_Type__c= 'Sales';
    camobj.Status__c= 'Draft';
    camobj.Response_Date__c = date.today();
    camobj.Start_Date__c= System.today();
    camobj.Close_Date__c= System.today()+30;
    //camobj.Campaign_Executer__c='Retail';
    camobj.Child_Campaign_Status__c='Response collection';
   // camobj.Campaign_Objectives__c = 'camobjectives';
    camobj.Description__c= 'testdescrip';
    camobj.Campaign_Execution_Channels__c='eMail';
    camobj.Campaign_Type__c = 'After Sales';
    insert camobj;
  
  
    
        Retail_Campaign__c camobj1 = new Retail_Campaign__c();
        camobj1.RecordTypeId = camIdExec;
        camobj1.Parent_Campaign1__c=camobj.id;
        camobj1.Child_Campaign_Status__c='Planning';
         camobj1.Response_Date__c = date.today();
      
        camobj1.MD__c='JP';
        camobj1.Name = 'camptest1';
        camobj1.Campaign_Type__c='After Sales';
      //  camobj1.Type = 'Other';
        camobj1.Segmentation_Date__c= System.today()+4;
        camobj1.Execution_Start_Date__c = System.today()+10;
        camobj1.Execution_Type__c= 'OB Call';
       // camobj1.Description = 'testdescrip';
        insert camobj1;
   
    Campaign_Member__c camMem = New Campaign_Member__c();
     camMem.Retail_Campaign_Id__c = camobj1.id;
     camMem.Status__c = 'Bounced';
     

      insert camMem;
      //camMem.Status__c = 'Bounced';
      //update camMem;
     Campaign_Member__c camMem1 = New Campaign_Member__c();
     camMem1.Retail_Campaign_Id__c = camobj1.id;
     camMem1.Status__c = 'Bounced';

      insert camMem1;
      //camMem1.Status__c = 'Bounced';
     // update camMem1;
      
      system.debug('+++++++++'+camMem1);
      system.debug('+++++++++'+camobj1);
      system.debug('+++++++++'+camobj);
  
    
    
    //Batch_BounceStatusretail batchSch = New Batch_BounceStatusretail();
            Test.startTest(); 
       
        Database.executeBatch(new Batch_BounceStatusretail(),200);
    

         Test.stopTest();
         

}
static testmethod void batchBounceStatus2()
   {
   
   
      DM_Material__c dm = new DM_Material__c(Name = 'test');
      insert dm;
    
    
   Retail_Campaign__c camobj = new Retail_Campaign__c();
    camobj.RecordTypeId = camIdPlan;
    camobj.Name = 'camptest1';
    camobj.Campaign_Sub_Type__c= 'Sales';
    camobj.Status__c= 'Draft';
    camobj.Response_Date__c = date.today();
    camobj.Start_Date__c= System.today();
    camobj.Close_Date__c= System.today()+30;
    //camobj.Campaign_Executer__c='Retail';
    camobj.Child_Campaign_Status__c='Response collection';
   // camobj.Campaign_Objectives__c = 'camobjectives';
    camobj.Description__c= 'testdescrip';
    camobj.Campaign_Execution_Channels__c='eMail';
    camobj.Campaign_Type__c = 'After Sales';
    insert camobj;
  
  
    
        Retail_Campaign__c camobj1 = new Retail_Campaign__c();
        camobj1.RecordTypeId = camIdExec;
        camobj1.Parent_Campaign1__c=camobj.id;
        camobj1.Child_Campaign_Status__c='Planning';
         camobj1.Response_Date__c = date.today();
      
        camobj1.MD__c='JP';
        camobj1.Name = 'camptest1';
        camobj1.Campaign_Type__c='After Sales';
      //  camobj1.Type = 'Other';
        camobj1.Segmentation_Date__c= System.today()+4;
        camobj1.Execution_Start_Date__c = System.today()+10;
        camobj1.Execution_Type__c= 'DM';
        camobj1.DM_Template__c = dm.id;
       // camobj1.Description = 'testdescrip';
        insert camobj1;
   
    Campaign_Member__c camMem = New Campaign_Member__c();
     camMem.Retail_Campaign_Id__c = camobj1.id;
     camMem.Status__c = 'Bounced';
     

      insert camMem;
      //camMem.Status__c = 'Bounced';
      //update camMem;
     Campaign_Member__c camMem1 = New Campaign_Member__c();
     camMem1.Retail_Campaign_Id__c = camobj1.id;
     camMem1.Status__c = 'Bounced';

      insert camMem1;
      //camMem1.Status__c = 'Bounced';
     // update camMem1;
      
      system.debug('+++++++++'+camMem1);
      system.debug('+++++++++'+camobj1);
      system.debug('+++++++++'+camobj);
  
    
    
    //Batch_BounceStatusretail batchSch = New Batch_BounceStatusretail();
            Test.startTest(); 
       
        Database.executeBatch(new Batch_BounceStatusretail(),200);
    

         Test.stopTest();
         

}


}