src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Retail_Email__c</fullName>
        <label>Retail Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Mobile__c</fullName>
        <label>Retail Mobile</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>Retail_Email__c</fullName>
        <description>Readonly</description>
        <label>Retail Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_LastName__c</fullName>
        <label>Retail LastName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Mobile__c</fullName>
        <description>Readonly</description>
        <label>Retail Mobile</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_PersonBirthdate__c</fullName>
        <description>Read Only</description>
        <label>Retail PersonBirthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Retail_UCID__c</fullName>
        <label>Retail UCID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>toRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links(External Link)</relationshipLabel>
        <relationshipName>Account_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/stouchPersonSearch.cls
@RestResource(urlMapping='/stouchPersonSearch/*')
global without sharing class stouchPersonSearch {
    @HttpPost
    global static JSON2ApexStouch PersonSearchResult()
    { 
        String jsonText = RestContext.request.requestBody.toString();
        Map<String, Object> cObjMap = (Map<String, Object>) JSON.deserializeUntyped(jsonText);
        List<Object> obj=(List<Object>)cObjMap.get('Input_IDS');
        String count=(String)cObjMap.get('Rec_count');
        system.debug('@@'+obj);
        list<String> accountlinklist1=new  list<String>();
        list<map<string,string>> newmap1=new  list<map<string,string>>();
        for(Object ob:obj)
        {
            accountlinklist1.add((String)ob);
        }
        list<Account_link__c> accountlinklist=[select toRole__r.MBK_Data_Source__c,Retail_PersonBirthdate__c,Retail_LastName__c,Retail_Mobile__c,Retail_Email__c,Retail_UCID__c,RecordTypeid,Ownerid from account_link__c where id=:accountlinklist1] ;
        JSON2ApexStouch ja= new JSON2ApexStouch();
        ja.record_count=count;
        for(Account_link__c ac:accountlinklist)
        {
            JSON2ApexStouch.Person jaw=new JSON2ApexStouch.Person(ac);
            ja.Output_IDS.add(jaw);
        }   
        return ja; 
    }
}