src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA')))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/TriggerAccountlinkHandlerMY.cls
public class TriggerAccountlinkHandlerMY implements TriggerHandlerIf {
    public void handleTrigger(boolean isInsert, boolean isUpdate, boolean isBefore, boolean isDelete, boolean isAfter) {
     
        AccountlinkhelperMY acchelper = new AccountlinkhelperMY();
      
        if (Trigger.isAfter && (Trigger.isupdate || Trigger.isInsert)) {
          
            if(Util_GetPermissionList.checkAccessOnUser(Label.MYGeneric)){ 
              acchelper.ValidateC2CAfterUpdateInsert(trigger.new);
            }
          
        }

      
    }
    
    public void handleIntegrationTrigger(boolean isInsert, boolean isUpdate, boolean isBefore, boolean isDelete, boolean isAfter) {
         List<Account_Link__c> AccListNewList = Trigger.new;
         
           if( !AccListNewList.isEmpty() && AccListNewList.size() > 0 && AccListNewList [0].MD__c == Label.MY){
               if (Trigger.isAfter && (Trigger.isupdate || Trigger.isInsert)) {
                   AccountlinkhelperMY acchelper = new AccountlinkhelperMY();
                   acchelper.ValidateC2CAfterUpdateInsert(trigger.new);
               }
               
           }
         
    }
}