src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Blacklist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Blacklist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Sales TEL</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Work Phone</fullName>
                </value>
                <value>
                    <fullName>Work Mobile</fullName>
                </value>
                <value>
                    <fullName>Other1</fullName>
                </value>
                <value>
                    <fullName>Other2</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>

src/main/metadata/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Activity_Status__c</fullName>
        <label>Activity Status</label>
        <picklist>
            <picklistValues>
                <fullName>not started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>no answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>need call back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>busy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>reject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>wrong number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>no such person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>invalid data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>failed to send SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>failed to send Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>failed to send fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>invalid call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>call transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail-Technical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail-Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail-Blacklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Click</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subscribe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsubscribe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hard Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>DMS</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>FirstName &amp; " " &amp;  LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/main/metadata/objects/DM_Request__c.object
<CustomObject>
    <description>Case: Track the DM Request. This is also used by Campaign for bulk DM Request</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DM Request</relationshipLabel>
        <relationshipName>DM_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account, Person Account Manual Merge, Person Account Soft Deleted</value>
            </filterItems>
            <infoMessage>Search and select account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DM Request</relationshipLabel>
        <relationshipName>DM_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select Leads that is linked to the same account as this DM Request.</errorMessage>
            <filterItems>
                <field>Lead__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Customer_Name__c</valueField>
            </filterItems>
            <infoMessage>Search and select leads.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>DM Request</relationshipLabel>
        <relationshipName>DM_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <formula>Contact__r.MobilePhone</formula>
        <label>Mobile</label>
        <type>Text</type>
    </fields>
    <label>DM Request</label>
    <nameField>
        <displayFormat>DMR-{000000}</displayFormat>
        <label>DM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DM Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Company_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Company Account)</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>IF( ISBLANK( Company_Account__c ) , IF( ISBLANK( Contact__c ) , '', Contact__r.Name ) , Company_Account__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Email__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.Email__c , 
Contact__r.Email__c 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Mobile__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.PersonMobilePhone, 
Collectioner_Name__r.MobilePhone
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile</label>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Work_Phone__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.Work_Phone__c  , 
 Collectioner_Name__r.Phone  
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Phone</label>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>eDM</fullName>
        <active>true</active>
        <label>eDM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
    <!---->
</CustomObject>

src/main/metadata/classes/TaskHelperTH.cls
/**
* Utility for Trigger on Task for TH(Thailand)
* Author: Bhushan K
* Created Date : 2017-03-02
*/

public without sharing class TaskHelperTH {
  private static String OBCAllTaskRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('OB Call').getRecordTypeId();
  private static String iBCAllTaskRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('IB Call').getRecordTypeId();
  private static String eDMTaskRecordTypeId = Schema.SObjectType.task.getRecordTypeInfosByName().get('eDM').getRecordTypeId();
  public static string leadTabId = (String)Schema.getGlobalDescribe().get('Lead__C').getDescribe().getKeyPrefix();//System.Label.LeadId;
  public static string dmRequestTabId = (String)Schema.getGlobalDescribe().get('DM_Request__c').getDescribe().getKeyPrefix();//System.Label.DMRequestTabId;
  /**
  *@Description : Updates Accounts if they are blacklisted based on Activity status of Tasks.
  *@param:List of Tasks.new , Task Old Map , Indicators for Insert/Update.
  *@return:This mehtod does not return any value.
  */     
    //As per new requirement requested by TH market Fail-blacklist is not applicable for TH market so commenting
   public static void TaskFailBlacklist(List<Task> tasks,Map<Id, Task> taskOldMap,boolean isInsert,boolean isUpdate)
   {    /*set<Id> setTaskIds = new set<Id>();
        Set<Id> conIds = new Set<Id>();
    list<account> accs=new list<account>();
        for(Task tk : tasks){
             if(tk.Activity_Status__c == 'Fail-Blacklist' &&  ( isInsert || (isUpdate &&!Test.isRunningTest()&& taskOldMap.get(tk.Id).Activity_Status__c != 'Fail-Blacklist')))
                setTaskIds.add(tk.Id);
        }            
        for(Task tks : [SELECT Id, WhoId FROM Task WHERE Id in :setTaskIds and WhoId != null] )
            conIds.add(tks.WhoId);                
        for(Account acc : [SELECT Id, Is_Blacklist__c FROM Account WHERE PersonContactId=:conIds And Is_Blacklist__c != true]){
            acc.Is_Blacklist__c = true;
            accs.add(acc);
        }
        if(accs.size()>0)   
            try{
            update accs;
            }
    catch(Exception e){
        
    }*/
   }
   
   /**
  *@Description : Fetches related Campaign members based on whoId and whatId and updates the campaignMember status
  based on task.Activity status and priority.
  *@param:List of Tasks.new , Task Old Map , Indicators for Insert/Update.
  *@return:This mehtod does not return any value.

  */
   public static void updateCampaignMemberStatus(List<Task> tasks,Map<Id, Task> taskOldMap,boolean isInsert,boolean isUpdate)
   {
        if(isInsert)
            UtilTaskTH.updateCampaignMemberStatus(tasks);
        if(isUpdate)
        {
             List<Task> lstTaskUpdate = new List<Task>();
             for (Task newTask : tasks)
             {
                if (newTask.Activity_Status__c != taskOldMap.get(newTask.Id).Activity_Status__c)
                    lstTaskUpdate.add(newTask);
             }
            if(lstTaskUpdate.size()>0)
                 UtilTaskTH.updateCampaignMemberStatus(lstTaskUpdate);
        }   
   }
   public static void updateAccountMobile(List<Task> lstTask){          
        Set<ID> accId = new Set<ID>();
        Set<ID> conId = new Set<ID>();
        Set<ID> leadId = new Set<ID>();
        set<id> contactId = new set<id>();
        Set<ID> dmRequestId = new Set<ID>();
        List<Account> lstAccount = new List<Account>();
        List<contact> lstcon = new List<contact>();
        List<Lead__c> lstLead = new List<Lead__c>();
        List<DM_Request__c> lstDMRequest = new List<DM_Request__c>();
        // Maps
        Map<Id , String> mapTask = new Map<Id , String>();
        Map<Id , String> mapEMailTask = new Map<Id , String>();
        Map<Id , String> mapLead = new Map<Id , String>();
        Map<Id , String> mapEMailLead = new Map<Id , String>();
        Map<Id , String> mapDMRequestPhone = new Map<Id , String>();
        Map<Id , String> mapDMRequestEmail = new Map<Id , String>();
        Map<Id , id> custname = new Map<Id , id>();
        
        for(Task tsk : lstTask){ 
            if( tsk.whoid != null && String.valueOf( tsk.whoid ).startsWith( '001' ))
                accId.add(tsk.whoid);       
            else if( tsk.whoid != null && String.valueOf( tsk.whoId ).startsWith( '003' ))
                conId.add(tsk.whoId);       
            else if(tsk.WhatId != null){
                if(String.valueOf( tsk.WhatId ).startsWith(leadTabId))
                  leadId.add(tsk.WhatId);        
                else if(String.valueOf( tsk.WhatId ).startsWith( dmRequestTabId ))
                  dmRequestId.add(tsk.WhatId);           
            }
        
        }
        if(accId.size()>0)
            lstAccount = [Select Id,Mobile__c,Email__c, Primary_Phone__c,individual_Home_Phone__c,PersonContactId,Work_Phone__c from Account where Id =:accId or id=:conId];
        if(conId.size()>0)
            lstcon = [Select Id, Account.Email__c,Account.Mobile__c,Account.Primary_Phone__c,Account.individual_Home_Phone__c,Account.Work_Phone__c from contact where Id =:conId];
        if(leadId.size()>0)
            lstLead = [Select Id,Contact__r.Mobile__c,Contact__c,Contact__r.Email__c, Contact__r.Primary_Phone__c,Contact__r.individual_Home_Phone__c,Contact__r.PersonContactId,Contact__r.Work_Phone__c,Company_Account__r.Mobile__c,Company_Account__r.Email__c from Lead__c where Id =:leadId];
        if(dmRequestId.size()>0)
           lstDMRequest = [Select Id,Customer_Name__c,Customer_Name__r.Mobile__c,Customer_Name__r.Primary_Phone__c,Customer_Name__r.individual_Home_Phone__c,Customer_Name__r.Work_Phone__c,Customer_Name__r.Email__c,Customer_Name__r.PersonContactId  from DM_Request__c where Id =:dmRequestId]; 
        for(contact con : lstcon){
            if(con.account.Primary_Phone__c!=null){
            String contactphone=con.account.Primary_Phone__c=='Mobile'?con.account.Mobile__c:con.account.Primary_Phone__c=='Home phone'?con.account.individual_Home_Phone__c:con.account.Primary_Phone__c=='Work Phone'?con.account.Work_Phone__c:'nophone';
            if(contactphone!='nophone')
                mapTask.put(con.id,contactphone);
            }       
        }
        for(Account acc : lstAccount){
            if(acc.Primary_Phone__c!=null){
            String contactphone=acc.Primary_Phone__c=='Mobile'?acc.Mobile__c:acc.Primary_Phone__c=='Home phone'?acc.individual_Home_Phone__c:acc.Primary_Phone__c=='Work Phone'?acc.Work_Phone__c:'nophone';
            if(contactphone!='nophone')
                mapTask.put(acc.id,contactphone);
            } 
            mapEMailTask.put(acc.id, acc.Email__c);
            }         
        
        for(Lead__c led : lstLead){

            if(led.contact__c!=null && led.Contact__r.Primary_Phone__c!=null){
                String contactphone=led.Contact__r.Primary_Phone__c=='Mobile'?led.Contact__r.Mobile__c:led.Contact__r.Primary_Phone__c=='Home phone'?led.Contact__r.individual_Home_Phone__c:led.Contact__r.Primary_Phone__c=='Work Phone'?led.Contact__r.Work_Phone__c:'nophone';
                if(contactphone!='nophone')
                mapLead.put(led.id,contactphone);
                }
                mapEMailLead.put(led.id, led.Contact__r.Email__c);
                custname.put(led.id,led.Contact__r.PersonContactId);
    
        }
        
        for(DM_Request__c dmr : lstDMRequest){   
             if(dmr.Customer_Name__c!=null && dmr.Customer_Name__r.Primary_Phone__c!=null){
                    String contactphone=dmr.Customer_Name__r.Primary_Phone__c=='Mobile'?dmr.Customer_Name__r.Mobile__c:dmr.Customer_Name__r.Primary_Phone__c=='Home phone'?dmr.Customer_Name__r.individual_Home_Phone__c:dmr.Customer_Name__r.Primary_Phone__c=='Work Phone'?dmr.Customer_Name__r.Work_Phone__c:'nophone';
                    if(contactphone!='nophone')
                        mapDMRequestPhone.put(dmr.id,contactphone);
                }         
            mapDMRequestEmail.put(dmr.id, dmr.Customer_Name__r.Email__c);
            custname.put(dmr.id,dmr.Customer_Name__r.PersonContactId);
        }
                
        for(Task t : lstTask){
            if(t.RecordTypeId == OBCAllTaskRecordTypeId||t.RecordTypeid==iBCAllTaskRecordTypeId){
                if(t.WhoId != Null && String.valueOf( t.whoid ).startsWith( '003' ))
                    t.Phone__c = mapTask.get(t.Whoid);  
                else if(t.whoid != Null && String.valueOf( t.whoid ).startsWith( '001' ))
                     t.Phone__c = mapTask.get(t.WhatId); 
                else if(t.WhatId != Null && String.valueOf( t.WhatId ).startsWith( leadTabId )){
                    t.Phone__c = mapLead.get(t.WhatId);  
                    t.whoid= custname.get(t.whatid);
                }
                else if(t.WhatId != Null && String.valueOf( t.WhatId ).startsWith(dmRequestTabId)){                    
                        t.Phone__c = mapDMRequestPhone.get(t.WhatId);
                        t.whoid= custname.get(t.whatid);
                }
            }else if(t.RecordTypeId == eDMTaskRecordTypeId){
                if(t.WhoId != Null && String.valueOf( t.whoid ).startsWith( '003' ))
                    t.Email_Address__c = mapEMailTask.get(t.WhoId);                    
                if(t.WhatId != Null && String.valueOf( t.WhatId ).startsWith( '001' ))
                    t.Email_Address__c = mapEMailTask.get(t.WhatId);
                if(t.WhatId != Null){
                    if(String.valueOf( t.WhatId ).startsWith(leadTabId))
                      t.Email_Address__c = mapEMailLead.get(t.WhatId); 
                    else if(String.valueOf( t.WhatId ).startsWith(dmRequestTabId))
                        t.Email_Address__c = mapDMRequestEmail.get(t.WhatId);       
            }
          }
      }
  }
}