src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Required by business during the workshop, which exists in current avarto system ( 区号).</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recall__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate whether the customer has vehicle for recall</description>
        <label>Recall</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Recall__c.object
<CustomObject>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Recalls</relationshipLabel>
        <relationshipName>Recalls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recall</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Recall ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recalls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <label>Trigger</label>
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>EuroVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Euro VIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is”Vehicle_EuroVIN“</description>
        <externalId>true</externalId>
        <label>EuroVIN</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recall__c</fullName>
        <defaultValue>false</defaultValue>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag whatever the vehicle has been recalled 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_Recall“</description>
        <label>Recall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Vehicle UsVIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_UsVIN“</description>
        <externalId>true</externalId>
        <label>UsVIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>MB</fullName>
        <active>true</active>
        <description>MB vehicle</description>
        <label>MB</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recall__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <formula>Vehicle_ID__r.UsVIN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UsVIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/RecallHelperTest.cls
@isTest
private with sharing class RecallHelperTest {

    static Id accPerson_RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();     // Person Account.                                        
    static Vehicle__c vehicles = new Vehicle__c(Recall__c = FALSE, EuroVIN__c = '12345678901011000',
                                                UsVIN__c = '12345678901011000', RecordTypeId = Schema.SObjectType.Vehicle__c.getRecordTypeInfosByName().get('MB').getRecordTypeId());
    static Vehicle_Relationship__c VR = new Vehicle_Relationship__c(Recall__c = FALSE); 
    static Account account = new Account(Recall__c = FALSE, Phone = '1234567',
                                        Area_Code__c ='010',
                                         RecordTypeId = accPerson_RecordTypeId,
                                         LastName = 'lai');                                          
    static Recall__c custom = new Recall__c(VIN__c = '12345678901011000');                                    
       static testMethod void myUnitTest() {        
        User user1 = UtilTestData.createUser('IB CSR','CAC IB CSR');   
        system.runAs(user1){
            Test.startTest();
            testMain();
            Test.stopTest();
            system.assertEquals([SELECT Recall__c FROM Vehicle__c WHERE id = :vehicles.id AND UsVIN__c = '12345678901011000'].Recall__c,false);
            system.assertEquals([SELECT Recall__c FROM Account WHERE id = :account.id].Recall__c,false);
      }        
    }
                                                                                                                                                                                      
    @future
    private static void testMain(){
         List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
         insert updatecustomsettings;
        insert vehicles;
        insert account;
        VR.Contact__c = account.id;
        VR.Vehicle_ID__c = vehicles.id;
        insert VR;
        custom.Vehicle_ID__c = vehicles.id;
        insert custom;
        
        //test Recall__c is auto checked When custom insert
        system.assertEquals([SELECT Recall__c FROM Vehicle__c WHERE id = :vehicles.id AND UsVIN__c = '12345678901011000'].Recall__c,TRUE);
        
        //test Recall__c is auto checked When custom insert
        system.assertEquals([SELECT Recall__c FROM Account WHERE id = :account.id].Recall__c,TRUE);

        //test Recall__c is auto checked When custom insert
        system.assertEquals([SELECT Recall__c FROM Vehicle_Relationship__c WHERE id = :VR.id].Recall__c,TRUE);


        delete custom;
        
        //test Recall__c is auto removed When custom insert
        system.assertEquals([SELECT Recall__c FROM Vehicle__c WHERE id = :vehicles.id AND UsVIN__c = '12345678901011000'].Recall__c,FALSE);
        
        //test Recall__c is auto removed When custom insert
        system.assertEquals([SELECT Recall__c FROM Account WHERE id = :account.id].Recall__c,FALSE);

        //test Recall__c is auto removed When custom insert
        system.assertEquals([SELECT Recall__c FROM Vehicle_Relationship__c WHERE id = :VR.id].Recall__c,FALSE);    
    
    }


}