src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retail_Email__c</fullName>
        <label>Retail Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Fax__c</fullName>
        <label>Retail Fax</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Mobile__c</fullName>
        <label>Retail Mobile</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Work_Phone__c</fullName>
        <label>Retail Work Phone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_ZipCode__c</fullName>
        <label>Retail ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA')))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Address_Line_1__c</fullName>
        <description>Readonly</description>
        <label>Retail Address Line 1</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Address_Line_2__c</fullName>
        <description>Readonly</description>
        <label>Retail Address Line 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Address_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read Only</description>
        <label>Retail Address Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.toRole__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Account Link</relationshipLabel>
        <relationshipName>Account_Link</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_City__c</fullName>
        <description>Readonly</description>
        <label>Retail City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Dealer_CompanyCode__c</fullName>
        <formula>fromRole__r.Dealer_GC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer GC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Email__c</fullName>
        <description>Readonly</description>
        <label>Retail Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Fax__c</fullName>
        <description>Readonly</description>
        <label>Retail Fax</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Individual_Home_Phone__c</fullName>
        <description>Readonly</description>
        <label>Retail Individual Home Phone</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Mobile__c</fullName>
        <description>Readonly</description>
        <label>Retail Mobile</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Province__c</fullName>
        <label>Retail Province</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Work_Phone__c</fullName>
        <description>Readonly</description>
        <label>Retail Work Phone</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_ZipCode__c</fullName>
        <description>Readonly</description>
        <label>Retail ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>toRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links(External Link)</relationshipLabel>
        <relationshipName>Account_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <recordTypes>
        <fullName>Retail_Company</fullName>
        <active>true</active>
        <description>Customer Copy for Company Account</description>
        <label>Retail Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retail_Person</fullName>
        <active>true</active>
        <description>Customer Copy for Person Account</description>
        <label>Retail Person</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
		IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
		IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA')))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Prefecture</label>
        <picklist>
            <picklistValues>
                <fullName>Hokkaido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aomori</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iwate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miyagi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamagata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukushima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ibaraki</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tochigi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gunma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saitama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tokyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kanagawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niigata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ishikawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamanashi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shizuoka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aichi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shiga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kyoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Osaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wakayama</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Post Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/classes/UpdateRetcopyAddresses.cls
global class UpdateRetcopyAddresses implements 
        Database.Batchable<sObject>, Database.Stateful {
      global List<Account_Link__C>RetcopyList = new list<Account_Link__C>();
       
        global Database.QueryLocator start(Database.BatchableContext bc) {
            return Database.getQueryLocator([Select id, Name, RETAIL_ZIPCODE__C, RETAIL_PROVINCE__C, RETAIL_CITY__C, RETAIL_ADDRESS_LINE_1__C, RETAIL_DEALER_COMPANYCODE__C, RETAIL_ADDRESS_LINE_2__C, RETAIL_EMAIL__C, RETAIL_INDIVIDUAL_HOME_PHONE__C, RETAIL_MOBILE__C,RecordType.DeveloperName, RETAIL_WORK_PHONE__C, RETAIL_FAX__C, Retail_Address_Reference__r.ZipCode__c, Retail_Address_Reference__r.Province__c, Retail_Address_Reference__r.CITY__C, Retail_Address_Reference__r.ADDRESS_LINE_1__C,Retail_Address_Reference__r.ADDRESS_LINE_2__C,toRole__r.EMAIL__C , toRole__r.Individual_Home_Phone__c, toRole__r.MOBILE__C, toRole__r.WORK_PHONE__C, toRole__r.FAX from Account_Link__C WHERE RETAIL_DEALER_COMPANYCODE__C != 'GC0002665' AND (RecordType.DeveloperName = 'Retail_Company' OR RecordType.DeveloperName= 'Retail_Person') AND MD__c = 'JP' AND Retail_Address_Reference__c !=null]);
        }
        global void execute(Database.BatchableContext bc, List<Account_link__C> scope){
         
            system.debug('Scope------>'+scope);
            String AccountLinklst = '';
                For (Account_link__C ALK:Scope){
                    if(ALK.Retail_Address_Reference__c != null){
                        ALK.RETAIL_ZIPCODE__C = ALK.Retail_Address_Reference__r.ZipCode__c;
                        ALK.RETAIL_PROVINCE__C = ALK.Retail_Address_Reference__r.PROVINCE__C;
                        ALK.RETAIL_CITY__C = ALK.Retail_Address_Reference__r.CITY__C;
                        ALK.RETAIL_ADDRESS_LINE_1__C = ALK.Retail_Address_Reference__r.ADDRESS_LINE_1__C;
                        ALK.RETAIL_ADDRESS_LINE_2__C = ALK.Retail_Address_Reference__r.ADDRESS_LINE_2__C;
                    }
                    if(ALK.toRole__c != null){
                        ALK.RETAIL_FAX__C = ALK.toRole__r.FAX;
                        System.debug('ALK.RecordType.DeveloperName---->'+ALK.RecordType.DeveloperName);
                        If (ALK.RecordType.DeveloperName== 'Retail_Person'){
                            System.debug('ALK.RETAIL_EMAIL__C ---->'+ALK.RETAIL_EMAIL__C );
                            System.debug('RETAIL_INDIVIDUAL_HOME_PHONE__C ---->'+ALK.RETAIL_INDIVIDUAL_HOME_PHONE__C );
                            System.debug('ALK.RETAIL_MOBILE__C ---->'+ALK.RETAIL_MOBILE__C );
                            System.debug('RETAIL_WORK_PHONE__C ---->'+ALK.RETAIL_WORK_PHONE__C );
                            ALK.RETAIL_EMAIL__C =  ALK.toRole__r.EMAIL__C;
                            ALK.RETAIL_INDIVIDUAL_HOME_PHONE__C = ALK.toRole__r.INDIVIDUAL_HOME_PHONE__C;
                            ALK.RETAIL_MOBILE__C=  ALK.toRole__r.MOBILE__C;
                            ALK.RETAIL_WORK_PHONE__C = ALK.toRole__r.WORK_PHONE__C;
                    }
                        }
                   RetcopyList.add(ALK);
                   system.debug('ListofRetCopies'+ ALK);
                }  
                
                    
                 //update RetcopyList;    
                 List<Database.SaveResult> sverel = Database.Update(RetcopyList,false);
                 String ErrorMsg = '';
                 for(Database.SaveResult res : sverel){  
                 
                     if(!res.isSuccess()){
                        ErrorMsg =    ErrorMsg + res.getErrors()[0].getMessage(); 
                     }               
                    AccountLinklst = AccountLinklst+res.id+',' + ErrorMsg + '\n';                    
                 }
                  
                 Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                    Blob csvBlob = Blob.Valueof(AccountLinklst);
                    efa.setFileName('UpdateccountLinklist.csv');
                    efa.setBody(csvBlob);                    
                    
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();  
            email.setSubject( 'AccountLinks Update' );
            email.setToAddresses( (new String[] {'shiva.sai@nttdata.com','kiran.pedinenikalva@nttdata.com','dasepalle.abhishekh@nttdata.com'} ));
            email.setPlainTextBody( 'Please find the attached list of Account records are updated' );
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
 
            // Sends the email
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email}); 
                    
                }
                
                
                
        
         
         global void finish(Database.BatchableContext BC) 
         {
            
          }
          
        global void execute(SchedulableContext s){
            Database.executeBatch(this);        
        }
        
}