src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to refer the related Customer/Contact  record</description>
        <label>Contact Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_Email__c</fullName>
        <label>Response Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retail_Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign member (Retail Campaign)</relationshipLabel>
        <relationshipName>Campaign_member1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to set the status of the campaign member</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Member__c.object
    <fields>
        <fullName>Response_FirstName__c</fullName>
        <label>Response FirstName</label>
        <length>100</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Campaign_Member__c.object
    <fields>
        <fullName>Response_LastName__c</fullName>
        <label>Response LastName</label>
        <length>100</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Participating_Dealer__c.object
<CustomObject>
    <description>Campaign: Dealers that participate the campaign</description>
    <label>Participating Dealer</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participating Dealers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participating_Dealer__c.object
    <fields>
        <fullName>Retail_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Retail Campaign</label>
        <referenceTo>Retail_Campaign__c</referenceTo>
        <relationshipLabel>Participating Dealers</relationshipLabel>
        <relationshipName>Participating_Dealers</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field can be used to track the progress of the campaign as part of campaign life cycle</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <label>Trigger</label>
</CustomObject>

src/main/metadata/classes/CampaignMembersCustomHelperJPTest.cls
@istest
public class CampaignMembersCustomHelperJPTest
{
 public static Account accobj;
  public static Contact contobj;
  public static Campaign camobj;
  public static Retail_Campaign__c campobj;
  public static Campaign_Member__c cm;
  public static List<Participating_Dealer__c> padealerlist;
  public static Id DealerAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
  public static Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
  public static Id centmarcampRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Central Marketing Campaign').getRecordTypeId();
  public static Id RetailcentmarcampRecordTypeId = Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
  static void createTestData() {  
 
      List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
            insert updatecustomsettings;
    accobj = new Account();
    accobj.FirstName = 'testaccount';
    accobj.lastName = 'testaccount';
    accobj.Email__c = 'Test@test.com';
    accobj.RecordTypeId = personAccRecordTypeId;
    //accobj.Name = 'testaccount';
    accobj.Phone = '012310086';
    accobj.MBK_Data_Source__c='Email';
    accobj.Mobile__c = '00000009642';
    insert accobj;
    system.debug('$$$$$$$$$$$$'+accobj);
    system.debug('$$$$$$$$$$$$'+accobj.id);
    
    campobj= new Retail_Campaign__c();
    campobj.RecordTypeId = RetailcentmarcampRecordTypeId;
    campobj.Name = 'camptest1';
    //campobj.Type = 'Other';
    //campobj.Status = 'Planned';
    //campobj.StartDate = System.today();
    //campobj.EndDate = System.today();
    //campobj.Campaign_Objectives__c = 'camobjectives';
    //campobj.Description = 'testdescrip';
    
    insert campobj;
    cm=new Campaign_Member__c();
    cm.Retail_Campaign_Id__c=campobj.id;
    cm.Status__c = 'Ready';
    //cm.contact_Id__c = accobj.Id;   
    insert cm;    
  }
    
  public static testMethod void updateContactTest() {
    createTestData();
      Map<Id, Campaign_Member__c> oldMap = new Map<Id, Campaign_Member__c> ();
    Map<Id, Campaign_Member__c> newMap = new Map<Id, Campaign_Member__c> ();
   List<Campaign_Member__c> newList = new List<Campaign_Member__c> ();
   oldMap.put(cm.Id , cm);
    cm.Response_FirstName__c ='testaccount';
    cm.Response_LastName__c = 'testaccount';
    cm.Response_Email__c = 'Test@test.com';
   cm.Status__c = 'Responded';
   update cm;
 newMap.put(cm.Id , cm);
 newList.add(cm);
    test.startTest();     
      CampaignMembersCustomHelperJP cth = new CampaignMembersCustomHelperJP(); 
      CampaignMembersCustomHelperJP.afterUpdateOperation(oldMap,newMap,newList); 
      CampaignMembersCustomHelperJP.updateCampaignMemberStatusResponseCollection (newList);   
      CampaignMembersCustomHelperJP.afterUpdateCampaignMembers(newMap);
    test.stoptest();
   
  }
  public static testMethod void updateContactTest1() {
    createTestData();
      Map<Id, Campaign_Member__c> oldMap = new Map<Id, Campaign_Member__c> ();
    Map<Id, Campaign_Member__c> newMap = new Map<Id, Campaign_Member__c> ();
   List<Campaign_Member__c> newList = new List<Campaign_Member__c> ();
   oldMap.put(cm.Id , cm);   
      cm.Retail_Campaign_Id__c = campobj.Id;
       cm.Status__c = 'Responded';
       update cm;
     newMap.put(cm.Id , cm);
     newList.add(cm);
    test.startTest();     
      CampaignMembersCustomHelperJP cth = new CampaignMembersCustomHelperJP(); 
      CampaignMembersCustomHelperJP.afterUpdateOperation(oldMap,newMap,newList); 
      CampaignMembersCustomHelperJP.updateCampaignMemberStatusResponseCollection (newList);   
      CampaignMembersCustomHelperJP.afterUpdateCampaignMembers(newMap);
    test.stoptest();
   
  }
  public static testMethod void updateContactTest2() {
    createTestData();
      Map<Id, Campaign_Member__c> oldMap = new Map<Id, Campaign_Member__c> ();
    Map<Id, Campaign_Member__c> newMap = new Map<Id, Campaign_Member__c> ();
   List<Campaign_Member__c> newList = new List<Campaign_Member__c> ();
   oldMap.put(cm.Id , cm); 
   cm.Response_FirstName__c ='testaccount1t';
    cm.Response_LastName__c = 'testaccount1s';
    cm.Response_Email__c = 'Testtre@test.com';
    update cm;
   newMap.put(cm.Id , cm);
     newList.add(cm);
    test.startTest();     
      CampaignMembersCustomHelperJP cth = new CampaignMembersCustomHelperJP(); 
      CampaignMembersCustomHelperJP.afterUpdateOperation(oldMap,newMap,newList); 
      CampaignMembersCustomHelperJP.updateCampaignMemberStatusResponseCollection (newList);   
      CampaignMembersCustomHelperJP.afterUpdateCampaignMembers(newMap);
    test.stoptest();
   
  }
}