src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Required by business during the workshop, which exists in current avarto system ( 区号).</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_SR_Code_2__c</fullName>
        <label>Dealer DMS SR Code 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_SR_Code__c</fullName>
        <label>Dealer DMS SR Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_SSI_Participation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Status of dealer&apos;s participation in the SSI program 
Used in: Page Layouts, Reports 

Modify History March 03, 2013
Modify By: Lio Huang
Modify Reason: Added the prefix &quot;Dealer&quot;, which indicates this field will only be used at dealer
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_NoSSI&quot;</description>
        <label>Dealer SSI Participation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/SSI__c.object
<CustomObject>
    <description>SSI: To record each SSI record</description>
    <fields>
        <fullName>CustomerName__c</fullName>
        <description>Customer Name from the sales contract</description>
        <label>CustomerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCheck_Status__c</fullName>
        <label>DealerCheck Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <description>Sales dealer code in CRM</description>
        <label>Dealer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HandoverDate__c</fullName>
        <description>Date of the vehicle-handover to the customer</description>
        <label>HandoverDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InvoiceDate__c</fullName>
        <description>Date for invoice</description>
        <label>InvoiceDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OfficePhone__c</fullName>
        <description>Office Phone Number from the sales contract</description>
        <label>OfficePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmatched</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VehicleDesc__c</fullName>
        <description>Vehicle description according to sales contract</description>
        <label>VehicleDesc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleModel__c</fullName>
        <description>Vehicle model according to sales contract</description>
        <label>VehicleModel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SSI</label>
    <nameField>
        <displayFormat>SSI-{000000}</displayFormat>
        <label>SSI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>EuroVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Euro VIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is”Vehicle_EuroVIN“</description>
        <externalId>true</externalId>
        <label>EuroVIN</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <description>Vehicle model</description>
        <label>Model</label>
        <picklist>
            <controllingField>Class__c</controllingField>
            <picklistValues>
                <fullName>A160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A180</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A 180 Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A 200 Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A 260 Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Dynamic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 BlueEFFICIENCY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Luxury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Luxury  night special edition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C 200 Entry Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C 280 Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 CGI Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 CGI Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C280  Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K Sport (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C260 Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240E  Elegance (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240A Avantgarde (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C280</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240 (not current series)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C260 CGI Avantgarde (CKD)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Vehicle UsVIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_UsVIN“</description>
        <externalId>true</externalId>
        <label>UsVIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SSI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SSI process:  Lookup to the SSI record that was correctly matched to this vehicle relationship</description>
        <label>SSI Matched</label>
        <referenceTo>SSI__c</referenceTo>
        <relationshipLabel>Vehicle Relationship</relationshipLabel>
        <relationshipName>Vehicle_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Status of vehicle for this person
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is "VehicleRel_Status"</description>
        <inlineHelpText>Status of vehicle for this person</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Previously Owned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currently Owned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <formula>Vehicle_ID__r.UsVIN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UsVIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/SSIDataCleanTest.cls
@isTest
private with sharing class SSIDataCleanTest {
Private static Account customer;
Private static String original='original';
Private static String valid='valid';
Private static String Inprocess='In process';
Private static String testcustomer='test-customer';
Private static String accept='accept';
Private static String allvalid='all valid';
Private static List<Account> accList;
Private static Id dealerid = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();

public static void preparedTestData()
{

         accList = new List<Account>();
        
        for(Integer i=0; i<21; i++){
               customer = new Account(
                Name = 'Test-00000' + i,
                Phone = '1234567', 
                ZipCode__c = '123456',
                Recordtypeid = dealerid,
                Dealer_SSI_Participation__c = true,
                Dealer_DMS_SR_Code__c = 'Test-00000' + i,
                Dealer_DMS_SR_Code_2__c = 'Test-00000-' + i
            );
            
            accList.add(customer);
        }
        
        insert accList;
        
        accList = [Select Id, Name, Dealer_DMS_SR_Code__c, Dealer_DMS_SR_Code_2__c From Account Where Id = :accList];
        
        // runDealerRule
        
        List<SSI__c> ssiList = new List<SSI__c>();
        
        SSI__c s1 = new SSI__c(Status__c = 'Invalid', InvoiceDate__c = date.newInstance(2013,10,1));
        insert s1;
        ssiList.add(s1);
        
        SSI__c s2 = new SSI__c(Status__c = original, InvoiceDate__c = date.newInstance(2013,10,1));
        insert s2;
        ssiList.add(s2);
        
        SSI__c s3 = new SSI__c(Dealer__c = accList[0].Dealer_DMS_SR_Code__c, Status__c = original, 
                               InvoiceDate__c = date.newInstance(2013,10,1));
        insert s3;
        ssiList.add(s3);
        
        Schema.DescribeFieldResult fieldResult = Vehicle__c.Model__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        SSI__c s4 = new SSI__c(Dealer__c = accList[0].Dealer_DMS_SR_Code_2__c, VehicleDesc__c = ple[0].getLabel(), 
                               Status__c = original, InvoiceDate__c = date.newInstance(2013,10,1));
        insert s4;
        ssiList.add(s4);
        
        SSI__c s5 = new SSI__c(Dealer__c = accList[0].Dealer_DMS_SR_Code_2__c + '-ERROR', Status__c = original, 
                               InvoiceDate__c = date.newInstance(2013,10,1));
        insert s5;
        ssiList.add(s5);
        
        SSIDataClean.runDealerRule(null,date.newInstance(2013,1,1),date.newInstance(2014,10,11));
        
        // runCarModelRule
        SSI__c s7 = new SSI__c(
            Dealer__c = accList[0].Dealer_DMS_SR_Code_2__c, 
            VehicleModel__c = ple[0].getLabel(),
            //VehicleDesc__c = ple[0].getLabel(), 
            DealerCheck_Status__c = valid,
            Status__c = Inprocess);
        insert s7;
        
        SSI__c s8 = new SSI__c(
            Dealer__c = accList[0].Dealer_DMS_SR_Code_2__c, 
            //VehicleDesc__c = ple[0].getLabel() + '-ERROR', 
            DealerCheck_Status__c = valid,
            Status__c = Inprocess);
        insert s8;
        
          // run rest rule
        Account dms = new Account(
            LastName = testcustomer,
            Phone = '1234567', 
            ZipCode__c = '123456',
            Area_Code__c = '101',
            Recordtypeid = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()
        );
        insert dms;
        Vehicle__c veh = new Vehicle__c(UsVIN__c = 'NUNFO004324942821', EuroVIN__c = 'ASFOTI09842713RFDS');
        insert veh;
        Vehicle_Relationship__c vr = new Vehicle_Relationship__c(Contact__c = dms.Id, Vehicle_ID__c = veh.Id);
        insert vr;
        
         
        
}

    static testMethod void TestrunRestRule() {
        preparedTestData();
        
        SSIDataClean.runCarModelRule(null, false);
        
      
        List<SSI__c> rests = new List<SSI__c>();
      //  Date d1 = Date.today().toStartOfMonth().addMonths(-1);
      //  Date d2 = Date.today().toStartOfMonth().addMonths(-2);
        Date d3 = Date.today().toStartOfMonth().addMonths(-3);
        Date d4 = Date.today().toStartOfMonth();
        
        SSI__c valid_W_1 = new SSI__c();
        valid_W_1.InvoiceDate__c = d4;
        valid_W_1.HandoverDate__c = d4;
        valid_W_1.CustomerName__c = testcustomer;
        valid_W_1.OfficePhone__c = '13011111112';
        valid_W_1.HomeMobilePhone__c = '13011111111';
        valid_W_1.VehicleUSvin__c = 'NUNFO004324942821';
        valid_W_1.OriginalCustomerName__c = 'testcustomer2';
        valid_W_1.Original_HomeMobilePhone__c = '13011111121';
        valid_W_1.OriginalOfficePhone__c = '13011111122';
        valid_W_1.DealerCheck_Status__c = accept;
        valid_W_1.CarModelCheck_Status__c = accept;
        valid_W_1.Status__c = Inprocess;
        rests.add(valid_W_1);
        
        SSI__c valid_1_nossi = new SSI__c();
        valid_1_nossi.InvoiceDate__c = d4;
        valid_1_nossi.HandoverDate__c = d4;
        valid_1_nossi.CustomerName__c = 'testcustomer-Error';
        valid_1_nossi.HomeMobilePhone__c = '13011121112'; 
        valid_1_nossi.DealerCheck_Status__c = accept;
        valid_1_nossi.CarModelCheck_Status__c = accept;
        valid_1_nossi.Status__c = Inprocess;
        valid_1_nossi.Original_HomeMobilePhone__c = '13011111121';
        valid_1_nossi.OriginalOfficePhone__c = '13011111122';       
        rests.add(valid_1_nossi);
        
        SSI__c valid_1_unmatchssi = new SSI__c();
        valid_1_unmatchssi.InvoiceDate__c = d4;
        valid_1_unmatchssi.HandoverDate__c = d4;
        valid_1_unmatchssi.CustomerName__c = testcustomer;
        valid_1_unmatchssi.OfficePhone__c = '13031111112';
        valid_1_unmatchssi.HomeMobilePhone__c = '13011111113';
        valid_1_unmatchssi.VehicleUSvin__c = 'NUNFO004324942821-Error';
        valid_1_unmatchssi.DealerCheck_Status__c = accept;
        valid_1_unmatchssi.CarModelCheck_Status__c = accept;
        valid_1_unmatchssi.Status__c = Inprocess;
        valid_1_unmatchssi.Original_HomeMobilePhone__c = '13011111121';
        valid_1_unmatchssi.OriginalOfficePhone__c = '13011111122';  
        rests.add(valid_1_unmatchssi); 
  
        // rule 1 
        SSI__c rule1failure = new SSI__c();
        rule1failure.DealerCheck_Status__c = accept;
        rule1failure.CarModelCheck_Status__c = accept;
        rule1failure.Status__c = Inprocess;     
        rests.add(rule1failure);
        
        SSI__c rule1failure1 = new SSI__c();
        rule1failure1.DealerCheck_Status__c = accept;
        rule1failure1.CarModelCheck_Status__c = accept;
        rule1failure1.Status__c = Inprocess;
        rule1failure1.InvoiceDate__c = d4;
        rule1failure1.HandoverDate__c = d3;        
        rests.add(rule1failure1);
        
        SSI__c rule1pass = new SSI__c();
        rule1pass.InvoiceDate__c = d4;
        rule1pass.HandoverDate__c = d4;
        rule1pass.DealerCheck_Status__c = accept;
        rule1pass.CarModelCheck_Status__c = accept;
        rule1pass.Status__c = Inprocess;
        rests.add(rule1pass);
        
        // rule 2
        SSI__c rule2failure = rule1pass.clone();
        rests.add(rule2failure);
        SSI__c rule2pass1 = rule1pass.clone();
        rule2pass1.HomeMobilePhone__c = '13022222222';
        rule2pass1.Original_HomeMobilePhone__c = '13022222232';
        rests.add(rule2pass1);
        SSI__c rule2pass2 = rule1pass.clone();
        rule2pass2.OfficePhone__c = '13022222223';
        rule2pass2.OriginalOfficePhone__c = '13022222233';
        rests.add(rule2pass2);
        SSI__c rule2pass3 = rule1pass.clone();
        rule2pass3.OfficePhone__c = '13581709501';
        rule2pass3.OriginalOfficePhone__c = '13581709502';
        rule2pass3.HomeMobilePhone__c = '13581709503';
        rule2pass3.Original_HomeMobilePhone__c = '13581709504';
        rests.add(rule2pass3);
        
        // rule 3
        SSI__c rule3failure1 = rule2pass3.clone();
        rests.add(rule3failure1);
        SSI__c rule3pass1 = rule2pass3.clone();
        rule3pass1.VehicleUSvin__c = 'rule3pass1-VIN';
        rests.add(rule3pass1);    
        SSI__c rule3failure2 = rule2pass3.clone();
        rule3failure2.VehicleUSvin__c = 'rule3pass-VIN';
        rule3failure2.Status__c = allvalid;
        rests.add(rule3failure2);   
        SSI__c rule3failure22 = rule2pass3.clone();
        rule3failure22.VehicleUSvin__c = 'rule3pass-VIN';
        rests.add(rule3failure22);     
        SSI__c rule3pass2 = rule2pass3.clone();
        rule3pass2.VehicleUSvin__c = 'rule3pass2-VIN';
        rule3pass2.InvoiceDate__c = d3;
        rests.add(rule3pass2);    
            
       // run rest rule
        Account dms2 = new Account(LastName = 'd1-customer-name1-8888a',PersonMobilePhone = '1301111111',PersonOtherPhone = '1301111122',ZipCode__c = '123456',
            Recordtypeid = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()
        );
        insert dms2;
        Vehicle__c veh2 = new Vehicle__c(UsVIN__c = 'NUNF1888899996666', EuroVIN__c = 'ASFOTI09842713RFDS');
        insert veh2;
        Vehicle_Relationship__c vr2 = new Vehicle_Relationship__c(Contact__c = dms2.Id, Vehicle_ID__c = veh2.Id);
        insert vr2;

      
       // insert periodList;        
        insert rests;
        
        Test.startTest();                         
        SSIDataClean.runRestRule(null, false);  
        Test.stopTest();
        system.assert(!accList.isEmpty());
    }
}