src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Lead__c.object
<CustomObject>
    <description>Lead: To link campaign and lead</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account, Person Account Manual Merge, Person Account Retail, Person Account Soft Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstTimeImported__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First-Time Imported</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Account_Id__c</fullName>
        <description>/* 
Created by: Mouse Liu 
Used by: Lead__c (US-Lead-15) 
Function: Supplement field used in UtilCampaignLead.cls
Used in: UtilCampaignLead.cls

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <formula>Lead__r.Contact__c</formula>
        <label>*Lead Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <label>Lead</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Lead</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Name_English__c</fullName>
        <label>Name (English)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>CAC_Lead_Status__c</fullName>
        <label>CAC Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Failed For 3 Days(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visited Showroom(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(CAC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(Dealer)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan to Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gave up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TA&amp;C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Need Follow Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Mobile__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.PersonMobilePhone, 
Collectioner_Name__r.MobilePhone
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile</label>
        <type>Text</type>
    </fields>

src/main/metadata/classes/UtilCampaignLeadTest.cls
@istest
public class UtilCampaignLeadTest {
  public static Account accobj;
  public static Contact contobj;
  public static Campaign camobj;
  public static Lead__c leadobj;
  public static Campaign_Lead__c camlead;
  public static List<Campaign_Lead__c> camleadlist;
  public static map<id,Campaign_Lead__c> campaignLeadOldMap;
  //public static String personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(); 
  public static String DealerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId(); 
  public static Id centmarcampRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Central Marketing Campaign').getRecordTypeId();
  public static Id salesleadRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('Aftersales Leads').getRecordTypeId();
  
  static void createTestData() {
    accobj = new Account();
    accobj.RecordTypeId = DealerRecordTypeId ;
    accobj.Name = 'testaccount';
    accobj.Phone = '000-0000-9642';
    accobj.MBK_Data_Source__c='Email';
    accobj.Mobile__c = '000-0000-9642';
    accobj.ZipCode__c= '1002347';
    insert accobj;
    system.debug('$$$$$$$$$$$$'+accobj);
    system.debug('$$$$$$$$$$$$'+accobj.id);
    
    contobj = new Contact();
    contobj.LastName = 'Testutilcampaignlead';
    contobj.Phone = '1212313';
    contobj.Title = 'contact title';
    contobj.Name_English__c = 'c';
    contobj.AccountId = accobj.Id;
    insert contobj;
    system.debug('$$$$$$$$$$$$'+contobj);
    system.debug('$$$$$$$$$$$$'+contobj.id);
    
    camobj = new Campaign();
    camobj.RecordTypeId = centmarcampRecordTypeId;
    camobj.Name = 'camptest1';
    camobj.Type = 'Other';
    camobj.Status = 'Planned';
    camobj.StartDate = System.today();
    camobj.EndDate = System.today();
    camobj.Campaign_Objectives__c = 'camobjectives';
    camobj.Description = 'testdescrip';
    insert camobj;
    system.debug('$$$$$$$$$$$$'+camobj);
    system.debug('$$$$$$$$$$$$'+camobj.id);
    
    leadobj = new Lead__c();
    leadobj.RecordTypeId = salesleadRecordTypeId;
    //leadobj.Contact__c = accobj.Id;
    leadobj.CAC_Lead_Status__c = 'Qualified';
    leadobj.Lead_Type__c = 'New Car';
    insert leadobj;
    system.debug('$$$$$$$$$$$$'+leadobj);
    system.debug('$$$$$$$$$$$$'+leadobj.id);
    
    camlead = new Campaign_Lead__c();
    camlead.Campaign__c = camobj.id;
    camlead.Lead__c = leadobj.id;
    camlead.FirstTimeImported__c = true;
    //camlead.Lead_Account_Id__c = accobj.Id;
    //insert camlead;
    system.debug('$$$$$$$$$$$$'+camlead);
    system.debug('$$$$$$$$$$$$'+camlead.id);
    
    camleadlist = new List<Campaign_Lead__c>();
    camleadlist.add(camlead);
    insert camleadlist;
    system.debug('$$$$$$$$$$$$'+camleadlist);
    
    //campaignLeadOldMap = new map<id,Campaign_Lead__c>();
    //campaignLeadOldMap.add(camlead);
    //insert campaignLeadOldMap;
    //system.debug('$$$$$$$$$$$$'+campaignLeadOldMap);
  } 
  public static testMethod void updateContactTest() {
    createTestData();
    test.startTest();
      //UtilCampaignLead ucl = new UtilCampaignLead();
      UtilCampaignLead.updateContact(camleadlist);
    test.stoptest();
    system.assertEquals(contobj.LastName,'Testutilcampaignlead');
  }
  public static testMethod void updateCampaignTitleAndNotesTest() {
    createTestData();
    test.startTest();
      UtilCampaignLead.updateCampaignTitleAndNotes(camleadlist);
    test.stoptest();
    system.assertEquals(contobj.LastName,'Testutilcampaignlead');
  }
  public static testMethod void beforeInsertEventsTest() {
    createTestData();
    test.startTest();
      UtilCampaignLead.beforeInsertEvents(camleadlist);
    test.stoptest();
    system.assertEquals(contobj.LastName,'Testutilcampaignlead');
  }
  /*public static testMethod void beforeUpdateEventsTest() {
    createTestData();
    test.startTest();
      UtilCampaignLead.beforeUpdateEvents(camleadlist,campaignLeadOldMap);
    test.stoptest();
    system.assertEquals(contobj.LastName,'Testutilcampaignlead');
  }*/
  public static testMethod void insertMembersTest() {
    createTestData();
    test.startTest();
      UtilCampaignLead.insertMembers(camleadlist);
    test.stoptest();
    system.assertEquals(contobj.LastName,'Testutilcampaignlead');
  }    
}