src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Attribute in Data Dictionary object Contact is &quot;Contact_CompanyName&quot;</description>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Link__c.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;) ,&apos;MY&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Address 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Block__c</fullName>
        <label>Block</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name_Native__c</fullName>
        <label>Company Name Native</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>Town</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Prefecture</label>
        <picklist>
            <picklistValues>
                <fullName>Hokkaido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aomori</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iwate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miyagi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamagata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukushima</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ibaraki</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tochigi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gunma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saitama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tokyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kanagawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niigata</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ishikawa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fukui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yamanashi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shizuoka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aichi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shiga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kyoto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Osaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wakayama</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TitleOfHonor__c</fullName>
        <label>TitleOfHonor</label>
        <picklist>
            <picklistValues>
                <fullName>To Person</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>To Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Post Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Record type for company addresses.</description>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer addresses.</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Address__c.object
    <fields>
        <fullName>Address_Line_1_Native__c</fullName>
        <label>Address Line 1 Native</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
    <fields>
        <fullName>Address_Line_2_Native__c</fullName>
        <label>Address Line 2 Native</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
    <fields>
        <fullName>Block_Native__c</fullName>
        <label>Block Native</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
    <fields>
        <fullName>City_Native__c</fullName>
        <label>City Native</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
    <fields>
        <fullName>District_Native__c</fullName>
        <label>Town Native</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
	<fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP', 
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'MY'), 'MY', 
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA'))))))</defaultValue>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata-au/objects/Address__c.object
    <fields>
        <fullName>Province_Native__c</fullName>
        <label>Prefecture Native</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>DMS_UserID__c</fullName>
        <label>DMS User ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/createRetailCopy.cls
public without sharing class createRetailCopy {

    public  Account account{get;set;}
    public  Account accList{get;set;}
    Public static String AccId{get;set;}
    public List<Address__c> ListAddress{set;get;}
    public List<Address__c> SelectedAdd{set;get;}
    public Id addId{get;set;} 
    public Id did{get;set;} 
    public  Boolean ShowHideError{set;get;}
    public List<Account_Link__c> Accountlinklist{get;set;}
    Public User  Usr{get;set;} 
    public List<Account> accc{set;get;}
    Public  Id DealeAccId{get;set;}
    public List<Contact> contactList{ get; set; }  
    public Account_Link__c newAlk;
    public List<Account_Link__c> InsertAlk; 
    public Account DealerID { get; set; }
    public User  CurrentUsr{set;get;}
    public List<Account> Dealeracc{set;get;}
    public static Id alkPerson_RecordTypeId = Schema.SObjectType.Account_Link__c.getRecordTypeInfosByName().get('Retail Person').getRecordTypeId();
    public static Id alkCompany_RecordTypeId = Schema.SObjectType.Account_Link__c.getRecordTypeInfosByName().get('Retail Company').getRecordTypeId();
    public static Id accPerson_RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    public static Id accCompany_RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
    public String MarketDiscriminator;
    // Constructor
    public createRetailCopy(ApexPages.StandardController controller) {
     AccId=ApexPages.currentPage().getParameters().get('id');
     ListAddress=new List<Address__c>();
     SelectedAdd=new List<Address__c>();
     InsertAlk=new List<Account_Link__c> ();
     account=new Account();
     ShowHideError=false; 
     
     CurrentUsr=[SELECT Market__c,DMS_UserID__c,IsPortalEnabled ,contactid,Id FROM User WHERE Id = :UserInfo.getUserId()];
     account = (Account)controller.getRecord();
     if(AccId!=null)
     {
      ListAddress= [select id,Name,Customer__c,Address_Type__c,ZipCode__c,Province__c ,Province_Native__c ,City__c,City_Native__c,District__c,District_Native__c ,Block__c ,Block_Native__c ,Address_Line_1__c,Address_Line_1_Native__c , Address_Line_2__c ,Address_Line_2_Native__c  ,Company_Name__c ,Company_Name_Native__c ,TitleOfHonor__c , Status__c ,Temp_ZipCode__c ,Temp_Address__c  FROM  Address__c where  Customer__c =:AccId];
     }
    
     system.debug('+++++++++++++'+account);
     system.debug('++++++++++++++'+AccId);
    MarketDiscriminator = 'JP';
    if(CurrentUsr.Market__c== 'KR'){
        MarketDiscriminator = CurrentUsr.Market__c; 
    }       

    } // Constructor  end
    
    
    //Method to selected Address  record Id
      public pageReference getSelectedAddress (){ 
    
           addId =ApexPages.currentPage().getParameters().get('idselected');  
           
           system.debug('+++++++++'+ addId );
         
    
      return null;
      
    }
    
  //Method to get selected dealer ID
      public void  getDealer(){
          Dealeracc=new List<Account>();
          AccId=ApexPages.currentPage().getParameters().get('id'); 
          // DealerID=ApexPages.currentPage().getParameters().get('DealerID');  
           accc=[Select id from account where id=:account.Main_Dealer__c and MD__c =: MarketDiscriminator];  
           System.debug('^&^&^&^&^&^&^&^ accc'+accc);
            System.debug('^&^&^&^&^&^&^&^ AccId '+AccId);
           System.debug('^&^&^ DealerID.Main_Dealer__c '+account.Main_Dealer__c);
      } //Method end
      
      
      // Method to Create retail copy
    Public void CreateRetailCopy()
    { 
     
    AccId=ApexPages.currentPage().getParameters().get('id');
    
   accList=[Select Id,Main_Dealer__c ,RecordtypeId from account where id=:AccId];
   accc=[Select id,Main_Dealer__c  from account where id=:account.Main_Dealer__c limit 1];
    system.debug('+++++++++'+ addId );
    System.debug('##################'+accc); 
    System.debug('#################'+ AccId);
    if(addId !=null)
    {
    SelectedAdd= [select id,Name,Customer__c,Address_Type__c,ZipCode__c,Province__c ,Province_Native__c ,City_Native__c,District__c,District_Native__c ,Block__c ,Block_Native__c ,Address_Line_1__c,Address_Line_1_Native__c , Address_Line_2__c ,Address_Line_2_Native__c  ,Company_Name__c ,Company_Name_Native__c ,TitleOfHonor__c , Status__c ,Temp_ZipCode__c ,Temp_Address__c  FROM  Address__c where id =:addId Limit 1];
    }
    CurrentUsr=[SELECT Market__c,DMS_UserID__c,IsPortalEnabled ,contactid,Id FROM User WHERE Id = :UserInfo.getUserId()];
 
 
  // For Dealer User Creating retail copy
    if(CurrentUsr.ContactId!=null)
    {
     Usr = [SELECT Market__c,contactid,IsPortalEnabled,Id,contact.AccountId FROM User WHERE Id = : UserInfo.getUserId() and User.Profile.UserLicense.Name='Partner Community']; 
    
    
     if(Usr.ContactId!=null)
     {
     contactList=[Select id,AccountId from Contact where id=:usr.ContactId];
     
            If(contactList!=null)
              {
              for(Contact con:contactList)
              {
              DealeAccId=con.AccountId;
              }
              }
    if(accList.RecordtypeId == accPerson_RecordTypeId)
    {
    Accountlinklist = [select id, fromRole__c, toRole__c,Retail_Delete_Flag__c from Account_Link__c WHERE fromRole__c=:DealeAccId and toRole__c =: AccId AND RecordTypeID =: alkPerson_RecordTypeId AND Retail_Delete_Flag__c = false];
    }
     if(accList.RecordtypeId == accCompany_RecordTypeId)
    {
    Accountlinklist = [select id, fromRole__c, toRole__c,Retail_Delete_Flag__c from Account_Link__c WHERE fromRole__c=:DealeAccId and toRole__c =: AccId AND RecordTypeID =: alkCompany_RecordTypeId AND Retail_Delete_Flag__c = false];
    }
    
    
     if(Accountlinklist ==null ||  Accountlinklist.isempty())
    {
    
     if(accList.RecordtypeId == accPerson_RecordTypeId)
    {     
     
    newAlk=new Account_Link__c ();
    newAlk.toRole__c = AccId;
    newAlk.Retail_Address_Reference__c=addId;
    newAlk.fromRole__c=DealeAccId;
    newAlk.RecordTypeId=alkPerson_RecordTypeId;
    InsertAlk.add(newAlk);
     
    }
    if(accList.RecordtypeId == accCompany_RecordTypeId)
    {     
     
     
    newAlk=new Account_Link__c ();
    newAlk.toRole__c = AccId;
    newAlk.Retail_Address_Reference__c=addId;
    newAlk.fromRole__c=DealeAccId;
    newAlk.RecordTypeId=alkCompany_RecordTypeId;
    InsertAlk.add(newAlk);
    System.debug('newAlk newAlk%%%%%%%'+newAlk);
     
    }
    } else if(Accountlinklist !=null)
    {
    ShowHideError=true;  
    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'Retail copy is already present'));
    }
   
    
    }
    }
    
    
    // For MBJ User Creating retail copy
    if(CurrentUsr.ContactId==null)
    { 
    //For MBJ User if user not selected  Dealer Outlet display error message
            if(account.Main_Dealer__c  ==null && account.Main_Dealer__c ==null)
            {    
              ShowHideError=true;                  
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please select Dealer'));
            }
            System.debug('CurrentUsr %%%%%%%'+CurrentUsr);
    if(accList.RecordtypeId == accPerson_RecordTypeId)
    {
    Accountlinklist = [select id, fromRole__c, toRole__c,Retail_Delete_Flag__c from Account_Link__c WHERE fromRole__c=:account.Main_Dealer__c and toRole__c =: AccId AND RecordTypeID =: alkPerson_RecordTypeId AND Retail_Delete_Flag__c = false];
    }
     if(accList.RecordtypeId == accCompany_RecordTypeId)
    {
    Accountlinklist = [select id, fromRole__c, toRole__c,Retail_Delete_Flag__c from Account_Link__c WHERE fromRole__c=:account.Main_Dealer__c and toRole__c =: AccId AND RecordTypeID =: alkCompany_RecordTypeId AND Retail_Delete_Flag__c = false];
    }
    
   System.debug('#$#$#$####$'+account.Main_Dealer__c);
   
         
    if(Accountlinklist ==null ||  Accountlinklist.isempty() && account.Main_Dealer__c  !=null)
    {
    
     if(accList.RecordtypeId == accPerson_RecordTypeId)
    {     
     
    newAlk=new Account_Link__c ();
    newAlk.toRole__c = AccId;
    newAlk.Retail_Address_Reference__c=addId;
    newAlk.fromRole__c=account.Main_Dealer__c;
    newAlk.RecordTypeId=alkPerson_RecordTypeId;
    InsertAlk.add(newAlk);
     
    }
    if(accList.RecordtypeId == accCompany_RecordTypeId)
    {     
     
     
    newAlk=new Account_Link__c ();
    newAlk.toRole__c = AccId;
    newAlk.Retail_Address_Reference__c=addId;
    newAlk.fromRole__c=account.Main_Dealer__c;
    newAlk.RecordTypeId=alkCompany_RecordTypeId;
    InsertAlk.add(newAlk);
    System.debug('newAlk newAlk%%%%%%%'+newAlk);
     
    }
    } else if(Accountlinklist !=null && account.Main_Dealer__c !=null )
    {
     ShowHideError=true;  
    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'Retail copy is already present'));
    }
    
    }  
    if(InsertAlk!=null && InsertAlk.size()>0)
    {
    insert InsertAlk;
    }
    
    }

}