src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_DMS_CRM_Code__c</fullName>
        <description>Used for dealer mapping</description>
        <label>Dealer DMS CRM Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Task__c.object
<CustomObject>
    <fields>
        <fullName>Related_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Dealer</label>
         <lookupFilter>
            <active>true</active>
			<booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please select the proper dealer account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>			
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>IntegrationAPI</value>
            </filterItems>
            <infoMessage>Search and select dealer account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retail Tasks</relationshipLabel>
        <relationshipName>Retail_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Retail Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Tasks</pluralLabel>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <label>Contract</label>
    </recordTypes>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/RetailTaskSharingWrapService.cls
**
** Wrap service for retail tasks to share.
** 1. Shares "Contract" retail tasks to active users of active dealers, who have both read access to the related person account and vehicle.
** 2. Shares "Retail Activity" retail tasks to active users of the related dealer and the active dealers with the same CRM Code.
** 3. Shares "Service" retail tasks to active users of the related dealer and the active dealers with the same CRM Code.
** 
** Created By: CC
** Date: 2014-6-15
Modified By : Sneha Chail
Modified date : 10-oct-2015
**/
public with sharing class RetailTaskSharingWrapService {
    public RetailTaskSharingWrapService() {
    }

    /**
    ** Gets all the required fields of retail tasks then wraps those retail tasks by record type.
    **/
    public List<SharingWrapper> wrapRetailTasks(List<Retail_Task__c> retailTasks) {       
        List<SharingWrapper> wrappers = new List<SharingWrapper>();
        List<Retail_Task__c> contracts = new List<Retail_Task__c>();
        List<Retail_Task__c> retailActivities = new List<Retail_Task__c>();
        List<Retail_Task__c> services = new List<Retail_Task__c>();                          
        
        for(Retail_Task__c retailTask : retailTasks) {       
            if(UtilRecordType.getRecordTypeNameByName('Retail_Task__c','Contract').equalsIgnoreCase('Contract')){
                    contracts.add(retailTask);
                }
             else if(UtilRecordType.getRecordTypeNameByName('Retail_Task__c','Retail Activity').equalsIgnoreCase('Retail Activity') && String.isNotBlank(retailTask.Related_Dealer__r.Dealer_DMS_CRM_Code__c)){
                  retailActivities.add(retailTask);                
                 } 
             else { 
                   services.add(retailTask);
                 }
              }          
                  
      // Adding all records having Contract recordtype to the list 
       if(!contracts.isEmpty()){
            wrappers.addAll(wrapContracts(contracts));
          }
      // Adding all records having Retail Activity recordtype to the list 
       if(!retailActivities.isEmpty()){
            wrappers.addAll(wrapRetailActivities(retailActivities));
          }
       // Adding all records having Services recordtype to the list 
       if(!services.isEmpty()){
           wrappers.addAll(wrapServices(services));
          }           
       return wrappers;
    }
    /**
    ** Wraps "Contract" retail tasks. 
    ** Users to share are decidied by their access to contrats' vehicle and dealer.
    **/
    public List<SharingWrapper> wrapContracts(List<Retail_Task__c> contracts) {
        UserService userService = new UserService();
        Map<Id, Set<Id>> contract2Users = userService.mapRetailTaskContract2Users(contracts);

        return SharingWrapperService.wrapSharings(contract2Users, Schema.Retail_Task__Share.RowCause.Contract_Share__c,UtilConstant.read_Access);
    }

    /**
    ** Wraps "Service" retail tasks.
    **/
    public List<SharingWrapper> wrapServices(List<Retail_Task__c> services) {
        return wrapRetailTasks(Schema.Retail_Task__Share.RowCause.Service_Share__c, services,UtilConstant.read_Access);
    }

    /**
    ** Wraps "Retail Activity" retail tasks.
    **/
    public List<SharingWrapper> wrapRetailActivities(List<Retail_Task__c> retailActivities) {
        return wrapRetailTasks(Schema.Retail_Task__Share.RowCause.Retail_Activity_Share__c, retailActivities,UtilConstant.read_Access);
    }

    private List<SharingWrapper> wrapRetailTasks(String rowCause, List<Retail_Task__c> retailTasks, String accessLevel) {
        UserService userService = new UserService();
        Map<String, Set<Id>> crmCode2Users = userService.mapCrmCode2Users(retailTasks);
        Map<Id, Set<Id>> retailTask2Users = new Map<Id, Set<Id>>();
        for(Retail_Task__c retailTask : retailTasks) {
            if(crmCode2Users.get(retailTask.Related_Dealer__r.Dealer_DMS_CRM_Code__c) != null){
                retailTask2Users.put(retailTask.Id, crmCode2Users.get(retailTask.Related_Dealer__r.Dealer_DMS_CRM_Code__c));
            }
        }

        return SharingWrapperService.wrapSharings(retailTask2Users, rowCause, accessLevel);
    }
}