src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: GS Code of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_GCcode &quot;</description>
        <label>Dealer GC Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <description>Added based on the GSSN interface mapping

Feb-18-2012: Added by Rob and Falk</description>
        <label>Dealer ND Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Outlet</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer in regards of complaint 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Primary Case Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Dealer)</relationshipLabel>
        <relationshipName>Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <label>MD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/caseShareBatch.cls
global class caseShareBatch implements Database.Batchable<sobject>,database.stateful
{
    public static List<string> dealerGCCodeList = new list<string>();
    public static List<string> dealerNDCodeList = new List<string>();
    public static Map<string,string> groupGcCodeMap = new Map<string,string>();
    public static Map<string,string> groupNdCodeMap = new Map<string,string>();
    public static List<CaseShare> caseShareList = new List<CaseShare>();
    
  global database.QueryLocator start(database.BatchableContext bc)
    { 
        string query = 'Select Id,Case_Dealer__c,Case_Dealer__r.Dealer_GC_Code__c,Case_Dealer__r.Dealer_ND_Code__c from Case where Case_Dealer__r.Dealer_GC_Code__c in '+ '(\'GC0037971\',\'GC0011433\',\'GC0037972\',\'GC0011422\',\'GC0011432\',\'GC0011423\',\'GC0037973\',\'GC0037970\',\'GC0011430\',\'GC0037969\',\'GC0011434\') '+ 'and Case_Dealer__c != null and MD__C =' +'\'KR\''+ '';
        return database.getQueryLocator(query);
    }
    global void execute(database.BatchableContext bc,List<case> scope)
    {
    
           system.debug('+++++'+scope.size());
        dealerGCCodeList.add('GC0037971');
        dealerGCCodeList.add('GC0037972');
        dealerGCCodeList.add('GC0011433');
        dealerGCCodeList.add('GC0011434');
        dealerGCCodeList.add('GC0011430');
        dealerGCCodeList.add('GC0011422');
        dealerGCCodeList.add('GC0037969');
        dealerGCCodeList.add('GC0011432');
        dealerGCCodeList.add('GC0011423');
        dealerGCCodeList.add('GC0037973');
        dealerGCCodeList.add('GC0037970');
        Set<string> ndCodeList = New Set<String>();
        
        List<Account> accntList = [select Id, Dealer_ND_Code__c, Dealer_GC_Code__c, Dealer_Type__c from Account where Recordtype.Name = 'Dealer' and Dealer_GC_Code__c =:dealerGCCodeList and MD__c = 'KR'];
        for(Account acc : accntList){
        
           ndCodeList.add(acc.Dealer_ND_Code__c);
        }
        
        system.debug('+++++++++++++'+ndCodeList);
        List<group> grpList = [select Id, Name, Type from Group where Name in :ndCodeList];
        if(!accntList.isEmpty() && accntList != null && !grpList.isEmpty() && grpList != null)
        {
            for(group gr : grpList)
            {
                for(Account acc : accntList)
                {
                    if(acc.Dealer_Type__c == 'Company' && gr.Name == acc.Dealer_ND_Code__c)
                    {
                        groupGcCodeMap.put(acc.Dealer_GC_Code__c,gr.Id);
                    }
                    
                    if(acc.Dealer_Type__c == 'outlet' &&gr.Name == acc.Dealer_ND_Code__c)
                    {
                        groupNdCodeMap.put(acc.Dealer_ND_Code__c,gr.Id);
                    }
                }
            }
        }
        
                For(Case cas : scope)
                {
                if((groupNdCodeMap.get(cas.Case_Dealer__r.Dealer_ND_Code__c))!=null && groupNdCodeMap!=null)
            {
                                CaseShare casShre = new CaseShare();
                                casShre.CaseAccessLevel = 'Edit';
                                casShre.CaseId = cas.Id;
                                casShre.UserOrGroupId = groupGcCodeMap.get(cas.Case_Dealer__r.Dealer_ND_Code__c);
                                caseShareList.add(casShre);
                }
                
                if((groupGcCodeMap.get(cas.Case_Dealer__r.Dealer_GC_Code__c))!=null && groupGcCodeMap!=null )
            {
            CaseShare casShre = new CaseShare();
                                casShre.CaseAccessLevel = 'Edit';
                                casShre.CaseId = cas.Id;
                                casShre.UserOrGroupId = groupGcCodeMap.get(cas.Case_Dealer__r.Dealer_GC_Code__c);
                                caseShareList.add(casShre);
                }
                }

if(!caseShareList.isEmpty() && caseShareList != null)
{
                insert caseShareList;
}
    }
    global void finish(database.BatchableContext bc)
    {
        
    }
}