src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag to allow data sharing 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_DoCdata&quot;</description>
        <label>Allow Data Sharing</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Choice Yet</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Recall__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate whether the customer has vehicle for recall</description>
        <label>Recall</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow Data Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assigned_Date_Time__c</fullName>
        <label>Assigned Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentMileage__c</fullName>
        <label>CurrentMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EuroVIN__c</fullName>
        <label>EuroVIN</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NextMileage__c</fullName>
        <label>NextMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <label>UsVIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleRel_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VehicleRel No.</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Vehicle_Relationship__c.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle_Relationship__c</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Mobile__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.PersonMobilePhone, 
Collectioner_Name__r.MobilePhone
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile</label>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>MB brand</description>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB saloon car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB business car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maybach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRUCKS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CurrentMileage__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: The current mileage 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is "Vehicle_CurrentMileage“</description>
        <label>CurrentMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EuroVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Euro VIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is”Vehicle_EuroVIN“</description>
        <externalId>true</externalId>
        <label>EuroVIN</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstRegistrationDate__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Date of the first ever registration of the vehicle 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_FirstRegistrationDate“</description>
        <label>FirstRegistrationDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NextMileage__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Vehicle mileage of the next service 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_NextMileage“</description>
        <label>NextMileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchase_Month__c</fullName>
        <description>Month of invoice date</description>
        <label>Purchase Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recall__c</fullName>
        <defaultValue>false</defaultValue>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag whatever the vehicle has been recalled 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_Recall“</description>
        <label>Recall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Vehicle UsVIN 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle is ”Vehicle_UsVIN“</description>
        <externalId>true</externalId>
        <label>UsVIN</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>MB</fullName>
        <active>true</active>
        <description>MB vehicle</description>
        <label>MB</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recall__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsVIN__c</fullName>
        <formula>Vehicle_ID__r.UsVIN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UsVIN</label>
        <type>Text</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle_Relationship__c.object
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The flag to identify if this record can be shared with MBJ</description>
        <label>Allow Data Sharing</label>
        <type>Checkbox</type>
    </fields>

src/main/metadata-au/objects/Vehicle_Relationship__c.object
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>

src/classes/UtilLeadTest.cls
@isTest
public With Sharing class UtilLeadTest
{
    public static List<Account> accList;
    public static Account accObj;
    public static Vehicle__c vehicleObj;
    public static Vehicle_Relationship__c vehicleRelationshipObj;
    public static Lead__c leadObj;
    public static List<Lead__c> leadlst;
    public static testmethod void updateLeadForDataSharing_test()
    {
        createData();
        Test.startTest();
            List<Lead__c> leadlstCustom = new List<Lead__c>();
            leadlstCustom.add(leadlst.get(0));
            UtilLead.updateLeadForDataSharing(leadlstCustom);
            UtilLead.updateRelatedVehicleRelFields(leadlstCustom);
            system.assertNotEquals(leadlstCustom ,null);
        Test.stopTest();
    }
    public static testmethod void beforeInsert_updateEvents_test()
    {
        createData();
        Test.startTest();
            List<Lead__c> leadlstCustom = new List<Lead__c>();
            leadlstCustom.add(leadlst.get(1));
            map<Id,Lead__c> leadOldmap = new map<Id,Lead__c>();
            leadOldmap.put(leadlst.get(1).Id,leadlst.get(1));
            UtilLead.beforeInsert_updateEvents(leadlstCustom,leadOldmap,true,false);
            leadlstCustom.clear();
            leadOldmap.clear();
            leadlstCustom.add(leadlst.get(2));
            leadOldmap.put(leadlst.get(2).Id,leadlst.get(2));
            UtilLead.beforeInsert_updateEvents(leadlstCustom,leadOldmap,false,true);
            system.assertNotEquals(leadlstCustom ,null);
            
            //UtilLead.updateRelatedVehicleRelFields(leadlstCustom);
        Test.stopTest();
    }
    public static testmethod void utilProfile_Test(){
        Test.startTest();
            UtilProfile.getProfileId('System Administrator');
           try{
            UtilProfile.getProfileId('');
            
            }catch(Exception e){
                system.assertNotEquals(e.getMessage(),null);
            }
            try{
              UtilProfile.getProfileId('Test');
            }catch(Exception e){
                system.assertNotEquals(e.getMessage(),null);
            }
        Test.stopTest();
        
    }
     public static testmethod void UtilSobject_test()
    {
        createData();
        Test.startTest();
            List<Lead__c> errorlist = new List<Lead__c>();
            errorlist.add(leadlst.get(0));
            
            UtilSobject.updateSobjects(errorlist);
            errorlist.clear();
            errorlist.add(leadlst.get(0));
            UtilSobject.updateSobjects(errorlist);
            errorlist.clear();
            UtilSobject.updateSobjects(errorlist);
            system.assertNotEquals(errorlist,null);
          
        Test.stopTest();
    }
    public static testmethod void UtilSobjectDelete_test()
    {
        createData();
        Test.startTest();
            List<Lead__c> errorlist = new List<Lead__c>();
            errorlist.add(leadlst.get(0));
            UtilSobject.deleteSobjects(errorlist);
            errorlist.clear();
            UtilSobject.deleteSobjects(errorlist);
            system.assertNotEquals(errorlist,null);
          
        Test.stopTest();
    }
     public static testmethod void UtilSobjectInsert_test()
    {
        createData();
        Test.startTest();
            Id salesRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('Sales Leads').getRecordTypeId();
            leadObj = new Lead__c(Current_Vehicle__c = vehicleObj.Id,Contact__c = accList.get(2).Id,VehicleRel_No__c = vehicleRelationshipObj.Id,RecordTypeId = salesRecordTypeId,Assigned_Date_Time__c = system.now());
            List<Lead__c> errorlist = new List<Lead__c>();
            errorlist.add(leadObj);
            UtilSobject.insertSobjects(errorlist);
            errorlist.clear();
            UtilSobject.insertSobjects(errorlist);
            system.assertNotEquals(errorlist,null);
          
        Test.stopTest();
    }
    
    public static void createData(){
        accList = new List<Account>();
        Id recordTypeAccObjId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
        accObj = new Account(RecordTypeId = recordTypeAccObjId,Name = 'Mercedez',
        Mobile__c ='01234567895');
        accList.add(accObj);
        Id recordTypeAccDealerObjId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        accObj = new Account(RecordTypeId = recordTypeAccDealerObjId,Name = 'Mercedez',
        Mobile__c ='01234567896');
        accList.add(accObj);
        Id recordTypeAccPersonAccountObjId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        accObj = new Account(RecordTypeId = recordTypeAccPersonAccountObjId,LastName = 'Mercedez',Allow_Data_Sharing__c='Yes',Phone ='09874760605',
        Mobile__c ='01234567892');
        accList.add(accObj);
        insert accList;
        Id recordTypeVehicleObjId = Schema.SObjectType.Vehicle__c.getRecordTypeInfosByName().get('MB').getRecordTypeId();
        vehicleObj = new Vehicle__c(RecordTypeId = recordTypeVehicleObjId,Brand__c = 'Maybach',UsVIN__c ='tlikkkkkkkklllll8',Recall__c = FALSE,
        EuroVIN__c = '12345678901111111',CurrentMileage__c=5000,NextMileage__c=6000,FirstRegistrationDate__c = date.today(),Purchase_Month__c ='02', Model__c = 'R350L 4MATIC', Class__c = 'A-Class', Purchase_Year__c = '2004',RegistrationNo__c = '12345');
        insert vehicleObj;
        
        vehicleRelationshipObj = new Vehicle_Relationship__c(Registration_Number__c = 'tlikkkkkkkklllll',Vehicle_ID__c = vehicleObj.Id,Selling_Dealer__c = accList.get(1).Id,Purchase_Date__c=system.today(),Contact__c =accList.get(2).Id );
        insert vehicleRelationshipObj;
        leadlst = new List<Lead__c>();
        leadObj = new Lead__c(Current_Vehicle__c = vehicleObj.Id,Contact__c = accList.get(2).Id,VehicleRel_No__c = vehicleRelationshipObj.Id,Assigned_Date_Time__c = system.now());
        leadlst.add(leadObj);
        Id aftersalesRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('Aftersales Leads').getRecordTypeId();
        leadObj = new Lead__c(Current_Vehicle__c = vehicleObj.Id,Contact__c = accList.get(2).Id,VehicleRel_No__c = vehicleRelationshipObj.Id,RecordTypeId = aftersalesRecordTypeId,Assigned_Date_Time__c = system.now());
        leadlst.add(leadObj);
        Id salesRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('Sales Leads').getRecordTypeId();
        leadObj = new Lead__c(Current_Vehicle__c = vehicleObj.Id,Contact__c = accList.get(2).Id,VehicleRel_No__c = vehicleRelationshipObj.Id,RecordTypeId = salesRecordTypeId,Assigned_Date_Time__c = system.now());
        leadlst.add(leadObj);
        insert leadlst;
       
        
        
    }
}