src/main/metadata/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-retrieve/objects/Account.object
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <recordTypes>
        <fullName>Dealer1</fullName>
        <active>true</active>
        <description>Recordtype for dealer</description>
        <label>Dealer1</label>
    </recordTypes>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer addresses.</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Address__c.object
	<fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP', 
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'MY'), 'MY', 
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA'))))))</defaultValue>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/CallOutHandlerSettingDFW__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>callout time value for webservice call</description>
    <fields>
        <fullName>DEFAULT_CALLOUT_TIME__c</fullName>
        <label>DEFAULT_CALLOUT_TIME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAX_CALLOUT_TIME__c</fullName>
        <label>MAX_CALLOUT_TIME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CallOutHandlerSettingDFW</label>
</CustomObject>

src/main/metadata/objects/DM_Material__c.object
<CustomObject>
    <description>Case: Track the Material used by DM Request</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>DM Material</label>
    <nameField>
        <label>DM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Material</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata/objects/DM_Request__c.object
<CustomObject>
    <description>Case: Track the DM Request. This is also used by Campaign for bulk DM Request</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field is created for DM request related list in account detail page.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>DM Request</label>
    <nameField>
        <displayFormat>DMR-{000000}</displayFormat>
        <label>DM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DM Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Functionality_Access_Master__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <externalId>true</externalId>
        <label>Module Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PermissionSet_Ids__c</fullName>
        <description>Ids of permission sets will be stored separating by ';'</description>
        <label>PermissionSet Ids</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Permission_Sets__c</fullName>
        <description>Name of all permission sets will be saved separating by ';'</description>
        <label>Permission Sets</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Functionality Access Master</label>
    <nameField>
        <displayFormat>FAM-{0000}</displayFormat>
        <label>Functionality Access Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functionality Access Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_Code__c</fullName>
        <externalId>true</externalId>
        <label>Market Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Persona__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Functionality_Access__c</fullName>
        <label>Functionality Access</label>
        <referenceTo>Functionality_Access_Master__c</referenceTo>
        <relationshipName>Market_Access_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market_Access__c</fullName>
        <label>Market Access</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>Market_Access_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Market_Access__r.Market_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonaName__c</fullName>
        <label>Persona Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProfileId__c</fullName>
        <label>ProfileId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profiles__c</fullName>
        <label>Profiles</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Persona</label>
    <nameField>
        <displayFormat>MAJ-{0000}</displayFormat>
        <label>Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persona</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/SystemSettingsDFW__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Logging framework</description>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Info__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Log_Purge__c</fullName>
        <label>Log Purge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Warning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Warning</label>
        <type>Checkbox</type>
    </fields>
    <label>SystemSettingsDFW</label>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata-au/objects/User.object
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>ChangesMadeInAssignedPersona__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to check if any changes made in the persona after assigned to user</description>
        <label>ChangesMadeInAssignedPersona</label>
        <type>Checkbox</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Persona_Assigned__c</fullName>
        <label>Persona Assigned</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/classes/TriggerDMRequestTriggerHandlerTRTest.cls
@isTest
public with sharing class TriggerDMRequestTriggerHandlerTRTest{

public static User user1;
public static User user2;
//public static User user3;
public static Market__c market_Obj;
public static Functionality_Access_Master__c functionality_access_master_Obj ;
public static id dealerType =RecordTypeAccessService.getRecordTypeid('Account','Dealer');                                                                                        
public static Persona__c persona_Obj; 

static testMethod void testTriggerDMRequestTriggerHandlerMY1() {
    PermissionSet ps = new PermissionSet();
    ps.Name = 'Test';
    ps.Label = 'Test';
    insert ps;
    
    CustomPermission cps = [SELECT ID From CustomPermission WHERE MasterLabel =: Label.TRGeneric ];

  SetupEntityAccess sea = new SetupEntityAccess();
  sea.ParentId = ps.Id;
  sea.SetupEntityId = cps.id;
  insert sea;
  
    Profile p1 = [select id, name from profile where Name='System Administrator' limit 1];
    user1 = new User(Alias = 'standt', Email='testUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p1.Id, Market__c='TR',
        TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@testorg.com'+String.valueof(DateTime.now().getTime()), isActive=true);
  //DMLManagerService.insertAsSystem(user1 );
   
  System.runAs (user1) {  
    CallOutHandlerSettingDFW__c cs=new CallOutHandlerSettingDFW__c();
    cs.DEFAULT_CALLOUT_TIME__c='1000';
    cs.MAX_CALLOUT_TIME__c='5000';
    cs.Name='CalloutValues';
    insert cs;
    
    SystemSettingsDFW__c sysSet = new SystemSettingsDFW__c();
    sysSet.Debug__c =true;
    sysSet.Error__c = true;
    sysSet.Info__c= true;
    sysSet.Warning__c = true;
    sysSet.Log_Purge__c =10;
    sysSet.Name=p1.Name;
    DMLManagerService.insertAsSystem(sysSet);

    market_Obj = new Market__c(Market_Code__c = 'TR', Market__c = 'Turkey');
    Insert market_Obj; 
    functionality_access_master_Obj = new Functionality_Access_Master__c(Description__c = '12', Module_Name__c = 'Modul230', PermissionSet_Ids__c = ps.id, Permission_Sets__c = ps.name);
    Insert functionality_access_master_Obj; 
    persona_Obj = new Persona__c(Market_Access__c = market_Obj.id, Functionality_Access__c = functionality_access_master_Obj.id, Active__c = true, PersonaName__c = 'IntegrationPerso111', ProfileId__c = p1.id , Profiles__c = p1.name);
    Insert persona_Obj; 
   user2 = new User(Username = 'TestUser7776920170921083316@codecoverage.com', LastName = 'LastName527', 
   Email = 'Email22@test.com', EmailPreferencesAutoBcc = false, EmailPreferencesAutoBccStayInTouch = false, 
   EmailPreferencesStayInTouchReminder = false, Alias = 'Alias474', CommunityNickname = 'null1', IsActive = true, 
   TimeZoneSidKey = 'Pacific/Kiritimati', LocaleSidKey = 'sq_AL', ReceivesInfoEmails = false, ReceivesAdminInfoEmails = false, EmailEncodingKey = 'UTF-8', 
   ProfileId = '00e28000000qHycAAE', LanguageLocaleKey = 'en_US', ChangesMadeInAssignedPersona__c = true, Persona_Assigned__c = 'IntegrationPerso111',Market__c='TR');
   }
    
    System.runAs (user2) {
    Trigger__c TriggerDMRequestTR= new Trigger__c(Name='TriggerDMRequestTR',Trigger_Name__c='TriggerDMRequest',Trigger_Handler__c='TriggerDMRequestTriggerHandlerTR',update__c=True,insert__c=True,delete__c=True,after__c=True,before__c=True,enabled__c=True,Market__c='TR');
    insert TriggerDMRequestTR;
    test.starttest();
        List<String> AccountFields=new List<String>();
        AccountFields.add('Lastname');
        AccountFields.add('Firstname');
        AccountFields.add('Mobile__c');
        AccountFields.add('Market__c');
        List<Account> AccountFieldsList=DataFactoryServices.createRecords('Account',AccountFields,'',1);
        AccountFieldsList[0].RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        AccountFieldsList[0].Lastname='Lastname1';
        AccountFieldsList[0].Firstname='Lastname1';
        AccountFieldsList[0].Mobile__c='+609856321478';
        AccountFieldsList[0].Market__c='TR';   
        insert AccountFieldsList;
        List<String> AddressFields=new List<String>();
        AddressFields.add('Address_Line_1__c');
        AddressFields.add('Address_Line_2__c');
        AddressFields.add('Address_Line_3__c');
        AddressFields.add('Address_Type__c');
        AddressFields.add('City__c');
        AddressFields.add('Province__c');
        AddressFields.add('Market__c');
        List<Address__c> AddressFieldsList=DataFactoryServices.createRecords('Address__c',AddressFields,'A',1);
        AddressFieldsList[0].Address_Line_1__c='Lastname1';
        AddressFieldsList[0].Address_Line_2__c='+6003123654789';
        AddressFieldsList[0].Address_Line_3__c='+60825634789541';
        AddressFieldsList[0].Address_Type__c='Home';
        AddressFieldsList[0].Province__c='+609856321478';
        AddressFieldsList[0].City__c='+609856321478';
        AddressFieldsList[0].Market__c='TR';
        AddressFieldsList[0].ZipCode__c='12345';
        AddressFieldsList[0].Customer__c=AccountFieldsList[0].id;  
		AddressFieldsList[0].country__c='Turkey';
        insert AddressFieldsList;
        List<String> DMReqFields=new List<String>();
        DMReqFields.add('Customer_Name__c');
        DMReqFields.add('Sending_Address__c');
        DMReqFields.add('Channel__c');        
        List<DM_Request__c> DMReqFieldsList=DataFactoryServices.createRecords('DM_Request__c',DMReqFields,'',1);
        DMReqFieldsList[0].Customer_Name__c=AccountFieldsList[0].id;
        DMReqFieldsList[0].Sending_Address__c='Home';
        DMReqFieldsList[0].Channel__c='Letter';
        insert DMReqFieldsList;
        DMReqFieldsList[0].Delivery_Type__c='1';
        update DMReqFieldsList;       
        test.stoptest();
          
        }                     
    }            
    
static testMethod void testTriggerDMRequestTriggerHandlerTR2() {
    PermissionSet ps = new PermissionSet();
    ps.Name = 'Test';
    ps.Label = 'Test';
    insert ps;
    
    CustomPermission cps = [SELECT ID From CustomPermission WHERE MasterLabel =: Label.TRGeneric ];
    CustomPermission cps1 = [SELECT ID From CustomPermission WHERE MasterLabel =: Label.TRRetail ];

   SetupEntityAccess sea1 = new SetupEntityAccess();
  sea1.ParentId = ps.Id;
  sea1.SetupEntityId = cps1.id;
  insert sea1;                                                                                                 

  SetupEntityAccess sea = new SetupEntityAccess();
  sea.ParentId = ps.Id;
  sea.SetupEntityId = cps.id;
  insert sea;
  group grp = new group(name = 'TR123456', developername = 'TR123456');
    insert grp;
  
  Account dealer1;                                                                 
  
    Profile p1 = [select id, name from profile where Name='IntegrationAPI' limit 1];
    user1 = new User(Alias = 'standt', Email='testUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p1.Id, Market__c='TR',
        TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@testorg.com'+String.valueof(DateTime.now().getTime()), isActive=true);
  //DMLManagerService.insertAsSystem(user1 );
  TriggerUtil.userCreate=false;  
  System.runAs (user1) {  
    
    CallOutHandlerSettingDFW__c cs=new CallOutHandlerSettingDFW__c();
    cs.DEFAULT_CALLOUT_TIME__c='1000';
    cs.MAX_CALLOUT_TIME__c='5000';
    cs.Name='CalloutValues';
    insert cs;
    
    SystemSettingsDFW__c sysSet = new SystemSettingsDFW__c();
    sysSet.Debug__c =true;
    sysSet.Error__c = true;
    sysSet.Info__c= true;
    sysSet.Warning__c = true;
    sysSet.Log_Purge__c =10;
    sysSet.Name=p1.Name;
    DMLManagerService.insertAsSystem(sysSet);
 dealer1 =  new Account(Dealer_DMS_CRM_Code__c = 'DealerCode',Market__c='TR', Individual_Home_Phone__c='02202123626', RecordTypeId = dealerType, Name = 'test dealer1',Dealer_GC_Code__c = 'Test123',Dealer_nd_Code__C='123456');
        insert dealer1;
    market_Obj = new Market__c(Market_Code__c = 'TR', Market__c = 'Turkey');
    Insert market_Obj; 
    functionality_access_master_Obj = new Functionality_Access_Master__c(Description__c = '12', Module_Name__c = 'Modul230', PermissionSet_Ids__c = ps.id, Permission_Sets__c = ps.name);
    Insert functionality_access_master_Obj; 
    persona_Obj = new Persona__c(Market_Access__c = market_Obj.id, Functionality_Access__c = functionality_access_master_Obj.id, Active__c = true, PersonaName__c = 'IntegrationPerso111', ProfileId__c = p1.id , Profiles__c = p1.name);
    Insert persona_Obj; 
     user2 = new User(Username = 'TestUser7776920170921083316@codecoverage.com', LastName = 'LastName527', Email = 'Email22@test.com',  Alias = 'Alias474', CommunityNickname = 'null1', IsActive = true, TimeZoneSidKey = 'Pacific/Kiritimati', LocaleSidKey = 'sq_AL',EmailEncodingKey = 'UTF-8', ProfileId = p1.id, LanguageLocaleKey = 'en_US', Active__c = false, Notification_Account_Finance_Update__c = false, Notification_Retail_Copy_Created__c = false, ChangesMadeInAssignedPersona__c = true, Persona_Assigned__c = 'IntegrationPerso111');
    insert user2;
      PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = user2.id;
        psa.PermissionSetId = ps.Id;
        insert psa;    
    }
     TriggerUtil.userCreate=false; 
    System.runAs (user2) {
       
    Trigger__c TriggerDMRequestMY= new Trigger__c(Name='TriggerDMRequestTR',Trigger_Name__c='TriggerDMRequest',Trigger_Handler__c='TriggerDMRequestTriggerHandlerTR',update__c=True,insert__c=True,delete__c=True,after__c=True,before__c=True,enabled__c=True,Market__c='TR');
    insert TriggerDMRequestMY;
     TriggerUtil.userCreate=false;     
    test.starttest();
        List<String> AccountFields=new List<String>();
        AccountFields.add('Lastname');
        AccountFields.add('Mobile__c');
        AccountFields.add('Market__c');
        List<Account> AccountFieldsList=DataFactoryServices.createRecords('Account',AccountFields,'',1);
        AccountFieldsList[0].RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        AccountFieldsList[0].Lastname='Lastname1';
        AccountFieldsList[0].Mobile__c='+609856321478';
        AccountFieldsList[0].Market__c='TR';   
        insert AccountFieldsList;
        List<String> AddressFields=new List<String>();
        AddressFields.add('Address_Line_1__c');
        AddressFields.add('Address_Line_2__c');
        AddressFields.add('Address_Line_3__c');
        AddressFields.add('Address_Type__c');
        AddressFields.add('City__c');
        AddressFields.add('Province__c');
        AddressFields.add('Market__c');
        List<Address__c> AddressFieldsList=DataFactoryServices.createRecords('Address__c',AddressFields,'A',2);
          AddressFieldsList[0].Address_Line_1__c='Lastname1';
        AddressFieldsList[0].Address_Line_2__c='+6003123654789';
        AddressFieldsList[0].Address_Line_3__c='+60825634789541';
        AddressFieldsList[0].Address_Type__c='Home';
        AddressFieldsList[0].Province__c='+609856321478';
        AddressFieldsList[0].City__c='+609856321478';
        AddressFieldsList[0].Market__c='TR';
        AddressFieldsList[0].ZipCode__c='12345';
        AddressFieldsList[0].Customer__c=AccountFieldsList[0].id;  
		AddressFieldsList[0].country__c='Turkey';
       // insert AddressFieldsList;
        AddressFieldsList[1].Address_Line_1__c='Lastname1';
        AddressFieldsList[1].Address_Line_2__c='+6003123654789';
        AddressFieldsList[1].Address_Line_3__c='+60825634789541';
        AddressFieldsList[1].Address_Type__c='Business';
        AddressFieldsList[1].Province__c='+609856321478';
        AddressFieldsList[1].City__c='+609856321478';
        AddressFieldsList[1].Market__c='TR';
        AddressFieldsList[1].ZipCode__c='12345';
        AddressFieldsList[1].Customer__c=AccountFieldsList[0].id;  
		AddressFieldsList[1].country__c='Turkey';
        insert AddressFieldsList;
        List<String> DMReqFields=new List<String>();
        DMReqFields.add('Customer_Name__c');
        DMReqFields.add('Sending_Address__c');
        DMReqFields.add('Channel__c');
        DMReqFields.add('Market__c');
         DM_Material__c dmtrl1 = new DM_Material__c(name = 'testmaterial1');
            insert dmtrl1;
             DM_Material__c dmtrl2 = new DM_Material__c(name = 'testmaterial2');
            insert dmtrl2;
             DM_Material__c dmtrl3 = new DM_Material__c(name = 'testmaterial3');
            insert dmtrl3;
        List<DM_Request__c> DMReqFieldsList=DataFactoryServices.createRecords('DM_Request__c',DMReqFields,'',1);
        DMReqFieldsList[0].Customer_Name__c=AccountFieldsList[0].id;
        DMReqFieldsList[0].Sending_Address__c='Home';
        DMReqFieldsList[0].Channel__c='Letter';
        DMReqFieldsList[0].Market__c='TR';
        insert DMReqFieldsList;
        DMReqFieldsList[0].Delivery_Type__c='1';
        update DMReqFieldsList; 
        DMReqFieldsList[0].Sending_Address__c='Business';
        DMReqFieldslIst[0].Assigned_Dealer__c=dealer1.id;
        DMReqFieldslIst[0].Expected_DM_Material1__c=dmtrl1.id;
        DMReqFieldslIst[0].Expected_DM_Material2__c=dmtrl2.id;
        DMReqFieldslIst[0].Expected_DM_Material3__c=dmtrl3.id;
        DMReqFieldslIst[0].Actual_DM_Material1__c=dmtrl1.id;
        DMReqFieldslIst[0].Actual_DM_Material2__c=dmtrl2.id;
        DMReqFieldslIst[0].Actual_DM_Material3__c=dmtrl3.id;
        update DMReqFieldsList;          
        test.stoptest();
          
        }                     
    }    
    
    
    
        
static testMethod void testTriggerDMRequestTriggerHandlerTY3() {
    PermissionSet ps = new PermissionSet();
    ps.Name = 'Test';
    ps.Label = 'Test';
    insert ps;
    
    CustomPermission cps = [SELECT ID From CustomPermission WHERE MasterLabel =: Label.TRGeneric ];
    CustomPermission cps1 = [SELECT ID From CustomPermission WHERE MasterLabel =: Label.TRRetail ];

  SetupEntityAccess sea = new SetupEntityAccess();
  sea.ParentId = ps.Id;
  sea.SetupEntityId = cps.id;
  insert sea;
   SetupEntityAccess sea1 = new SetupEntityAccess();
  sea1.ParentId = ps.Id;
  sea1.SetupEntityId = cps1.id;
  insert sea1;
    group grp = new group(name = 'TR123456', developername = 'TR1234562');
    insert grp;
  
    Profile p1 = [select id, name from profile where Name='System Administrator' limit 1];
    userRole r=[select id from userRole where Name='MBMY Management'];
    user1 = new User(Alias = 'standt', Email='testUser@testorg.com', userroleid=r.id,
        EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p1.Id, Market__c='TR',
        TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@testorg.com'+String.valueof(DateTime.now().getTime()), isActive=true);
  //DMLManagerService.insertAsSystem(user1 );
     Account dealer1,dealer;
  TriggerUtil.userCreate=false;  
  System.runAs (user1) {  
     dealer1 =  new Account(Dealer_DMS_CRM_Code__c = 'DealerCode',Market__c='TR', Individual_Home_Phone__c='02202123626', RecordTypeId = dealerType, Name = 'test dealer1',Dealer_GC_Code__c = 'Test123',Dealer_nd_Code__C='123456');
        insert dealer1;
        Contact dealerContact = new Contact(FirstName = 'Test',Market__c='TR', Lastname = 'Amit', AccountId = dealer1.Id, Email = 'test@test.com');
        insert dealerContact;
      dealer =  new Account(Dealer_DMS_CRM_Code__c = 'DealerCode', Market__c='TR',Individual_Home_Phone__c='02202123626', RecordTypeId = dealerType, Name = 'test dealer',Dealer_GC_Code__c = 'Test123',Dealer_nd_Code__C='12345');
        insert dealer;

        Account dealerAccount =  new Account(Dealer_DMS_CRM_Code__c = 'DealerCode',Market__c='TR', Individual_Home_Phone__c='02202123626', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(UtilTestData.ACCOUNT_RT_DEALER).getRecordTypeId(), Name = 'test dealer1',Dealer_GC_Code__c = 'Test123',Dealer_nd_Code__C='12345');
        insert dealerAccount;
        Contact c1=new Contact(FirstName = 'Test',Lastname = 'Contact',AccountId=dealerAccount.Id,Market__c='TR');
        insert c1;
    CallOutHandlerSettingDFW__c cs=new CallOutHandlerSettingDFW__c();
    cs.DEFAULT_CALLOUT_TIME__c='1000';
    cs.MAX_CALLOUT_TIME__c='5000';
    cs.Name='CalloutValues';
    insert cs;
    
    SystemSettingsDFW__c sysSet = new SystemSettingsDFW__c();
    sysSet.Debug__c =true;
    sysSet.Error__c = true;
    sysSet.Info__c= true;
    sysSet.Warning__c = true;
    sysSet.Log_Purge__c =10;
    sysSet.Name=p1.Name;
    DMLManagerService.insertAsSystem(sysSet);
    profile d=[select id from profile where name='Malaysia Dealer User'];
    market_Obj = new Market__c(Market_Code__c = 'TR', Market__c = 'Turkey');
    Insert market_Obj; 
    functionality_access_master_Obj = new Functionality_Access_Master__c(Description__c = '12', Module_Name__c = 'Modul230',
    PermissionSet_Ids__c = ps.id, Permission_Sets__c = ps.name);
    Insert functionality_access_master_Obj; 
    persona_Obj = new Persona__c(Market_Access__c = market_Obj.id, Functionality_Access__c = functionality_access_master_Obj.id, 
    Active__c = true, PersonaName__c = 'IntegrationPerso111', ProfileId__c = p1.id , Profiles__c = p1.name);
    Insert persona_Obj; 
    user2 = new User(contactid=dealerContact.id,Username = 'TestUser70921083316@codsecoverage.com', LastName = 'LastName527',
     Email = 'Email22@test.com', EmailPreferencesAutoBcc = false, EmailPreferencesAutoBccStayInTouch = false, 
     EmailPreferencesStayInTouchReminder = false, Alias = 'Alias474', CommunityNickname = 'null1', IsActive = true,
      TimeZoneSidKey = 'Pacific/Kiritimati', LocaleSidKey = 'sq_AL', ReceivesInfoEmails = false, ReceivesAdminInfoEmails = false, 
      EmailEncodingKey = 'UTF-8', ProfileId = p1.id, LanguageLocaleKey = 'en_US', UserPermissionsMarketingUser = false, 
             UserPreferencesFavoritesWTShown = false, IsPortalSelfRegistered = false, DigestFrequency = 'D', 
             DefaultGroupNotificationFrequency = 'P', Active_Permission_Set__c = false, Active__c = false,
              Notification_Account_Finance_Update__c = false, Notification_Retail_Copy_Created__c = false,
               ChangesMadeInAssignedPersona__c = true, Persona_Assigned__c = 'IntegrationPerso111',Market__c='TR');
    user2.profileid=d.id;
    insert user2;
     PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = user2.id;
        psa.PermissionSetId = ps.Id;
        insert psa;
    }
     TriggerUtil.userCreate=false; 
    System.runAs (user2) {
       
    Trigger__c TriggerDMRequestMY= new Trigger__c(Name='TriggerDMRequestTR',Trigger_Name__c='TriggerDMRequest',Trigger_Handler__c='TriggerDMRequestTriggerHandlerTR',update__c=True,insert__c=True,delete__c=True,after__c=True,before__c=True,enabled__c=True,Market__c='TR');
    insert TriggerDMRequestMY;
     TriggerUtil.userCreate=false;     
    test.starttest();
        List<String> AccountFields=new List<String>();
        AccountFields.add('Lastname');
        AccountFields.add('Firstname');
        AccountFields.add('Mobile__c');
        AccountFields.add('Market__c');
        List<Account> AccountFieldsList=DataFactoryServices.createRecords('Account',AccountFields,'',1);
        AccountFieldsList[0].RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        AccountFieldsList[0].Lastname='Lastname1';
        AccountFieldsList[0].Firstname='Firstname1';
        AccountFieldsList[0].Mobile__c='+609856321478';
        AccountFieldsList[0].Market__c='TR';   
        insert AccountFieldsList;
        List<String> AddressFields=new List<String>();
        AddressFields.add('Address_Line_1__c');
        AddressFields.add('Address_Line_2__c');
        AddressFields.add('Address_Line_3__c');
        AddressFields.add('Address_Type__c');
        AddressFields.add('City__c');
        AddressFields.add('Province__c');
        AddressFields.add('Market__c');
        List<Address__c> AddressFieldsList=DataFactoryServices.createRecords('Address__c',AddressFields,'A',2);
                                                           
        AddressFieldsList[0].Address_Line_1__c='Lastname1';
        AddressFieldsList[0].Address_Line_2__c='+6003123654789';
        AddressFieldsList[0].Address_Line_3__c='+60825634789541';
        AddressFieldsList[0].Address_Type__c='Home';
        AddressFieldsList[0].Province__c='+609856321478';
        AddressFieldsList[0].City__c='+609856321478';
        AddressFieldsList[0].Market__c='TR';
        AddressFieldsList[0].ZipCode__c='12345';
        AddressFieldsList[0].Customer__c=AccountFieldsList[0].id;  
        AddressFieldsList[0].Country__c='Turkey';  
        // insert AddressFieldsList;
        AddressFieldsList[1].Address_Line_1__c='Lastname1';
        AddressFieldsList[1].Address_Line_2__c='+6003123654789';
        AddressFieldsList[1].Address_Line_3__c='+60825634789541';
        AddressFieldsList[1].Address_Type__c='Business';
        AddressFieldsList[1].Province__c='+609856321478';
        AddressFieldsList[1].City__c='+609856321478';
        AddressFieldsList[1].Market__c='TR';
        AddressFieldsList[1].ZipCode__c='12345';
        AddressFieldsList[1].Country__c='Turkey';  
        AddressFieldsList[1].Customer__c=AccountFieldsList[0].id;                          
        insert AddressFieldsList;
        List<String> DMReqFields=new List<String>();
        DMReqFields.add('Customer_Name__c');
        DMReqFields.add('Sending_Address__c');
        DMReqFields.add('Channel__c');
        DMReqFields.add('Market__c');
        List<DM_Request__c> DMReqFieldsList=DataFactoryServices.createRecords('DM_Request__c',DMReqFields,'',1);
        DMReqFieldsList[0].Customer_Name__c=AccountFieldsList[0].id;
        DMReqFieldsList[0].Sending_Address__c='Home';
        DMReqFieldsList[0].Channel__c='Letter';
        DMReqFieldsList[0].Market__c='TR';
        insert DMReqFieldsList;
        DMReqFieldsList[0].Delivery_Type__c='1';
        update DMReqFieldsList;       
        DMReqFieldsList[0].Sending_Address__c='Business';
        DMReqFieldslIst[0].Assigned_Dealer__c=dealer1.id;
        update DMReqFieldsList;                                              
        test.stoptest();
          
        }                     
    }                
}