src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: GS Code of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_GCcode &quot;</description>
        <label>Dealer GC Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Sub_Type__c</fullName>
        <label>Campaign Sub Type</label>
        <picklist>
            <picklistValues>
                <fullName>Crosspoint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales and After Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance - &gt;  Prematurity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales -&gt; Crosspoint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <description>This field can be used to track the progress of the execution campaign life cycle</description>
        <label>Campaign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Execution_Start_Date__c</fullName>
        <description>This field is used to capture the start date of the execution campaign</description>
        <label>Execution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Execution_Type__c</fullName>
        <description>Used only for Campaign Execution record type. To defined the execution channel.</description>
        <label>Execution Type</label>
        <picklist>
            <picklistValues>
                <fullName>OB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Mercedes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
		IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
		IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',IF(ISPICKVAL($User.Market__c, 'KR'), 'KR',IF(ISPICKVAL($User.Market__c, 'TH'), 'TH','NA')))))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segmentation_Base__c</fullName>
        <description>This setting field is used to capture if the segmentation (either for wholesales segmentation in Marketing Cloud or for retail in SFDC segmentation) is done on the customer, vehicle or contract data basis</description>
        <label>Segmentation Base</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Lead__c.object
<CustomObject>
    <description>Lead: To link campaign and lead</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <label>Lead</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>Campaign Leads</relationshipLabel>
        <relationshipName>Campaign_Leads</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Lead</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Campaign Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to refer the related retail campaign execution record</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to refer the related Customer/Contact  record</description>
        <label>Contact Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campaign member (Preferred Dealer)</relationshipLabel>
        <relationshipName>Campaign_member1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to set the status of the campaign member</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will have Vehicle reference ID from Marketing Cloud</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_Member__c.object
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Members (Campaign)</relationshipLabel>
        <relationshipName>Campaign_Members3</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/CampaignLeadCreationBasedoncmmWs.cls
/***********************************************************************************
Created By          :    Venky  
Created Date        :    2018.08.15
Company             :    NTT Data,Inc.
Usage               :     This Batch class will Cretae Whole sale and retail campaign leads based on campaign member records.
JIRA NO             :         SFDCJP-3453                                          
Bug JIRA NO         :     

MODIFICATION DETAILS:

1. Modified By      :    
Modifide Date    :    
************************************************************************************/
global class CampaignLeadCreationBasedoncmmWs implements Database.Batchable<sObject> ,Database.stateful  {

       private static final String salesRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get(UtilConstant.SALES_LEADS).getRecordTypeId();
     global Database.QueryLocator start(Database.BatchableContext bc){
       
      return Database.getQueryLocator([Select id,Status__c,Campaign_ID__c,market__c,Campaign_ID__r.Segmentation_Base__c,Vehicle__c,Preferred_Dealer__r.Dealer_GC_Code__c,Contact_Id__c,Campaign_ID__r.Child_Campaign_Status__c,Campaign_ID__r.Execution_type__c ,Campaign__c,Campaign_ID__r.Execution_Start_Date__c,Campaign_ID__r.Parent.Campaign_Sub_Type__c,Campaign__r.Parent.Campaign_Sub_Type__c from Campaign_member__c where Campaign_ID__c !=null and market__c='JP' and Contact_Id__c!=null and Campaign_ID__r.Execution_Start_Date__c=today and Market__c='JP' and (Campaign_ID__r.Execution_type__c !='My Mercedes' and Campaign_ID__r.Execution_type__c !='Lead' and Campaign_ID__r.Execution_type__c !='Survey') and (Campaign_ID__r.Parent.Campaign_Sub_Type__c='Sales' OR Campaign_ID__r.Parent.Campaign_Sub_Type__c='Sales and After Sales')]);
    }
     //execute method 
    global void execute(Database.BatchableContext bc,List<Campaign_Member__c> scope){
        Set<Id> Accid=new Set<Id>();
        List<Lead__c> ListLead=new List<Lead__c>();
        List<Campaign_Lead__c> insertcamlead=new List<Campaign_Lead__c>();
        Map<Id,Campaign_member__c> updatecammember=new Map<id,Campaign_member__c>();
        for(Campaign_Member__c cmm:scope)
        {
            if(cmm.Contact_Id__c !=null)
            {
                Accid.add(cmm.Contact_Id__c);
            }
        }
        if(Accid !=null)
        {
        ListLead=[Select id,MD__c ,AfterSales_Vehicle__c,Assigned_Dealer__r.Dealer_GC_Code__c,CAC_Lead_Status__c,Recordtypeid,Dealer_Lead_Status__c,contact__c from Lead__c where  Md__c='JP' and Recordtypeid=:salesRecordTypeId  and Contact__c !=null and Contact__c=:Accid and Dealer_Lead_Status__c !='Lost' and Dealer_Lead_Status__c !='Purchased(Only Non BDC)' and Dealer_Lead_Status__c !='Order Placed' and CAC_Lead_Status__c = 'Allocated'];    
        }
        
        if(ListLead !=null && ListLead.size()>0)
        {
            for(Campaign_Member__c cm:scope)
            {                
                    for(Lead__c le:ListLead)
                        {
                            if(le.contact__c == cm.Contact_Id__c)
                            {
                                Campaign_Lead__c newcamlead =new Campaign_Lead__c();
                                            newcamlead.lead__c=le.id;
                                             newcamlead.Campaign__c=cm.Campaign_ID__c;
                                             newcamlead.Campaign_Member__c=cm.Id;  
                                             insertcamlead.add(newcamlead);
                            }  
                            if(cm.Preferred_Dealer__r.Dealer_GC_Code__c == le.Assigned_Dealer__r.Dealer_GC_Code__c)
                            {
                                cm.Convert_To_Lead_Flag__c=true;
                                cm.Status__c='Responded';
                                updatecammember.put(cm.id,cm);
                            }
                            if(cm.Preferred_Dealer__r.Dealer_GC_Code__c != le.Assigned_Dealer__r.Dealer_GC_Code__c)
                            {
                                cm.Convert_To_Lead_Flag__c=true;
                                cm.Convert_By_Others__c=true;  
                                cm.Status__c='Responded'; 
                                 updatecammember.put(cm.id,cm);
                            }
                            
                        }                 
            }
            
        }
        if(insertcamlead !=null)
        {
            database.insert(insertcamlead);
        }
        if(updatecammember !=null)
        {
            Database.update(updatecammember.values(),false);
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
}