src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_DMS_CRM_Code__c</fullName>
        <description>Used for dealer mapping</description>
        <label>Dealer DMS CRM Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Marketing_Manager__c</fullName>
        <label>Dealer Marketing Manager</label>
        <length>500</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata4au/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Dealer_Marketing_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Permission set: annual sales plans, sales and marketing activities (joint marketing campaigns and organise), aftermarket annual plan, aftermarket activities, best campaign, Toolbox, information center, distributor points, the report</inlineHelpText>
        <label>Dealer Marketing Manager</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Assigned_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Assigned_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <recordTypes>
        <fullName>Retail_Sales_Leads</fullName>
        <active>true</active>
        <label>Retail Sales Leads</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Mobile__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.PersonMobilePhone, 
Collectioner_Name__r.MobilePhone
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile</label>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <label>Trigger</label>
</CustomObject>

src/classes/LeadSharingTest.cls
@isTest
private With Sharing class LeadSharingTest {
    
    private static Account dealer;
    private static Account contact;
    private static Lead__c lead;
    
    static {
        RecordType dealerType = [select Id from RecordType where SObjectType = 'Account' and DeveloperName = 'Dealer' limit 1];
        dealer =  new Account(Dealer_DMS_CRM_Code__c = 'DealerCode', RecordTypeId = dealerType.Id, Name = 'test dealer', MBK_Data_Source__c ='Email');
        insert dealer;

        Contact dealerContact = new Contact(FirstName = 'Test', Lastname = 'Amit', AccountId = dealer.Id, Email = 'test@test.com', Dealer_Marketing_Manager__c = true);
        insert dealerContact;
        
        contact = (Account)UtilTestData.createSobject(new Account(Mobile__c ='0001234567'), 
                UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);

        RecordType retailLeadType = [select Id, developername from recordtype where sobjecttype = 'lead__c' and developername = 'Retail_Sales_Leads'];
        lead = new Lead__c(Assigned_Dealer__c = dealer.Id, Contact__c = contact.Id, RecordTypeId = retailLeadType.Id);
        insert lead;
    }
    
    @isTest 
    static void testWrapLeads() {
        List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
        insert updatecustomsettings;

        Test.startTest();
        LeadSharingWrapService wrapService = new LeadSharingWrapService();
        List<SharingWrapper> wrapLeads=wrapService.wrapLeads(new List<Lead__c>{lead});
        Test.stopTest();
        system.assertNotEquals(null, wrapLeads);
    }
    
}