src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: GS Code of dealer 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_GCcode &quot;</description>
        <label>Dealer GC Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Lead_Gate_Keeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Mouse Liu 
Used by: Lead__c (US-Lead-15) 
Function: Used in Email Template

Used in: 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>*Dealer Lead Gate Keeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <description>Added based on the GSSN interface mapping

Feb-18-2012: Added by Rob and Falk</description>
        <label>Dealer ND Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <fields>
        <fullName>Relevant_Central_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relevant Central Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Retail Campaigns</relationshipLabel>
        <relationshipName>Retail_Central_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;,IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_GC_Code__c</fullName>
        <formula>Contact.Account.Dealer_GC_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer GC Code</label>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Dealer_ND_Code__c</fullName>
        <formula>Contact.Account.Dealer_ND_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer ND Code</label>
        <type>Text</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/DealerPickerControllerGeneric.cls
public with Sharing class DealerPickerControllerGeneric {
    private  String campaignId{set;get;} 
    public List<DealersList> dList{set;get;}
    public static Id dealerAccount = RecordTypeAccessService.getRecordTypeId('Account','Dealer');
    public list<Account> dealerList{set;get;}
    List<Retail_Campaign__Share> accessonRetailcamp{Set;get;}
    Retail_campaign__C retcamp=new Retail_Campaign__c();
    public boolean displayPopup{set;get;}
    String market=[Select market__c from User where id=:UserInfo.getUserId()][0].market__c;
    List<campaignShare> campaignToShare=new List<campaignShare>();
    public DealerPickerControllerGeneric(){
    campaignId=ApexPages.currentPage().getParameters().get('CampaignId');//'a160l000000LgYf';//= 
    //system.debug('&&&&&&&'+campaignId);
       dealerList =new List<Account>();
        accessonRetailcamp=new List<Retail_Campaign__Share>();
        dealerList=[select id,Name,Dealer_Nd_code__c,Dealer_Gc_code__C,Dealer_Lead_Gate_Keeper__c,Mobile__c from Account where RecordTypeId=:dealerAccount and MD__c=:market and Dealer_Nd_code__c!=''];
        dList=new List<DealersList>();
        for(Account dealerrec:dealerList){
            dList.add(new DealersList(dealerrec));
        }
    }
    public class DealersList{
        public Account dealerlist{set;get;}
        public Boolean isSelected{set;get;}
        public DealersList(Account acc){
            this.dealerlist=acc;
            this.isSelected=false;
            }
        }
    public PageReference cancel() {
        return new PageReference('/' + campaignId);
        }
    public Retail_Campaign__Share shareRetailcampaignRecords(){
        Retail_Campaign__Share alshare=new Retail_Campaign__Share ();
        alshare.AccessLevel='EDIT';
        alshare.RowCause = Schema.Retail_Campaign__Share.RowCause.Manual;
        alshare.ParentId = campaignID;
        return alshare;  
    }
    public void showPopup() {        
        displayPopup = true;    
    }
    public PageReference SharetoDealers(){
        Retail_Campaign__c camp=new Retail_Campaign__c();
        camp=[select id,Relevant_Central_Campaign__c from Retail_Campaign__c where id=:campaignId limit 1];
        //String market=[Select market__c from User where id=:UserInfo.getUserId()][0].market__c;
        List<Retail_campaign__share> retailcampaignstosharewithdealergroups=new List<Retail_campaign__Share>();
        List<Account> retailcampaingstosharewithdealers=new List<Account>();
        Set<String> dealerndCode=new Set<String>();
        Set<String> dealerndcodetosendEmails=new Set<String>();
        Set<Group> groupName=new Set<Group>();
        Set<Group> actualgrouptoshare=new Set<Group>();
        for(DealersList listdealer:dList){
            if(listdealer.isSelected){
                retailcampaingstosharewithdealers.add(listdealer.dealerlist);
                String grpName=market+listdealer.dealerlist.dealer_nd_code__c;
                dealerndCode.add(grpName);
            } 
        }
        if(dealerndCode.size()>0){
            List<group> gnames=[select Id, Name, Type from Group where Name IN:dealerndCode];
            groupName.addAll(gnames);
            accessonRetailcamp=[select id, Accesslevel, userOrgroupid from Retail_Campaign__Share where parentid=:campaignId];
            Set<Retail_Campaign__Share> accssonRetailcampset=new Set<Retail_campaign__share>();
            accssonRetailcampset.addAll(accessonRetailcamp);
            if(groupName.size()>0&&accssonRetailcampset.size()>0){
                for(Group g:groupName){
                    for(Retail_Campaign__Share retshare:accssonRetailcampset){
                        if(g.id!=retshare.userOrgroupid&&!String.valueof(retshare.UserOrGroupId).Startswith('00G')){
              actualgrouptoshare.add(g);
                            dealerndcodetosendEmails.add(g.name);
                        }
                    }
                }
            }
            else{
                actualgrouptoshare.addAll(groupName);
            }
            
        }
        for(Group gp:actualgrouptoshare ){ 
        
            Retail_campaign__Share sharerec=new Retail_Campaign__Share();
            sharerec=shareRetailcampaignRecords();
            sharerec.UserOrGroupId=gp.id;
            retailcampaignstosharewithdealergroups.add(sharerec);
            //system.debug('@@@@'+retailcampaignstosharewithdealergroups.size());
            if(camp.Relevant_Central_Campaign__c!=null){
            CampaignShare campShare=new CampaignShare();
            campShare.UserOrGroupId=gp.id;
            campShare.CampaignId=camp.Relevant_Central_Campaign__c;
            campShare.CampaignAccessLevel='READ';
            campShare.RowCause=CampaignShare.RowCause.Manual;
            campaignToShare.add(campShare);
            }
        }
        if(retailcampaignstosharewithdealergroups.size()>0){
            try{
                database.insert(retailcampaignstosharewithdealergroups,false);
                if(market=='MY'){
                    sendEmailNotificationtoDealerMY(actualgrouptoshare,dealerndcodetosendEmails);
                }
            }
            Catch(Exception e){
                throw new applicationException(e.getMessage());
            }
        }
        if(campaignToShare.size()>0){
            try{
            database.insert(campaignToShare,false);
            //sendEmailNotificationtoDealer(actualgrouptoshare,dealerndcodetosendEmails);
            }
            Catch(Exception e){
                throw new applicationException(e.getMessage());
            }
        }
        return new PageReference('/' + campaignId);
        
    }
    public void sendEmailNotificationtoDealerMY(Set<Group> groupnames, Set<String> dealerndcode){
         Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
         String commubaseurl='';
         boolean flag;        
         String communityName='Dealer Community MB Malaysia';    //market specific community name
         List<Network>  myNetwork = [SELECT Id,Name FROM Network];
         retcamp=[select name,id,ownerid from Retail_Campaign__C where id =:campaignID];
         for(Network net:myNetwork){
               if(net.name==communityName){
               flag=true;
               commubaseurl=Network.getLoginUrl(net.id)+'/'+campaignId;
               break;
           }
       }
       //MY specific email template
       EmailTemplate temp=(EmailTemplate)[select id,Body,subject from emailtemplate where name=:'MBMY_Retail_Campaign_Planning_And_Design_Notification_to_Dealers' limit 1];
       message.setTemplateid(temp.id);
       message.setTargetObjectId(retcamp.ownerid);
       message.setSaveAsActivity(false);
       string body=temp.Body.replace('{!Retail_Campaign__c.Name}',retcamp.name).replace('{!Retail_Campaign__c.Link} ',commubaseurl);
       message.setPlainTextBody(body);
       List<User> usrlist=new List<User>();
       usrlist=[select id,name,Email from User where dealer_nd_code__C IN:dealerndcode];
       Set<User> userset=new Set<USer>();
       userset.addall(usrlist);
       List<String> ToAdd=new List<String>();
        for(USer usr:userset){
            ToAdd.add(usr.email);
        }
        message.setToAddresses(ToAdd);
        try{
            Messaging.SendEmailResult[] m2=Messaging.SendEmail(new Messaging.SingleEmailMessage[]{message});
        }
        catch(Exception e){
           throw new applicationException(e.getMessage()); 
        }
    }
    public PageReference cancelURLS(){
        return new PageReference(URL.getSalesforceBaseUrl().toExternalForm()+'/apex/DealerPicker?core.apexpages.request.devconsole=1');
    }
    
}