src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active Flag for this dealer
Attribute in Data Dictionary object Dealer is &quot;Dealer_ActiveFlag&quot;</description>
        <label>Dealer Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_DMS_CRM_Code__c</fullName>
        <description>Used for dealer mapping</description>
        <label>Dealer DMS CRM Code 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Lead_Gate_Keeper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Mouse Liu 
Used by: Lead__c (US-Lead-15) 
Function: Used in Email Template

Used in: 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>*Dealer Lead Gate Keeper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Account Links</relationshipLabel>
        <relationshipName>Account_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fromRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links (Contact to Contact)</relationshipLabel>
        <relationshipName>Account_Links1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>toRole__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Links(External Link)</relationshipLabel>
        <relationshipName>Account_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer in regards of complaint 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Primary Case Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Dealer)</relationshipLabel>
        <relationshipName>Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used by Central Complaint Case. Need Clarification</description>
        <label>Vehicle Relationship</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account must be the same as Vehicle Relationship Account</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Vehicle_Relationship__c.Contact__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle_Relationship__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/*
Created by:  Chris.Huang
Used by:  Chris.Huang
Function:
Used in: Page Layouts, Reports 

Modify History
Modify By: 
Modify Reason: 
*/</description>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata4au/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Dealer_Complaint_Gate_Keeper__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Permission set:</inlineHelpText>
        <label>Dealer Complaint Gate Keeper</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dealer_Lead_Gate_Keeper__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Permission set: clues</inlineHelpText>
        <label>Dealer Lead Gate Keeper</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To indicates which dealer owns the vehicle relationship</description>
        <label>Owner Dealer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationship (Owner Dealer)</relationshipLabel>
        <relationshipName>Vehicle_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-todo/classes/TestBatchSharingPersonAccountOfComplaint.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBatchSharingPersonAccountOfComplaint {

    static Id recordTypeRetail = 
        Schema.SObjectType.Vehicle_Relationship__c.getRecordTypeInfosByName().get('Vehicle Relationship Retail').getRecordTypeId();

    static List<Account> accounts = new List<Account>();
    static List<Contact> contacts = new List<Contact>();
    static List<Vehicle__C> cars = new List<Vehicle__C>();
    static List<Vehicle_Relationship__c> vehicleRelates = 
            new List<Vehicle_Relationship__c>();
    static List<User> newUsers = new List<User>();  
    static List<Account> dealers = new List<Account>();
    static User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
    static List<Profile> profileIds = [
                Select Id 
                From Profile 
                Where Name ='Dealer-Complaint Manager'];

    @isTest
    static void testA() {
        // TO DO: implement unit test
        //initialData();
      
        List<Account> dealerst = new List<Account>();
        Map<String, Sobject> dealerA = createDealer('KL');
        dealerst.add((Account)dealerA.get('Account'));
        Map<String, Sobject> dealerB = createDealer('KL');
        dealerst.add((Account)dealerB.get('Account'));
        Map<String, Sobject> dealerC = createDealer('AF');
        dealerst.add((Account)dealerC.get('Account'));        
        /**

        Map<String, Sobject> dealerD = createDealer('AF');
        dealerst.add((Account)dealerD.get('Account'));        
        Map<String, Sobject> dealerE = createDealer('DE');
        dealerst.add((Account)dealerE.get('Account'));        
        Map<String, Sobject> dealerF = createDealer('ED');
        dealerst.add((Account)dealerF.get('Account'));        
*/
        Test.StartTest();
        
        List<Account> accountsT = new List<Account>();
        for(integer i = 0; i< 2; i++) {
            Account personAccountA = (Account)UtilTestData.createSobject(new Account(), 
                    UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
            accountsT.add(personAccountA);
                        
            Case MBcomplaint = (Case)UtilTestData.createSobject(new Case(), 
                    UtilTestData.CASE_RT_MB_COMPLAINT);
            
            //Case fireObj = new Case();
            MBcomplaint.AccountId = personAccountA.id;
            MBcomplaint.Case_Dealer__C = dealerst[i].id;
            update MBcomplaint;

        }
        
        system.debug('ready to excuteBatch');
                    
        BatchSharingAccountOfComplaint batch1 = new BatchSharingAccountOfComplaint();
        ID batchprocessid = Database.executeBatch(batch1);
        system.debug(batchprocessid);
        //id bLeadKeeperId = dealerB.get('LeadKeeper').id;
        Test.StopTest();
        
        system.assertEquals(1, [select id from AccountShare where AccountId = :accountsT[0].id and userorgroupid = :dealerB.get('LeadKeeper').id].size());
        system.assertEquals(0, [select id from AccountShare where AccountId = :accountsT[0].id and userorgroupid = :dealerC.get('LeadKeeper').id].size());
        

    }
/**
    @isTest
    static void TestShareCompalintPersonAccountToGateKeeper() {
        // TO DO: implement unit test
        //initialData();
        
        Map<String, Sobject> dealerA = createDealer('KL');
        Map<String, Sobject> dealerB = createDealer('KL');
        Map<String, Sobject> dealerC = createDealer('AF');

        Test.StartTest();
        Account personAccountA = (Account)UtilTestData.createSobject(new Account(), 
                UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
                        
        Case MBcomplaint = (Case)UtilTestData.createSobject(new Case(), 
                UtilTestData.CASE_RT_MB_COMPLAINT);
        
        //Case fireObj = new Case();
        MBcomplaint.AccountId = personAccountA.id;
        MBcomplaint.Case_Dealer__C = dealerA.get('Account').id;
        
        update MBcomplaint;
        
        id bLeadKeeperId = dealerB.get('LeadKeeper').id;
        
        system.assertEquals(1, [select id from AccountShare where AccountId = :personAccountA.id and userOrgroupId = :bLeadKeeperId].size());
        
        Test.StopTest();
    }

/**
    @isTest
    static void TestShareAccountLinkPersonAccountToDealer() {
        // TO DO: implement unit test
        //initialData();
        
        Map<String, Sobject> dealerA = createDealer('KL');
        Map<String, Sobject> dealerB = createDealer('KL');
        Map<String, Sobject> dealerC = createDealer('AF');

        Test.StartTest();
        Account personAccountA = (Account)UtilTestData.createSobject(new Account(), 
                UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
        Account personAccountB = (Account)UtilTestData.createSobject(new Account(), 
                UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
                                        
        Account_Link__c accountLink = new Account_Link__c();
        
        //Case fireObj = new Case();
        accountLink.fromRole__c = personAccountA.id;
        accountLink.toRole__c = personAccountB.id;
        accountLink.Name = 'PA-DMS-ABCKL-001XXX';
        
        insert accountLink;
        
        Map<id, User> dealerUser = new Map<Id, User>([select id from User where AccountId = :dealerA.get('Account').id or Accountid = :dealerB.get('Account').id]);
        
        system.assertEquals(8, [select id from AccountShare where AccountId = :personAccountA.id and userOrgroupId in :dealerUser.keyset() ].size());
        
        Test.StopTest();
    }
    
    @isTest
    static void TestShareVRPersonAccountToDealer() {
        // TO DO: implement unit test
        //initialData();
        
        Map<String, Sobject> dealerA = createDealer('KL');
        Map<String, Sobject> dealerB = createDealer('KL');
        Map<String, Sobject> dealerC = createDealer('AF');

        Test.StartTest();
        Account personAccountA = (Account)UtilTestData.createSobject(new Account(), 
                UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
        Account personAccountB = (Account)UtilTestData.createSobject(new Account(), 
                UtilTestData.ACCOUNT_RT_PERSON_ACCOUNT);
                                        
        Vehicle_Relationship__c vrc = new Vehicle_Relationship__c();
        String retailRvId = UtilRecordType.getRecordTypeIdByName('Vehicle_Relationship__c', 'Vehicle Relationship Retail'); 
        
        vrc.RecordTypeId = retailRvId;
        vrc.Contact__c = personAccountA.id;
        vrc.Owner_Dealer__c = dealerA.get('Account').id;
        
        insert vrc;
        
        Map<id, User> dealerUser = new Map<Id, User>([select id from User where AccountId = :dealerA.get('Account').id]);
        
        system.assertEquals(4, [select id from AccountShare where AccountId = :personAccountA.id and userOrgroupId in :dealerUser.keyset() ].size());
        
        Test.StopTest();
    }
   */  
    /**
     * Create a Dealer and retrun a Map contains info of the dealer
     * key: Account , return account object
     * key: ComplaintKeeper, return case keeper user
     * key: LeadKeeper, return lead keeper user
     *
     */    
    private static Map<String, Sobject> createDealer(String crmCode){
        
        Map<String, Sobject> rtnDealerInfo = new Map<String, Sobject>();
        
        //Following is Create Dealer info
        //A and B have same CRM code
        Account dealer = (Account)UtilTestData.createSobject(new Account(), 
                UtilTestData.ACCOUNT_RT_DEALER);

        dealer.Dealer_Active__c = true;
        dealer.Dealer_DMS_CRM_Code__c = crmCode;
        update dealer;
        rtnDealerInfo.put('Account', dealer);
        
        //AccountA contact
        List<Contact> dealerContacts = new List<Contact>();

        for (integer i = 0; i<4 ; i++){
            //Contact
            Contact contact = (Contact)UtilTestData.createSobject(new Contact(), 
                '');
            contact.AccountId = dealer.id;
            if(i==0){
                contact.Dealer_Complaint_Gate_Keeper__c = true;
            }
            if(i==1){
                contact.Dealer_Lead_Gate_Keeper__c = true;
            }

            dealerContacts.add(contact);
        }
        
        update dealerContacts;
        
        //Create users
        integer i = 0;
        List<User> newUsers1 = new List<User>();  
        System.runAs ( thisUser ) {
            
            for(Contact c: dealerContacts){
                User usr = new User();
                usr.UserName = 'test' + Math.rint(Math.random() * 100000) + '@daimler.com';
                usr.ProfileId = profileIds[0].Id;
                usr.LastName = 'Test User';
                usr.Email = 'test001@daimler.com.full';
                usr.Alias = 'test';
                usr.TimeZoneSidKey = 'Asia/Shanghai';
                usr.EmailEncodingKey = 'UTF-8';
                usr.LanguageLocaleKey = 'en_US';
                usr.localesidkey='en_US';
                usr.contactId = c.ID;
                i++;
                newUsers1.add(usr);
            }
            
            insert newUsers1;

        }
        
         rtnDealerInfo.put('ComplaintKeeper', newUsers1[0]);
         rtnDealerInfo.put('LeadKeeper', newUsers1[1]);
         
         return rtnDealerInfo;
    }

}