src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Current status of the person in relation to Daimler 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_CustomerStatus&quot;</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driving Academy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Dealer Type</label>
        <picklist>
            <picklistValues>
                <fullName>My Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Selling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Servicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Territory Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign/Project Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Shops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Link__c.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;) ,&apos;MY&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Record type for company addresses.</description>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer addresses.</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Address__c.object
	<fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP', 
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'MY'), 'MY', 
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA'))))))</defaultValue>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/SurveyTaker__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipName>SurveyTakers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata-au/objects/SurveyTaker__c.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Taken By Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys Taken</relationshipLabel>
        <relationshipName>Surveys_Taken</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata-au/objects/SurveyTaker__c.object
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys Taken (Dealer Account)</relationshipLabel>
        <relationshipName>Surveys_Taken1</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata-au/objects/SurveyTaker__c.object
    <fields>
        <fullName>View_By_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View By All</label>
        <type>Checkbox</type>
    </fields>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/classes/SurveyTakerHelperJPTest.cls
@isTest
public class SurveyTakerHelperJPTest{
 public Static Account objAccount;
  public static Account objAccount2;  
  public static Account objAccount3; 
  public Static Account DealerAccount;
  public Static Account DealerAccount1;
  public static Account_Link__c AccLink;
  public static  Group grp;
   public static String companyAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
  public static String DealerAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
  public static String personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(); 
 
 
public static  testmethod void afterUpdateEvent_test()
  {
         createTestData();
        Survey__c sur= new Survey__c();
          sur.name = 'testsurvey';
          insert sur;
       SurveyTaker__c st = new SurveyTaker__c();
            st.account__c = objAccount.id;
            st.survey__c = sur.id;
           insert st;
           test.starttest();
           st.account__c = objAccount2.id;
           update st;
           test.stoptest();
  }
public static  testmethod void afterInsertEvent_test()
  {
         createTestData();
      
           test.starttest();
            Survey__c sur= new Survey__c();
          sur.name = 'testsurvey';
          insert sur;
           SurveyTaker__c st = new SurveyTaker__c();
            st.dealer_account__c= DealerAccount.id;
             st.survey__c = sur.id;
           insert st;
           test.stoptest();
  }
public static  testmethod void afterInsertEvent_test1()
  {
         createTestData();
      
           test.starttest();
            Survey__c sur= new Survey__c();
          sur.name = 'testsurvey';
          insert sur;
           SurveyTaker__c st = new SurveyTaker__c();
            st.dealer_account__c= DealerAccount.id;
             st.survey__c = sur.id;
             st.view_by_all__c = true;
           insert st;
           st.view_by_all__c = false;
           update st;
           test.stoptest();
  }
  public static  testmethod void afterInsertEvent_test2()
  {
         createTestData();
      
           test.starttest();
            Survey__c sur= new Survey__c();
          sur.name = 'testsurvey';
          insert sur;
           SurveyTaker__c st = new SurveyTaker__c();
            st.dealer_account__c= DealerAccount.id;
             st.survey__c = sur.id;
             st.view_by_all__c = false;
           insert st;
           st.view_by_all__c = true;
           update st;
           test.stoptest();
  }
  
  public static  testmethod void afterInsertEvent_test3()
  {
         createTestData();
      
           test.starttest();
            Survey__c sur= new Survey__c();
          sur.name = 'testsurvey';
          insert sur;
           SurveyTaker__c st = new SurveyTaker__c();
            st.dealer_account__c= DealerAccount.id;
             st.survey__c = sur.id;
            
           insert st;
           st.dealer_account__c= DealerAccount1.id;
           update st;
           test.stoptest();
  }
  static void createTestData()
    {
        Trigger__c TriggerSurveTaker=new Trigger__c(Name='TriggerSurveyTaker',Trigger_Name__c='TriggerSurveyTaker',Trigger_Handler__c='TriggerSurveyTakerTriggerHandlerJP',update__c=True,insert__c=True,delete__c=True,after__c=True,before__c=True,enabled__c=True,Market__c='JP');
             insert TriggerSurveTaker;
     
        
         DealerAccount= new Account();
        DealerAccount.RecordtypeId=DealerAccRecordTypeId;
        DealerAccount.Name='Test Person 1st';
        DealerAccount.Type='Personal';
        DealerAccount.Status__c='Active';
        DealerAccount.Province__c='Province1';
        DealerAccount.City__c='Test';
        DealerAccount.Email__c='test@mbj.com';
        DealerAccount.Mobile__c ='0435488899';
        
        
        insert DealerAccount;
        
        DealerAccount1= new Account();
        DealerAccount.RecordtypeId=DealerAccRecordTypeId;
        DealerAccount1.Name='Test Person';
        DealerAccount1.Type='Personal';
        DealerAccount1.Status__c='Active';
        DealerAccount1.Province__c='Province1';
        DealerAccount1.City__c='Test';
        DealerAccount1.Email__c='test@mbj.com';
        DealerAccount1.Mobile__c ='0435488899';
        
        
        insert DealerAccount1;
        
        objAccount= new Account();
        objAccount.RecordtypeId=personAccRecordTypeId;
        objAccount.LastName='Test Person 1st';
        //objAccount.Type='Personal';
        objAccount.Status__c='Active';
        objAccount.Province__c='Province1';
        objAccount.City__c='Test';
        objAccount.ZipCode__c = '1004235';
        objAccount.Email__c='test@mbj.com';
        objAccount.Mobile__c ='0435488899';
        objAccount.Phone = '08022420181';
        objAccount.Main_Dealer__c = DealerAccount.id;
        objAccount.Customer_Lifecycle_Phase__c = 'Care';
        
        insert objAccount;    
        //inserted new address record
        Address__c addr = new Address__c(Customer__c = objAccount.id, Address_Type__c = 'Home', Province__c = 'Hokkaido');
        insert addr;
        //added address reference to address 
        Account objacc = new Account(id = objAccount.id, Primary_Address_Reference__c = addr.id); 
        update objacc;
        
        objAccount2= new Account();
        objAccount2.RecordtypeId=personAccRecordTypeId;
        objAccount2.LastName='Test Person 1st';
        //objAccount.Type='Personal';
        objAccount2.Status__c='Active';
        objAccount2.Province__c='Province1';
        objAccount2.City__c='Test';
        objAccount2.ZipCode__c = '1004209';
        objAccount2.Email__c='test@mbj.com';
        objAccount2.Mobile__c ='0435488899';
        objAccount2.Phone = '08022420181';
        objAccount2.Main_Dealer__c = DealerAccount.id;
        objAccount2.Customer_Lifecycle_Phase__c = 'Care';
        
        insert objAccount2;
        
        objAccount3= new Account();
        objAccount3.RecordtypeId=personAccRecordTypeId;
        objAccount3.LastName='Test Person 1st';
        //objAccount.Type='Personal';
        objAccount3.Status__c='Active';
        objAccount3.Province__c='Province1';
        objAccount3.City__c='Test';
        objAccount3.ZipCode__c = '1063723';
        objAccount3.Email__c='test@mbj.com';
        objAccount3.Mobile__c ='0435488899';
        objAccount3.Phone = '08022420181';
        objAccount3.Main_Dealer__c = DealerAccount.id;
        objAccount3.Customer_Lifecycle_Phase__c = 'Care';
        
        insert objAccount3;
        
      
           
        
        AccLink = new Account_Link__c();
        AccLink.fromRole__c = DealerAccount.id;
        AccLink.toRole__c = objAccount.id;        
        
        insert AccLink; 
        grp=new Group();
        grp.name=DealerAccount.Name;
        insert grp;
        
    }

}