src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Required by business during the workshop, which exists in current avarto system ( 区号).</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Function: Customer Number 
  For Dealer Accounts this field is used for the &quot;DMS magic number&quot;
Used in: Page Layouts, Reports 

Created by: Tony Li    Used by: Tony Li
Attribute in Data Dictionary object Contact is &quot;Contact_MagicNo&quot;</description>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Customer Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Dealer_Address_CN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Main address field, line 1 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: Lio Huang
Modify Reason: Dealer Address (Chinese) from GSSN
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_AddressCN&quot;</description>
        <label>Dealer Address CN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-retrieve/objects/Account.object
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <externalId>true</externalId>
        <label>Campaign Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Execution_Type__c</fullName>
        <description>Used only for Campaign Execution record type. To defined the execution channel.</description>
        <label>Execution Type</label>
        <picklist>
            <picklistValues>
                <fullName>OB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Mercedes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OBSMSTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OB SMS Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Template__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>SMS</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>OB Call</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Campaigns (OB)</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used only for Campaign Execution record type. To lookup Template object to define Callscript, eDM name, SMS or MMS template based on the Execution Type.</description>
        <inlineHelpText>Select Callscript, eDM name,  SMS or MMS template based on the Execution Type</inlineHelpText>
        <label>SMS/MMS/eDM Template</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>OB Call</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Callscript</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>SMS</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>SMS</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>eDM</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>eDM</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>MMS</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>MMS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Campaign Executions</relationshipLabel>
        <relationshipName>Campaign_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Result__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Result from BBAC 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DUP_Number__c</fullName>
        <description>Duplication number to identify the suspected duplication group to be filled by EP</description>
        <label>DUP Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/SMS__c.object
<CustomObject>
    <description>Case: This object is used by VF page for ad hoc SMS, Hidden for all users.</description>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SMS(Dealer Name)</relationshipLabel>
        <relationshipName>SMS_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <description>Send Message to Customer</description>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
    <!---->
</CustomObject>

src/main/metadata/objects/Template__c.object
<CustomObject>
    <description>Case: Use to store SMS, eDM Name for campaign, eDM for ad hoc request, MMS template name. This object is maintenace by data manager and is used by Ad Hoc and Campaign batch request</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message_Detail__c</fullName>
        <label>Message Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <recordTypes>
        <fullName>Callscript</fullName>
        <active>true</active>
        <label>Callscript</label>
    </recordTypes>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata-au/objects/User.object
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

src/main/metadata/classes/TaskSMSControllerExtensionTest.cls
/*
    Type:       test class
    Purpose:    TaskSMSControllerExtension test class
    User Story: Central Interactive SMS Workbook

    Used By:    TaskSMSControllerExtension
    ---------------------------------------------------------------
    History:

    27-Nov-2013 Chaos Huang (Nttdata)    Created
*/
@isTest(SeeAllData=true)
public class TaskSMSControllerExtensionTest 
{

    public static testMethod void testTaskSMSControllerExtension1() 
    {
        User usr = UtilTestData.createUser('OB TL','CAC OB TL');
        system.runas(usr)
        {
	        Test.startTest();
	        // Testing the SMS Send
	        ApexPages.standardController controller = new ApexPages.standardController(new SMS__c());
	        
	        // Add parameters to page URL
	        String personAccountRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
	        String dealerRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
	        Account customer = new Account(Area_Code__c = '010', LastName = 'Acme Customer', Phone = '8888888', RecordTypeId = personAccountRecordTypeId,PersonMobilePhone = '1301111111',PersonOtherPhone = '1301111122');
	        insert customer;
	        customer = [Select Customer_Number__c, PersonContactId From Account Where Id=:customer.Id];
	        Account dealer = new Account(Name = 'Acme Dealer', Phone = '8888888', RecordTypeId = dealerRecordTypeId
	            ,Dealer_Address_CN__c = 'chaoyang', City__c = 'beijing', Province__c = '151');
	        insert dealer;
	
	        //User usr = UtilTestData.createUser('OB TL','CAC OB TL');
	
	        Campaign cp = campaignPreparation();
	        String obTaskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('OB Task').getRecordTypeId();
	        Task tas = new Task(
	            RecordTypeId = obTaskRecordTypeId,
	            OwnerId = usr.Id,
	            WhatId = cp.Id,
	            WhoId = customer.PersonContactId,
	            Subject = 'OB Task',
	            Result__c = 'Solved',
	            Activity_Status__c = 'no answer',
	            Dealer_Name__c = 'Test Dealer',
	            DUP_Number__c = '123'
	        );
	        
	        insert tas;
	        
	        ApexPages.currentPage().getParameters().put('taskId', tas.Id);
	        
	        // Test click SMS button from Account
	        // Instantiate a new controller extension with all parameters in the page
	        TaskSMSControllerExtension extension = new TaskSMSControllerExtension(controller);
	        extension.sms.Dealer__c = dealer.Id; 
	        String templateRecordTypeId = Schema.SObjectType.Template__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();       
	        List<Template__c> tems = new List<Template__c>();
	        Template__c tem1 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true, 
	                                           Name = 'lai', Message_Detail__c = '{Contact_Name}');
	        insert tem1;
	        cp.OBSMSTemplate__c = tem1.id;
	        update cp;
	        //insert tem2;
	        tems.add(tem1);
	        //tems.add(tem2);
	        for(Template__c tem : tems) 
	        {
	            if(tem.Message_Detail__c.indexof('{Contact_') != -1) 
	            {
	                extension.templateId = tem.id;
	            }
	        }
	        //extension.templateId
	        List<SelectOption> Templates = extension.getTemplates();
	        extension.parseTemplateMessage();
	        String message = extension.optimzeContent('temp{CONTACT_SALUTATION}temp');
	    
	        // Send SMS
	        extension.send();
	        String recordTypeSMS = Schema.SObjectType.task.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
	        Task t = [Select t.WhoId, t.WhatId, t.Subject, t.Status, t.SMS_Content__c From Task t Where RecordTypeId=:recordTypeSMS and WhatId = :cp.Id]; // and SMS_Content__c=:extension.templateMessage
	        
	        // Test case 2
	        customer.PersonOtherPhone='1234678901';
	        customer.PersonMobilePhone = '';
	        update customer;
	        //Test click SMS button from Task
	        Task tas1 = new Task(
	            RecordTypeId = obTaskRecordTypeId,
	            OwnerId = usr.Id,
	            WhatId = cp.Id,
	            WhoId = customer.PersonContactId,
	            Subject = 'OB Task',
	            Result__c = 'Solved',
	            Activity_Status__c = 'no answer',
	            Dealer_Name__c = 'Test Dealer',
	            DUP_Number__c = '123'
	        );
	        insert tas1;
	        ApexPages.currentPage().getParameters().put('taskId', tas1.Id);
	        
	        extension = new TaskSMSControllerExtension(controller);
	        Template__c tem3 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true, 
	                                           Name = 'lai', Message_Detail__c = '{DEALER_ADDRESS}');
	        insert tem3;
	        extension.templateId = tem3.id;
	        Templates = extension.getTemplates();
	        extension.sms.Dealer__c = null; 
	        extension.parseTemplateMessage();        
	        extension.sms.Dealer__c = dealer.Id; 
	        extension.parseTemplateMessage();
	        message = extension.optimzeContent('temp{DEALER_ADDRESS}temp');
	        // Send SMS
	        extension.send();
	        Test.stopTest();
	        system.assertequals(ApexPages.currentPage().getParameters().get('taskId'),tas1.Id);
	        system.assert(tems!=Null);
	        system.assertEquals(t.Subject, 'SMS');
	        system.assertEquals(t.Status, 'Closed');
	        system.assertEquals(t.WhoId, [Select Id From Contact Where accountId = :customer.Id limit 1].Id);
	        system.assertEquals(cp.OBSMSTemplate__c,tem1.id);
	        system.assertEquals(tem3.Message_Detail__c, '{DEALER_ADDRESS}');
            system.assertEquals(tem3.RecordTypeId, templateRecordTypeId);
            system.assertEquals(tas1.WhoId,customer.PersonContactId);  
            system.assertEquals(extension.sms.Dealer__c,dealer.Id); 
            system.assertequals(extension.parseTemplateMessage(),Null);	  
	        system.assertequals(extension.optimzeContent('temp{DEALER_ADDRESS}temp'),message);	        	         
	        system.assertEquals(extension.getTemplates(),Templates);	      
        }
    }

    public static testMethod void testTaskSMSControllerExtensionErr1() 
    {
    	Test.startTest();
        // Testing the SMS Send
        ApexPages.standardController controller = new ApexPages.standardController(new SMS__c());
        // Add parameters to page URL
        String personAccountRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        String dealerRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
        Account dealer = new Account(Name = 'Acme Dealer', Phone = '8888888', RecordTypeId = dealerRecordTypeId);
        insert dealer;     
        TaskSMSControllerExtension extension = new TaskSMSControllerExtension(controller);
        extension.sms.Dealer__c = dealer.Id;
        String templateRecordTypeId = Schema.SObjectType.Template__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
        Campaign cp = campaignPreparation();
        Template__c tem1 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true, 
                                           Name = 'lai', Message_Detail__c = '{DEALER_NAME}');
        insert tem1;
        extension.templateId = tem1.id;
        List<SelectOption> Templates = extension.getTemplates();
        extension.parseTemplateMessage();
        // Send SMS
        extension.send();
        Test.stopTest();
        system.assertEquals(dealer.RecordTypeId, dealerRecordTypeId);
        system.assertEquals(extension.templateId,tem1.id);        
	    system.assert(tem1!=Null);
	    system.assertEquals(tem1.Message_Detail__c, '{DEALER_NAME}');
        system.assertEquals(tem1.RecordTypeId, templateRecordTypeId);        
        system.assertEquals(extension.sms.Dealer__c,dealer.Id); 
        system.assertequals(extension.parseTemplateMessage(),Null);	   	              
	    system.assertEquals(extension.getTemplates(),Templates);
    }


    public static testMethod void testTaskSMSControllerExtensionErr2() 
    {
        User usr = UtilTestData.createUser('OB TL','CAC OB TL');
        system.runas(usr)
        {
	        Test.startTest();
	        // Testing the SMS Send
	        ApexPages.standardController controller = new ApexPages.standardController(new SMS__c());
	        
	        // Add parameters to page URL
	        String personAccountRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
	        String dealerRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
	        Account customer = new Account(Area_Code__c = '010', LastName = 'Acme Customer', Phone = '8888888', RecordTypeId = personAccountRecordTypeId);
	        insert customer;
	        customer = [Select Customer_Number__c, PersonContactId From Account Where Id=:customer.Id];
	        Account dealer = new Account(Name = 'Acme Dealer', Phone = '8888888', RecordTypeId = dealerRecordTypeId
	            ,Dealer_Address_CN__c = 'chaoyang', City__c = 'beijing', Province__c = '151');
	        insert dealer;
	
	        //User usr = UtilTestData.createUser('OB TL','CAC OB TL');
	        Campaign cp = campaignPreparation();
	        String obTaskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('OB Task').getRecordTypeId();
	        Task tas = new Task(
	            RecordTypeId = obTaskRecordTypeId,
	            OwnerId = usr.Id,
	            WhatId = cp.Id,
	            WhoId = customer.PersonContactId,
	            Subject = 'OB Task',
	            Result__c = 'Solved',
	            Activity_Status__c = 'no answer',
	            Dealer_Name__c = 'Test Dealer',
	            DUP_Number__c = '123'
	        );
	        
	        insert tas;
	        
	        ApexPages.currentPage().getParameters().put('taskId', tas.Id);
	        
	        // Test click SMS button from Account
	        // Instantiate a new controller extension with all parameters in the page
	        TaskSMSControllerExtension extension = new TaskSMSControllerExtension(controller);
	        extension.sms.Dealer__c = dealer.Id; 
	        String templateRecordTypeId = Schema.SObjectType.Template__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();       
	        List<Template__c> tems = new List<Template__c>();
	        Template__c tem1 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true, 
	                                           Name = 'lai', Message_Detail__c = '{DEALER_NAME}');
	        Template__c tem2 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true, 
	                                           Name = 'lai', Message_Detail__c = '{DEALER_NAME}');
	        insert tem1;
	        insert tem2;
	        tems.add(tem1);
	        tems.add(tem2);
	        for(Template__c tem : tems) {
	            if(tem.Message_Detail__c.indexof('{DEALER_') != -1) {
	                extension.templateId = tem.id;
	            }
	        }
	        //extension.templateId
	        List<SelectOption> Templates = extension.getTemplates();
	        extension.parseTemplateMessage();
	        String message = extension.optimzeContent('temp{DEALER_NAME}temp');
	    
	        // Send SMS
	        extension.send();
	        
	        extension.templateMessage = '';
	        extension.send();
	        
	        extension.templateId = '';
	        extension.send();
	        Test.stopTest();
        	system.assertEquals(tem1.Message_Detail__c,'{DEALER_NAME}');
        	system.assertEquals(extension.send(), null);
        	system.assertequals(ApexPages.currentPage().getParameters().get('taskId'),tas.Id);	      
	        system.assertEquals(extension.templateMessage,'');	      
            system.assertEquals(tem1.RecordTypeId,templateRecordTypeId);
            system.assertEquals(tas.WhoId,customer.PersonContactId);  
            system.assertEquals(extension.sms.Dealer__c,dealer.Id); 
            system.assertequals(extension.parseTemplateMessage(),Null);	  
	        system.assertequals(extension.optimzeContent('temp{DEALER_ADDRESS}temp'),message);	        	         
	        system.assertEquals(extension.getTemplates(),Templates);
        }
    }

    // Create Campaign
    private static Campaign campaignPreparation()
    {
        String tempRecordTypeId1 = Schema.SObjectType.Template__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
        String tempRecordTypeId2 = Schema.SObjectType.Template__c.getRecordTypeInfosByName().get('Callscript').getRecordTypeId();
        Template__c tem1 = new Template__c(RecordTypeId = tempRecordTypeId1, Active__c = true,
                                           Name = 'lai', Message_Detail__c = '{Contact_Name}');
        Template__c tem2 = new Template__c(RecordTypeId = tempRecordTypeId2, Active__c = true,
                                           Name = 'lai', Message_Detail__c = '{Contact_Name}');
        insert tem1;
        insert tem2;
        // Campaign Record Type Id Search
        Map<String, Schema.RecordTypeInfo> cpRecordTypeMap_test = Schema.SObjectType.Campaign.getRecordTypeInfosByName();  
        // Central Campaign
        Id centCampaignRT = cpRecordTypeMap_test.get('Central Marketing Campaign').getRecordTypeId();                         
        // Centre Campaign Data Prepared
        // Central Campaign Inital
        Campaign TestData_CCA = new Campaign(Name='TestData_CCA_Campaign',
                                             //Campaign_Code__c='Code_CCA',
                                             Type='Other',
                                             Campaign_Objectives__c='Objectives',
                                             Description='Description',
                                             Status='Confirmed',
                                             StartDate=date.newinstance(2013, 8, 17),
                                             EndDate=date.newinstance(2013, 11, 17),
                                             RecordTypeId=centCampaignRT,
                                             Execution_Type__c= 'OB Call',
                                             OBSMSTemplate__c=tem1.Id,
                                             Template__c=tem2.Id);  
        insert TestData_CCA;
        System.assertEquals(TestData_CCA.OBSMSTemplate__c,tem1.Id);
        System.assert(TestData_CCA.id!=null);
        return TestData_CCA;
    }
  
}