src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Address_CN__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Main address field, line 1 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: Lio Huang
Modify Reason: Dealer Address (Chinese) from GSSN
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_AddressCN&quot;</description>
        <label>Dealer Address CN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer Province Name in English and translated in Chinese 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Address is &quot;Address_Province&quot;
Attribute in Data Dictionary object Dealer is &quot;Dealer_ProvinceEN&quot;</description>
        <label>Province</label>
		<picklist>
            <picklistValues>
                <fullName>Province1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>City__c</fullName>
        <description>Chinese dealer city name - 
For Dealers this is populated by the GSSN system - not modified in SFDC
Attribute in Data Dictionary object Dealer is "Dealer_CityCN"</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/City__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map the area and zip code for cities.</description>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>City</label>
</CustomObject>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Assigned_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Assigned_Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAC_Lead_Status__c</fullName>
        <label>CAC Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Failed For 3 Days(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visited Showroom(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(CAC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(Dealer)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan to Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gave up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_Vehicle_Brand__c</fullName>
        <label>Interested Vehicle Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Desired_Service__c</fullName>
        <label>Lead Desired Service</label>
        <picklist>
            <picklistValues>
                <fullName>Buy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TA&amp;C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Need Follow Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Time__c</fullName>
        <label>Purchase Time</label>
        <picklist>
            <picklistValues>
                <fullName>0 - 3 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - 6 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - 12 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Above 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Three Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Four Weeks above</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>within 1 month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>within 1 week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>above 6 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>within 12 month</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relation_With_The_Leads__c</fullName>
        <label>Relation With The Leads</label>
        <picklist>
            <picklistValues>
                <fullName>本人车主</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>司机</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>经销商</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>家庭成员</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>秘书</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>朋友</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>同事/下属(公司)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>其他</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>未知</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trade_In_MB_Vehicle_Model__c</fullName>
        <label>Trade-In MB Vehicle Model</label>
        <picklist>
            <controllingField>Trade_In_Vehicle_Class__c</controllingField>
            <picklistValues>
                <fullName>A160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A180</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A 180 Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A 200 Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A 260 Hatchback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B180 BlueEFFICIENCY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 BlueEFFICIENCY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Luxury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B 200 Luxury 夜行独享版</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Dynamic model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B200 Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C180KClassic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C180 K Classic(CKD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 CGI elegant type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200 CGI Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C 200 Entry Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C200K Sports轿跑车(Non- current car models)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 Avantgarde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 Elegance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C230 Sports轿跑车(Non- current car models)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240 (Non- current car models)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240A Avantgarde(Non- current car models)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C240E Elegance(Non- current car models)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/SMSSendLeadResultExtensionTest.cls
/*
    Type:       test class
    Purpose:    SMSSendLeadResultExtension test class
    User Story: US-Lead-023 - Send SMS content to customer

    Used By:    SMSSendLeadResultExtension
    ---------------------------------------------------------------
    History:

    20-May-2013 Sinow zhang (Nttdata)    Created
*/
@isTest
public class SMSSendLeadResultExtensionTest {

    public static testMethod void testSMSSendLeadResultExtension1()
    {
        User usr = UtilTestData.createUser('IB CSR','CAC IB CSR');
        User UsedCarDM = UtilTestData.createUser('Used Car DM (E)','CAC IB CSR');
        User SmartDM = UtilTestData.createUser('smart DM (E1)','CAC IB CSR');

        Profile profile = [select Id from Profile where Name = 'IntegrationAPI'];
        User user1 = new User(ProfileId = profile.Id, isActive = true, Username = 'lai1@nttdata.com', LastName = 'sichao',
                                  Email = 'sichao.lai@nttdata.com', Alias = 'laisc', CommunityNickname = 'barney1',
                                  TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                                  EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert user1;

        System.runAs ( user1 ) {
	        String personAccountRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
	        String dealerRecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
			Test.startTest();
            Account customer = new Account(LastName = 'Acme Customer', Phone = '8888888', RecordTypeId = personAccountRecordTypeId, PersonMobilePhone = '12345678901');
            insert customer;
            Account dealer = new Account(Name = 'Acme Dealer', Phone = '8888888', RecordTypeId = dealerRecordTypeId     ,Dealer_Address_CN__c = 'chaoyang', City__c = 'beijing', Province__c = '151');
            insert dealer;

            Lead__c lead = new Lead__c();
            lead.Assigned_Dealer__c = dealer.Id;
            lead.Contact__c = customer.Id;
            lead.CAC_Lead_Status__c = 'Qualified';
            lead.Lead_Type__c = 'Used Car';
            lead.Relation_With_The_Leads__c = 'test';
            lead.Lead_Desired_Service__c = 'Trade-In';
            lead.Purchase_Time__c = '0 - 3 months';
            lead.Interested_Vehicle_Brand__c = 'test';
            lead.Trade_In_MB_Vehicle_Model__c = 'benz';
            lead.Trade_In_Vehicle_Brand__c = 'c230';
            lead.Trade_In_Vehicle_Class__c = 'C-CLASS';
            lead.Trade_In_Other_Vehicle_Model__c = 'C-CLASS';
            insert lead;

            // Testing the SMS Send
            ApexPages.standardController controller = new ApexPages.standardController(new SMS__c());
            ApexPages.currentPage().getParameters().put('leadId',lead.Id);
            ApexPages.currentPage().getParameters().put('retURL',lead.Id);

            // Test click SMS button from Lead
            // Instantiate a new controller extension with all parameters in the page
            SMSSendLeadResultExtension extension = new SMSSendLeadResultExtension(controller);
            List<Template__c> tems = new List<Template__c>();
            String templateRecordTypeId = Schema.SObjectType.Template__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
            Template__c tem1 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true,
                                               Message_Detail__c = '{DEALER_name}', Name = 'lai');
            Template__c tem2 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true,
                                               Message_Detail__c = '{DEALER}', Name = 'lais');
            insert tem1;
            insert tem2;
            tems.add(tem1);
            tems.add(tem2);
            for(Template__c tem : tems) {
                if(tem.Message_Detail__c.indexOf('{DEALER_') != -1) {
                    extension.templateId = tem.id;
                }
            }
            //extension.templateId = tem.id;
            List<SelectOption> Templates = extension.getTemplates();
            extension.parseTemplateMessage();
            String message = extension.optimzeContent('temp{DEALER_NAME}temp');
            // Send SMS
            extension.send();
            Test.stopTest();
            System.assertEquals(tem1.Message_Detail__c, '{DEALER_name}');
            System.assertEquals(tem2.RecordTypeId, templateRecordTypeId);
            System.assertEquals(lead.Assigned_Dealer__c, dealer.Id);               
	        system.assertEquals(dealer.Phone, '8888888');
	        system.assertEquals(customer.RecordTypeId, personAccountRecordTypeId);
	        system.assertEquals(dealer.RecordTypeId, dealerRecordTypeId);
	        system.assert(Templates!=Null);	         
	        system.assertEquals(extension.getTemplates(),Templates);
	        system.assertequals(extension.parseTemplateMessage(),Null);	        
	        system.assertequals(ApexPages.currentPage().getParameters().get('leadId'),lead.Id);
	        system.assertequals(ApexPages.currentPage().getParameters().get('retURL'),lead.Id);
        }
    }
    
    /**
     * for SMSSendLeadResultExtension Line 31 & 40
     */
    public static testMethod void testSMSSendLeadResultExtension4()
    {
        User usr = UtilTestData.createUser('IB CSR','CAC IB CSR');
        User UsedCarDM = UtilTestData.createUser('Used Car DM (E)','CAC IB CSR');
        User SmartDM = UtilTestData.createUser('smart DM (E1)','CAC IB CSR');

        Profile profile = [select Id from Profile where Name = 'IntegrationAPI'];
        User user1 = new User(ProfileId = profile.Id, isActive = true, Username = 'lai1@nttdata.com', LastName = 'sichao',
                                  Email = 'sichao.lai@nttdata.com', Alias = 'laisc', CommunityNickname = 'barney1',
                                  TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                                  EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US');
        insert user1;

        System.runAs ( user1 ) {
        	Test.startTest();
            Account customer = new Account(LastName = 'acme', Allow_Data_Sharing__c = 'Yes', Province__c = 'jiangsu', City__c = 'nanjing', Preferred_Language__c = 'English');
            customer.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            customer.OwnerId = usr.Id;
            insert customer;

            // Create a dealer for lead dealer
            Account dealer = (Account)UtilTestData.createSobject(new Account(), UtilTestData.ACCOUNT_RT_DEALER);

            Lead__c lead = new Lead__c();
            lead.Assigned_Dealer__c = dealer.Id;
            lead.Contact__c = customer.Id;
            lead.CAC_Lead_Status__c = 'Qualified';
            lead.Lead_Type__c = 'Used Car';
            lead.Relation_With_The_Leads__c = 'test';
            lead.Lead_Desired_Service__c = 'Trade-In';
            lead.Purchase_Time__c = '0 - 3 months';
            lead.Interested_Vehicle_Brand__c = 'test';
            lead.Trade_In_MB_Vehicle_Model__c = 'benz';
            lead.Trade_In_Vehicle_Brand__c = 'c230';
            lead.Trade_In_Vehicle_Class__c = 'C-CLASS';
            lead.Trade_In_Other_Vehicle_Model__c = 'C-CLASS';
            insert lead;

            // Testing the SMS Send
            ApexPages.standardController controller = new ApexPages.standardController(new SMS__c());
            ApexPages.currentPage().getParameters().put('leadId',lead.Id);
            ApexPages.currentPage().getParameters().put('retURL',lead.Id);

            // Test click SMS button from Lead
            // Instantiate a new controller extension with all parameters in the page
            SMSSendLeadResultExtension extension = new SMSSendLeadResultExtension(controller);

            String templateRecordTypeId = Schema.SObjectType.Template__c.getRecordTypeInfosByName().get('SMS').getRecordTypeId();
            Template__c tem1 = new Template__c(RecordTypeId = templateRecordTypeId, Active__c = true,
                                               Message_Detail__c = 'temp{DEALER_ADDRESS}temp', Name = 'lai');
            insert tem1;
            extension.templateId = '123';
            List<SelectOption> Templates = extension.getTemplates();
            //extension.sms.dealer=null;
            extension.parseTemplateMessage();
            String message = extension.optimzeContent('temp{DEALER_NAME}temp');
            // Send SMS
            extension.send();
            Test.stopTest();
            system.assert(lead!=Null);
            system.assertEquals(lead.Contact__c, customer.Id);            
            system.assertEquals(tem1.Message_Detail__c, 'temp{DEALER_ADDRESS}temp');
            system.assertEquals(tem1.RecordTypeId, templateRecordTypeId);
            system.assertEquals(lead.Assigned_Dealer__c, dealer.Id);               
	        system.assertEquals(dealer.Phone, '021-000000');
	        system.assert(Templates!=Null);        
	        system.assertEquals(extension.getTemplates(),Templates);
	        system.assertequals(extension.parseTemplateMessage(),Null);	      
	        system.assertequals(ApexPages.currentPage().getParameters().get('leadId'),lead.Id);
	        system.assertequals(ApexPages.currentPage().getParameters().get('retURL'),lead.Id);
        }
    }
}