src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Complaint_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Complaint Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Class__c</fullName>
        <label>Case Class</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After-Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others-Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others-After-Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBDA Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBDA Complaint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DeadLine__c</fullName>
        <label>DeadLine</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <label>MD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Inquiry</fullName>
        <active>true</active>
        <businessProcess>Inquiry Process</businessProcess>
        <description>Customer Inquiry Case</description>
        <label>Inquiry</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/CaseDeadelineCalc__mdt.object
<CustomObject>
    <fields>
        <fullName>CaseDeadelineCalc10__c</fullName>
        <label>CaseDeadelineCalc10</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc11__c</fullName>
        <label>CaseDeadelineCalc11</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc12__c</fullName>
        <label>CaseDeadelineCalc12</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc13__c</fullName>
        <label>CaseDeadelineCalc13</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc14__c</fullName>
        <label>CaseDeadelineCalc14</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc15__c</fullName>
        <label>CaseDeadelineCalc15</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc16__c</fullName>
        <label>CaseDeadelineCalc16</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc17__c</fullName>
        <label>CaseDeadelineCalc17</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc18__c</fullName>
        <label>CaseDeadelineCalc18</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc19__c</fullName>
        <label>CaseDeadelineCalc19</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc1__c</fullName>
        <label>CaseDeadelineCalc1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc20__c</fullName>
        <label>CaseDeadelineCalc20</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc21__c</fullName>
        <label>CaseDeadelineCalc21</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc22__c</fullName>
        <label>CaseDeadelineCalc22</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc23__c</fullName>
        <label>CaseDeadelineCalc23</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc24__c</fullName>
        <label>CaseDeadelineCalc24</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc25__c</fullName>
        <label>CaseDeadelineCalc25</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc26__c</fullName>
        <label>CaseDeadelineCalc26</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc27__c</fullName>
        <label>CaseDeadelineCalc27</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc28__c</fullName>
        <label>CaseDeadelineCalc28</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc29__c</fullName>
        <label>CaseDeadelineCalc29</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc2__c</fullName>
        <label>CaseDeadelineCalc2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc30__c</fullName>
        <label>CaseDeadelineCalc30</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc31__c</fullName>
        <label>CaseDeadelineCalc31</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc32__c</fullName>
        <label>CaseDeadelineCalc32</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc33__c</fullName>
        <label>CaseDeadelineCalc33</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc34__c</fullName>
        <label>CaseDeadelineCalc34</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc35__c</fullName>
        <label>CaseDeadelineCalc35</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc3__c</fullName>
        <label>CaseDeadelineCalc3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc4__c</fullName>
        <label>CaseDeadelineCalc4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc5__c</fullName>
        <label>CaseDeadelineCalc5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc6__c</fullName>
        <label>CaseDeadelineCalc6</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc7__c</fullName>
        <label>CaseDeadelineCalc7</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc8__c</fullName>
        <label>CaseDeadelineCalc8</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseDeadelineCalc9__c</fullName>
        <label>CaseDeadelineCalc9</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CaseDeadelineCalc</label>
    <pluralLabel>CaseDeadelineCalcs</pluralLabel>
</CustomObject>

src/main/metadata/classes/CaseHelperJP.cls
public with sharing class CaseHelperJP {
    
    public Id caseInquiryRec_Id = UtilRecordType.getRecordTypeIdByName('Case', UtilConstant.INQUIRY);
    public List<Id> tmpCaseIds = new List<Id>();
    public List<Account> updateAccount = new List<Account>();
    public Map<Id, List<Id>> accountCaseMap = new Map<Id, List<Id>>();
        
    public void calculateComplaintAmount(List<Case> cases, Map<Id,SObject> case_Map){
        system.debug('Trigger Old Map...' +case_Map);
        Set<Id> accounts = new Set<Id>();
        Map<Id, List<Integer>> acc_Count = new Map<Id, List<Integer>>();
        for (Case c : cases){
            if (c.MD__c == 'JP' || c.MD__c == 'KR'){
                Case caseRec = (Case)case_Map.get(c.Id);
                if (c.AccountId != caseRec.AccountId){
                    List<Integer> count = acc_Count.get(caseRec.AccountId);
                    if (count == null){
                        acc_Count.put(caseRec.AccountId, new List<Integer>{1});
                    }else{
                        count[0]++;
                    }
                    accounts.add(caseRec.AccountId);               
                }
             }
        }
        
        System.debug('Count of the Accounts changed...' +acc_Count);
        
        List<Case> case_acc = [Select Id, AccountId From Case 
                                      Where AccountId IN :accounts AND RecordTypeId =:caseInquiryRec_Id 
                                      AND Case_Class__c = 'Complaint'];           
        for(Case c : case_acc){
            tmpCaseIds = accountCaseMap.get(c.AccountId);
            if (tmpCaseIds == null){
                accountCaseMap.put(c.AccountId, new List<Id>{c.Id});
            }else{
                tmpCaseIds.add(c.Id);
            }
        }
        
        accounts = new Set<Id>();
        accounts = accountCaseMap.keySet();
        List<Account> accRecords = [Select Id, Complaint_Amount__c From Account Where Id IN:accounts];
        for (Account acc : accRecords){
           List<Id> caseIds = accountCaseMap.get(acc.Id);
           List<Integer> caseCount = acc_Count.get(acc.Id);
           acc.Complaint_Amount__c = caseIds.size()-caseCount[0];
           updateAccount.add(acc);
        }
        system.debug('Accounts to be updated...' +updateAccount);
        update updateAccount;
    }
    
    public void calculateComplaintAmount(List<Case> cases){
        system.debug('Incoming Cases...' +cases);
        Set<Id> accounts = new Set<Id>();
        List<Account> accRecords;
        for(Case c : cases){
            if(c.MD__c == 'JP' || c.MD__c == 'KR'){
                accounts.add (c.AccountId);
            } 
        }                       
        system.debug('Accounts...' +accounts);
        
        List<Case> case_acc = [Select Id, AccountId From Case 
                                          Where AccountId IN :accounts AND RecordTypeId =:caseInquiryRec_Id 
                                          AND Case_Class__c = 'Complaint'];                                  
        
        system.debug('Case_acc...' +case_acc);
        if (case_acc != null && !case_acc.isEmpty()){                                         
            for(Case c : case_acc){
                tmpCaseIds = accountCaseMap.get(c.AccountId);
                if (tmpCaseIds == null){
                    accountCaseMap.put(c.AccountId, new List<Id>{c.Id});
                }else{
                    tmpCaseIds.add(c.Id);
                }
            }
            
            system.debug('accountCaseMap...' +accountCaseMap);
            accounts = new Set<Id>();
            accounts = accountCaseMap.keySet();
            accRecords = [Select Id, Complaint_Amount__c From Account Where Id IN:accounts];
            for (Account acc : accRecords){
               List<Id> caseIds = accountCaseMap.get(acc.Id);
               acc.Complaint_Amount__c = caseIds.size();
               updateAccount.add(acc);
            }
            system.debug('Accounts to be updated...' +updateAccount);
        }else{
            Set<Id> accountIds = new Set<Id>();
            for (Id accId : accounts){
                accountIds.add(accId);
            }
            accRecords = [Select Id, Complaint_Amount__c From Account Where Id IN:accountIds];
            for (Account acc : accRecords){
               acc.Complaint_Amount__c = 0;
               updateAccount.add(acc);
            } 
        }
        update updateAccount;                                                                                                                 
    }
    
    public void updateCaseDeadline(List<Case> cases){
        CaseDeadelineCalc__mdt caseDeadline;
        Date todayDate = Date.today();
        Integer days;
        Schema.DescribeSobjectResult results = CaseDeadelineCalc__mdt.getSObjectType().getDescribe();
        system.debug('Custom metadata :' +results.fields.getMap());
        
        Set<String> fields = results.fields.getMap().keySet();
        String fieldsToQuery = '';

        Integer i = 0;
        for (String f : fields){
            system.debug('map values...' +results.fields.getMap().get(f));
            if (i > 0){
                fieldsToQuery = String.ValueOf(fieldsToQuery+ ' ,'+results.fields.getMap().get(f));
                system.debug('fieldsToQuery...1' +fieldsToQuery); 
            }
            else{
                fieldsToQuery = String.ValueOf(results.fields.getMap().get(f));
                system.debug('fieldsToQuery...2' +fieldsToQuery); 
            }
            i++;
            system.debug('fieldsToQuery...3' +fieldsToQuery);  
        }
        
        String queryString = 'Select ' + fieldsToQuery + ' FROM CaseDeadelineCalc__mdt WHERE QualifiedApiName ='  +'\'Japan_Case_Deadlines\'';
        system.debug('Final query string..' +queryString);
        caseDeadline = Database.query(queryString);
        system.debug('Case deadline values...' +caseDeadline);
        
        for (Case c : cases){
            if (c.Case_Class__c == 'Others' && c.MD__c == 'JP' && c.RecordTypeId == caseInquiryRec_Id){
                if(c.Priority == 'A'){
                    system.debug('Case Deadlines...' +caseDeadline);
                    days = (Integer)caseDeadline.CaseDeadelineCalc1__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'B'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc2__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'C'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc3__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'D'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc4__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'E'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc5__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }
            }
            if (c.Case_Class__c == 'Complaint' && c.MD__c == 'JP'){
                if(c.Priority == 'A'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc6__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'B'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc7__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'C'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc8__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'D'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc9__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'E'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc10__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }
            }
            if (c.Case_Class__c == 'Claim' && c.MD__c == 'JP'){
                if(c.Priority == 'A'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc11__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'B'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc12__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'C'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc13__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'D'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc14__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'E'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc15__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }
            }
            if (c.Case_Class__c == 'Inquiry' && c.MD__c == 'JP'){
                if(c.Priority == 'A'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc16__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'B'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc17__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'C'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc18__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'D'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc19__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'E'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc20__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }
            }
            if (c.Case_Class__c == 'Request' && c.MD__c == 'JP'){
                if(c.Priority == 'A'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc21__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'B'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc22__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'C'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc23__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'D'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc24__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'E'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc25__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }
            }
            if (c.Case_Class__c == 'Touring Support' && c.MD__c == 'JP'){
                if(c.Priority == 'A'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc26__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'B'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc27__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'C'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc28__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'D'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc29__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'E'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc30__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }
            }
            if (c.Case_Class__c == 'Finance' && c.MD__c == 'JP'){
                if(c.Priority == 'A'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc31__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'B'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc32__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'C'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc33__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'D'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc34__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }else if(c.Priority == 'E'){
                    days = (Integer)caseDeadline.CaseDeadelineCalc35__c;
                    c.DeadLine__c = todayDate.addDays(days);
                }
            }
          if ((c.Priority == 'A' || c.Priority == 'Red >= 4') && c.MD__c == 'KR'){
               c.DeadLine__c=System.Now() + 1;         
            }
          if ((c.Priority == 'B' || c.Priority == 'Yellow = 3') && c.MD__c == 'KR'){
              c.DeadLine__c= System.Now() + 3;
           }
          if ((c.Priority == 'C' || c.Priority == 'Green <= 2') && c.MD__c == 'KR'){
               c.DeadLine__c= System.Now() + 10;          
           }  
        }        
    }
   public void updateCaseDeadline(List<Case> cases, Map<Id,SObject> case_Map){     
         for (Case c : cases){ 
               Case caseRec = (Case)case_Map.get(c.Id);
            if ((c.Priority == 'A' || c.Priority =='Red >= 4') && c.Priority!=caseRec.Priority && c.MD__c == 'KR'){
               
                c.DeadLine__c=System.Now() + 1;         
             }
           if ((c.Priority == 'B' || c.Priority =='Yellow = 3') && c.Priority!=caseRec.Priority && c.MD__c == 'KR'){
               c.DeadLine__c= System.Now() + 3;
            }
           if ((c.Priority == 'C' || c.Priority =='Green <= 2') && c.Priority!=caseRec.Priority && c.MD__c == 'KR'){
               c.DeadLine__c= System.Now() + 10;          
            } 
          }      
       }
 }