src/main/metadata/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Task__c.object
<CustomObject>
    <fields>
        <fullName>Related_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Dealer</label>
         <lookupFilter>
            <active>true</active>
			<booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please select the proper dealer account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>			
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>IntegrationAPI</value>
            </filterItems>
            <infoMessage>Search and select dealer account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retail Tasks</relationshipLabel>
        <relationshipName>Retail_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Labour_Amount__c</fullName>
        <label>Service Labour Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Parts_Amount__c</fullName>
        <label>Service Parts Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Total_Amount__c</fullName>
        <label>Service Total Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Retail Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Dealer_Company_Name__c</fullName>
        <formula>Contact.Account.Company_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Company Name</label>
        <type>Text</type>
    </fields>

src/main/metadata/classes/RetailtaskInlineEditController.cls
Public class RetailtaskInlineEditController{
public Retail_Task__c retailtask{get;set;}
public Boolean ShowAmount{get;set;}
public RetailtaskInlineEditController(ApexPages.StandardController sc){
ShowAmount=false;
Id id = ApexPages.currentPage().getParameters().get('id');
if(id!=null){
    retailtask = [select id,Service_Labour_Amount__c,Service_Parts_Amount__c,Related_Dealer__r.name,Service_Total_Amount__c from Retail_Task__c where id=: id];
    user us=[select id,Dealer_Company_Name__c,profile.name from user where id=: userinfo.getUserid()];
    
    If(us.Dealer_Company_Name__c==retailtask.Related_Dealer__r.name && (us.profile.name.contains('MBJ')||us.profile.name.contains('MBF') ||us.profile.name.contains('Dealer') ||(us.profile.name=='System Administrator')) )
    {
        ShowAmount=true;
    }
}
}
}