src/main/metadata/objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>Owner_Relation__c</fullName>
        <label>Owner Relation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Grand Child</fullName>
                </value>
                <value>
                    <fullName>Husband Wife</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Relative</fullName>
                </value>
                <value>
                    <fullName>Same</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>UCID__c</fullName>
        <label>UCID</label>
        <length>50</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
			IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;)))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Loyalty_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loyalty Card</relationshipLabel>
        <relationshipName>Loyalty_Card</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Loyalty_Card_End_Date__c</fullName>
        <label>LoyaltyCardEndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loyalty_Card_Number__c</fullName>
        <externalId>true</externalId>
        <label>Loyalty Card Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP', 
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA')))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Loyalty Card</relationshipLabel>
        <relationshipName>Loyalty_Card</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>owner_relation__c</fullName>
        <label>Owner Relation</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grand Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband Wife</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Same</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loyalty Card</label>
    <nameField>
        <displayFormat>LC-{0000000000}</displayFormat>
        <label>Loyalty Record No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Card</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA')))</defaultValue>
        <label>MD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegistrationNo__c</fullName>
        <label>RegistrationNo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link the competitor vehicle to Account</description>
        <label>Related Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Other_Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Relationship end date
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_EndDate“</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP','NA')))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Relation__c</fullName>
        <description>Person's relationship to the vehicle's owner</description>
        <label>Owner Relation</label>
        <picklist>
            <picklistValues>
                <fullName>Same</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband・Wife</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grand parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grand child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/LoyalityManger.cls
@RestResource(urlMapping='/Loyality/*')
global without sharing class LoyalityManger {
    @HttpPost
    global static Map<String,String> LAValidateCardHolder()
        {
        String jsonText = RestContext.request.requestBody.toString();
        Map<String, Object> cObjMap = (Map<String, Object>) JSON.deserializeUntyped(jsonText);
        Object res=cObjMap.get('data');
        Map<String,Object> obj= (Map<String,Object>)res;
        String Loyalty_Card_No=(String)obj.get('Loyalty_Card_No');
        String Vehicle_Registration=(String)obj.get('Vehicle_Registration');
        list<Vehicle__c> vehlist=new list<Vehicle__c>();
        list<Loyalty_Card__c> Lclist=new list<Loyalty_Card__c>();
        list<Vehicle_Relationship__c> vehrel=new list<Vehicle_Relationship__c>();
        map<string,string> responsemap=new map<string,string>();
        responsemap.put('Vehicle_exist','False');
        responsemap.put('UCID','Nil');
        //considering removal of white spaces
        Vehicle_Registration=Vehicle_Registration.deleteWhitespace();
        if(Vehicle_Registration!=null || Vehicle_Registration!=''){
            String regNumwithwildcards='%';
            for(Integer i=0;i<Vehicle_Registration.length();i++)
            {
                regNumwithwildcards+=Vehicle_Registration.substring(i,i+1)+'%';
            }
            List<Vehicle__c> vehicles=new List<Vehicle__c>();
            vehicles=[select id,RegistrationNo__c from vehicle__c where RegistrationNo__c like :regNumwithwildcards and MD__c='KR'];
            String regNumber=null;
            system.debug(vehicles);
                for(vehicle__c v:vehicles)
            {
                if(v.RegistrationNo__c.deleteWhitespace().right(5)==Vehicle_Registration)
                {
                    regNumber=v.RegistrationNo__c;
                }
            }  
        if(regNumber!=null && regNumber!='' && !String.isBlank(regNumber))
        {  
        vehlist=[select id,Related_contact__c,RegistrationNo__c from Vehicle__c where RegistrationNo__c =:regNumber and MD__c='KR'];
        }
        }
    system.debug(vehlist);
    if(Loyalty_Card_No!=null && Loyalty_Card_No!='' && !String.isBlank(Loyalty_Card_No))
    {
    Lclist=[select Loyalty_Card_Number__c,Account__c from Loyalty_Card__c where Loyalty_Card_Number__c =:Loyalty_Card_No and Loyalty_Card_End_Date__c>=:system.today() and MD__c='KR'];
    }     
    if(Lclist.size()>0)
       {
          responsemap.put('Loyalty_Card',Lclist[0].Loyalty_Card_Number__c );
       }
      else
       {
               responsemap.put('Loyalty_Card','Nil');
               //Return responsemap;
       }
     if(vehlist.size()>0)
        {
            if(Lclist.size()>0){
                vehrel=[select owner_relation__c,Contact__r.ucid__c  from Vehicle_Relationship__c where contact__c=:Lclist[0].Account__c and Vehicle_ID__c=:vehlist[0].id and End_Date__c=null and MD__c='KR'];   
            }
            responsemap.put('Vehicle_exist','True');
            responsemap.put('Vehicle_ID',vehlist[0].id);
        }
        
      if(vehrel.size()>0)
        {
          String relation=vehrel[0].Owner_Relation__c=='Same'?'Owner':'Contact';
          responsemap.put('UCID',vehrel[0].Contact__r.ucid__c+';'+relation);
        }
       return responsemap;  
    }
}