src/main/metadata/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Car_Model__c.object
<CustomObject>
    <description>Knowledge: This object is to store Car Model info to be used in DM and Car Model comparison.</description>
    <label>Car Model</label>
    <nameField>
        <label>Car Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Model</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata/objects/Lead_Details__c.object
<CustomObject>
    <description>This is used to capture lead related details such as interested vehicle, competitor vehicle.</description>
    <fields>
        <fullName>Car_Model__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Vehicle Model details from car Model object.</description>
        <label>Car Model</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car_Model__c.Status__c</field>
                <operation>equals</operation>
                <value>Own Sellable</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Car_Model__c</referenceTo>
        <relationshipLabel>Lead Details</relationshipLabel>
        <relationshipName>Lead_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Market selection.</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IN</fullName>
                    <default>true</default>
                    <label>IN</label>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead Details</label>
    <nameField>
        <displayFormat>LDI-{0000}</displayFormat>
        <label>Lead Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/MultiselectAutoCompleteCtrlTest.cls
@IsTest
public class MultiselectAutoCompleteCtrlTest
{
    public static SelectOption[] leftOptions   { get; set; }
  	public SelectOption[] rightOptions  { get; set; }
  	public SelectOption[] prePopulateOptions { get; set; }
  	public String strSelectedOptions    { get; set; }  
    public static String salesLeadRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales Lead').getRecordTypeId();
    public static String aftersalesLeadRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Aftersales Lead').getRecordTypeId();
    public static String companyAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();    
    public static Opportunity oppSales;
    public static Opportunity oppafterSales;
    public static List<Car_Model__c> carModelList ;
      public static  List<Lead_Details__c> ledDetList ;
       public static  List<Lead_Details__c> ledDetList1;
    @TestSetup
    public static void initData(){
        Profile p1 = [select id,name from profile WHERE Name='System Administrator'];  
        User usr = new User(Alias = 'standt', Email='testUser@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='Test', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p1.Id, Market__c='AU',
                            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@testorg.com'+String.valueof(DateTime.now().getTime()), isActive=true);
        DMLManagerService.insertAsSystem(usr);
        System.runAs(usr){
            Account companyAcc = TestUtils.createGenericAccount(usr, '1236', companyAccRecordTypeId, '+61445789654');
         
        }
    }
    
    @IsTest
    private static void CarModelMappingUtilityTest() {
        test.startTest();
        User user1 = TestUtils.createGenericAdminUser('India', 'Asia/Kolkata', 'IN');
        System.runAs (user1) {
            initData();
           SelectOption leftOptions = new SelectOption('a','a');
            MultiselectAutoCompleteCtrl MS = new MultiselectAutoCompleteCtrl();
           MS.assignToSelectedOption();
            String Str = MS.getMultiselectOptions();
            Str = MS.getPrepopulatedData();
     
        }
        test.stopTest();
        
        
    }
     
}