src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Federation_ID__c</fullName>
        <label>GEMS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Contact.object
    <recordTypes>
        <fullName>DealerStaff</fullName>
        <active>true</active>
        <description>Staff that work at the Dealership ie: Sales Manager etc</description>
        <label>DealerStaff</label>
    </recordTypes>

src/main/metadata/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Submit_Response__c</fullName>
        <description>Message to be displayed to the user when the Survey has been submitted</description>
        <inlineHelpText>Message to be displayed to the user when the Survey has been submitted</inlineHelpText>
        <label>Submit Response</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/SurveyTaker__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipName>SurveyTakers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata-au/objects/SurveyTaker__c.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Taken By Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys Taken</relationshipLabel>
        <relationshipName>Surveys_Taken</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/classes/SurveyHelperJPTest.cls
@isTest
public class SurveyHelperJPTest{
    public static Survey__c testSurvey;
    public static Survey__c testSurvey1;
    public static List<Survey__c> SurveyList;
    public static Map<Id,Survey__c> surveyMap;
    public static SurveyTaker__c svrTkrtest;
    public static Account dlrAcc;
    public static Contact dlrContact;
    public static User usr;
    public static Group accGrp;
    public static Id ContactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('DealerStaff').getRecordTypeId();
    public static Id dlrAccRecordTypeId = Schema.SobjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId();
public static testmethod  void handleInsertOrUpdateEventtest(){
     
    createTestData();
     test.startTest();
        SurveyHelperJP.handleInsertOrUpdateEvent(SurveyList,surveyMap);
     test.stopTest();
    
     }
    static void createTestData(){
     // Survey__c record
     SurveyList = new List<Survey__c>();
    testSurvey =new Survey__c(Name='Survey1');
    insert testSurvey;
    testSurvey1 =new Survey__c(Name='Survey2');
    insert testSurvey1;
    
    SurveyList.add(testSurvey);
    SurveyList.add(testSurvey1);
    
    testSurvey.Submit_Response__c ='Response to Survey';
    update testSurvey;
    testSurvey1.Submit_Response__c = 'Response to Survey1';
    update testSurvey1;
    
    surveyMap = new Map<Id,Survey__c>();
     surveyMap.put(testSurvey.Id,testSurvey);
     surveyMap.put(testSurvey1.Id,testSurvey1);
        
    // Dealer Account 
        dlrAcc = (Account)UtilTestData.createSobject(new Account(mobile__c='09865324152'), UTilTestData.ACCOUNT_RT_DEALER);  
    // Create Contact
        dlrContact =new Contact(AccountId=dlrAcc.Id,LastName ='Contact1',Federation_ID__c='12546',Email='contact@dealer.com',Phone='(856)421-3702');
        insert dlrContact;
        
     // Japan Dealer Company Manager Profile
          Profile profile= [select Id from Profile where name='Japan Dealer Company Manager'];
     // UserRole
     // UserRole ur = new UserRole(name = dlrAcc.name + ' ' + 'Partner Executive');
      //  insert ur;   
    // Create User 
           usr = new User(alias = 'standt',email = 'test@9876test.com',emailencodingkey = 'UTF-8'
                         , lastname = 'TestLasName', languagelocalekey = 'en_US',ContactID= dlrContact.Id,
                                      localesidkey = 'en_US', profileid =profile.Id,
                                      timezonesidkey = 'America/Los_Angeles',  username = 'testUniqudeName@test.com'); 
        insert usr;  
    // Survey Taker Record
       svrTkrtest = new SurveyTaker__c(Survey__c=testSurvey.Id,Account__c=dlrAcc.Id); 
        insert svrTkrtest;
        accGrp = new Group(Name='test dealer');
        insert accGrp;
    }
}