src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allow_Data_Sharing__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Flag to allow data sharing 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Contact is &quot;Contact_DoCdata&quot;</description>
        <label>Allow Data Sharing</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Choice Yet</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Foundation_Date__c</fullName>
        <label>Foundation Date</label>
        <type>Date</type>
    </fields>

src/main/metadata-au/objects/Account.object
    <fields>
        <fullName>Individual_Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;,
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <label>MD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Inquiry</fullName>
        <active>true</active>
        <businessProcess>Inquiry Process</businessProcess>
        <description>Customer Inquiry Case</description>
        <label>Inquiry</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/CaseCommentCustomControllerTHTest.cls
/*************************************************************************
Author: Tejbir Singh
Used for: Thailand Market
Description: Code coverage for CaseCommentCustomController class.
Date:14th Sept 2018
************************************************************************/
@isTest
public class CaseCommentCustomControllerTHTest {

    public static User user1 = TestUtils.createAdminUser();
    public static Case caseObj;
    public static id fsinq =RecordTypeAccessService.getRecordTypeId('case','FS Inquiry');
    public static Id recordTypeAccPersonAccountObjId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
    public static CaseCommentCustomController controller;
    public static CaseCommentCustomController controller2;
    public static void testData()
    {
        Account personAcc = new Account(Foundation_Date__c=system.today(),RecordTypeId = recordTypeAccPersonAccountObjId,LastName = 'Mercedez',Allow_Data_Sharing__c='Yes',Individual_Home_Phone__c='+66-12-123-789');
      	insert personAcc;
        caseObj = new Case(Subject='testing',accountid=personAcc.Id,Recordtypeid=fsinq,MD__c='TH',COS_Ticket_Number__c='T000347');
        insert caseObj; 
        ApexPages.StandardController stdController=new ApexPages.StandardController(caseObj);
        controller=new CaseCommentCustomController(stdController);
    }
    
    public static testMethod void saveFile()
    {
        System.runAs(user1)
        {
            testData();
            controller.fileBody= Blob.valueOf('Image');
            controller.fileName='TestImage.jpg';
        	PageReference page=controller.saveCaseCommentWithAttachment();
            ApexPages.StandardController stdController2=new ApexPages.StandardController(caseObj);
        	controller2=new CaseCommentCustomController(stdController2);
            PageReference page2=controller2.saveCaseCommentWithAttachment();
            PageReference page3=controller2.back();
        }
        
    }
}