src/main/metadata/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>mobile phone number of dealer</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Zip Code (Post Code) of customer&apos;s address 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Dealer is &quot;Dealer_ZipCode&quot;</description>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;), &apos;MY&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Account.object
    <fields>
        <fullName>MBK_Data_Source__c</fullName>
        <label>MBK Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>24 hours Touring Support</fullName>
                </value>
                <value>
                    <fullName>3rd party data</fullName>
                </value>
                <value>
                    <fullName>Advertisement</fullName>
                </value>
                <value>
                    <fullName>After-service center</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Circle of excellence</fullName>
                </value>
                <value>
                    <fullName>Dealers</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>IB Call</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>MB Card</fullName>
                </value>
                <value>
                    <fullName>MB Magazine</fullName>
                </value>
                <value>
                    <fullName>MB website</fullName>
                </value>
                <value>
                    <fullName>Mercedes Call Catalogue</fullName>
                </value>
                <value>
                    <fullName>Mercedes Magazine Survey</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz Academy</fullName>
                </value>
                <value>
                    <fullName>My Mercedes</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Road Assistant</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>StarClass</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Account_Link__c.object
<CustomObject>
    <label>Account Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Link</pluralLabel>
    <recordTypes>
        <fullName>ContactSector</fullName>
        <active>true</active>
        <description>To link customer records with dealer records.</description>
        <label>ContactSector</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Link__c.object
    <fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;, 
IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,
IF(ISPICKVAL($User.Market__c, &apos;MY&apos;) ,&apos;MY&apos;,&apos;NA&apos;))))))</defaultValue>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Address__c.object
<CustomObject>
    <description>Contains the Address information of the Customers.</description>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Post Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Company</fullName>
        <active>true</active>
        <description>Record type for company addresses.</description>
        <label>Company</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record type for dealer addresses.</description>
        <label>Dealer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>Record type for individual addresses.</description>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Address__c.object
	<fields>
        <fullName>Market__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
IF(ISPICKVAL($User.Market__c, 'JP'), 'JP', 
IF(ISPICKVAL($User.Market__c, 'TH'), 'TH',
IF(ISPICKVAL($User.Market__c, 'MY'), 'MY', 
IF(ISPICKVAL($User.Market__c, 'KR'), 'KR','NA'))))))</defaultValue>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>

src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>CAC_Lead_Status__c</fullName>
        <label>CAC Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Failed For 3 Days(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visited Showroom(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(CAC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(Dealer)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan to Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gave up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TA&amp;C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Need Follow Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-au/objects/Lead__c.object
    <fields>
        <fullName>Mobile__c</fullName>
        <formula>IF( 
ISBLANK(Contact__c), 
Company_Account__r.PersonMobilePhone, 
Collectioner_Name__r.MobilePhone
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile</label>
        <type>Text</type>
    </fields>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/classes/LeadHelperAccountLinkCreateJPTest.cls
@istest
public class LeadHelperAccountLinkCreateJPTest {
  public static Account accobj;
  public static Account accobj1;
  public static Account accobj2;
  public static Contact contobj;
  public static Contact contobj1;
  public static Contact contobj2;
  public static List<Contact> contobjlist;
  public static Lead__c leadobj;
  public static Lead__c le;
  public static List<Lead__c> leadlist;
  //public static map<id,Lead__c> leadOldMap;
  public static Account_Link__c acclink;
  public static Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(); 
  public static Id AccountCompanyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
  public static Id DealerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').getRecordTypeId(); 
  public static Id companyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId(); 
  public static Id salesleadRecordTypeId = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('Aftersales Leads').getRecordTypeId();
  public static Id retailpersonRecordTypeId = Schema.SObjectType.Account_Link__c.getRecordTypeInfosByName().get('Retail Person').getRecordTypeId(); 
  public static Id ContactSectorRecordTypeId = Schema.SObjectType.Account_Link__c.getRecordTypeInfosByName().get('ContactSector').getRecordTypeId(); 
  public static Id AddressRecordTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId(); 
  
  static void createTestData() {
      
      Trigger__c TriggerLed=new Trigger__c(Name='TriggerLead',Trigger_Name__c='TriggerLead',Trigger_Handler__c='TriggerLeadTriggerHandlerJP',update__c=true,insert__c=true,delete__c=true,after__c=true,before__c=true,enabled__c=true,Market__c='JP');
      insert TriggerLed;
      
      accobj = new Account();
      accobj.RecordTypeId = DealerRecordTypeId;
      accobj.Name = '翁長';
      accobj.Phone = '00000009642';
      accobj.MBK_Data_Source__c='Email';
      accobj.Mobile__c = '00000009642';
      accobj.ZipCode__c= '1002347';
      insert accobj;
      system.debug('$$$$$$$$$$$$'+accobj);
      system.debug('$$$$$$$$$$$$'+accobj.id);
      
      accobj1 = new Account();
      accobj1.RecordTypeId = personAccRecordTypeId ;
      accobj1.LastName = '雄';
      accobj1.Phone = '00000009842';
      accobj1.MBK_Data_Source__c='Campaign';
      accobj1.Mobile__c = '00000009842';
      accobj1.ZipCode__c= '3332347';
      insert accobj1;
      system.debug('$$$$$$$$$$$$'+accobj1);
      system.debug('$$$$$$$$$$$$'+accobj1.id);
      
      leadobj = new Lead__c();
      leadobj.RecordTypeId = salesleadRecordTypeId;
      leadobj.CAC_Lead_Status__c = 'Qualified';
      leadobj.Lead_Type__c = 'New Car';
      leadobj.MD__c = 'KR';
      leadobj.Assigned_Dealer__c = accobj.Id;
      leadobj.Contact__c = accobj1.id;
      //insert leadobj;
      system.debug('$$$$$$$$$$$$'+leadobj);
      leadlist = new LIst<Lead__c>();
      leadlist.add(leadobj);
      insert leadlist;
      system.debug('$$$$$$$$$$$$'+leadlist);
      
      //if(leadobj.RecordTypeId=='Person Account') {
      
      acclink = new Account_Link__c(); 
    acclink.RecordTypeId = retailpersonRecordTypeId;
    acclink.Name = 'testaccounlink';
    acclink.fromRole__c = accobj.Id;
    acclink.toRole__c = accobj.Id;
    acclink.Retail_PersonBirthdate__c=system.today();
    acclink.Retail_Special_Care__c='testing';
    acclink.Retail_Individual_Home_Phone__c='045878956';
    acclink.Retail_Work_Phone__c='0455862358';
    acclink.Retail_Mobile__c='076-789-1452';
    acclink.Retail_Email__c='asdfg@gmail.com';
    acclink.Retail_Gender__c='female';
    acclink.Retail_Occupation__c='Business';
    acclink.Retail_Preferred_Language__c='english';
    acclink.Retail_Preferred_Contact_Method__c='phone';
    insert acclink;
    system.debug('$$$$$$$$$$$$'+acclink);
    system.debug('$$$$$$$$$$$$'+acclink.id);
    //}
  }
 
      
    public static testmethod void createAccountLinkRecordTest() 
    {
        createTestData();
        le = new Lead__c();
        le.RecordTypeId = salesleadRecordTypeId;
        le.CAC_Lead_Status__c = 'Approved';
        le.Lead_Type__c = 'Newwww Car';
        le.MD__c = 'JP';
        le.Assigned_Dealer__c = accobj.Id;
        
        test.starttest();
        	insert le;
        test.stoptest();
    }   
}