src/main/metadata/objects/App_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>System App Settings</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>App Setting</label>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <label>Trigger</label>
</CustomObject>

src/main/metadata/classes/ViewVoiceRecordingControllerTest.cls
/*
    Type:       Test class of ViewVoiceRecordingController
    Purpose:    1. ViewVoiceRecording page Controller    
    User Story: US-CTI-001 - view voice recording for a IB Call or OB Call
    Used By:   VF Page - ViewVoiceRecording.page 
    History:    
    19-Jul-2013 Barney Lai (NTTData)  Created
*/  

@isTest
public with sharing class ViewVoiceRecordingControllerTest {
Private static ViewVoiceRecordingController extension;
Private static App_Setting__c app;
    public static testMethod void testViewVoiceRecordingController1(){
        List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
        insert updatecustomsettings;
        Task t1 = new Task(InteractionIds__c = 'test');
        app= new App_Setting__c ();
        app.name='Voice Recording Location';
        app.Value__c='test@gmail.com';
                
        Test.StartTest();
        insert t1;
        insert app;        
        ApexPages.standardController controller = new ApexPages.standardController(t1);
        extension = new ViewVoiceRecordingController(controller);
        Test.stopTest();
        system.assertNotEquals(null,t1);
        system.assertEquals(app.name,'Voice Recording Location');
        system.assertNotEquals(null,extension);
    }
}