src/main/metadata/objects/Batch_Job__c.object
<CustomObject>
    <description>Batch organization object</description>
    <fields>
        <fullName>Fail_Reason__c</fullName>
        <label>Fail Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Batch Job Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Batch Job</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Content_Preview__c</fullName>
        <description>Used only for Campaign Execution. To display the Message Detail of Template selected. Updated by workflow (because it's a long text not able to use formula).</description>
        <label>SMS Preview</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Create_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for Batch Task Generation, will not put on page layout.</description>
        <label>Create Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DM_Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DM Material</label>
        <referenceTo>DM_Material__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Execution_Type__c</fullName>
        <description>Used only for Campaign Execution record type. To defined the execution channel.</description>
        <label>Execution Type</label>
        <picklist>
            <picklistValues>
                <fullName>OB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Mercedes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Flow_URL__c</fullName>
        <label>Flow URL</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Campaign_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used only for Campaign Execution record type. To build the sequence of Campaign Executions.</description>
        <label>Previous Campaign Execution</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Consequent Campaign Executions</relationshipLabel>
        <relationshipName>Consequent_Campaign_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_De_dup_Range__c</fullName>
        <label>Task De-dup Range</label>
        <picklist>
            <picklistValues>
                <fullName>By CAC Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>By Campaign Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <formula>Template__r.Name</formula>
        <label>Template Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used only for Campaign Execution record type. To lookup Template object to define Callscript, eDM name, SMS or MMS template based on the Execution Type.</description>
        <inlineHelpText>Select Callscript, eDM name,  SMS or MMS template based on the Execution Type</inlineHelpText>
        <label>SMS/MMS/eDM Template</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>OB Call</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Callscript</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>SMS</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>SMS</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>eDM</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>eDM</value>
            </filterItems>
            <filterItems>
                <field>$Source.Execution_Type__c</field>
                <operation>equals</operation>
                <value>MMS</value>
            </filterItems>
            <filterItems>
                <field>Template__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>MMS</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Campaign Executions</relationshipLabel>
        <relationshipName>Campaign_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>FirstName &amp; " " &amp;  LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Task Generated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DUP_Number__c</fullName>
        <description>Duplication number to identify the suspected duplication group to be filled by EP</description>
        <label>DUP Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/DM_Material__c.object
<CustomObject>
    <description>Case: Track the Material used by DM Request</description>
    <label>DM Material</label>
    <nameField>
        <label>DM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DM Material</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata/objects/DM_Request__c.object
<CustomObject>
    <description>Case: Track the DM Request. This is also used by Campaign for bulk DM Request</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>DM Request</relationshipLabel>
        <relationshipName>DM_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Company, Person Account, Person Account Manual Merge, Person Account Soft Deleted</value>
            </filterItems>
            <infoMessage>Search and select account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DM Request</relationshipLabel>
        <relationshipName>DM_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_DM_Material1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expected DM Material1</label>
        <referenceTo>DM_Material__c</referenceTo>
        <relationshipLabel>DM Request (Expected DM Material1)</relationshipLabel>
        <relationshipName>DM_Request2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status1__c</fullName>
        <label>Status1</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>to be sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not send</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>to be sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DM Request</label>
    <nameField>
        <displayFormat>DMR-{000000}</displayFormat>
        <label>DM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DM Request</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>DM</fullName>
        <active>true</active>
        <description>Direct mail</description>
        <label>DM</label>
    </recordTypes>
    <recordTypes>
        <fullName>MMS</fullName>
        <active>true</active>
        <label>MMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <description>Send Message to Customer</description>
        <label>SMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>eDM</fullName>
        <active>true</active>
        <label>eDM</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
    <!---->
</CustomObject>

src/main/metadata/objects/Template__c.object
<CustomObject>
    <description>Case: Use to store SMS, eDM Name for campaign, eDM for ad hoc request, MMS template name. This object is maintenace by data manager and is used by Ad Hoc and Campaign batch request</description>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_ID__c</fullName>
        <label>Template ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <recordTypes>
        <fullName>MMS</fullName>
        <active>true</active>
        <label>MMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>SMS</fullName>
        <active>true</active>
        <label>SMS</label>
    </recordTypes>
    <recordTypes>
        <fullName>eDM</fullName>
        <active>true</active>
        <label>eDM</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata/classes/UtilCampaignTaskGenerationByAccount.cls
/*
    Type:       Apex Class
    Purpose:    Define methods used in trigger.DearlerOffering
    User Story: US-Cpn-018, US-Cpn-019, US-Cpn-020, US-Cpn-021
    Used By:    TriggerCampaign.trigger
    ---------------------------------------------------------------
    History:

    25-Mar-2013 Jorry Chen (Breakingpoint)    Created    
    28-May-2013 Stephano Shi (Breakingpoint)    Modified
    24-June-2013 Stephano Shi (Breakingpoint)    Modified
    2014-04-03 updated by Justin Yu
    2014-04-18 updated by Shuang Li
*/

global Class UtilCampaignTaskGenerationByAccount implements Database.Batchable<sObject>{
    global List<ID> cpIdList = new List<ID>();
    
    private static String mms ='MMS';
    private MisunderstoodTaskGeneration mis;
    public List<Campaign> cpUpdateList = new List<Campaign>(); 
    public List<User> genericUserQueryList = new List<User>(); 
    public List<GroupMember> obuserList = new List<GroupMember>();
    public Group CCCQueue;
    public User intUser;
    public User fulfillmentSpUser;
    public User usr ;
    public string alias=System.Label.Task_Assigned_User;
    
    private ID taskRecordTypeId;
    private String strSMS = 'SMS';
    private String strOBCall = 'OB Call';
    private String streDM = 'eDM';
    private String strDM = 'DM';
    
    private String strOpenStatus = 'Open';
    private String strCloseStatus = 'Closed';
    private String strVeriStatus = 'Need Verification';
    private String strSentActivityStatus = 'Sent';
   
    private String CallCenterSupervisor ='Call Center Supervisor';
    public List<DM_Request__c> dmRequestList = new List<DM_Request__c>();
   
    global Id jobId;
    
    global Map<String, Schema.RecordTypeInfo> taskRecordTypeMap;
    
    global UtilCampaignTaskGenerationByAccount(List<Campaign> cpList) 
    {    
        usr = [select id, Name,userRole.Name from user  where userRole.Name =: CallCenterSupervisor limit 1];
        //usr = [Select Id, Name,Alias from user where Alias =:alias limit 1]; 
        CCCQueue = [Select Id from Group where Name = 'CCC Manager KR' and Type = 'Queue'];
        obuserList = [select UserOrGroupId from GroupMember where GroupId =:CCCQueue.Id];
        //intUser = [SELECT Id FROM User WHERE Profile.Name = 'IntegrationAPI' AND isActive = true  LIMIT 1];
        //fulfillmentSpUser = [SELECT Id FROM User WHERE UserRole.Name like '%Fulfillment Specialist%' AND isActive = true LIMIT 1];

        for(Campaign cp : cpList) {
            cpIdList.add(cp.Id);
            cpUpdateList.add(new Campaign(id = cp.Id, Create_Task__c = false));
        }

        // Initiate Mis
        mis = new MisunderstoodTaskGeneration(cpList, false);
system.debug('&******************'+cpList);
        
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(
            [select id, ContactId, Contact.AccountId, Contact.MobilePhone, Contact.Email, LeadId, Task_Generated__c, CampaignId, Campaign.Content_Preview__c,
                    Campaign.Execution_Type__c, Campaign.Name, Contact.DUP_Number__c, Campaign.Template_Name__c, Campaign.DM_Material__c, Campaign.Flow_URL__c,
                    Campaign.Template__r.Subject__c, Campaign.Template__r.Template_ID__c,
                    Campaign.Parent.Task_De_dup_Range__c,
                    Campaign.Parent.ParentId,
                    Campaign.Previous_Campaign_Execution__c,
                    Campaign.Template__c, Status
            from CampaignMember
            where CampaignId in :cpIdList and Task_Generated__c = false]);
    } 
    
    global void execute(Database.BatchableContext BC, List<CampaignMember> scope) {
    system.debug('&*********scope'+scope);
        List<Task> taskList = new List<Task>();
        taskRecordTypeMap = Schema.SObjectType.Task.getRecordTypeInfosByName();
        Savepoint sp = Database.setSavepoint();
        try {            
            for(CampaignMember cpm : scope) {
                taskList.addAll(generateTask(cpm,taskRecordTypeMap));
                cpm.Task_Generated__c = true;
            }
            
            Map<String, Task> upSMSTaskList = new Map<String, Task>();
            Map<String, Task> upMMSTaskList = new Map<String, Task>();
            Map<String, Task> upEDMTaskList = new Map<String, Task>();
            List<Task> upOtherTaskList = new List<Task>();
            for(task tk : taskList){
                if(tk.Subject == strSMS){
                    upSMSTaskList.put(tk.UniqueCampaignMobile__c, tk);
                }
                else if(tk.Subject == mms){
                    upMMSTaskList.put(tk.UniqueCampaignMobile__c, tk);
                }
                else if(tk.Subject == streDM){
                    upEDMTaskList.put(tk.UniqueCampaignEmail__c, tk);
                } else{
                    upOtherTaskList.add(tk);
                }
            }
            taskList = upOtherTaskList;
            taskList.addAll(upSMSTaskList.Values());
            taskList.addAll(upMMSTaskList.Values());
            taskList.addAll(upEDMTaskList.Values());
            
            update scope;
            if(dmRequestList.size() > 0) insert dmRequestList;     
            
            // No need to consider duplicate Campaign Task of the same CAC Campaign
            // So if it is caused this reason, we need to append the campaign execution to 
            // task UniqueCampaignGenerateTask__c
            Database.SaveResult[] srs = Database.insert(taskList, false);
            system.debug('srs>>>' + srs);
            mis.processMisunderstoodTasks(srs, taskList);
        } 
        catch(exception ex) {
            Database.rollback(sp);
            System.debug('create task failed : ' + ex.getTypeName());
            throw ex;
        }
    }
    
    
    private List<Task> generateTask(CampaignMember cpm, Map<String, Schema.RecordTypeInfo> taskRecordTypeMap) {
        List<Task> taskList = new List<Task>();        
        String uniqueTaskField = '';
        if (cpm.Campaign.Parent.Task_De_dup_Range__c == 'By Campaign Execution'
                && cpm.Campaign.Previous_Campaign_Execution__c == null) {
            uniqueTaskField = 
                String.valueOf(cpm.Campaign.ParentId) + 
                String.valueOf(cpm.ContactId) + 
                cpm.Campaign.Execution_Type__c;
        }
        else if (cpm.Campaign.Parent.Task_De_dup_Range__c == 'By CAC Campaign') {
            uniqueTaskField = 
                String.valueOf(cpm.Campaign.Parent.ParentId) + 
                String.valueOf(cpm.ContactId) + 
                cpm.Campaign.Execution_Type__c;
        }

        if(cpm.Campaign.Execution_Type__c == strOBCall) {        
            //for(GroupMember u : obuserList) {
                taskList.add(new Task(
                    Subject= strOBCall, 
                    RecordTypeId = taskRecordTypeMap.get('OB Task').getRecordTypeId(),
                    Status = strOpenStatus,
                    DUP_Number__c = (cpm.ContactId == null ? ' ' : cpm.Contact.DUP_Number__c), 
                    WhoId = (cpm.ContactId == null ? cpm.LeadId : cpm.ContactId),
                    WhatId = (cpm.ContactId == null ? null : cpm.CampaignId),
                    Campaign_Member_ID__c = String.valueOf(cpm.Id), 
                    Campaign_Name__c = cpm.Campaign.Name, 
                    Activity_Status__c = 'not started',
                    ActivityDate = date.today(),
                    UniqueCampaignGenerateTask__c = uniqueTaskField,
                    OwnerId= usr.Id));
            
            //} Flow_URL__c = cpm.Campaign.Flow_URL__c, removed as part of SFDCJP-1765
        } else if (cpm.Campaign.Execution_Type__c == strSMS && cpm.Contact.MobilePhone != null && cpm.Contact.MobilePhone != '') {
            taskList.add(new Task(
                Subject= strSMS, 
                RecordTypeId = taskRecordTypeMap.get('SMS').getRecordTypeId(),
                OwnerId = usr.Id,
                Activity_Status__c = strVeriStatus,
                Phone__c = cpm.Contact.MobilePhone,
                WhoId = (cpm.ContactId == null ? cpm.LeadId : cpm.ContactId),
                WhatId = (cpm.ContactId == null ? null : cpm.CampaignId),
                ActivityDate = date.today(),
                UniqueCampaignMobile__c = cpm.CampaignId + '-' + cpm.Contact.MobilePhone,
                SMS_Content__c = cpm.Campaign.Content_Preview__c,
                SMSTemplateID__c = cpm.Campaign.Template__c,
                UniqueCampaignGenerateTask__c = uniqueTaskField)
            );
        } 
        else if (cpm.Campaign.Execution_Type__c == mms && cpm.Contact.MobilePhone != null && cpm.Contact.MobilePhone != '') {
            taskList.add(new Task(
                Subject= mms, 
                RecordTypeId = taskRecordTypeMap.get(mms).getRecordTypeId(),
                OwnerId = usr.Id,
                Activity_Status__c = strVeriStatus,
                Phone__c = cpm.Contact.MobilePhone,
                WhoId = (cpm.ContactId == null ? cpm.LeadId : cpm.ContactId),
                WhatId = (cpm.ContactId == null ? null : cpm.CampaignId),
                ActivityDate = date.today(),
                UniqueCampaignMobile__c = cpm.CampaignId + '-' + cpm.Contact.MobilePhone,
                SMSTemplateID__c = cpm.Campaign.Template__c,
                eDM_Template__c = cpm.Campaign.Template__r.Template_ID__c,
                UniqueCampaignGenerateTask__c = uniqueTaskField)
            );
        }
        else if (cpm.Campaign.Execution_Type__c == streDM) {
            taskList.add(new Task(
                Subject= streDM, 
                RecordTypeId = taskRecordTypeMap.get('eDM').getRecordTypeId(),
                OwnerId = usr.Id,
                Status = strCloseStatus,
                Campaign_eDM_Template_Subject__c = cpm.Campaign.Template__r.Subject__c,
                Campaign_eDM_Template_ID__c = cpm.Campaign.Template__r.Template_ID__c,                                 
                WhoId = (cpm.ContactId == null ? cpm.LeadId : cpm.ContactId),
                WhatId = (cpm.ContactId == null ? null : cpm.CampaignId),
                Campaign_Member_ID__c = String.valueOf(cpm.Id), 
                Campaign_Name__c = cpm.Campaign.Name,
                UniqueCampaignEmail__c = cpm.CampaignId + '-' + cpm.Contact.Email,
                Email_Address__c = cpm.Contact.Email,
                Activity_Status__c = strSentActivityStatus,
                ActivityDate = date.today(),
                eDM_Template__c = cpm.Campaign.Template_Name__c,
                UniqueCampaignGenerateTask__c = uniqueTaskField)
            );
        } else if (cpm.Campaign.Execution_Type__c == strDM) {
            taskList.add(new Task(
                Subject = strDM, 
                RecordTypeId = taskRecordTypeMap.get('DM').getRecordTypeId(),
                OwnerId = usr.Id,
                Status = strOpenStatus,
                WhoId = (cpm.ContactId == null ? cpm.LeadId : cpm.ContactId),
                WhatId = (cpm.ContactId == null ? null : cpm.CampaignId),
                Campaign_Member_ID__c = String.valueOf(cpm.Id), 
                Campaign_Name__c = cpm.Campaign.Name,
                ActivityDate = date.today(),
                UniqueCampaignGenerateTask__c = uniqueTaskField)
            );
            if(cpm.Contact.AccountId <> null && cpm.ContactId <> null)
                     dmRequestList.add(new DM_Request__c(
                     Campaign__c = cpm.CampaignId, 
                     Customer_Name__c = cpm.Contact.AccountId,
                     Expected_DM_Material1__c = cpm.Campaign.DM_Material__c,
                     Status1__c = cpm.Status
                    )
                );
        } 
        return taskList;
    }
    
    
    global void finish(Database.BatchableContext BC) {
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email, ExtendedStatus  
                           FROM   AsyncApexJob 
                           WHERE  Id = :BC.getJobId()];
        
        // Batch Job Compeleted.
        if(jobId != null){
            String updateMsg = '';
            try{
                if(cpUpdateList.size() > 0) update cpUpdateList;
            }catch (Exception ex){
                updateMsg = ex.getMessage();
            }

            Batch_Job__c bj = new Batch_Job__c(Id = jobId);
            if (job.ExtendedStatus == null && updateMsg.length() == 0) {                
                bj.Status__c = 'Completed';                
            }else{
                bj.Status__c = 'Fail';  
                bj.Fail_Reason__c =  job.ExtendedStatus != null ? job.ExtendedStatus : updateMsg;    
            }
            update bj;
        } else {
            System.debug('JOBID>>> null');
        }
    }
}