src/main/metadata/objects/Batch_Job__c.object
<CustomObject>
    <description>Batch organization object</description>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <description>Created By Type</description>
        <label>Batch Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Set__c</fullName>
        <description>Campaign ID Set for batch job</description>
        <label>Campaign Set</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Batch Job Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Batch Job</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Create_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for Batch Task Generation, will not put on page layout.</description>
        <label>Create Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
		IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
		IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',IF(ISPICKVAL($User.Market__c, 'KR'), 'KR',IF(ISPICKVAL($User.Market__c, 'TH'), 'TH','NA')))))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <label>MD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Task Generated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/main/metadata/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, &apos;AU&apos;) ,&apos;AU&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;CN&apos;), &apos;CN&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;JP&apos;), &apos;JP&apos;, 
			IF(ISPICKVAL($User.Market__c, &apos;TH&apos;), &apos;TH&apos;,
			IF(ISPICKVAL($User.Market__c, &apos;KR&apos;), &apos;KR&apos;,&apos;NA&apos;)))))</defaultValue>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/classes/campaignMemberHelperKR.cls
/*********************************************************************************
Name         : campaignMemberHelperKR
Created By   : 
Modified BY  : 
Company Name : NTT Data
Project      : Daimler APAC  
Created Date : 25th July 2017
Modified Date:
Requirement  : SFDCKR - 1388
Usages       : Helper class for campaignMember trigger flow
			   To update Create Task field on Campaign for newly added campaign members 
*********************************************************************************/
public with sharing class campaignMemberHelperKR 
{    
	/*********************************************************************************
	Method Name  : setCreateTaskFieldFalseOrTrueOnCampaign
	Created By   : 
	Created Date : 25th July 2017
	Project      : Daimler APAC
	Usages       : This method would update Create Task field on Campaign for newly added campaign members
				   Before update scenario would update the Create Task flag to False.
				   After update scenario would update the Create Task flag to True.
	
	**********************************************************************************/
	//public static void setCreateTaskFieldFalseOrTrueOnCampaign (list<CampaignMember> campMemList)
	public static void setCreateTaskFieldFalseOrTrueOnCampaign (Id campnId)
	{
		set<Id> campaignIdSet = new set<Id>();
		list<Campaign> updateCampaignList = new list<Campaign>();
		list<Campaign> campaignList = new list<Campaign>();
		Batch_Job__c accJob = new Batch_Job__c(Batch_Type__c='Contact', Status__c='Pending');
		/*if(!campMemList.isEmpty() && campMemList != null)
		{
			for(CampaignMember camMem : campMemList)
			{
				if(camMem.Task_Generated__c == false)
				{
					campaignIdSet.add(camMem.CampaignId);
				}
			}			
		}*/
		//if(!campaignIdSet.isEmpty() && campaignIdSet != null)
		//{
			//campaignList = [select Id, Create_Task__c from Campaign where Id in : campaignIdSet];	
			campaignList = [select Id, Create_Task__c from Campaign where Id =: campnId];	
			if(!campaignList.isEmpty() && campaignList != null) 
			{          
	            database.executeBatch(new UtilCampaignTaskGenerationByAccount(campaignList), 200);
	            accJob.Campaign_Set__c = string.valueOf(campaignIdSet);
	            if(accJob!=Null)
	            {
	           		 insert accJob;
				}
	        }
		//}
	}
	
	
	 public static void updatecustomstatus (list<CampaignMember> campMemList,Map<Id,CampaignMember>oldCMmap)
    {
     list<CampaignMember> updateCampaignMemList = new list<CampaignMember>();
       
            for(CampaignMember camMem : campMemList)
            {
               system.debug('camMem.Status__c---'+camMem.Status__c);
               system.debug('trigger.isUpdate'+trigger.isUpdate);
                if(camMem.Status__c!=null && camMem.MD__c=='KR')
                {  
                system.debug('camMem.Status__c---'+camMem.Status__c);
                if(oldCMmap!=null)
                {
                if((camMem.Status__c == '응답함' || camMem.Status__c == 'Responded') && oldCMmap.get(camMem.id).Status__c != camMem.Status__c && oldCMmap.get(camMem.id).Status__c!=null)
                {
                 
                      camMem.Status = 'Responded';
                 
                }
                }
                if((camMem.Status == 'Sent' || camMem.Status == 'Responded') && ((camMem.Status__c == 'Sent' || camMem.Status__c == '발송함') || (camMem.Status__c == 'Responded' || camMem.Status__c == '응답함')))
                {
                  system.debug('I am here');
                  camMem.Status__c = camMem.Status;
                  system.debug(camMem.Status+'Status'+camMem.Status__c);
                }
                if(trigger.isUpdate && oldCMmap.get(camMem.id).Status != camMem.Status && ((camMem.Status__c == 'Failed/No Response' || camMem.Status__c == '실패/응답 없음') || (camMem.Status__c == 'Decline' || camMem.Status__c == '거절')))
                {
                  system.debug('I am here in update');
                  camMem.Status__c = camMem.Status;
                  system.debug(camMem.Status+'Status'+camMem.Status__c);
                }
                }
            }  
           
           
    }
}