src/main/metadata/objects/CallOutHandlerSettingDFW__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>callout time value for webservice call</description>
    <fields>
        <fullName>DEFAULT_CALLOUT_TIME__c</fullName>
        <label>DEFAULT_CALLOUT_TIME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAX_CALLOUT_TIME__c</fullName>
        <label>MAX_CALLOUT_TIME</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CallOutHandlerSettingDFW</label>
</CustomObject>

src/main/metadata/objects/CDM_Integration_URLs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>It contains URLs from Informatica</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Informatica_URL__c</fullName>
        <label>Informatica URL</label>
        <type>Url</type>
    </fields>
	<fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CDM Integration URLs</label>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/SystemSettingsDFW__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Logging framework</description>
    <fields>
        <fullName>Log_Purge__c</fullName>
        <label>Log Purge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SystemSettingsDFW</label>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/CaseCommentHelperTHTest.cls
/*
    Type:Test class
    Purpose:Test Class for CaseCommentHelperTH
    User Story:
    Used By:     
    ---------------------------------------------------------------
    History:
    1. Created on 18-04-2018 by Abhishek Mohanty 
    2. Modified     
*/
@isTest 
public class CaseCommentHelperTHTest {
	public static User user1 = TestUtils.IntegrationAPIUser();
    static testMethod void testmethod1() {
       // Create the Case Record.
        Trigger__c CaseCommentTriggerTH=new Trigger__c();
        CaseCommentTriggerTH.Name='CaseCommentTriggerTH';
        CaseCommentTriggerTH.Market__c='TH';
        CaseCommentTriggerTH.Trigger_Handler__c='CaseCommentTriggerHandlerTH';
        CaseCommentTriggerTH.Trigger_Name__c='CaseCommentTrigger';
        CaseCommentTriggerTH.after__c=true;
        CaseCommentTriggerTH.before__c=true;
        CaseCommentTriggerTH.enabled__c=true;
        CaseCommentTriggerTH.insert__c=true;
        CaseCommentTriggerTH.update__c=true;
        insert CaseCommentTriggerTH;
        Case cas = new Case(Status ='New', Priority = 'Low' , COS_Ticket_Number__c='T745119'); 
        insert cas;
        
        Casecomment casecomment = new Casecomment (ParentId=cas.id , CommentBody='Test');
        insert casecomment; 
        
        //Map<id,sObject> caseComments = new Map<id,sObject>([Select Id, ParentId, IsPublished, CommentBody, CreatedById, CreatedDate, SystemModstamp, LastModifiedDate, LastModifiedById, IsDeleted From CaseComment where ParentId=:cas.id]);
        
        //CaseCommentHelperTH.SendCaseCommentsToCOS(caseComments);
    }
    @isTest
    static void THIntegrationtestmethod1() {      
        user1=[select Id,Name,profile.Name from user where id=:user1.Id];
        system.runAs(user1){
        Test.startTest();
        TriggerUtil.userCreate=false;
        Trigger__c CaseCommentTriggerTH=new Trigger__c();
        CaseCommentTriggerTH.Name='CaseCommentTriggerTH';
        CaseCommentTriggerTH.Market__c='TH';
        CaseCommentTriggerTH.Trigger_Handler__c='CaseCommentTriggerHandlerTH';
        CaseCommentTriggerTH.Trigger_Name__c='CaseCommentTrigger';
        CaseCommentTriggerTH.after__c=true;
        CaseCommentTriggerTH.before__c=true;
        CaseCommentTriggerTH.enabled__c=true;
        CaseCommentTriggerTH.insert__c=true;
        CaseCommentTriggerTH.update__c=true;
        insert CaseCommentTriggerTH;
            Trigger__C casetrigger=new Trigger__C(name='TriggerCaseTH',after__c=true,before__c=true,delete__c=true,enabled__c=true,insert__c=true,Market__c='TH',Trigger_Handler__c='CaseTriggerHandlerTH',Trigger_Name__c='CaseTrigger',update__c=true);
    insert casetrigger;
       CDM_Integration_URLs__c cdm= new CDM_Integration_URLs__c();
            cdm.Name='TH-Case Update';
            cdm.Context__c='Case';
            cdm.Country__c='TH';
            cdm.Type__c='Update';
            cdm.Informatica_URL__c='https://ps1w2.rt.informaticacloud.com/active-bpel/public/rt/001FL6/pd-TH-FS-Salesforce-COS';
            insert cdm;
            
            CallOutHandlerSettingDFW__c callout=new CallOutHandlerSettingDFW__c();
            callout.Name='CalloutValues';
            callout.DEFAULT_CALLOUT_TIME__c='5000';
            callout.MAX_CALLOUT_TIME__c='30000';
            insert callout;
            
            SystemSettingsDFW__c setting=new SystemSettingsDFW__c();
            setting.Log_Purge__c=2;
            insert setting;
            
           Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorCase());
        
        TriggerUtil.userCreate=false;
        Case cas = new Case(Status ='New', Priority = 'Low' , COS_Ticket_Number__c='T745119',market__C='TH'); 
        insert cas;
        
            TriggerUtil.userCreate=false;
        Casecomment casecomment = new Casecomment (ParentId=cas.id , 
         CommentBody='CR/n'+system.now()+'/ntest from COS/n Htpps://test.com');
        insert casecomment; 
        TriggerUtil.userCreate=false;
        Casecomment casecomment2 = new Casecomment (ParentId=cas.id , 
         CommentBody='CR/n'+system.now()+'/ntest from COS/n');
        insert casecomment2; 
        test.stoptest();
        }
        
    }
}