src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <defaultValue>IF(ISPICKVAL($User.Market__c, 'AU') ,'AU', 
		IF(ISPICKVAL($User.Market__c, 'CN'), 'CN', 
		IF(ISPICKVAL($User.Market__c, 'JP'), 'JP',IF(ISPICKVAL($User.Market__c, 'KR'), 'KR',IF(ISPICKVAL($User.Market__c, 'TH'), 'TH','NA')))))</defaultValue>
        <description>For JP users set to JP</description>
        <label>Market Discriminator</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <description>System Field</description>
        <label>MD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>MD__c</fullName>
        <label>MD</label>
        <length>2</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/CampaignMemberHelperBase.cls
/*
    Type:       class
    Purpose:    Campaign Member Helper Base  
    User Story:     
    Used By:    
*/
public class CampaignMemberHelperBase{
   /* Data Migration Explicit Fix - Santosh Mohanty */
    public static void updateCampaignMembermarket(List<CampaignMember> campMemList){       
        
               for(CampaignMember campMem : campMemList){
                    if(Test.isRunningTest()){
                        campMem.isTestRunning__c=true;
                    }
                   if(campMem.Market__c =='' || campMem.Market__c==NULL){
                      campMem.Market__c=campMem.MD__c;
                  }  
              }       
    }    
    public static void updateCampaignMemberCustommarket(List<Campaign_Member__c> campMemCustList){       
        
               for(Campaign_Member__c campMemCust : campMemCustList){
                    if(Test.isRunningTest()){
                        campMemCust.isTestRunning__c=true;
                    }
                   if(campMemCust.Market__c =='' || campMemCust.Market__c==NULL){
                      campMemCust.Market__c=campMemCust.MD__c;
                  }  
              }       
    }
	
	public static void beforeInsertevents(List<CampaignMember> camp,String Market){
		for(CampaignMember ca:camp){
			if(ca.status==''){
			ca.status='Added';
			}

		}
		}
   
}