src/main/metadata/objects/Campaign_member__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to refer the related retail campaign execution record</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign member</relationshipLabel>
        <relationshipName>Campaign_member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to set the status of the campaign member</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bounced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Responded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Campaign member</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Campaign member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/classes/ConvertToDMRequestTest.cls
 @isTest
 public class ConvertToDMRequestTest
 {
   public static Id parentCampaign_RecordTypeID = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Planning & Design Campaign').getRecordTypeId();
   public static testMethod void CampaignTest()
    {
       Test.startTest();
   
       Campaign parentCamp=new Campaign(
             Name='test par',
            EndDate=Date.Today().adddays(-10),
            StartDate=Date.Today(),
            RecordtypeID=parentCampaign_RecordTypeID,
            Status='Responded');
            insert parentCamp;       
              Campaign_Member__c cmm=new Campaign_Member__c(     
             Status__c='Responded',
             Campaign_ID__c=parentCamp.id);
             insert cmm;     
           ConvertToDMRequest controller = new ConvertToDMRequest();
            ConvertToDMRequest.wrapAccount newt =  new ConvertToDMRequest.wrapAccount(cmm); 
            newt.selected = True;
            controller.wrapAccountList.add(newt);
           controller.processSelected();
          
       Test.stopTest();
     }
  }

}