src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CAC_Campaign_Type__c</fullName>
        <description>Used for CAC CRM Campaign reporting purpose. Also used for CAC Campaign. Different LOVs for each controlled by record type.</description>
        <label>CAC Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Auto Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loyalty Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitions and Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Car Launch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad-hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CAC_Frequency_Category__c</fullName>
        <description>Used on CAC Campaign Planning layout. Also used to differentiate the CAC Campaign Calendar view.</description>
        <label>CAC Category</label>
        <picklist>
            <controllingField>Repeated_Campaign__c</controllingField>
            <picklistValues>
                <fullName>Ad Hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular-Continuous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular-Periodic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <externalId>true</externalId>
        <label>Campaign Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Campaign_Objectives__c</fullName>
        <label>Campaign Objectives</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Execution_Type__c</fullName>
        <description>Used only for Campaign Execution record type. To defined the execution channel.</description>
        <label>Execution Type</label>
        <picklist>
            <picklistValues>
                <fullName>OB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Mercedes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repeat_End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Repeat_Frequency__c</fullName>
        <label>Repeat Frequency</label>
        <picklist>
            <controllingField>Repeated_Campaign__c</controllingField>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repeat_From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Repeated_Campaign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Repeated Campaign?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Created_By__c</fullName>
        <label>Task Created By</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <label>Trigger</label>
</CustomObject>

src/main/metadata/classes/CpCallControllerClass_Test.cls
/*
    Type:       Test Class
    Purpose:    Test On Campaign Trigger Coding
     4-June-2013 Stephano Shi (Breakingpoint)    Created
    Patrick Zhang(Breakingpoint) updated on 2013-10-12

*/
@isTest
public with sharing class CpCallControllerClass_Test{
    private static string blank='';
    static testMethod void runCpCallControllerClass_Test(){
    List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
    insert updatecustomsettings;
        Map<String, Schema.RecordTypeInfo> cpRecordTypeMap = Schema.SObjectType.Campaign.getRecordTypeInfosByName();
       
        /* Test Method queAllCamps */
        // DATA Preparation
        // Central Marketing Campaign
        Campaign centralCamp1 = new Campaign(Name='Central Campaign 1',
                                            RecordTypeId=cpRecordTypeMap.get('Central Marketing Campaign').getRecordTypeId(),
                                            Campaign_Code__c='Central Campaign 1',
                                            Type='Other',
                                            Status='Open',
                                            Campaign_Objectives__c='OB',
                                            StartDate=date.newinstance(2013, 5, 17),
                                            EndDate=date.newinstance(2013, 10, 17),
                                            Description = blank 
                                            );
        
        // CAC Campaign
        Campaign cacCamp1 = new Campaign(Name='CAC Campaign 1',
                                         Campaign_Code__c='CAC Campaign 1',
                                         ParentId=centralCamp1.Id,
                                         Repeat_From__c=datetime.newinstance(2013, 5, 17),
                                         Repeat_End__c=datetime.newinstance(2013, 10, 17),
                                         RecordTypeId=cpRecordTypeMap.get('CAC Campaign').getRecordTypeId()
                                         );
        
        // CAC Campaign 2
        Campaign cacCamp2 = new Campaign(Name='CAC Campaign 2',
                                         Campaign_Code__c='CAC Campaign 2',
                                         ParentId=centralCamp1.Id,
                                         Repeated_Campaign__c=true,
                                         Repeat_Frequency__c='Daily',
                                         RecordTypeId=cpRecordTypeMap.get('CAC Campaign').getRecordTypeId()
                                         );     
        
        // Execution Campaign
        Campaign exeCamp1 = new Campaign(Name='Execution Campaign 1',
                                         Campaign_Code__c='Execution Campaign 1',
                                         Execution_Type__c='OB Call',
                                         Task_Created_By__c='Contact',
                                         ParentId=cacCamp1.Id,
                                         RecordTypeId=cpRecordTypeMap.get('Campaign Execution - Simple').getRecordTypeId()
                                         );  
        
        // CAC CRM Campaign
        Campaign cacCrmCamp1 = new Campaign(Name='CAC CRM Campaign 1',
                                            Campaign_Code__c='CAC CRM Campaign 1',
                                            CAC_Campaign_Type__c='Others',
                                            CAC_Frequency_Category__c='Ad Hoc',
                                            Campaign_Objectives__c='objective',
                                            Description='123',
                                            StartDate=date.newinstance(2013, 5, 17),
                                            EndDate=date.newinstance(2013, 10, 17),   
                                            RecordTypeId=cpRecordTypeMap.get('CAC CRM Campaign').getRecordTypeId()
                                            ); 
        
        // CAS Campaign
        Campaign casCamp1 = new Campaign(Name='CAS Campaign 1',
                                            Campaign_Code__c='CAS Campaign 1',                                            
                                            Type='other',
                                            Campaign_Objectives__c='dsfda',
                                            Description='123',
                                            Status='Planned',
                                            StartDate=date.newinstance(2013, 5, 17),
                                            EndDate=date.newinstance(2013, 10, 17),   
                                            RecordTypeId=cpRecordTypeMap.get('CAS Marketing Campaign').getRecordTypeId()
                                            );
       
        Test.startTest();
        insert(centralCamp1);
        insert(cacCamp1);
        insert(cacCamp2);
        insert(exeCamp1);
        insert(cacCrmCamp1);
        insert(casCamp1);
        list<Campaign> listCamp =new list<Campaign> ();
        listCamp.add(casCamp1);
       Campaign casCamp = [select Name,Campaign_Code__c,Description from Campaign where id IN: listCamp];
       
        cpCalController.queAllCamps(blank,blank,blank,blank,blank,blank);
        cpCalController.queAllCamps('2012','2014', String.valueOf(centralCamp1.Id),'Regular-Continuous','CRM Acquisition Program','Auto Show');
        Test.stopTest();
        system.assertEquals(casCamp1.Name, casCamp.Name);
    }
}