src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <description>This field can be used to track the progress of the execution campaign life cycle</description>
        <label>Campaign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <label>Campaign Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Segmentation</fullName>
                </value>
                <value>
                    <fullName>Execution</fullName>
                </value>
                <value>
                    <fullName>Response collection</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Parent_Campaign1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Campaign</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Retail_Campaign__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Planning &amp; Design Campaign</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Retail_Campaign__c</referenceTo>
        <relationshipLabel>Retail Campaigns (Parent Campaign)</relationshipLabel>
        <relationshipName>Retail_Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field can be used to track the progress of the campaign as part of campaign life cycle</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ongoing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/classes/UpdateChildCampaignStatusToNoResponseMY.cls
/* Purpose: Batch class hosting code to be executed for Malaysia. updates the child campaign status to no response  Once the parent campaign reaches its end date
   Date: 01/02/2018
   Created By: Sushma */

global class UpdateChildCampaignStatusToNoResponseMY implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
    String market=System.Label.MarketMY;
    UpdateChildCampaignStatusToNoResponse bag=new UpdateChildCampaignStatusToNoResponse();
    global Database.QueryLocator start(Database.BatchableContext bc) {
         return bag.queryMethod(bc,market);
    }
    global void execute(Database.BatchableContext bc, List<Retail_Campaign__c> scope) {
        set<Retail_campaign__C> retcampaignset=new Set<Retail_campaign__C>();
        List<Retail_campaign__C> retcampaigntoupdate=new List<Retail_campaign__C>();
        for(Retail_campaign__C retcamp:scope){
        //retcamp.Parent_Campaign1__r.status__c='Completed';
        if(retcamp.child_campaign_status__c=='Execution'){
        retcamp.child_campaign_status__c='No Response';
            retcampaignset.add(retcamp);
        }
        //retcampaignset.add(retcamp.Parent_Campaign1__r);
        }
        if(retcampaignset.size()>0){
        retcampaigntoupdate.addAll(retcampaignset);
        update retcampaigntoUpdate;
        }
    }
    global void finish(Database.BatchableContext bc) {
        
        }
    global void execute(SchedulableContext ctx) {
        Database.ExecuteBatch(new UpdateChildCampaignStatusToNoResponseMY(),10);
    }
}