src/main/metadata/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_CCC_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to user to identify the CCC Manger to whom all tasks will be assigned in case of OB execution</description>
        <label>Campaign CCC Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Child_Campaign_Status__c</fullName>
        <description>This field can be used to track the progress of the execution campaign life cycle</description>
        <label>Campaign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Execution_Start_Date__c</fullName>
        <description>This field is used to capture the start date of the execution campaign</description>
        <label>Execution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Execution_Type__c</fullName>
        <description>Used only for Campaign Execution record type. To defined the execution channel.</description>
        <label>Execution Type</label>
        <picklist>
            <picklistValues>
                <fullName>OB Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segmentation Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MyM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eMail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Mercedes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/Batch_CreateCampaignTask.cls
/***********************************************************************************
Created By          :    Siva Krishna k   
Created Date        :    01.18.2017
Company             :    NTT Data,Inc.
Usage               :    Campaign Execution via OB Call Scheduler and Notification
                          
JIRA NO             :    SFDCJP-1013                                               
************************************************************************************/

global class Batch_CreateCampaignTask implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
    
    global List<String> notiMailerList = new List<String>();
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Id devRecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Campaign Execution').getRecordTypeId();
        String strExecutionType = 'OB Call';
        String strChildCampStatus= 'Segmentation';
        Date today = Date.Today();
        String query = 'Select Id, Campaign_CCC_Manager__c, Child_Campaign_Status__c from Campaign Where Execution_Type__c =: strExecutionType AND Child_Campaign_Status__c =: strChildCampStatus'+
                        +' AND Execution_Start_Date__c =:today';
        
        return Database.getQueryLocator(query);
    
    }
     
    
    global void execute(Database.BatchableContext bc, List<Campaign> scope) {
        
        List<Task> tskList = new List<Task>();
        List<Campaign> campList = new List<Campaign>();

        for(Campaign camp : scope){
            Task task = new Task();
            task.WhatID = camp.Id;
            task.Status = 'Completed';
            task.Type = 'Campaign';
            task.subject = 'Campaign Executed';
            task.ownerId = camp.Campaign_CCC_Manager__c;
            task.priority = 'Normal';
            camp.Child_Campaign_Status__c = 'Execution';
            tskList.add(task);
            campList.add(camp);  
            if(camp.Campaign_CCC_Manager__c != null){
                notiMailerList.add(camp.Campaign_CCC_Manager__c);
            }
        }
        if(tskList.size() > 0){
            Database.insert(tskList,false);
        }
        if(campList.size() > 0){
            Database.update(campList,false);
        }
    }
    
    global void finish(Database.BatchableContext bc) {
       
       EmailTemplate templateId = [Select id from EmailTemplate where name = 'test email'];
       List<Messaging.SingleEmailMessage> msgList= new List<Messaging.SingleEmailMessage>();
       
       for(String userId : notiMailerList){
           Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
           msg.SetsaveAsActivity(false); 
           msg.setTemplateId(templateId.Id);
           msg.setTargetObjectId(userId);  
           msgList.add(msg);
       }
       Messaging.sendEmail(msgList);    
    }
    
    
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new Batch_CreateCampaignTask ());
    }
}