src/main/metadata/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Dealer in regards of complaint 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Primary Case Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Dealer)</relationshipLabel>
        <relationshipName>Dealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Contact__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Complainant refused dealer contact 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Dealer Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ref_No_Central__c</fullName>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: Central document reference number 
Used in: Page Layouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/</description>
        <label>Ref No. Central</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendEmailToGateKeeper__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email to Gate Keeper</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Community_License_Switch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>used to switch off/on the portal specific apex classes.</description>
    <fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the community enabled for the market specific (default is disabled).</description>
        <label>Enable</label>
        <type>Checkbox</type>
    </fields>
    <label>Community License Switch</label>
</CustomObject>

src/main/metadata4au/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Dealer_Complaint_Gate_Keeper__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Permission set:</inlineHelpText>
        <label>Dealer Complaint Gate Keeper</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata-au/objects/Trigger__c.object
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>2</length>
        <type>Text</type>
    </fields>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/classes/AssignCaseToDealerControllerTest.cls
/*
    Type:       Test Class
    Purpose:    Test On AssignCaseToDealerController
    1. Chaos Created on 2014-02-24

*/
@isTest
public Without Sharing class AssignCaseToDealerControllerTest {  
    
    final static String MBRecordtypeid = Schema.SObjectType.Case.getRecordTypeInfosByName().
                                                get('MB Complaint').getRecordTypeId();
    private static user user1;
    private static user user2;
    private static User Usr;
    private static User portalUser;
    private static user selectedUser;
    Private static Case c;  
    Private static Community_License_Switch__c cls;
   
    public static void preparedTestData()
    {
        List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
        //insert updatecustomsettings;
        Trigger__c newtrg = new Trigger__c(Name= 'TriggerDMRequest1',Trigger_Name__c = 'TriggerAccountLink',Trigger_Handler__c = 'TriggerAccountLinkTriggerHandlerJP',Market__c ='JP',
                               enabled__c = False,after__c= False,before__c= False,delete__c= False,update__c= False,insert__c= False);
        insert newtrg;
       //Creating User   
        user1=UtilTestData.createPortalUser('Dealer User','Dealer Community User');
        user2=UtilTestData.createPortalUser('Dealer User','Dealer Delegate Admin'); 
       //creating custom setting  
       cls=new Community_License_Switch__c();
       cls.Enable__c=true;
       cls.name='Community Enabled';
       insert cls;  
       //AssignCaseToDealerController.userName=user2.name;
        portalUser = [select name,accountId,email from user where contact.Dealer_Complaint_Gate_Keeper__c = true and id =:user1.Id and isActive = true limit 1];  
     
       selectedUser = [select name,accountId,email from user where id =:user2.Id and contact.Dealer_Complaint_Gate_Keeper__c = true and isActive = true limit 1];                               
    
       //Creating Case       
        c = new Case(Subject='For Controller test',
                                  RecordTypeId = MBRecordtypeid, 
                                  Ref_No_Central__c = 'test',
                                  Case_Dealer__c = portalUser.AccountId,
                                  Dealer_Contact__c = 'YES');
       insert c; 
     
    }
    
    public static testMethod void testquery() 
    {
      
        //Added community license switching mechanism     
          preparedTestData();
            Usr=[select id from user where id=:UserInfo.getuserId()];
            System.runAs(usr) {
                Test.startTest();         
               
                Test.setCurrentPage(Page.AssignCaseToDealer);
                ApexPages.currentPage().getParameters().put('caseId', c.Id);
                AssignCaseToDealerController con = new AssignCaseToDealerController();
                con.userName=selectedUser.name;
                con.query();          
                Test.stopTest();
               system.assert(user1!=null);
               System.assertEquals(portalUser.AccountId,c.Case_Dealer__c); 
             }
       
    } 
      
    public static testMethod void testclear() 
    { 
        preparedTestData();
            Usr=[select id from user where id=:UserInfo.getuserId()];
            System.runAs(usr) {
                Test.startTest(); 
                Test.setCurrentPage(Page.AssignCaseToDealer);
                ApexPages.currentPage().getParameters().put('caseId', c.Id);
                AssignCaseToDealerController con = new AssignCaseToDealerController();    
                con.clear();         
                Test.stopTest();
                system.assert(user1!=null);
                system.assertEquals(portalUser.AccountId,c.Case_Dealer__c);
                system.assertEquals(con.hasQueryResult,false); 
                
             }       
    }
    public static testMethod void testassign() 
    {
       preparedTestData();
            Usr=[select id from user where id=:UserInfo.getuserId()];
            System.runAs(usr) {
                Test.startTest(); 
                Test.setCurrentPage(Page.AssignCaseToDealer);
                ApexPages.currentPage().getParameters().put('caseId', c.Id);
                AssignCaseToDealerController con = new AssignCaseToDealerController();       
                con.selectedUserId = selectedUser.Id;
                con.assign();
                Test.stopTest();
               system.assert(user1!=null);
                system.assertEquals(portalUser.AccountId,c.Case_Dealer__c);
                system.assertEquals(selectedUser.Id,con.assignCase.ownerId);
                system.assertEquals(c.SendEmailToGateKeeper__c,false);   
             }
    }
}