src/main/metadata/objects/Environment_Specific_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Environment Specific Values</label>
</CustomObject>

src/main/metadata/objects/Trigger_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Create a Custom Setting called "Trigger Status" with 2 fields - Trigger Name, Enabled (Yes/No)

On top of every trigger, check the Enabled value of the correspondent trigger in "Trigger Status", exit if Enabled = 'No'
(This should be wrapped in a Helper/Utility class function)

This way we can easily enabled/disable all/individual trigger any time we need it.</description>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Create a Custom Setting called "Trigger Status" with 2 fields - Trigger Name, Enabled (Yes/No)

On top of every trigger, check the Enabled value of the correspondent trigger in "Trigger Status", exit if Enabled = 'No'
(This should be wrapped in a Helper/Utility class function)

This way we can easily enabled/disable all/individual trigger any time we need it.</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Status</label>
</CustomObject>

src/main/metadata/classes/UtilCustomSettings.cls
/*
    Type:       Utility for disable trigger 
    Purpose:    This way we can easily enabled/disable all/individual trigger
    User Story: Every Trigger
    Used By:    All Triggers
    ---------------------------------------------------------------
    History:
    
    1. Mouse Created on 2013-05-06
*/
public class UtilCustomSettings {
    public static Boolean isEnabled(String triggerName) {
	    if (triggerName != null && Trigger_Status__c.getAll().get(triggerName) != null) {
            return Trigger_Status__c.getAll().get(triggerName).Enabled__c;         
		}
		else {
            // If no corresonding data, just assign default true
		    return true;
		}
    }
    
    public static Id getProfileId(String profileName)
    {
	    if (profileName != null && Environment_Specific_Values__c.getAll().get(profileName) != null) {
            return Environment_Specific_Values__c.getAll().get(profileName).Value__c;         
		}
		else {
		    return null;
        }
    }
}