src/main/metadata/objects/External_Key__c.object
<CustomObject>
    <description>External Key</description>
    <label>External Key</label>
    <nameField>
        <label>External Key Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Key</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/External_Picklist__c.object
<CustomObject>
    <description>External values for integration picklists.</description>
    <fields>
        <fullName>External_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used for updates by Data Loader only.</description>
        <externalId>true</externalId>
        <inlineHelpText>Used for updates by Data Loader only.</inlineHelpText>
        <label>External Key</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Integration_Picklist__c</fullName>
        <label>Integration Picklist</label>
        <referenceTo>Integration_Picklist__c</referenceTo>
        <relationshipLabel>External Picklists</relationshipLabel>
        <relationshipName>External_Picklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Picklist_Mapping__c</fullName>
        <formula>Integration_Picklist__r.Picklist_Mapping__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Picklist Mapping</label>
        <type>Text</type>
    </fields>
    <label>External Picklist</label>
    <nameField>
        <label>External Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-retrieve/objects/Integration_Picklist__c.object
<CustomObject>
    <description>Values for integration picklists.</description>
    <fields>
        <fullName>External_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used for updates by Data Loader only.</description>
        <externalId>true</externalId>
        <inlineHelpText>Used for updates by Data Loader only.</inlineHelpText>
        <label>External Key</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Integration_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this checkbox is checked, no value is available in the picklist in SFDC for this Integraton Value. Otherwise a picklist value must be provided.</description>
        <inlineHelpText>If this checkbox is checked, no value is available in the picklist in SFDC for this Integraton Value. Otherwise a picklist value must be provided.</inlineHelpText>
        <label>Integration Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Picklist_Mapping__c</fullName>
        <label>Picklist Mapping</label>
        <referenceTo>Picklist_Mapping__c</referenceTo>
        <relationshipLabel>Integration Picklists</relationshipLabel>
        <relationshipName>Integration_Picklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Integration Picklist</label>
    <nameField>
        <label>Integration Value</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata-retrieve/objects/Picklist_Mapping__c.object
<CustomObject>
    <description>Maps from picklists defined by object and field to LOV name.</description>
    <fields>
        <fullName>External_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used for updates by Data Loader only.</description>
        <externalId>true</externalId>
        <inlineHelpText>Used for updates by Data Loader only.</inlineHelpText>
        <label>External Key</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Integration_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should be checked if this LOV is used in EP only and does not relate to a picklist in SFDC.</description>
        <inlineHelpText>Should be checked if this LOV is used in EP only and does not relate to a picklist in SFDC.</inlineHelpText>
        <label>Integration Only</label>
        <type>Checkbox</type>
    </fields>
    <label>Picklist Mapping</label>
    <nameField>
        <label>LOV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata-circle/classes/PicklistMappingHelperTest.cls
@isTest
public class PicklistMappingHelperTest {

    @isTest
    public static void testExternalKeyNotEmpty() {
        Integration_Picklist__c ip = new Integration_Picklist__c();
        ip.External_Key__c = 'IP-123456';
        
        List<Integration_Picklist__c> triggerNew = new List<Integration_Picklist__c>();
        triggerNew.add(ip);
        
        PicklistMappingHelper.updateExternalKey(triggerNew, 'IP'); 
        
        System.assert('IP-123456'.equals(triggerNew[0].External_Key__c));
    }
    
    @isTest
    public static void testExternalKeyNotEmptyFormatMismatch() {
        Integration_Picklist__c ip = new Integration_Picklist__c();
        ip.External_Key__c = 'IP-12345';
        
        List<Integration_Picklist__c> triggerNew = new List<Integration_Picklist__c>();
        triggerNew.add(ip);
        
        PicklistMappingHelper.updateExternalKey(triggerNew, 'IP'); 
        
        System.assert('IP-000001'.equals(triggerNew[0].External_Key__c));
    }
    
    @isTest
    public static void testNoExistingObjects() {
        List<Integration_Picklist__c> triggerNew = new List<Integration_Picklist__c>();
        triggerNew.add(new Integration_Picklist__c());
        
        PicklistMappingHelper.updateExternalKey(triggerNew, 'IP');
        
        System.assert('IP-000001'.equals(triggerNew[0].External_Key__c));   
    }
    
    @isTest
    public static void testExistingObjects() {
        Picklist_Mapping__c existingPM = new Picklist_Mapping__c(External_Key__c='PM-000122', Name='LOV', Integration_Only__c=true);
        insert existingPM;
        
        List<Picklist_Mapping__c> triggerNew = new List<Picklist_Mapping__c>();
        triggerNew.add(new Picklist_Mapping__c());
        
        PicklistMappingHelper.updateExternalKey(triggerNew, 'PM');
        
        System.assert('PM-000123'.equals(triggerNew[0].External_Key__c));   
    }
    
    @isTest
    public static void testMultipleNewValues() {
        List<Integration_Picklist__c> triggerNew = new List<Integration_Picklist__c>();
        triggerNew.add(new Integration_Picklist__c());
        
        Integration_Picklist__c ip = new Integration_Picklist__c();
        ip.External_Key__c = 'IP-000006';
        triggerNew.add(ip);
        triggerNew.add(new Integration_Picklist__c());
        
        PicklistMappingHelper.updateExternalKey(triggerNew, 'IP');
        
        System.assert(3 == triggerNew.size());
        System.assert('IP-000007'.equals(triggerNew[0].External_Key__c));
        System.assert('IP-000006'.equals(triggerNew[1].External_Key__c));
        System.assert('IP-000008'.equals(triggerNew[2].External_Key__c));
    }
    
    @isTest
    public static void testPicklistMappingBeforeTrigger() {
        Picklist_Mapping__c newPM = new Picklist_Mapping__c(Name='LOV', Integration_Only__c=true);
        insert newPM;
        
        Picklist_Mapping__c savedPM = [SELECT External_Key__c FROM Picklist_Mapping__c WHERE Id =: newPM.Id];
        
        System.assertEquals('PM-000001', savedPM.External_Key__c);
    }
    
    @isTest
    public static void testIntegrationPicklistBeforeTrigger() {
        Picklist_Mapping__c newPM = new Picklist_Mapping__c(Name='LOV', Integration_Only__c=true);
        insert newPM;
        
        Integration_Picklist__c newIP = new Integration_Picklist__c(Picklist_Mapping__c=newPM.Id, Name='IV', Integration_Only__c=true);
        insert newIP;
        
        Integration_Picklist__c savedIP = [SELECT External_Key__c FROM Integration_Picklist__c WHERE Id =: newIP.Id];
        
        System.assertEquals('IP-000001', savedIP.External_Key__c);
    }
    
    @isTest
    public static void testExternalPicklistBeforeTrigger() {
        Picklist_Mapping__c newPM = new Picklist_Mapping__c(Name='LOV', Integration_Only__c=true);
        insert newPM;
        
        Integration_Picklist__c newIP = new Integration_Picklist__c(Picklist_Mapping__c=newPM.Id, Name='IV', Integration_Only__c=true);
        insert newIP;
        //TODO: Added External_Key__c='EP-000001'
        External_Picklist__c newEP = new External_Picklist__c(Integration_Picklist__c=newIP.Id,External_Key__c='EP-000001');
        insert newEP;
        
        External_Picklist__c savedEP = [SELECT External_Key__c FROM External_Picklist__c WHERE Id =: newEP.Id];
        
        System.assertEquals('EP-000001', savedEP.External_Key__c);
    }
}