src/main/metadata/objects/Functionality_Access_Master__c.object
<CustomObject>
    <fields>
        <fullName>Module_Name__c</fullName>
        <externalId>true</externalId>
        <label>Module Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Functionality Access Master</label>
    <nameField>
        <displayFormat>FAM-{0000}</displayFormat>
        <label>Functionality Access Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functionality Access Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Market</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/Persona__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Functionality_Access__c</fullName>
        <label>Functionality Access</label>
        <referenceTo>Functionality_Access_Master__c</referenceTo>
        <relationshipName>Market_Access_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>Market_Access__r.Market_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonaName__c</fullName>
        <label>Persona Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProfileId__c</fullName>
        <label>ProfileId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Persona</label>
    <nameField>
        <displayFormat>MAJ-{0000}</displayFormat>
        <label>Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persona</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/metadata/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/metadata-au/objects/User.object
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>ChangesMadeInAssignedPersona__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to check if any changes made in the persona after assigned to user</description>
        <label>ChangesMadeInAssignedPersona</label>
        <type>Checkbox</type>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Market__c</fullName>
        <description>Set to JP</description>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>KR</fullName>
                </value>
                <value>
                    <fullName>MY</fullName>
                </value>
                <value>
                    <fullName>TH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/User.object
    <fields>
        <fullName>Persona_Assigned__c</fullName>
        <label>Persona Assigned</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/main/metadata/classes/MRC_AssignPersonaToUserExt.cls
/*******************************************************************************************
* Class:                            MRC_AssignPersonaToUserExt 
* Description:                      This class is used to update persona of user based on the value selected from persona list. 
* ------------------------------------------------------------------------------------------
* Date          Name                   Modification Description
* 20/4/2017     Harshit Kabra           Modified  

===========================================================================================*/
public class MRC_AssignPersonaToUserExt {
    
    public boolean isError{get; set;}
    public String isPersona {get;set;}
    public List<Persona__c> majList{get;set;}
    public id UserId{get;set;}
    public User u{get;set;}
    public ID selMajID{get;set;}
    public Persona__c selectedMaj{get;set;}
    public String assignedMajID{get;set;}
    public Persona__c AssignedMaj{get;set;}
    public MRC_AssignPersonaToUserExt(ApexPages.StandardController controller) 
    {  isError=false;
       UserId=ApexPages.currentPage().getParameters().get('id');
       u= [select Market__c,Persona_Assigned__c,ChangesMadeInAssignedPersona__c from User where id =: UserId]; 
       if(u.Market__c == null)
       {   isError=true;
           ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter user market before assigning Persona'));
          
       }
        else{
            if(u.Persona_Assigned__c != null) AssignedMaj = [Select PersonaName__c,Functionality_Access__r.Module_Name__c from Persona__c where PersonaName__c =: u.Persona_Assigned__c ]; 
            if(AssignedMaj != null) 
             {assignedMajID  = AssignedMaj.id;
              isPersona=assignedMajID ;
             } 
           //assignedMajID = assignedMajID.left(15);
            majList=new List<Persona__c>();
            majList=[Select id,PersonaName__c,Functionality_Access__r.Module_Name__c from Persona__c where Active__c= True and Market__c=:u.Market__c ];
            if(majList != null && majList.size()==0)
            {
                isError=true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No Persona is present for the market of user'));
            }
        } 
    }
    
    public List<selectOption> getPersonas(){
         List<SelectOption> options = new List<SelectOption>();
        if(majList != null && majList.size()>0){
          for(Persona__c p: majList)
          {   String s=p.PersonaName__c+'   -   '+p.Functionality_Access__r.Module_Name__c;
              //String s=p.PersonaName__c;
              
              options.add(new SelectOption(p.id,s));
          }
        return options;   
       }
        return null;


        
    }    

    public pagereference selectPersona()
    {
        system.debug('!!!!!@@'+isPersona);
        selectedMaj=[Select name,id,PersonaName__c,ProfileId__c from Persona__c where id=: isPersona];
        u.Persona_Assigned__c=selectedMaj.PersonaName__c;
        u.ProfileId=selectedMaj.ProfileId__c;
        //ChangesMadeInAssignedPersona__c is false:  as we are assigning new persona, not making change in existing.
        u.ChangesMadeInAssignedPersona__c=false;
        DMLManagerService.updateAsSystem(u); 
        return new Pagereference('/'+u.id+'?noredirect=1&isUserEntityOverride=1');
       
    }
    
    public pagereference cancel()
    {
        return new Pagereference('/'+u.id+'?noredirect=1&isUserEntityOverride=1');
    }

    
}