src/main/metadata/objects/Ideas__c.object
<CustomObject>
    <label>Idea</label>
    <nameField>
        <label>Idea Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Idea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/objects/IdeasVoting__c.object
<CustomObject>
    <fields>
        <fullName>Ideas__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Its lookup to an idea</description>
        <label>Ideas</label>
        <referenceTo>Ideas__c</referenceTo>
        <relationshipLabel>IdeasVoting</relationshipLabel>
        <relationshipName>IdeasVoting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Likeuser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Its lookup to an user</description>
        <label>Likeuser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IdeasVoting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IdeasVoting</label>
    <nameField>
        <displayFormat>IV-{0000}</displayFormat>
        <label>IdeaVoting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IdeasVoting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata/classes/StarRatingControllerTest.cls
/************************************************************************************
* Created By:Sarath M
* Created Date:11-Dec-17
* Company:Infosys Ltd
* Description: Testclass for starRatingControllerTest
* ***********************************************************************************/
@isTest
public class StarRatingControllerTest {
    
    static testmethod void test_createRatingDB(){
        ideas__c ideaTest=Rug_util.newIdea(); 
        Decimal rating=0;
        rating =4;
        test.startTest();
        StarRatingController.createRatingDB(rating,ideaTest.id);
        system.assertNotEquals(null, ideaTest.id);
        test.stopTest();
    }
    static testMethod void test_getRatingOnLoad(){
        ideas__c ideaTest=Rug_util.newIdea(); 
        Integer num=StarRatingController.getRatingOnLoad(ideaTest.Id);
        System.assertnotEquals(null,num);
    }
    static testMethod void test_getPointsCount(){
        ideas__c ideaTest=Rug_util.newIdea();
        IdeasVoting__c ideaVotingObj = new IdeasVoting__c(Ideas__c = ideaTest.id, rating__c= 4,Likeuser__c=userinfo.getUserId());
        Integer num=StarRatingController.getPointsCount(ideaTest.Id);
        System.assertnotEquals(null,num);
    }
    static testMethod void test_getRatingEnableValue(){
        user testHonorary=Rug_util.honoraryProfileUser();
        ideas__c ideaTest=Rug_util.newIdea();
        system.runas(testHonorary){
            boolean result=StarRatingController.getRatingEnableValue(ideaTest.Id);        
            System.assertEquals(false,result);  
        }
    } 
    
}