src/main/metadata/objects/Lead__c.object
<CustomObject>
    <description>Lead: purchase intention of customer</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Lead_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Lead_Status__c</fullName>
        <label>Dealer Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Failed For 3 Days(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Contact Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visited Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Placed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased(Only Non BDC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost(Dealer)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/stouchUtilForLead.cls
@RestResource(urlMapping='/stouchUtilForLead/*')
global without sharing class stouchUtilForLead {
    @HttpPost
    global static Map<String,String> LeadIfnoSendToAL(){
        String jsonText = RestContext.request.requestBody.toString();
        Map<String, Object> cObjMap = (Map<String, Object>) JSON.deserializeUntyped(jsonText);
        Object res=cObjMap.get('data');
        Map<String,Object> obj= (Map<String,Object>)res;
        String LeadId=(String)obj.get('LeadId');
        String DealerID=(String)obj.get('DealerID');
        String AccountLinkId=(String)obj.get('AccountLinkId');
        map<String,String> response=new Map<String,String>();
        list<lead__c> ld=[select id,Dealer_Lead_Status__c,Contact__c from Lead__c where id=:LeadId];
        response.put('Message', system.Label.This_Lead_cannot_be_send_to_Autoline);
        system.debug(ld);
        if(ld.size()>0){
            if(ld[0].Dealer_Lead_Status__c=='Lost' || ld[0].Contact__c==null || ld[0].Dealer_Lead_Status__c=='Purchased(Only Non BDC)' ){
                response.put('Message', system.Label.This_Lead_cannot_be_send_to_Autoline);
            }
            else{
                try{
                    UtilWebservice.LeadIfnoSendToAL(LeadId, DealerID, AccountLinkId);
                   response.put('Message', system.Label.Successfully_Sent_Information_to_AutoLine);
                }
                catch(Exception ex){
                   response.put('Message', system.Label.Web_service_callout_failed);
                }
                
            }
        }
        return response;
    }
}