src/main/metadata/objects/News__c.object
<CustomObject>
    <description>This Object is used to create and post new updates or news on Bulletin.</description>
    <fields>
        <fullName>Category_Type__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>After Sales</fullName>
                </value>
                <value>
                    <fullName>Network Development</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Logistic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Allows users to enter up to 131,072 characters on separate lines.</description>
        <inlineHelpText>Allows users to enter up to 131,072 characters on separate lines.</inlineHelpText>
        <label>Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Need_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>content that should be approved, and also decide if the content does not need approval</description>
        <label>Need Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Save_As_Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Content Author can save News as Draft. Which we cannot publish until check box unchecked.</description>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_With_Groups__c</fullName>
        <label>Share With Groups</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RCP_NewsReader_All</fullName>
                </value>
                <value>
                    <fullName>RCP_NewsReader_Restricted_1</fullName>
                </value>
                <value>
                    <fullName>RCP_NewsReader_Restricted_2</fullName>
                </value>
                <value>
                    <fullName>RCP_NewsReader_Restricted_3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <label>News</label>
    <nameField>
        <displayFormat>Bulletin-{00000}</displayFormat>
        <label>News Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <recordTypes>
        <fullName>News</fullName>
        <active>true</active>
        <description>This record type used in News creation</description>
        <label>News</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/newsReport_Test.cls
@isTest
public class newsReport_Test {

@isTest
public static void getDetails_test(){
    

    News__c news = new News__c();
    news.Title__c = 'Test News';
    news.Start_Date__c = Date.today();
    news.Expiration_Date__c = Date.today().adddays(5);
    news.Share_With_Groups__c = 'RCP_NewsReader_All';
    news.Save_As_draft__c = true;
    news.Need_approval__c = false;
    news.Description__c = 'test';
    news.Category_Type__c='Logistic';
    insert news; 
    //inserting File
    ContentVersion contentVersion = new ContentVersion(
        Title = 'Penguins',
        PathOnClient = 'Penguins.jpg',
        VersionData = Blob.valueOf('Test Content'),
        IsMajorVersion = true
    );
    insert contentVersion;    
    List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
    
    //create ContentDocumentLink  record 
    ContentDocumentLink cdl = New ContentDocumentLink();
    cdl.LinkedEntityId = news.id;
    cdl.ContentDocumentId = documents[0].Id;
    //cdl.shareType = 'I';
    insert cdl;
    //
    newsReport.getDetails();
    
}
}