src/main/metadata/objects/News__c.object
<CustomObject>
    <description>This Object is used to create and post new updates or news on Bulletin.</description>
    <fields>
        <fullName>Approver_List__c</fullName>
        <inlineHelpText>For multiple approvers, Please use CTRL + Select Approver.</inlineHelpText>
        <label>Approver List</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>WorkFlow_Group__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Director</fullName>
                </value>
                <value>
                    <fullName>After Sales Committee</fullName>
                </value>
                <value>
                    <fullName>After Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>ND Manager</fullName>
                </value>
                <value>
                    <fullName>Approver1</fullName>
                </value>
                <value>
                    <fullName>Approver10</fullName>
                </value>
                <value>
                    <fullName>Approver11</fullName>
                </value>
                <value>
                    <fullName>Approver12</fullName>
                </value>
                <value>
                    <fullName>Approver2</fullName>
                </value>
                <value>
                    <fullName>Approver3</fullName>
                </value>
                <value>
                    <fullName>Approver4</fullName>
                </value>
                <value>
                    <fullName>Approver5</fullName>
                </value>
                <value>
                    <fullName>Approver6</fullName>
                </value>
                <value>
                    <fullName>Approver7</fullName>
                </value>
                <value>
                    <fullName>Approver8</fullName>
                </value>
                <value>
                    <fullName>Approver9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>News</label>
    <nameField>
        <displayFormat>Bulletin-{00000}</displayFormat>
        <label>News Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/GetDependentPicklistValues_Test.cls
/**
Type:       Test class for GetDependentPicklistValues    
Purpose:    1. Code coverage for GetDependentPicklistValues class

User Story: RCP-141
Used By:    
---------------------------------------------------------------
History:

28-Sep-2018 Surendranath  Created
*/
@isTest
public class GetDependentPicklistValues_Test {
    
    @isTest
    public static void Test_Case(){        
        GetDependentPicklistValues.getDependentPicklistValues('News__c.Approver_List__c');        
    }
}