src/main/metadata/objects/News__c.object
<CustomObject>
    <description>This Object is used to create and post new updates or news on Bulletin.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Allows users to enter up to 131,072 characters on separate lines.</description>
        <inlineHelpText>Allows users to enter up to 131,072 characters on separate lines.</inlineHelpText>
        <label>Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DocStatus_FileUpload__c</fullName>
        <defaultValue>false</defaultValue>
        <description>variable using for file upload from UI if doc status is ready to publish</description>
        <label>DocStatus_FileUpload</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Need_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>content that should be approved, and also decide if the content does not need approval</description>
        <label>Need Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Save_As_Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Content Author can save News as Draft. Which we cannot publish until check box unchecked.</description>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_With_Groups__c</fullName>
        <label>Share With Groups</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RCP_NewsReader_All</fullName>
                </value>
                <value>
                    <fullName>RCP_NewsReader_Restricted_1</fullName>
                </value>
                <value>
                    <fullName>RCP_NewsReader_Restricted_2</fullName>
                </value>
                <value>
                    <fullName>RCP_NewsReader_Restricted_3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <label>News</label>
    <nameField>
        <displayFormat>Bulletin-{00000}</displayFormat>
        <label>News Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <recordTypes>
        <fullName>News</fullName>
        <active>true</active>
        <description>This record type used in News creation</description>
        <label>News</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/ContentDocumentLinkHandler_Test.cls
@isTest
public class ContentDocumentLinkHandler_Test {
    @isTest
    public static void shareFilesWithCommunityUsers_Test(){
        News__c news = new News__c();
        news.Title__c = 'Test News1';
        news.Start_Date__c = Date.today();
        news.Expiration_Date__c = Date.today().adddays(5);
        news.Share_With_Groups__c = 'RCP_NewsReader_All';
        news.Save_As_draft__c = true;
        news.Need_approval__c = false;
        news.Description__c = 'test';
        insert news; 
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = news.id;
        cdl.ContentDocumentId = documents[0].Id;
        //cdl.shareType = 'I';
        insert cdl;
      	system.assert(cdl.Id != null);
        news.Save_As_Draft__c=false;
        news.DocStatus_FileUpload__c=false;
        update news;
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl2 = New ContentDocumentLink();
        cdl2.LinkedEntityId = news.id;
        cdl2.ContentDocumentId = documents[0].Id;
        //cdl1.shareType = 'I';
        DmlException expectedException;
        try
        {
            // save record which should be prevented from saving
              insert cdl2;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('Insert failed') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
       
    }
}