src/main/metadata/objects/QC__c.object
<CustomObject>
    <description>QC: Quality Control record based on a outbound call or SSI record</description>
    <fields>
        <fullName>Approved__c</fullName>
        <description>share to Sinotrust user</description>
        <label>Approved</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Qualified__c</fullName>
        <description>If all the Fatal score equal to &apos;High&apos;or &apos;Medium&apos; ， system will update Qualified to be &apos;Pass&apos;.
Otherwise system will update Qualified to be &apos;Fail&apos;.
Fatal score refers to &apos;SSI Quality standards and algorithms 2&apos;.</description>
        <label>Qualified</label>
        <picklist>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SSI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup related SSI record</description>
        <label>SSI</label>
        <referenceTo>SSI__c</referenceTo>
        <relationshipLabel>QC</relationshipLabel>
        <relationshipName>QC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QC</label>
    <nameField>
        <displayFormat>QC-{000000}</displayFormat>
        <label>QC No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/SSI__c.object
<CustomObject>
    <description>SSI: To record each SSI record</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmatched</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SSI</label>
    <nameField>
        <displayFormat>SSI-{000000}</displayFormat>
        <label>SSI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-excluded/objects/Survey_Result__c.object
<CustomObject>
    <description>SSI: To record SSI survey result</description>
    <fields>
        <fullName>SSI_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SSI Record</label>
        <referenceTo>SSI__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Result No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/QCMassApprovalControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class QCMassApprovalControllerTest {

    static testMethod void myUnitTest() {
    
        SSI__c ssi = new SSI__c();
        insert ssi;
        
        Survey_Result__c sr = new Survey_Result__c();
        sr.SSI_Record__c = ssi.Id;
        insert sr;
        
        QC__c qc1 = new QC__c(Survey_Result__c = sr.Id, SSI__c = ssi.Id, Status__c = 'Complete');
        insert qc1;
        qc1.Qualified__c = 'Pass';
        update qc1;
        
        QC__c qc2 = new QC__c(Survey_Result__c = sr.Id, SSI__c = ssi.Id, Status__c = 'Complete');
        insert qc2;
        qc2.Qualified__c = 'Fail';
        update qc2;
    
        // Test Start
        Test.startTest();
        
        PageReference pr = new PageReference('/apex/QCMassApproval?objIds=' + qc1.Id + ',' + qc2.Id);
        Test.setCurrentPage(pr);
        
        QCMassApprovalController con = new QCMassApprovalController();
        con.massApproved();
        
        qc1 = [Select Approved__c From QC__c Where Id = :qc1.Id];
        qc2 = [Select Approved__c From QC__c Where Id = :qc2.Id];
        
        System.assertEquals(qc1.Approved__c, 'Yes');
        System.assertEquals(qc2.Approved__c, null);
        
        Test.stopTest();
    }
}