src/main/metadata/objects/Retail_Task__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contractor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retail Tasks (Account Name)</relationshipLabel>
        <relationshipName>Retail_Tasks5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Balance_Update_Date__c</fullName>
        <label>Update date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Common_Comments__c</fullName>
        <label>Common Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Loan_Principal__c</fullName>
        <label>Loan Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_lease_extention_Date__c</fullName>
        <label>Maximum lease extention Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parent Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Re_lease_Prohibit_flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Re-lease Prohibit flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Split_Payment_Comission_Fee__c</fullName>
        <label>Total Interest Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pullback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for cancellation approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subrogation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consent Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forced Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Owner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Suspend_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suspend Payment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Split_Payment__c</fullName>
        <label>Total Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Retail Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Tasks</pluralLabel>
    <recordTypes>
        <fullName>Contract</fullName>
        <active>true</active>
        <label>Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/LeaseRetailTask.cls
public class LeaseRetailTask
{
public LeaseRetailTask() 
{
}
public list<Retail_Task__c>Leaselist{get;set;}
public id acc;
public LeaseRetailTask(apexpages.standardcontroller controller)
{
    acc= ApexPages.currentPage().getParameters().get('id');
    Leaselist=[Select Name,Common_Comments__c,Maximum_lease_extention_Date__c,Re_lease_Prohibit_flag__c,Source_System__c,Status__c,Suspend_Payment__c,Balance_Update_Date__c,Loan_Principal__c,Parent_Flag__c,Split_Payment_Comission_Fee__c,Total_Split_Payment__c from Retail_Task__c  where Account__c=:acc and Recordtype.name=:'Lease Contract'];
}
}