src/main/metadata/objects/Retail_Task__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Month__c</fullName>
        <label>Booking Month</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_Change_Date__c</fullName>
        <label>Date of contract condition change</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Condition_Change__c</fullName>
        <label>Change of Contract Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Contract Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Replacement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contractor_Address1__c</fullName>
        <label>Address (kanji)-Actual</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contractor_BirthDate__c</fullName>
        <label>Contractor Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contractor_Name_Native__c</fullName>
        <label>Contractor Name (katakana)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contractor_Name__c</fullName>
        <label>Contractor Name (kanji)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contractor_Phone1__c</fullName>
        <label>Phone1-Actual</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contractor_ZipCode1__c</fullName>
        <label>Zip Code-Actual</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Company__c</fullName>
        <label>Insurance Company</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mitsui Sumitomo Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tokyo Marine &amp; Nichido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sompo Japan Nipponkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aioi Nissay Dowa</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Insured_Name_Native__c</fullName>
        <label>Insured Name (Kana)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Premium2__c</fullName>
        <label>Net premium(2nd Year   long-term policy)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Premium3__c</fullName>
        <label>Net premium(3rd Year   long-term policy)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Premium__c</fullName>
        <label>Net premium</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Non_MB_Insurance__c</fullName>
        <label>Non MB Branded Insurance</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outlet_Name__c</fullName>
        <label>Outlet Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment method of long term</label>
        <picklist>
            <picklistValues>
                <fullName>Lump-Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Premium_Change__c</fullName>
        <label>Change of premium</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vehicle_Registration_No__c</fullName>
        <label>Vehicle Registration No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Retail Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/RelatedDealerViewForInsuranceTest.cls
@isTest
public class RelatedDealerViewForInsuranceTest
{
    public static Retail_Task__c Ins;
    static Testmethod void ValidateInsurance()
        {
            Ins=new Retail_Task__c();
            Ins.Contractor_Address1__c='Test1';
            Ins.Booking_Month__c='may';
            Ins.Condition_Change__c='Test2';
            Ins.Premium_Change__c=3465;
            Ins.Company_Name__c='Vcs';
            Ins.Contractor_BirthDate__c=date.today()-10;
            Ins.Contractor_Name__c='rama';
            Ins.Contractor_Name_Native__c='rama1';
            Ins.Condition_Change_Date__c=date.today()-5;
            Ins.Insurance_Company__c='vccs';
            Ins.Insured_Name_Native__c='vccs1';
            Ins.Net_Premium__c=123.00;
            Ins.Net_Premium2__c=456.00;
            Ins.Net_Premium3__c=789.00;
            Ins.Non_MB_Insurance__c='Test4';
            Ins.Outlet_Name__c='Test5';
            Ins.Payment_Method__c='cash';
            Ins.Contractor_Phone1__c='7598623345';
            Ins.Vehicle_Registration_No__c='456738';
            Ins.Contractor_ZipCode1__c='5600032';
        insert Ins;
        Test.StartTest();
        ApexPages.currentPage().getParameters().put('Id',Ins.id);
        ApexPages.StandardController controller = new ApexPages.StandardController(Ins);
        RelatedDealerViewForInsurance I= new RelatedDealerViewForInsurance(controller);
        Test.StopTest();
		
		
        }
}