src/main/metadata/objects/Retail_Campaign__c.object
<CustomObject>
    <description>This Object is used for Retail Campaign, Yearly Target, Monthly Target.</description>
    <fields>
        <fullName>Driven__c</fullName>
        <label>Driven</label>
        <picklist>
            <picklistValues>
                <fullName>Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Driven</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Organized by BMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extended Activities from BMBS’s Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Campaign on Festivals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Organized by Dealer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>M_ATL_BTL__c</fullName>
        <label>ATL/BTL</label>
        <picklist>
            <picklistValues>
                <fullName>Media Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>M_Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>MB + StarElite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>smart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>M_KPI_Type__c</fullName>
        <label>KPI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Marketing Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>M_YearlyTA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Yearly TA</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Retail_Campaign__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sales &amp; Marketing Yearly TA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Retail_Campaign__c</referenceTo>
        <relationshipLabel>Records (MonthlyTA)</relationshipLabel>
        <relationshipName>Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Y_AMG_Marketing_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AMG Marketing Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y_AMG_Marketing_Expense__c</fullName>
        <defaultValue>0</defaultValue>
        <label>AMG Marketing Expense</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y_MB_Dealer_Driven_Marketing_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MB Dealer Driven Marketing Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y_MB_Joint_Marketing_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MB Joint Marketing Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y_MB_Marketing_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MB Marketing Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y_MB_Marketing_Expense__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MB Marketing Expense</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y_SMART_Marketing_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SMART Marketing Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Y_SMART_Marketing_Expense__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SMART Marketing Expense</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Retail_Campaign__c.object
    <fields>
        <fullName>Campaign_Execution_Channels__c</fullName>
        <label>Campaign Execution Channels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eMail</fullName>
                </value>
                <value>
                    <fullName>DM</fullName>
                </value>
                <value>
                    <fullName>OB</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>DM Magazine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <label>Trigger</label>
</CustomObject>

src/main/metadata/classes/YearlyTAReportControllerTest.cls
/*
    Type:       test class
    Purpose:    YearlyTAReportController test class
    User Story: Release 1.2 Report S&M R006
    Used By:    YearlyTAReportController
    9-Jun-2014 Sinow    Created
*/
@isTest
public with sharing class YearlyTAReportControllerTest {

Private Static Retail_Campaign__c rc;
Private Static String RTId = Schema.SObjectType.Retail_Campaign__c.getRecordTypeInfosByName().get('Sales & Marketing Yearly TA').getRecordTypeId();
Private Static String mbsatrelite='mb + starelite';
Private Static String marketingbudget='marketing budget';
Private Static String joint='joint';
Private Static String mediaplan='media plan';
Private Static String id='id';
Private Static String eventplan='event plan';
Private Static String dealerdriven='dealer driven';
Private Static String newlead='new lead';
Private Static String neworder='new order';
Private Static String smart='smart';
Private Static String amg='amg';
Private Static YearlyTAReportController extension;

    public static testMethod void testYearlyTAReportController(){
       preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=mbsatrelite;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =joint;
        YearlyTA.M_ATL_BTL__c =mediaplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
        System.assertEquals(rc.M_Brand__c,'mbsatrelite');
        System.assertEquals(YearlyTA.M_KPI_Type__c,marketingbudget);
    }
    public static testMethod void testYearlyTAJointEventPlan(){
      
        preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=mbsatrelite;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =joint;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
        System.assertEquals(YearlyTA.M_ATL_BTL__c,eventplan);
    }
    
    public static testMethod void testYearlyTAReportControllerelse(){
      
        preparedTestData();                  
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=mbsatrelite;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =mediaplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
        System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.Driven__c,dealerdriven);
    }
     public static testMethod void testYearlyTAReportControllerelseEventPlan(){
       
        preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=mbsatrelite;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
		YearlyTA.Campaign_Execution_Channels__c='DM';
         
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
          System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_ATL_BTL__c ,eventplan);
    }
     public static testMethod void testYearlyKPITypeNewLead(){
       
        preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=mbsatrelite;
        YearlyTA.M_KPI_Type__c=newlead;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
         
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
        System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_KPI_Type__c,newlead);
    }
     public static testMethod void testYearlyKPITypeNewOrder(){
        
        preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=mbsatrelite;
        YearlyTA.M_KPI_Type__c=neworder;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
         
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();        
        System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_KPI_Type__c,neworder);
    }
    
    public static testMethod void testYearlyBrandsmart(){
        preparedTestData();    
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=smart;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =joint;
        YearlyTA.M_ATL_BTL__c =mediaplan;
        YearlyTA.M_YearlyTA__c=rc.id;
         YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;                
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
         System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_Brand__c,smart);
    }
     public static testMethod void testYearlyBrandAMG(){
     
        preparedTestData();
        
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=amg;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =joint;
        YearlyTA.M_ATL_BTL__c =mediaplan;
        YearlyTA.M_YearlyTA__c=rc.id;
         YearlyTA.Campaign_Execution_Channels__c='DM';
         
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
          System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_Brand__c,amg);
    }
    
     public static testMethod void testYearlyTAAMGEventPlan(){
       
       
        preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=amg;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
         YearlyTA.Campaign_Execution_Channels__c='DM';
         
        Test.startTest();
        insert YearlyTA;    
         PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
          System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_Brand__c,amg);
    }
    
     public static testMethod void testYearlyTAsmartEventPlan(){
        
       preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=smart;
        YearlyTA.M_KPI_Type__c=marketingbudget;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
         YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
          System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_Brand__c,smart);
    }

 public static testMethod void testYearlyTAsmartNewLead(){
      preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=smart;
        YearlyTA.M_KPI_Type__c=newlead;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
        System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_Brand__c,smart);
    }
 


public static testMethod void testYearlyTAsmartNewOrder(){
    preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=smart;
        YearlyTA.M_KPI_Type__c=neworder;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM'; 
        
        Test.startTest();
        insert YearlyTA;                
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
         System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_Brand__c,smart);
    }
    public static testMethod void testYearlyTAAMGNewOrder(){
    
        preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=amg;
        YearlyTA.M_KPI_Type__c=neworder;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
         System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.M_Brand__c,amg);
    }
    public static testMethod void testYearlyTAAMGNewLead(){
    
        preparedTestData();
        Retail_Campaign__c YearlyTA= new Retail_Campaign__c();
        YearlyTA.RecordTypeId = RTId;
        YearlyTA.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        YearlyTA.Y_MB_Joint_Marketing_Budget__c=3;
        YearlyTA.Y_MB_Marketing_Budget__c=4;
        YearlyTA.Y_MB_Marketing_Expense__c=5;
        YearlyTA.Y_SMART_Marketing_Budget__c=6;
        YearlyTA.Y_SMART_Marketing_Expense__c=7;
        YearlyTA.Y_AMG_Marketing_Budget__c=8;
        YearlyTA.Y_AMG_Marketing_Expense__c=9;
        YearlyTA.M_Brand__c=amg;
        YearlyTA.M_KPI_Type__c=newlead;
        YearlyTA.Driven__c =dealerdriven;
        YearlyTA.M_ATL_BTL__c =eventplan;
        YearlyTA.M_YearlyTA__c=rc.id;
        YearlyTA.Campaign_Execution_Channels__c='DM';
        
        Test.startTest();
        insert YearlyTA;        
        PageReference YearlyTAReport = Page.Yearly_TA_Report;
        YearlyTAReport.getParameters().put(id,rc.id);
        Test.setCurrentPage(YearlyTAReport);        
        extension = new YearlyTAReportController();
        Test.stopTest();
        System.assertEquals(rc.M_ATL_BTL__c ,mediaplan);
        System.assertEquals(YearlyTA.Driven__c ,dealerdriven);
        system.assertNotEquals(null,extension);
    }
   
    

    public static void preparedTestData()
    {
        List<Trigger__c> updatecustomsettings =  UtilCustomSettingsJP.customSettingDetails();
        insert updatecustomsettings;
     rc = new Retail_Campaign__c();
        rc.RecordTypeId = RTId;
        rc.Y_MB_Dealer_Driven_Marketing_Budget__c=2;
        rc.Y_MB_Joint_Marketing_Budget__c=3;
        rc.Y_MB_Marketing_Budget__c=4;
        rc.Y_MB_Marketing_Expense__c=5;
        rc.Y_SMART_Marketing_Budget__c=6;
        rc.Y_SMART_Marketing_Expense__c=7;
        rc.Y_AMG_Marketing_Budget__c=8;
        rc.Y_AMG_Marketing_Expense__c=9;
        rc.M_Brand__c='mbsatrelite';
        rc.M_KPI_Type__c=marketingbudget;
        rc.Driven__c =joint;
        rc.M_ATL_BTL__c =mediaplan;
        rc.Campaign_Execution_Channels__c='DM';
        
        insert rc;
        
    }
   }