src/main/metadata/objects/smart_SSI__c.object
<CustomObject>
    <fields>
        <fullName>CarModelCheck_Status__c</fullName>
        <label>CarModelCheck Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <description>Company Name from the sales contract</description>
        <label>CompanyName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <description>The start date for the sales contract.</description>
        <label>ContractDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_By_EP_Transaction__c</fullName>
        <label>Created By EP Transaction</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <description>Customer Name from the sales contract</description>
        <label>CustomerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerTitle__c</fullName>
        <description>Customer Title from the sales contract</description>
        <label>CustomerTitle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCheck_Status__c</fullName>
        <label>DealerCheck Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DealerName__c</fullName>
        <description>The dealer name on the sales record</description>
        <label>DealerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <description>Sales dealer code in CRM</description>
        <label>Dealer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Encode_Dealer_Name__c</fullName>
        <description>Store URLEncode Dealer Name.
Used in Report HyberLink.</description>
        <label>Encode Dealer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HandoverDate__c</fullName>
        <description>Date of the vehicle-handover to the customer</description>
        <label>HandoverDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HomeMobilePhone__c</fullName>
        <description>Private Phone Number from the sales contract</description>
        <label>HomeMobilePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>InvoiceDate__c</fullName>
        <description>Date for invoice</description>
        <label>InvoiceDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Month__c</fullName>
        <formula>TEXT(YEAR(InvoiceDate__c)) + IF(MONTH(InvoiceDate__c) &lt; 10, &apos;0&apos; + TEXT(MONTH(InvoiceDate__c)), TEXT(MONTH(InvoiceDate__c)))</formula>
        <label>Invoice Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newly_Task_Id__c</fullName>
        <description>Store the newly task id , updated by View SSI button on task, used in interaction log &amp; task relationship.</description>
        <label>*Newly Task Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficePhone__c</fullName>
        <description>Office Phone Number from the sales contract</description>
        <label>OfficePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>OriginalCustomerName__c</fullName>
        <label>OriginalCustomerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalOfficePhone__c</fullName>
        <label>OriginalOfficePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Original_HomeMobilePhone__c</fullName>
        <label>Original HomeMobilePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ownertype__c</fullName>
        <description>Whether the vehicle is private or company owned</description>
        <label>Ownertype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The sales person involved in the contract</description>
        <label>Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmatched</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VehicleCBUCKD__c</fullName>
        <description>Vehicle manufacture type according to sales contract</description>
        <label>VehicleCBUCKD</label>
        <picklist>
            <picklistValues>
                <fullName>CBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CKD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VehicleDesc__c</fullName>
        <description>Vehicle description according to sales contract</description>
        <label>VehicleDesc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleModel__c</fullName>
        <description>Vehicle model according to sales contract</description>
        <label>VehicleModel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleUSvin__c</fullName>
        <description>Vehicle US VIN according to sales contract</description>
        <label>VehicleUSvin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>smart SSI</label>
    <nameField>
        <displayFormat>SM-SSI{000000}</displayFormat>
        <label>SSI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>smart SSI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/SSI__c.object
<CustomObject>
    <description>SSI: To record each SSI record</description>
    <fields>
        <fullName>CarModelCheck_Status__c</fullName>
        <label>CarModelCheck Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <description>Company Name from the sales contract</description>
        <label>CompanyName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractDate__c</fullName>
        <description>The start date for the sales contract.</description>
        <label>ContractDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_By_EP_Transaction__c</fullName>
        <label>Created By EP Transaction</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <description>Customer Name from the sales contract</description>
        <label>CustomerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerTitle__c</fullName>
        <description>Customer Title from the sales contract</description>
        <label>CustomerTitle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCheck_Status__c</fullName>
        <label>DealerCheck Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DealerName__c</fullName>
        <description>The dealer name on the sales record</description>
        <label>DealerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <description>Sales dealer code in CRM</description>
        <label>Dealer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HandoverDate__c</fullName>
        <description>Date of the vehicle-handover to the customer</description>
        <label>HandoverDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HomeMobilePhone__c</fullName>
        <description>Private Phone Number from the sales contract</description>
        <label>HomeMobilePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>InvoiceDate__c</fullName>
        <description>Date for invoice</description>
        <label>InvoiceDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Month__c</fullName>
        <formula>TEXT(YEAR(InvoiceDate__c)) + IF(MONTH(InvoiceDate__c) &lt; 10, &apos;0&apos; + TEXT(MONTH(InvoiceDate__c)), TEXT(MONTH(InvoiceDate__c)))</formula>
        <label>Invoice Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Newly_Task_Id__c</fullName>
        <description>Store the newly task id , updated by View SSI button on task, used in interaction log &amp; task relationship.</description>
        <label>*Newly Task Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficePhone__c</fullName>
        <description>Office Phone Number from the sales contract</description>
        <label>OfficePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>OriginalCustomerName__c</fullName>
        <label>OriginalCustomerName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalOfficePhone__c</fullName>
        <label>OriginalOfficePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Original_HomeMobilePhone__c</fullName>
        <label>Original HomeMobilePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ownertype__c</fullName>
        <description>Whether the vehicle is private or company owned</description>
        <label>Ownertype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The sales person involved in the contract</description>
        <label>Person</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Original</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmatched</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VehicleCBUCKD__c</fullName>
        <description>Vehicle manufacture type according to sales contract</description>
        <label>VehicleCBUCKD</label>
        <picklist>
            <picklistValues>
                <fullName>CBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CKD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VehicleDesc__c</fullName>
        <description>Vehicle description according to sales contract</description>
        <label>VehicleDesc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleModel__c</fullName>
        <description>Vehicle model according to sales contract</description>
        <label>VehicleModel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleUSvin__c</fullName>
        <description>Vehicle US VIN according to sales contract</description>
        <label>VehicleUSvin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SSI</label>
    <nameField>
        <displayFormat>SSI-{000000}</displayFormat>
        <label>SSI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata-todo/classes/SSIScheduleMassCarDeletion.cls
/*
    Type:       SSI Schedule Smart Car Deletion
    Purpose:    Everyday at midnight, system will automatically delete "Smart" model car.
    User Story: 
    Used By:    
    ---------------------------------------------------------------
    History:
    
    1. Patrick Zhang Created on 2013-11-14
*/
global class SSIScheduleMassCarDeletion implements Schedulable{

    private User sinotrust;

    global void execute(SchedulableContext sc){
        if(sinotrust == null){
            List<User> sList = [Select Id From User Where Profile.Name = 'BMBS Sinotrust User' And IsActive = true Limit 1];
            if (sList.size() > 0) {
                sinotrust = sList[0];
            }       
        }  
        List<SSI__c> smartCars;
        if (smartCars == null) {
            smartCars = new List<SSI__c>();
            for(List<SSI__c> ssis : [
                SELECT 
                    VehicleUSvin__c, 
                    VehicleModel__c, 
                    VehicleDesc__c, 
                    VehicleCBUCKD__c, 
                    Person__c, 
                    Ownertype__c, 
                    Original_HomeMobilePhone__c, 
                    OriginalOfficePhone__c, 
                    OriginalCustomerName__c, 
                    OfficePhone__c, 
                    Invoice_Month__c, 
                    InvoiceDate__c, 
                    HomeMobilePhone__c, 
                    HandoverDate__c, 
                    Dealer__c, 
                    DealerName__c, 
                    CustomerTitle__c, 
                    CustomerName__c, 
                    ContractDate__c, 
                    CompanyName__c,
                    //Barney lai 2014-3-14 start
                    Newly_Task_Id__c,
                    CarModelCheck_Status__c,
                    Comments__c,
                    Created_By_EP_Transaction__c,
                    DealerCheck_Status__c,
                    Encode_Dealer_Name__c,
                    Mark__c,
                    SSI_SourceId__c,
                    Status__c,
                    Survey_Finished__c,
                    SuspectCarModel_Review__c,
                    SuspectDealer_Review__c,
                    Suspect_Reason__c,
                    Updated_By_EP_Transactions__c,
                    VehicleID__c,
                    New_Used__c
                    //Barney lai 2014-3-14 start
                FROM SSI__c
                WHERE CreatedDate >= LAST_N_DAYS:60 AND VehicleDesc__c LIKE 'smart%']){
                for (SSI__c ssi : ssis) {
                      smartCars.add(ssi);
                }
            }
        }
        
        try{
            if(smartCars != null && smartCars.size() > 0){
                List<Smart_SSI__c> smarts = new List<Smart_SSI__c>();
                for (SSI__c ssi : smartCars) {
                    Smart_SSI__c smart = new Smart_SSI__c(                        
                        VehicleUSvin__c = ssi.VehicleUSvin__c , 
                        VehicleModel__c = ssi.VehicleModel__c , 
                        VehicleDesc__c = ssi.VehicleDesc__c , 
                        VehicleCBUCKD__c = ssi.VehicleCBUCKD__c , 
                        Person__c = ssi.Person__c , 
                        Ownertype__c = ssi.Ownertype__c , 
                        Original_HomeMobilePhone__c = ssi.Original_HomeMobilePhone__c, 
                        OriginalOfficePhone__c = ssi.OriginalOfficePhone__c , 
                        OriginalCustomerName__c = ssi.OriginalCustomerName__c , 
                        OfficePhone__c = ssi.OfficePhone__c ,  
                        InvoiceDate__c = ssi.InvoiceDate__c , 
                        HomeMobilePhone__c = ssi.HomeMobilePhone__c , 
                        HandoverDate__c = ssi.HandoverDate__c , 
                        Dealer__c = ssi.Dealer__c , 
                        DealerName__c = ssi.DealerName__c , 
                        CustomerTitle__c = ssi.CustomerTitle__c , 
                        CustomerName__c = ssi.CustomerName__c , 
                        ContractDate__c = ssi.ContractDate__c , 
                        CompanyName__c = ssi.CompanyName__c ,                       
                        //Barney lai 2014-3-14 start
                        Newly_Task_Id__c = ssi.Newly_Task_Id__c ,
                        CarModelCheck_Status__c = ssi.CarModelCheck_Status__c ,
                        Comments__c = ssi.Comments__c ,
                        Created_By_EP_Transaction__c = ssi.Created_By_EP_Transaction__c ,
                        DealerCheck_Status__c = ssi.DealerCheck_Status__c ,
                        Encode_Dealer_Name__c = ssi.Encode_Dealer_Name__c ,
                        Mark__c = ssi.Mark__c ,
                        SSI_SourceId__c = ssi.SSI_SourceId__c ,
                        Status__c = ssi.Status__c ,
                        Survey_Finished__c = ssi.Survey_Finished__c ,
                        SuspectCarModel_Review__c = ssi.SuspectCarModel_Review__c ,
                        SuspectDealer_Review__c = ssi.SuspectDealer_Review__c ,
                        Suspect_Reason__c = ssi.Suspect_Reason__c ,
                        Updated_By_EP_Transactions__c = ssi.Updated_By_EP_Transactions__c ,
                        VehicleID__c = ssi.VehicleID__c,
                        New_Used__c = ssi.New_Used__c
                        //Barney lai 2014-3-14 end
                    );
                    if (sinotrust != null) {
                        smart.OwnerId = sinotrust.Id;
                    }
                    smarts.add(smart);
                }
                insert smarts;
                delete smartCars;
            }
        }catch(DmlException e){
            System.debug('An unexpected error has occured: ' + e.getMessage());
        }
    }
}