src/main/metadata/objects/smart_SSI__c.object
<CustomObject>
    <fields>
        <fullName>CarModelCheck_Status__c</fullName>
        <label>CarModelCheck Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accept</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VehicleDesc__c</fullName>
        <description>Vehicle description according to sales contract</description>
        <label>VehicleDesc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleModel__c</fullName>
        <description>Vehicle model according to sales contract</description>
        <label>VehicleModel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>smart SSI</label>
    <nameField>
        <displayFormat>SM-SSI{000000}</displayFormat>
        <label>SSI No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>smart SSI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle_Model_Mapping__c.object
<CustomObject>
    <description>Contact Portfolio: Mapping object used by EP to get correct vehicle model description from incorrect model description</description>
    <fields>
        <fullName>SSI_Model__c</fullName>
        <label>SSI Model</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Model__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Source Model</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle Model Mapping</label>
    <nameField>
        <displayFormat>VMM-{000000}</displayFormat>
        <label>Vehicle Model Mapping Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Model Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/metadata-excluded/classes/SmartSSIBatchCarModelCheck.cls
/*
    Type:       smart SSI car model cleansing 
    Purpose:    Clean car model
    User Story: smart SSI
    Used By:    
    ---------------------------------------------------------------
    History:
    
    1. Barney Lai Created on 2014-03-14

*/
global class SmartSSIBatchCarModelCheck implements Database.Batchable<SObject>, Database.Stateful  {
    
    private String query;
    
    private Integer successCount = 0;
    
    private Map<String, String> cmMap;
    
    global SmartSSIBatchCarModelCheck(String q) {
        this.query = q;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        if(cmMap == null){
            cmMap = new Map<String, String>();
            for(List<Vehicle_Model_Mapping__c> cmList : [Select Source_Model__c, SSI_Model__c From Vehicle_Model_Mapping__c]){
                for(Vehicle_Model_Mapping__c vmm : cmList){
                    cmMap.put(vmm.Source_Model__c, vmm.SSI_Model__c );
                }
            }
        }
        
      for(smart_SSI__c ssi : (List<smart_SSI__c>)scope){
        
        if(ssi.VehicleDesc__c != null && cmMap.containsKey(ssi.VehicleDesc__c)){
            ssi.VehicleModel__c = cmMap.get(ssi.VehicleDesc__c);
        }else{
            ssi.VehicleModel__c = null;
        }              
      
        if(ssi.VehicleModel__c!=null && ssi.VehicleModel__c.length()>0){
          ssi.CarModelCheck_Status__c = 'Valid';
        }else{
          ssi.CarModelCheck_Status__c = 'Pending';
        }
      }
        
        if(scope.size()>0){
            update scope;
            successCount += scope.size();
        }

    }
    
    global void finish(Database.BatchableContext bc) {
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                           JobItemsProcessed, TotalJobItems
                    FROM AsyncApexJob
                    WHERE Id = :bc.getJobId()]; 
                    
        User currentUser = [Select Email From User Where Id = :UserInfo.getUserId()];
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {currentUser.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Car Model Rule Batch Status: ' + job.Status);
        mail.setPlainTextBody('The batch Apex job processed ' + job.TotalJobItems +
            ' batches with '+ job.NumberOfErrors + ' failures. \nTotal Records Updated: ' + successCount);
        try {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
        catch(Exception ex) {
            system.debug('Send Car Model Rule Batch Status Email Exception ::' + ex.getMessage());
        }
    }
}