src/main/metadata/objects/Trigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Defines whether a Trigger is enabled in a certain context and which trigger handler to call.

"Trigger Name" is the name of the trigger as in ApexTriggers.
"before", "after", "insert", "update", "delete" define the context to be considered.
"enabled" specifies whether the trigger is enabled or disabled in this context.

On start of a trigger this CustomerSetting is checked for the trigger's name and the current context.
If the trigger is disabled, it is not processed, execution terminates.</description>
    <fields>
        <fullName>Trigger_Handler__c</fullName>
        <description>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</description>
        <inlineHelpText>Name of an Apex class that implements interface TriggerHandlerIf and contains all code to be executed if the trigger is called.</inlineHelpText>
        <label>Trigger Handler</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the trigger (can be multiply used with different context settings)</description>
        <label>Trigger Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>after__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger after execution of an event</description>
        <label>after</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>before__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger before execution of an event</description>
        <label>before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on delete events</description>
        <label>delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the trigger for the specified context enabled or disabled (default is enabled).</description>
        <label>enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>insert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on insert events</description>
        <label>insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger on update events</description>
        <label>update</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger</label>
</CustomObject>

src/main/metadata/classes/TriggerUtil.cls
/*
    Type:       Utility methods for triggers
    ---------------------------------------------------------------
    History:
    
    1. HNG Created on 2015-04-09
*/
public class TriggerUtil 
{
    public static Boolean isTriggerEnabled(String aTriggerName) 
    {
        return isTriggerEnabled(getTriggerInfo(aTriggerName));
    }
    
    public static Boolean isTriggerEnabled(Trigger__c aTriggerInfo) 
    {
	    if (aTriggerInfo != null) {
            return aTriggerInfo.enabled__c;
		}
        else {
		    return true;
        }
    }
    
    public static void handleTrigger(String aTriggerName)
    {
        Trigger__c triggerInfo = getTriggerInfo(aTriggerName);
        
        if (isTriggerEnabled(triggerInfo)) {
            TriggerHandlerIf triggerHandler = getTriggerHandler(triggerInfo);
            
            if (triggerHandler != null) {
                triggerHandler.handleTrigger();
            }
        }
    }
    
    public static Trigger__c getTriggerInfo(String aTriggerName) 
    {
	    if (aTriggerName != null) {
            for (Trigger__c triggerInfo : Trigger__c.getAll().values()) {
                if (aTriggerName.equals(triggerInfo.Trigger_Name__c)) {
                    if (trigger.isAfter && !triggerInfo.after__c) {
                        continue;
                    }
                    if (trigger.isBefore && !triggerInfo.before__c) {
                        continue;
                    }
                    if (trigger.isInsert && !triggerInfo.insert__c) {
                        continue;
                    }
                    if (trigger.isUpdate && !triggerInfo.update__c) {
                        continue;
                    }
                    if (trigger.isDelete && !triggerInfo.delete__c) {
                        continue;
                    }
                    return triggerInfo;
                }
            }
		}
        
        // If no corresonding data, just return null
		return null;
    }
    
    public static TriggerHandlerIf getTriggerHandler(Trigger__c aTriggerInfo)
    {
        if (aTriggerInfo != null && aTriggerInfo.Trigger_Handler__c != null) {
            Type triggerHandlerType = Type.forName(aTriggerInfo.Trigger_Handler__c);
            
            if (triggerHandlerType == null) {
                throw new IllegalArgumentException('Configured trigger handler class ' + aTriggerInfo.Trigger_Handler__c + ' not found. Please check custom setting Trigger for trigger name ' + aTriggerInfo.Trigger_Name__c);
            }
            
            return (TriggerHandlerIf)triggerHandlerType.newInstance();
        }
        else {
            return null;
        }
    }
}