src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Car_Relation__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Person's relationship to the vehicle
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_CarRelation“</description>
        <inlineHelpText>Person's relationship to the vehicle</inlineHelpText>
        <label>Car Relation</label>
        <picklist>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Contact Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aftersales Contact Target 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aftersales Contact Target 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Relationship end date
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_EndDate“</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/VehicleHelperTR.cls
/**************************************************************************************************************************************************
* Class:                            vehicleHelperTR
* Description:                      This class will Close all the Tasks under Sales VR when Warranty Type - Advantage Plus
on after insert context.
@methods Description            
* --------------------------------------------------------------------------------------------------------------------------------------------------
* Date                              Name                        Modification Description
* Created Date : 2018-6-6    	Hildaa                     Created  

=====================================================================================================================================================*/
public class VehicleHelperTR{
    Public static void autoCloseTasksInSalesVR(List<Vehicle__c> newVehicleRecords,Map<Id,Vehicle__c> oldMapVR){
        set<Id> VHIds = new set<Id>();
		set<Id> VRIds = new set<Id>();
		list<Task> tasktoClose = new list<task>();
		for(Vehicle__c vh : newVehicleRecords)
		{
			if(vh.warranty_type__c == 'Advantage Plus' && vh.warranty_type__c != oldMapVR.get(vh.id).warranty_type__c)
				VHIds.add(vh.Id);
		}
		for(Vehicle_Relationship__c vr : [select id,end_date__c,vehicle_id__c,car_relation__c from Vehicle_Relationship__c where vehicle_id__c in :VHIds and end_date__c = null and car_relation__c = 'Sales' ]) {
			VRIds.add(vr.id);	
		}
		for(Task tk : [select id,whoid,whatid,status from task where whatid in :VRIds and status != 'Closed' ])
		{
			tk.status = 'Closed';
			tasktoClose.add(tk);
		}
		if(tasktoClose.size()>0){
              DMLManagerService.updateAsSystem(tasktoClose);
        }
		
    } 
}