src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Car_Relation__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Person's relationship to the vehicle
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_CarRelation“</description>
        <inlineHelpText>Person's relationship to the vehicle</inlineHelpText>
        <label>Car Relation</label>
        <picklist>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Contact Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aftersales Contact Target 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aftersales Contact Target 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Number__c</fullName>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship
Function: Licence plate number of vehicle 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is" VehicleRel_RegistrationNumber"</description>
        <externalId>true</externalId>
        <inlineHelpText>Licence plate number of vehicle</inlineHelpText>
        <label>Registration Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Brand__c</fullName>
        <formula>TEXT(Vehicle_ID__r.Brand__c)</formula>
        <label>Vehicle Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Class__c</fullName>
        <formula>TEXT(Vehicle_ID__r.Class__c)</formula>
        <label>Vehicle Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <formula>Vehicle_ID__r.Model_Description__c</formula>
        <label>Vehicle Model</label>
        <type>Text</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/VehicleRelLookingController.cls
/**
** This is a controller class for the VehicleRelLookingPage.
** 1. Provides the data for the required data for the Lookup page.
**
** Created By: CC
** Date:  
**/

public with sharing class VehicleRelLookingController {

    public List<Vehicle_Relationship__c> VehilceRels { get; set; }
    public String elementNum  { get; set; }
    private final String contactId = ApexPages.currentPage().getParameters().get('id');
    private final String num = ApexPages.currentPage().getParameters().get('num');
    
    /**
	*@Description :This mehtod fetches the vehicle records based on the contact Id retrived from the page.
	*@Author :Shrinivas Desai.
	*@Date : 27/10/2015
	*@param: None
	*@return:This mehtod does not return any value.
	*@see:VehicleRelLookingController (Constructor method)
	*/
    public VehicleRelLookingController() {
        if(contactId instanceof Id) {
            elementNum = num; 
            VehilceRels = [select Id, Name, Vehicle_ID__c, Vehicle_ID__r.Name, Car_Relation__c, Registration_Number__c, 
                           Vehicle_Brand__c, Vehicle_Class__c, Vehicle_Model__c from Vehicle_Relationship__c where Contact__c = :contactId];
        }
    }
}