src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/VehicleInsightControllerTest.cls
@isTest
public class VehicleInsightControllerTest {
  
    @isTest
    static void VehicleInsightTest(){
      string vehicleName;
      string vehicleId;
        
      string name;
      string recordId;
        account acc = new account(name='testconn');
        insert acc;
        Vehicle_Relationship__c vr= new Vehicle_Relationship__c();
        vr.contact__c = acc.id;
        insert vr;
      List <PrepopulateInsighstWrapper> lstPIW;
        VehicleInsightController.VehicleInsightWrapper viw = new VehicleInsightController.VehicleInsightWrapper('vehicleName', 'vehicleId','name','recordId',lstPIW);
      VehicleInsightController.VRByCustId(acc.id); 
    }

    
}