src/main/metadata/objects/Vehicle__c.object
<CustomObject>
    <description>Contact Portfolio: To record all Vehicle which is linked to a Vehicle Relationship for a customer</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Person Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Account)</relationshipLabel>
        <relationshipName>Vehicles2</relationshipName>
        <type>Lookup</type>
    </fields>

src/main/metadata/objects/Vehicle_Relationship__c.object
<CustomObject>
    <description>Contact Portfolio: Vehicle Relationship record linked to customer and a vehicle</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Amy Liang 
Used by: Vehicle Relationship 
Function: ID of related person 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is ”VehicleRel_Contact“</description>
        <inlineHelpText>ID of related person</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select the proper account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Company, PersonAccount, Person_Account_Manual_Merge, Person_Account_Soft_Deleted</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>/* 
Created by: Tony Li 
Used by: Tony Li 
Function: ID of vehicle in CRM 
Used in: Pagelayouts, Reports 

Modify History 
Modify By: 
Modify Reason: 
*/
Attribute in Data Dictionary object Vehicle Relationship is"VehicleRel_VehicleID"</description>
        <label>Vehicle ID</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicle Relationships</relationshipLabel>
        <relationshipName>Vehicle_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <formula>Vehicle_ID__r.Model_Description__c</formula>
        <label>Vehicle Model</label>
        <type>Text</type>
    </fields>
    <label>Vehicle Relationship</label>
    <nameField>
        <displayFormat>VR-{0000000000}</displayFormat>
        <label>VehicleRel No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Relationship</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/metadata/classes/VehicleInsightController.cls
public class VehicleInsightController {

    @AuraEnabled
    public static List < VehicleInsightWrapper > VRByCustId(String recordId) {
		List < VehicleInsightWrapper > lstVehicleWrapper = new List < VehicleInsightWrapper > ();
        List < Vehicle_Relationship__c > vehicleList = [Select id, name, Vehicle_Model__c, Vehicle_ID__c, Vehicle_ID__r.name from Vehicle_Relationship__c 
                                                        where contact__c =: recordId limit 5];
        for (Vehicle_Relationship__c tempVR: vehicleList)
            lstVehicleWrapper.add(new VehicleInsightWrapper(tempVR.Vehicle_Model__c, (String) tempVR.Vehicle_ID__c, tempVR.name, recordId, 
                                                            InsightsController.fetchPrepopulatedQuestions(tempVR.Id, 'Vehicle')));  
        return lstVehicleWrapper;
    }
    public class VehicleInsightWrapper {

        @AuraEnabled public string vehicleName;
        @AuraEnabled public string vehicleId;
        @AuraEnabled public string name;
        @AuraEnabled public string recordId;
        @AuraEnabled public List <PrepopulateInsighstWrapper> lstPIW;

        public VehicleInsightWrapper(String vehicleName, String vehicleId, String name, String recordId, List<PrepopulateInsighstWrapper> lstPIW) {
            this.vehicleName = vehicleName;
            this.vehicleId = vehicleId;
            this.name = name;
            this.recordId = recordId;
            this.lstPIW = lstPIW;
        }
    }
}